table crm
	lineageTag: deee83fc-4184-4d0b-8229-32031f2212a8

	column id
		dataType: string
		lineageTag: 538af23a-32a1-4905-99cb-fc02a4076674
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: 8c342305-befa-40f6-8f24-f999e0275dbf
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 82c4faec-6742-4913-b04c-3b8a9c9ca07b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column x_studio_mcleod_code
		dataType: string
		lineageTag: e853fd5d-61a3-46cf-a0ff-100623c90454
		summarizeBy: none
		sourceColumn: x_studio_mcleod_code

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: b79e549d-6e71-4b63-9b46-287f7f86a2df
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column x_studio_sdr
		dataType: string
		lineageTag: f83f9536-855b-4cd8-b961-3f53978a545a
		summarizeBy: none
		sourceColumn: x_studio_sdr

		annotation SummarizationSetBy = Automatic

	column activity_date_deadline
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9808314c-62c6-4854-806a-3e1dc05d1af7
		summarizeBy: none
		sourceColumn: activity_date_deadline

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_open
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a93491e-cf52-4268-a5d2-5832c4efb92e
		summarizeBy: none
		sourceColumn: date_open

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_do_not_move
		dataType: string
		lineageTag: b30e6499-7afa-4b61-80ee-1e4dd312a3a2
		summarizeBy: none
		sourceColumn: x_studio_do_not_move

		annotation SummarizationSetBy = Automatic

	column x_studio_lead_type
		dataType: string
		lineageTag: cb198dbc-b49f-4fa7-9238-915c2378c69d
		summarizeBy: none
		sourceColumn: x_studio_lead_type

		annotation SummarizationSetBy = Automatic

	column x_studio_originally_passed_to
		dataType: string
		lineageTag: 98dc6be6-04ba-40eb-b0fd-0da4989587e8
		summarizeBy: none
		sourceColumn: x_studio_originally_passed_to

		annotation SummarizationSetBy = Automatic

	column x_studio_lead_passed_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cbdfb664-1786-40a6-aa3f-b54b99b0bf2d
		summarizeBy: none
		sourceColumn: x_studio_lead_passed_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_enrichment_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 06037bb5-cf63-424d-bf8d-41073c8d8097
		summarizeBy: none
		sourceColumn: x_studio_enrichment_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 10787a78-8861-4a20-98d7-1493120ed95b
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column x_studio_revenue_range
		dataType: string
		lineageTag: 854c2afa-b3ee-4dc6-9b5e-fc9069be05f8
		summarizeBy: none
		sourceColumn: x_studio_revenue_range

		annotation SummarizationSetBy = Automatic

	column x_studio_primary_industry
		dataType: string
		lineageTag: 55d82ce9-ddc5-4ee7-8aaa-9e064b7037c7
		summarizeBy: none
		sourceColumn: x_studio_primary_industry

		annotation SummarizationSetBy = Automatic

	column state_id
		dataType: string
		lineageTag: 89d32111-399b-444f-99a8-e09699ed8cd9
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 478a1e20-c309-4962-9018-994051868f88
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: bce60713-a850-4182-ba21-62448f7a8391
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column user_login
		dataType: string
		lineageTag: 6ca675eb-4945-4ddd-a8c4-015f6ef59d98
		summarizeBy: none
		sourceColumn: user_login

		annotation SummarizationSetBy = Automatic

	column Stage
		dataType: string
		lineageTag: e500af9f-59b8-47b6-a5fa-45330aa0027d
		summarizeBy: none
		sourceColumn: Stage

		annotation SummarizationSetBy = Automatic

	column 'Last Stage Change'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4d454f42-a8ee-4cbb-aa6f-63ede13320d1
		summarizeBy: none
		sourceColumn: Last Stage Change

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'At Risk' = ```
			
			Var Working = 
			    IF([Days since Last Salesperson Update]<7,"False",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>90,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var NoForNow = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>90,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>90,"TRUE",
			    "FALSE")))))
			
			Var Qualified = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			    
			Var Quoted = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var CreditApp = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var OneToThree = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since Last Shipment]>120,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var Customer = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since Last Shipment]>120,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			
			Var AtRisk =
			    IF(CRM[Stage]="Working",Working,
			    IF(CRM[Stage]="No For Now",NoForNow,
			    IF(CRM[Stage]="Qualified",Qualified,
			    IF(CRM[Stage]="Quoted",Quoted,
			    IF(CRM[Stage]="Credit App",CreditApp,
			    IF(CRM[Stage]="1-3 Loads",OneToThree,
			    IF(CRM[Stage]="Customer",Customer,
			
			    "FALSE")))))))
			
			Return
			AtRisk
			```
		lineageTag: 2f304527-0231-4bc8-9101-1e86f075fd4e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column x_studio_zoominfo_company_id
		dataType: string
		lineageTag: 96cfdcac-bec3-4e5a-b465-612560150132
		summarizeBy: none
		sourceColumn: x_studio_zoominfo_company_id

		annotation SummarizationSetBy = Automatic

	partition crm = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/CRM/crm.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Extracted Text Between Delimiters" = Table.TransformColumns(#"Promoted Headers", {{"user_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"stage_id", each Text.BetweenDelimiters(_, "'", "'"), type text}, {"x_studio_primary_industry", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"state_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"x_stage_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}}),
				    #"Extracted Text Between Delimiters1" = Table.TransformColumns(#"Extracted Text Between Delimiters", {{"partner_id", each Text.BetweenDelimiters(_, "[", ","), type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Extracted Text Between Delimiters1",false,null,Replacer.ReplaceValue,{"x_studio_mcleod_code", "x_studio_sdr", "stage_id", "date_last_stage_update", "activity_date_deadline", "date_open", "x_studio_lead_type", "x_studio_originally_passed_to", "x_studio_lead_passed_date", "x_studio_enrichment_date", "city", "x_studio_revenue_range"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Stage", each if [type] = "lead" then [x_stage_id] else [stage_id]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"stage_id", "x_stage_id"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Removed Columns", "Last Stage Change", each if [type] = "lead" then [x_date_last_prospect_stage_change] else [date_last_stage_update]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column1",{"date_last_stage_update", "x_date_last_prospect_stage_change"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"date_open", type datetime}, {"Last Stage Change", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Last Stage Change", type date}, {"x_studio_enrichment_date", type date}, {"date_open", type date}, {"activity_date_deadline", type date}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"partner_id"}),
				    #"Extracted Text Between Delimiters2" = Table.TransformColumns(#"Removed Errors", {{"x_studio_sdr", each Text.BetweenDelimiters(_, "'", "'"), type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Extracted Text Between Delimiters2",{{"x_studio_lead_passed_date", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type2",{{"user_id", Text.Trim, type text}})
				in
				    #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

