table consignee_zip_codes
	lineageTag: 46c19c9d-3ed3-48e3-8b58-b4786c10fdf4

	column 'Consignee Zip'
		dataType: string
		lineageTag: 986f85f3-5f5e-43c2-951a-dedaa23e4e0c
		summarizeBy: none
		sourceColumn: Consignee Zip

		annotation SummarizationSetBy = Automatic

	column 'Consignee Three Digit Zip'
		dataType: string
		lineageTag: d5c05e67-8415-4199-a116-73601f5b7eae
		summarizeBy: none
		sourceColumn: Consignee Three Digit Zip

		annotation SummarizationSetBy = Automatic

	partition consignee_zip_codes = m
		mode: import
		queryGroup: 'Zip Codes'
		source =
				let
				    Source = orders,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Consignee Zip"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Inserted First Characters" = Table.AddColumn(#"Removed Blank Rows", "First Characters", each Text.Start([Consignee Zip], 3), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "Consignee Three Digit Zip"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

