table crm
	lineageTag: d01f0c30-7638-4790-9321-156b67073a2b

	column id
		dataType: string
		lineageTag: 670c2b00-410a-4f0b-ba56-ea882c236e78
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column partner_id
		dataType: string
		lineageTag: c7c85075-49fc-4907-95b5-bba58fc867a2
		summarizeBy: none
		sourceColumn: partner_id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: bb090e43-3b26-4d53-9d8b-5d58daf9c87b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column x_studio_mcleod_code
		dataType: string
		lineageTag: cc38dc54-a22d-4bfb-8859-914030ce54aa
		summarizeBy: none
		sourceColumn: x_studio_mcleod_code

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: cf632617-887f-4b7a-a7d0-876a1a51a008
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column x_studio_sdr
		dataType: string
		lineageTag: bb50e29e-a7ca-4335-80b1-5f6ff3b968da
		summarizeBy: none
		sourceColumn: x_studio_sdr

		annotation SummarizationSetBy = Automatic

	column activity_date_deadline
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8e9fd55b-76b5-4e22-a598-159d095d47c1
		summarizeBy: none
		sourceColumn: activity_date_deadline

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_open
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7d0eb0dc-ea1d-486b-9cd2-4c470b2a723b
		summarizeBy: none
		sourceColumn: date_open

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_do_not_move
		dataType: string
		lineageTag: 79791bb1-54c9-448a-bd91-8e7362b041b6
		summarizeBy: none
		sourceColumn: x_studio_do_not_move

		annotation SummarizationSetBy = Automatic

	column x_studio_lead_type
		dataType: string
		lineageTag: d055850b-618f-42d7-93bb-e1ae8b75ca02
		summarizeBy: none
		sourceColumn: x_studio_lead_type

		annotation SummarizationSetBy = Automatic

	column x_studio_originally_passed_to
		dataType: string
		lineageTag: fd189add-4221-435f-8e2e-72f0c51c6af0
		summarizeBy: none
		sourceColumn: x_studio_originally_passed_to

		annotation SummarizationSetBy = Automatic

	column x_studio_lead_passed_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa58afa3-60ce-48fc-86cb-0bc1403a5b61
		summarizeBy: none
		sourceColumn: x_studio_lead_passed_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_enrichment_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 68822cfd-960f-483c-887e-adcdbbf0d743
		summarizeBy: none
		sourceColumn: x_studio_enrichment_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 9673b817-dda1-4c13-bb1f-bc3ec479e068
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column x_studio_revenue_range
		dataType: string
		lineageTag: 1500e821-5ba5-459f-ace2-f288927cc9c2
		summarizeBy: none
		sourceColumn: x_studio_revenue_range

		annotation SummarizationSetBy = Automatic

	column x_studio_primary_industry
		dataType: string
		lineageTag: 9767e576-2426-40fd-bb54-52555cb72a0a
		summarizeBy: none
		sourceColumn: x_studio_primary_industry

		annotation SummarizationSetBy = Automatic

	column state_id
		dataType: string
		lineageTag: d98bfe8d-0d73-45af-a454-6f2647ee29c8
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = Automatic

	column phone
		dataType: string
		lineageTag: 97ecdc6a-8ae4-43bb-9db6-290958ca910e
		summarizeBy: none
		sourceColumn: phone

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: baaa6696-2546-4995-ba47-d4e43f02d973
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column user_login
		dataType: string
		lineageTag: b461cc2c-c03a-4211-bdef-420b4457371b
		summarizeBy: none
		sourceColumn: user_login

		annotation SummarizationSetBy = Automatic

	column Stage
		dataType: string
		lineageTag: 539d2186-2edf-4262-8759-27aa10e44812
		summarizeBy: none
		sourceColumn: Stage

		annotation SummarizationSetBy = Automatic

	column 'Last Stage Change'
		dataType: dateTime
		formatString: Short Date
		lineageTag: faa235ff-97dc-45aa-9c02-63e85b4fcc4c
		summarizeBy: none
		sourceColumn: Last Stage Change

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'At Risk' = ```
			
			Var Working = 
			    IF([Days since Last Salesperson Update]<7,"False",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>90,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var NoForNow = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>90,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>90,"TRUE",
			    "FALSE")))))
			
			Var Qualified = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			    
			Var Quoted = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var CreditApp = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Since Last Stage Update]>60,"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var OneToThree = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since Last Shipment]>120,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			Var Customer = 
			    IF([Days since Last Salesperson Update]<7,"FALSE",
			    IF(crm[activity_date_deadline]=BLANK(),"TRUE",
			    IF([Days Over Due]>14,"TRUE",
			    IF([Days since Last Shipment]>120,"TRUE",
			    IF([Days since last Behaivor]>60,"TRUE",
			    "FALSE")))))
			
			
			Var AtRisk =
			    IF(CRM[Stage]="Working",Working,
			    IF(CRM[Stage]="No For Now",NoForNow,
			    IF(CRM[Stage]="Qualified",Qualified,
			    IF(CRM[Stage]="Quoted",Quoted,
			    IF(CRM[Stage]="Credit App",CreditApp,
			    IF(CRM[Stage]="1-3 Loads",OneToThree,
			    IF(CRM[Stage]="Customer",Customer,
			
			    "FALSE")))))))
			
			Return
			AtRisk
			```
		lineageTag: b548f0ba-b25d-4924-866f-7af29065654b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition crm = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/CRM/crm.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Extracted Text Between Delimiters" = Table.TransformColumns(#"Promoted Headers", {{"user_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"stage_id", each Text.BetweenDelimiters(_, "'", "'"), type text}, {"x_studio_primary_industry", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"state_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"x_stage_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}}),
				    #"Extracted Text Between Delimiters1" = Table.TransformColumns(#"Extracted Text Between Delimiters", {{"partner_id", each Text.BetweenDelimiters(_, "[", ","), type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Extracted Text Between Delimiters1",false,null,Replacer.ReplaceValue,{"x_studio_mcleod_code", "x_studio_sdr", "stage_id", "date_last_stage_update", "activity_date_deadline", "date_open", "x_studio_lead_type", "x_studio_originally_passed_to", "x_studio_lead_passed_date", "x_studio_enrichment_date", "city", "x_studio_revenue_range"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Replaced Value", "Stage", each if [type] = "lead" then [x_stage_id] else [stage_id]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"stage_id", "x_stage_id"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Removed Columns", "Last Stage Change", each if [type] = "lead" then [x_date_last_prospect_stage_change] else [date_last_stage_update]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column1",{"date_last_stage_update", "x_date_last_prospect_stage_change"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns1",{{"date_open", type datetime}, {"Last Stage Change", type datetime}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Last Stage Change", type date}, {"x_studio_enrichment_date", type date}, {"date_open", type date}, {"activity_date_deadline", type date}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"partner_id"}),
				    #"Extracted Text Between Delimiters2" = Table.TransformColumns(#"Removed Errors", {{"x_studio_sdr", each Text.BetweenDelimiters(_, "'", "'"), type text}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Extracted Text Between Delimiters2",{{"x_studio_lead_passed_date", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type2",{{"user_id", Text.Trim, type text}})
				in
				    #"Trimmed Text"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

