table customer_key
	lineageTag: b98d9d2d-73b0-4ee7-9962-b97515159738

	column 'Customer ID'
		dataType: string
		lineageTag: 0037c396-c76d-4c0f-97ef-2530d6fc629d
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 4458d786-5a20-4f6e-ba5e-7407c024a222
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 0e0f67f9-6182-4e36-b014-24e03e62ce7c
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Customer Bridge ID'
		dataType: string
		lineageTag: e834a5e7-96bd-4e08-b739-20353ab1a8d9
		summarizeBy: none
		sourceColumn: Customer Bridge ID

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: f1966a9c-3199-473f-af05-6289f8fd6097
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 6093c3dd-902d-4961-be9b-603ebcc36275
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: string
		lineageTag: 749334e4-bdc5-45b8-a56f-ee82cc025079
		summarizeBy: none
		sourceColumn: Zip Code

		annotation SummarizationSetBy = Automatic

	column 'Date Added'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 116af2b0-8133-4bfa-a5d9-7570be2ae072
		summarizeBy: none
		sourceColumn: Date Added

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Change Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: db7ddb3e-b198-4370-99b5-b4f14c35cbf9
		summarizeBy: none
		sourceColumn: Change Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pay Terms'
		dataType: int64
		formatString: 0
		lineageTag: 31052aba-47da-427f-b39f-c7123fceedb6
		summarizeBy: sum
		sourceColumn: Pay Terms

		annotation SummarizationSetBy = Automatic

	column 'Customer.Credit Limit'
		dataType: string
		lineageTag: 73559a05-eb60-465d-9ac4-30f9f279dae3
		summarizeBy: none
		sourceColumn: Customer.Credit Limit

		annotation SummarizationSetBy = Automatic

	column 'Billed Orders'
		dataType: int64
		formatString: 0
		lineageTag: 8d005452-425f-4b6f-925e-0875dcd8a900
		summarizeBy: sum
		sourceColumn: Billed Orders

		annotation SummarizationSetBy = Automatic

	column Orders
		dataType: int64
		formatString: 0
		lineageTag: 79dee731-057a-4e84-9e68-bf9fad69f3ba
		summarizeBy: sum
		sourceColumn: Orders

		annotation SummarizationSetBy = Automatic

	column 'Average Days To Pay'
		dataType: double
		lineageTag: 67ebec48-f4c3-4107-9550-84ce46c2cc1e
		summarizeBy: sum
		sourceColumn: Average Days To Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Customer.Obsolete Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 20613f96-10da-4db1-9210-fd52da005770
		summarizeBy: none
		sourceColumn: Customer.Obsolete Date

		annotation SummarizationSetBy = Automatic

	partition customer_key = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Databases("bl-mcbiserver", [TypedMeasureColumns=true, Implementation="2.0"]),
				    McLeodIQ_2019_Powerbroker = Source{[Name="McLeodIQ_2019_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker1 = McLeodIQ_2019_Powerbroker{[Id="McLeodIQ_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker2 = McLeodIQ_Powerbroker1{[Id="McLeodIQ_Powerbroker"]}[Data],
				    #"Added Items" = Cube.Transform(McLeodIQ_Powerbroker2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[Customer]", {"[Customer].[Bill Due Days].[Bill Due Days]", "[Customer].[Credit Limit].[Credit Limit]", "[Customer].[Credit Status].[Credit Status]", "[Customer].[Customer ID].[Customer ID]", "[Customer].[Customer Name].[Customer Name]", "[Customer].[Customer.Bridge ID].[Customer.Bridge ID]", "[Customer].[Customer.City].[Customer.City]", "[Customer].[Customer.State].[Customer.State]", "[Customer].[Customer.Zip Code].[Customer.Zip Code]", "[Customer].[Date Added].[Date Added]", "[Customer].[Obsolete Date].[Obsolete Date]"}, {"Customer.Bill Due Days", "Customer.Credit Limit", "Customer.Credit Status", "Customer.Customer ID", "Customer.Customer Name", "Customer.Customer.Bridge ID", "Customer.Customer.City", "Customer.Customer.State", "Customer.Customer.Zip Code", "Customer.Date Added", "Customer.Obsolete Date"}},
				            {Cube.AddMeasureColumn, "Billed Orders", "[Measures].[Billed Orders]"},
				            {Cube.AddMeasureColumn, "Orders", "[Measures].[Orders]"}
				        }),
				    #"Renamed Columns3" = Table.RenameColumns(#"Added Items",{{"Customer.Bill Due Days", "Pay Terms"}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Renamed Columns3",{{"Customer.Customer ID", "Customer ID"}, {"Customer.Credit Status", "Status"}, {"Customer.Customer Name", "Customer Name"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns",{{"Customer.Obsolete Date", type datetime}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type3",{{"Customer ID", Order.Ascending}, {"Customer.Obsolete Date", Order.Ascending}}),
				    #"Removed Duplicates1" = Table.Distinct(#"Sorted Rows", {"Customer ID"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates1",{"Customer ID", "Status", "Customer Name", "Customer.Customer.Bridge ID", "Customer.Customer.City", "Customer.Customer.State", "Customer.Customer.Zip Code", "Customer.Date Added"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Customer.Customer.Bridge ID", "Customer Bridge ID"}, {"Customer.Customer.City", "City"}, {"Customer.Customer.State", "State"}, {"Customer.Customer.Zip Code", "Zip Code"}, {"Customer.Date Added", "Date Added"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns1", {"Customer ID"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Duplicates",{{"Date Added", type date}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"Customer ID"}, salesperson_change, {"Customer ID"}, "salesperson_change", JoinKind.LeftOuter),
				    #"Expanded salesperson_change" = Table.ExpandTableColumn(#"Merged Queries", "salesperson_change", {"Change Date"}, {"Change Date"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Expanded salesperson_change",{{"Pay Terms", Int64.Type}}),
				    #"Merged Queries1" = Table.NestedJoin(#"Changed Type1", {"Customer ID"}, avereage_days_to_pay, {"Customer.Customer ID"}, "avereage_days_to_pay", JoinKind.LeftOuter),
				    #"Expanded avereage_days_to_pay" = Table.ExpandTableColumn(#"Merged Queries1", "avereage_days_to_pay", {"Customer.Average Pay Days "}, {"Customer.Average Pay Days "}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Expanded avereage_days_to_pay",{{"Customer.Average Pay Days ", "Average Days To Pay"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Average Days To Pay", type number}})
				in
				    #"Changed Type2"

	annotation PBI_ResultType = Table

