table daily_number_override
	lineageTag: bb333896-6093-4734-9017-1842a5629564

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: fdb0d3f0-e116-41c7-950b-c58fbee1eb64
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Margin Number'
		dataType: int64
		formatString: 0
		lineageTag: ee92a63c-e7a4-4b91-841a-32dc1bfdfcea
		summarizeBy: sum
		sourceColumn: Margin Number

		annotation SummarizationSetBy = Automatic

	partition daily_number_override = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    daily_number_override_Table = Source{[Item="daily_number_override",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(daily_number_override_Table,{{"Month", type date}, {"Margin Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

