table dispatcher_key
	lineageTag: ff69ace9-66a1-4c1b-b797-0305f2b98a1b

	column ID
		dataType: int64
		formatString: 0
		lineageTag: ac26ec4e-e6c1-437d-adc5-d422998c1f10
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 10f13f45-4150-4246-967f-96e8b1fa128c
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Hire Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84962da2-41aa-4525-a361-54bd2a131ce3
		summarizeBy: none
		sourceColumn: Hire Date

		variation Variation
			isDefault
			relationship: 22881cbf-eb4e-4f66-afd5-a0ec21a1eb7c
			defaultHierarchy: LocalDateTable_602d0dc9-a979-4162-a15e-cf937935b0b7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Termination Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 180a1027-c792-43b3-9b95-fa90c6902143
		summarizeBy: none
		sourceColumn: Termination Date

		variation Variation
			isDefault
			relationship: 89783f8c-5a09-40cd-8fe0-005c7da2b54b
			defaultHierarchy: LocalDateTable_7e773c2c-a1bd-4f2f-b9f7-efdc6b4a7c73.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Reporting to'
		dataType: string
		lineageTag: a30925f9-3e25-4873-8f0b-58e8383c642e
		summarizeBy: none
		sourceColumn: Reporting to

		annotation SummarizationSetBy = Automatic

	column 'Termination Type'
		dataType: string
		lineageTag: 220b7152-7966-4db2-bd41-68075996bb94
		summarizeBy: none
		sourceColumn: Termination Type

		annotation SummarizationSetBy = Automatic

	column 'Termination Reason'
		dataType: string
		lineageTag: 569856d1-27ab-4cce-9a69-def1250793cf
		summarizeBy: none
		sourceColumn: Termination Reason

		annotation SummarizationSetBy = Automatic

	column 'Regrettable or non- regrettable'
		dataType: string
		lineageTag: 6737f2b4-5098-44c5-8511-db0e9553b7aa
		summarizeBy: none
		sourceColumn: Regrettable or non- regrettable

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: 7eb80008-0538-415c-aac2-d63ff007f32f
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column 'McLeod User Code'
		dataType: string
		lineageTag: efd2d279-ac7c-4627-a24a-543bc4588f9c
		summarizeBy: none
		sourceColumn: McLeod User Code

		annotation SummarizationSetBy = Automatic

	column 'McLeod Salesperson Code'
		dataType: string
		lineageTag: 2220481a-2f8e-4ab0-bbe9-89a5252ec393
		summarizeBy: none
		sourceColumn: McLeod Salesperson Code

		annotation SummarizationSetBy = Automatic

	column 'Work Email'
		dataType: string
		lineageTag: 18c42962-98d4-479b-ab57-70b042e79fcf
		summarizeBy: none
		sourceColumn: Work Email

		annotation SummarizationSetBy = Automatic

	column Devision
		dataType: string
		lineageTag: 6e68814c-8e5e-4214-a4e2-df8a47ea733c
		summarizeBy: none
		sourceColumn: Devision

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: ec08ed91-bb2b-4bc3-ae18-151d36d68bac
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'users.revenue_code_id'
		dataType: string
		lineageTag: 671118c3-d10c-474e-97e0-9e6cbabf1ef7
		summarizeBy: none
		sourceColumn: users.revenue_code_id

		annotation SummarizationSetBy = Automatic

	partition dispatcher_key = m
		mode: import
		source =
				let
				    Source = employees,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([McLeod User Code] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

