table margin_load_count_goals
	lineageTag: 2df3ab1a-6f5c-4bca-a24d-86d23e0977ab

	column 'Salesperson Name'
		dataType: string
		lineageTag: a5f32b6a-bc6a-484e-b530-4a99e3b77f0b
		summarizeBy: none
		sourceColumn: Salesperson Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8b376bdf-f542-4208-bf1b-56ad3ee9507a
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Margin Goal'
		dataType: decimal
		formatString: 0
		lineageTag: 64222b01-cead-46b2-ba52-affa3f44d520
		summarizeBy: sum
		sourceColumn: Margin Goal

		annotation SummarizationSetBy = Automatic

	column 'Load Count Goal'
		dataType: int64
		formatString: 0
		lineageTag: 6c7fe682-eee1-4e10-84d6-a4dba7e20ffa
		summarizeBy: sum
		sourceColumn: Load Count Goal

		annotation SummarizationSetBy = Automatic

	column 'Margin Per Order Goal'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b53df584-aa91-4c96-abcb-f49790a111e8
		summarizeBy: sum
		sourceColumn: Margin Per Order Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Margin % Goal'
		dataType: double
		lineageTag: 96ee1ac6-add9-4522-89c4-8c9778e3ceef
		summarizeBy: sum
		sourceColumn: Margin % Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition margin_load_count_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    MarginLoadCountGoals_Sheet = Source{[Item="MarginLoadCountGoals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(MarginLoadCountGoals_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Salesperson Name", type text}, {"Month", type date}, {"Margin Goal", Int64.Type}, {"Load Count Goal", Int64.Type}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"Salesperson Name", Text.Upper, type text}}),
				    #"Uppercased Text1" = Table.TransformColumns(#"Uppercased Text",{{"Salesperson Name", Text.Upper, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Uppercased Text1",{{"Margin Goal", Currency.Type}, {"Margin Per Order Goal", Currency.Type}, {"Margin % Goal", Percentage.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

