table margin_load_count_goals
	lineageTag: 9b67fda5-3b12-423b-9032-0dd4db6d6344

	column 'Salesperson Name'
		dataType: string
		lineageTag: 980dc038-a26d-4d78-84a9-ac722f14846a
		summarizeBy: none
		sourceColumn: Salesperson Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: bc068d44-af09-4ceb-9ec8-47e9316bd4fe
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Margin Goal'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 61fc996b-901b-4f4b-96b6-5ca0ccad3f84
		summarizeBy: sum
		sourceColumn: Margin Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Load Count Goal'
		dataType: int64
		formatString: 0
		lineageTag: cdb9c0ee-a3a7-4d49-b8da-718ebe85070f
		summarizeBy: sum
		sourceColumn: Load Count Goal

		annotation SummarizationSetBy = Automatic

	column 'Margin Per Order Goal'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cbe6a68d-f97d-4b7b-851b-751c2543a3c6
		summarizeBy: sum
		sourceColumn: Margin Per Order Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Margin % Goal'
		dataType: double
		lineageTag: 61f4b55e-9a63-4aba-991f-d4ce778c4008
		summarizeBy: sum
		sourceColumn: Margin % Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column7
		dataType: string
		lineageTag: 24064e78-7ddc-45f3-84da-9bec1f1186de
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column Column8
		dataType: string
		lineageTag: c432ccea-425a-4f65-b09f-7ebec3a6b1c9
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: da290cb4-52c7-421f-ad9f-895379a58e7a
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	column Column10
		dataType: string
		lineageTag: 0505da06-51ca-46b5-ae4b-54157757b3a3
		summarizeBy: none
		sourceColumn: Column10

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: bf0af2f6-8766-40de-b043-c03e339a4bd2
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column Column12
		dataType: string
		lineageTag: fdfbf07c-a118-44d4-9a4a-3b978c02db04
		summarizeBy: none
		sourceColumn: Column12

		annotation SummarizationSetBy = Automatic

	partition margin_load_count_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    MarginLoadCountGoals_Sheet = Source{[Item="MarginLoadCountGoals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(MarginLoadCountGoals_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Salesperson Name", type text}, {"Month", type date}, {"Margin Goal", Int64.Type}, {"Load Count Goal", Int64.Type}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"Salesperson Name", Text.Upper, type text}}),
				    #"Uppercased Text1" = Table.TransformColumns(#"Uppercased Text",{{"Salesperson Name", Text.Upper, type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Uppercased Text1",{{"Margin Goal", Currency.Type}, {"Margin Per Order Goal", Currency.Type}, {"Margin % Goal", Percentage.Type}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

