table orders
	lineageTag: aa3b9040-5a73-4edf-938f-bd361198cbf4

	column 'Consignee City'
		dataType: string
		lineageTag: 26b0e2d5-56ab-4666-af54-64307378ff30
		summarizeBy: none
		sourceColumn: Consignee City

		annotation SummarizationSetBy = Automatic

	column 'Consignee Name'
		dataType: string
		lineageTag: 451f5dc2-9995-467a-8062-cd23a758ceaf
		summarizeBy: none
		sourceColumn: Consignee Name

		annotation SummarizationSetBy = Automatic

	column 'Consignee State'
		dataType: string
		lineageTag: 4738e4d8-1daa-41b6-9b00-d484a664e258
		summarizeBy: none
		sourceColumn: Consignee State

		annotation SummarizationSetBy = Automatic

	column 'Consignee Zip'
		dataType: string
		lineageTag: efd2687e-4b5d-48ef-94f0-7d47addf9a17
		summarizeBy: none
		sourceColumn: Consignee Zip

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: eaeb8042-279e-4398-949f-51b5322eb08f
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer PO Number'
		dataType: string
		lineageTag: 84fb1e78-92c9-4418-878c-3c2ac0f62336
		summarizeBy: none
		sourceColumn: Customer PO Number

		annotation SummarizationSetBy = Automatic

	column 'BOL Received'
		dataType: string
		lineageTag: 4943948e-8ad9-4fed-95fd-70377c4d2b6c
		summarizeBy: none
		sourceColumn: BOL Received

		annotation SummarizationSetBy = Automatic

	column 'Commodity ID'
		dataType: string
		lineageTag: 94034ab7-a3ff-4a2e-afff-98b89e5a0d21
		summarizeBy: none
		sourceColumn: Commodity ID

		annotation SummarizationSetBy = Automatic

	column 'BOL Number'
		dataType: string
		lineageTag: 35244911-5913-4e3a-a797-0d34cf5f6b6e
		summarizeBy: none
		sourceColumn: BOL Number

		annotation SummarizationSetBy = Automatic

	column 'Delivery Scheduled Early Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f820712d-6ebc-47dd-977e-810048d4b96e
		summarizeBy: none
		sourceColumn: Delivery Scheduled Early Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Scheduled Early Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8cf28e88-a116-4822-91a0-a6b1d6ed6cc1
		summarizeBy: none
		sourceColumn: Delivery Scheduled Early Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Delivery Scheduled Late Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 7851a6a1-bfab-498d-b6a7-ebc1d59c532e
		summarizeBy: none
		sourceColumn: Delivery Scheduled Late Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Scheduled Late Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 297eaf4a-e860-415a-8a98-3544d75776c4
		summarizeBy: none
		sourceColumn: Delivery Scheduled Late Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Entered By'
		dataType: string
		lineageTag: b2c78712-b7bc-40af-a4fa-a1216a2fa320
		summarizeBy: none
		sourceColumn: Entered By

		annotation SummarizationSetBy = Automatic

	column 'Entry Method'
		dataType: string
		lineageTag: c9e3e625-b5ee-4b97-8dfd-931f8b572390
		summarizeBy: none
		sourceColumn: Entry Method

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 5e82bff2-84ba-4cb4-934e-96e024eddd4f
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Status'
		dataType: string
		lineageTag: 48bdeb5e-8a54-470b-8be9-8f9f1790648c
		summarizeBy: none
		sourceColumn: Order Status

		annotation SummarizationSetBy = Automatic

	column 'Order Type'
		dataType: string
		lineageTag: f24b7619-858c-4281-bc37-02fa368a59b9
		summarizeBy: none
		sourceColumn: Order Type

		annotation SummarizationSetBy = Automatic

	column 'Revenue Code'
		dataType: int64
		formatString: 0
		lineageTag: f50b5671-7823-4196-b4c4-dc620c4957d3
		summarizeBy: count
		sourceColumn: Revenue Code

		annotation SummarizationSetBy = Automatic

	column 'Ship Scheduled Early Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 9fa7115b-0621-4adb-87f0-b07439c1be43
		summarizeBy: none
		sourceColumn: Ship Scheduled Early Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Scheduled Early Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: cb2d3265-4b52-463e-b912-a0e85e261cef
		summarizeBy: none
		sourceColumn: Scheduled Early Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Ship Scheduled Late Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 154b8824-f51b-4d85-8019-203571602490
		summarizeBy: none
		sourceColumn: Ship Scheduled Late Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Scheduled Late Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: db435d1b-376b-414e-861e-64118767ec7f
		summarizeBy: none
		sourceColumn: Ship Scheduled Late Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Trailer Type'
		dataType: string
		lineageTag: 434f877a-1a8a-42f4-a437-275a25b2ff3b
		summarizeBy: none
		sourceColumn: Trailer Type

		annotation SummarizationSetBy = Automatic

	column 'Salesperson ID'
		dataType: string
		lineageTag: 5974c6ee-f658-4120-b6b6-090687d4ff47
		summarizeBy: none
		sourceColumn: Salesperson ID

		annotation SummarizationSetBy = Automatic

	column 'Shipper City'
		dataType: string
		lineageTag: e863c43c-d200-4ee0-8d41-ccd3d2ce154b
		summarizeBy: none
		sourceColumn: Shipper City

		annotation SummarizationSetBy = Automatic

	column 'Shipper.Shipper.Location Name'
		dataType: string
		lineageTag: 71f4cf8e-9067-447d-b4ed-4ab8cce4a497
		summarizeBy: none
		sourceColumn: Shipper.Shipper.Location Name

		annotation SummarizationSetBy = Automatic

	column 'Shipper State'
		dataType: string
		lineageTag: 7b7acf0d-cea5-4004-949a-d140572b7c85
		summarizeBy: none
		sourceColumn: Shipper State

		annotation SummarizationSetBy = Automatic

	column 'Shipper Zip'
		dataType: string
		lineageTag: 862f2334-462e-4a7d-ba0a-45de61aca3b2
		summarizeBy: none
		sourceColumn: Shipper Zip

		annotation SummarizationSetBy = Automatic

	column 'Cases Pieces'
		dataType: int64
		formatString: 0
		lineageTag: cf7f7f86-6a77-45d8-aa3d-ec08c926216c
		summarizeBy: sum
		sourceColumn: Cases Pieces

		annotation SummarizationSetBy = Automatic

	column 'Total Charges'
		dataType: double
		lineageTag: a1ae526a-f268-48be-a677-0835ccfc4148
		summarizeBy: sum
		sourceColumn: Total Charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Other Charges'
		dataType: double
		lineageTag: 197b1261-6a87-40ed-adf4-e0ed43149eea
		summarizeBy: sum
		sourceColumn: Total Other Charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Projected Freight Carrier Pay'
		dataType: double
		lineageTag: bb26b761-205f-41a9-8fe1-c3916397c7bd
		summarizeBy: sum
		sourceColumn: Projected Freight Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Projected Other Carrier Pay'
		dataType: double
		lineageTag: 27d407fd-1c53-4101-9ba8-be340f977427
		summarizeBy: sum
		sourceColumn: Projected Other Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Projected Total Carrier Pay'
		dataType: double
		lineageTag: c1bf5929-a72a-4595-ad6b-8fdf7a900b0f
		summarizeBy: sum
		sourceColumn: Projected Total Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Linehaul Charges'
		dataType: double
		lineageTag: 2db7e680-af95-42f6-9cac-64845d42d464
		summarizeBy: sum
		sourceColumn: Linehaul Charges

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bill Distance'
		dataType: double
		lineageTag: e9d9f68a-1abc-4ec5-a1ab-e4063775bcda
		summarizeBy: sum
		sourceColumn: Bill Distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Order Entered.Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: a6e9459f-de94-4155-b4b7-8217a1f2876c
		summarizeBy: none
		sourceColumn: Date Order Entered.Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Lane
		dataType: string
		lineageTag: 10f48857-f387-444f-8f50-74854b41d0a2
		summarizeBy: none
		sourceColumn: Lane

		annotation SummarizationSetBy = Automatic

	column 'Payment Recvd'
		dataType: double
		lineageTag: ffdf8b90-f98f-4ace-ac16-be2a9e68ddd3
		summarizeBy: sum
		sourceColumn: Payment Recvd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Consignee.Consignee.Location ID'
		dataType: string
		lineageTag: b6e40f71-81b1-453a-8765-b9ae62bb56cc
		summarizeBy: none
		sourceColumn: Consignee.Consignee.Location ID

		annotation SummarizationSetBy = Automatic

	column 'Shipper.Shipper.Location ID'
		dataType: string
		lineageTag: ad2eb186-8cdb-4ad1-9126-166b75e98f50
		summarizeBy: none
		sourceColumn: Shipper.Shipper.Location ID

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: f8138a98-023d-4f1b-bd74-389c65c7929c
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition orders = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Databases("bl-mcbiserver", [TypedMeasureColumns=true, Implementation="2.0"]),
				    McLeodIQ_2019_Powerbroker = Source{[Name="McLeodIQ_2019_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker1 = McLeodIQ_2019_Powerbroker{[Id="McLeodIQ_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker2 = McLeodIQ_Powerbroker1{[Id="McLeodIQ_Powerbroker"]}[Data],
				    #"Added Items" = Cube.Transform(McLeodIQ_Powerbroker2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[Consignee]", {"[Consignee].[Consignee.Location City].[Consignee.Location City]", "[Consignee].[Consignee.Location ID].[Consignee.Location ID]", "[Consignee].[Consignee.Location Name].[Consignee.Location Name]", "[Consignee].[Consignee.Location State].[Consignee.Location State]", "[Consignee].[Consignee.Location Zip].[Consignee.Location Zip]"}, {"Consignee.Consignee.Location City", "Consignee.Consignee.Location ID", "Consignee.Consignee.Location Name", "Consignee.Consignee.Location State", "Consignee.Consignee.Location Zip"}},
				            {Cube.AddAndExpandDimensionColumn, "[Customer]", {"[Customer].[Customer ID].[Customer ID]"}, {"Customer.Customer ID"}},
				            {Cube.AddAndExpandDimensionColumn, "[Order]", {"[Order].[BOL Number].[BOL Number]", "[Order].[BOL Received].[BOL Received]", "[Order].[Commodity ID].[Commodity ID]", "[Order].[Consignee Reference Number].[Consignee Reference Number]", "[Order].[Delivery Scheduled Early Date].[Delivery Scheduled Early Date]", "[Order].[Delivery Scheduled Early Date Time].[Delivery Scheduled Early Date Time]", "[Order].[Delivery Scheduled Late Date].[Delivery Scheduled Late Date]", "[Order].[Delivery Scheduled Late Date Time].[Delivery Scheduled Late Date Time]", "[Order].[Entered By].[Entered By]", "[Order].[Entry Method].[Entry Method]", "[Order].[Order ID].[Order ID]", "[Order].[Order Status].[Order Status]", "[Order].[Order Type].[Order Type]", "[Order].[Revenue Code ID].[Revenue Code ID]", "[Order].[Ship Scheduled Early Date].[Ship Scheduled Early Date]", "[Order].[Ship Scheduled Early Date Time].[Ship Scheduled Early Date Time]", "[Order].[Ship Scheduled Late Date].[Ship Scheduled Late Date]", "[Order].[Ship Scheduled Late Date Time].[Ship Scheduled Late Date Time]", "[Order].[Trailer Type].[Trailer Type]"}, {"Order.BOL Number", "Order.BOL Received", "Order.Commodity ID", "Order.Consignee Reference Number", "Order.Delivery Scheduled Early Date", "Order.Delivery Scheduled Early Date Time", "Order.Delivery Scheduled Late Date", "Order.Delivery Scheduled Late Date Time", "Order.Entered By", "Order.Entry Method", "Order.Order ID", "Order.Order Status", "Order.Order Type", "Order.Revenue Code ID", "Order.Ship Scheduled Early Date", "Order.Ship Scheduled Early Date Time", "Order.Ship Scheduled Late Date", "Order.Ship Scheduled Late Date Time", "Order.Trailer Type"}},
				            {Cube.AddAndExpandDimensionColumn, "[Salesperson]", {"[Salesperson].[Salesperson ID].[Salesperson ID]"}, {"Salesperson.Salesperson ID"}},
				            {Cube.AddAndExpandDimensionColumn, "[Shipper]", {"[Shipper].[Shipper.Location City].[Shipper.Location City]", "[Shipper].[Shipper.Location ID].[Shipper.Location ID]", "[Shipper].[Shipper.Location Name].[Shipper.Location Name]", "[Shipper].[Shipper.Location State].[Shipper.Location State]", "[Shipper].[Shipper.Location Zip].[Shipper.Location Zip]"}, {"Shipper.Shipper.Location City", "Shipper.Shipper.Location ID", "Shipper.Shipper.Location Name", "Shipper.Shipper.Location State", "Shipper.Shipper.Location Zip"}},
				            {Cube.AddMeasureColumn, "Cases Pieces", "[Measures].[Cases Pieces]"},
				            {Cube.AddMeasureColumn, "Total Charges", "[Measures].[Total Charges]"},
				            {Cube.AddMeasureColumn, "Total Other Charges", "[Measures].[Total Other Charges]"},
				            {Cube.AddMeasureColumn, "Projected Freight Carrier Pay", "[Measures].[Projected Freight Carrier Pay]"},
				            {Cube.AddMeasureColumn, "Projected Other Carrier Pay", "[Measures].[Projected Other Carrier Pay]"},
				            {Cube.AddMeasureColumn, "Projected Total Carrier Pay", "[Measures].[Projected Total Carrier Pay]"},
				            {Cube.AddMeasureColumn, "Linehaul Charges", "[Measures].[Linehaul Charges]"},
				            {Cube.AddMeasureColumn, "Bill Distance", "[Measures].[Bill Distance]"},
				            {Cube.AddAndExpandDimensionColumn, "[Date Order Entered]", {"[Date Order Entered].[Date Order Entered.Date].[Date Order Entered.Date]"}, {"Date Order Entered.Date Order Entered.Date"}},
				            {Cube.AddMeasureColumn, "Payment Recvd", "[Measures].[Payment Recvd]"},
				            {Cube.AddMeasureColumn, "Weight", "[Measures].[Weight]"}
				        }),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Items",{{"Consignee.Consignee.Location City", "Consignee City"}, {"Consignee.Consignee.Location Name", "Consignee Name"}, {"Consignee.Consignee.Location State", "Consignee State"}, {"Consignee.Consignee.Location Zip", "Consignee Zip"}, {"Customer.Customer ID", "Customer ID"}, {"Order.BOL Number", "Customer PO Number"}, {"Order.BOL Received", "BOL Received"}, {"Order.Commodity ID", "Commodity ID"}, {"Order.Consignee Reference Number", "BOL Number"}, {"Order.Delivery Scheduled Early Date", "Delivery Scheduled Early Date"}, {"Order.Delivery Scheduled Early Date Time", "Delivery Scheduled Early Date Time"}, {"Order.Delivery Scheduled Late Date", "Delivery Scheduled Late Date"}, {"Order.Delivery Scheduled Late Date Time", "Delivery Scheduled Late Date Time"}, {"Order.Entered By", "Entered By"}, {"Order.Entry Method", "Entry Method"}, {"Order.Order ID", "Order ID"}, {"Order.Order Status", "Order Status"}, {"Order.Revenue Code ID", "Revenue Code"}, {"Order.Ship Scheduled Early Date", "Ship Scheduled Early Date"}, {"Order.Ship Scheduled Early Date Time", "Scheduled Early Date Time"}, {"Order.Ship Scheduled Late Date", "Ship Scheduled Late Date"}, {"Order.Ship Scheduled Late Date Time", "Ship Scheduled Late Date Time"}, {"Order.Trailer Type", "Trailer Type"}, {"Salesperson.Salesperson ID", "Salesperson ID"}, {"Shipper.Shipper.Location City", "Shipper City"}, {"Shipper.Shipper.Location State", "Shipper State"}, {"Shipper.Shipper.Location Zip", "Shipper Zip"}, {"Order.Order Type", "Order Type"}, {"Date Order Entered.Date Order Entered.Date", "Date Order Entered.Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Delivery Scheduled Early Date", type date}, {"Delivery Scheduled Early Date Time", type time}, {"Delivery Scheduled Late Date", type date}, {"Delivery Scheduled Late Date Time", type time}, {"Ship Scheduled Early Date", type date}, {"Scheduled Early Date Time", type time}, {"Ship Scheduled Late Date", type date}, {"Ship Scheduled Late Date Time", type time}, {"Revenue Code", Int64.Type}, {"Date Order Entered.Date", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"Consignee State", Text.Trim, type text}, {"Consignee City", Text.Trim, type text}, {"Shipper State", Text.Trim, type text}, {"Shipper City", Text.Trim, type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Trimmed Text", "Consignee City", "Consignee City - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Consignee State", "Consignee State - Copy"),
				    #"Merged Columns" = Table.CombineColumns(#"Duplicated Column1",{"Consignee City - Copy", "Consignee State - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Consignee City, State"),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Merged Columns", "Shipper City", "Shipper City - Copy"),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Duplicated Column2", "Shipper State", "Shipper State - Copy"),
				    #"Merged Columns1" = Table.CombineColumns(#"Duplicated Column3",{"Shipper City - Copy", "Shipper State - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Shipper City, State"),
				    #"Merged Columns2" = Table.CombineColumns(#"Merged Columns1",{"Shipper City, State", "Consignee City, State"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Lane"),
				    #"Uppercased Text" = Table.TransformColumns(#"Merged Columns2",{{"Lane", Text.Upper, type text}})
				in
				    #"Uppercased Text"

	annotation PBI_ResultType = Table

