table sop_issues
	lineageTag: 09e1a60e-cb2b-4eed-98f2-15161c3da2e7

	column 'Movement ID'
		dataType: string
		lineageTag: bdc81be9-2c92-4f75-aa28-3ca4d830ee81
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'SOP Type'
		dataType: string
		lineageTag: c35dc264-ef1a-421f-b0d4-2a9887911f83
		summarizeBy: none
		sourceColumn: SOP Type

		annotation SummarizationSetBy = Automatic

	column Date_time
		dataType: dateTime
		formatString: Long Date
		lineageTag: b8774774-7d5b-434c-8c51-d46d7276051b
		summarizeBy: none
		sourceColumn: Date_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6f0ea4a2-a36b-42d9-9c54-11586b2a6a73
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition sop_issues = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/SOP%20Has%20Been%20Marked/SOP%20Has%20Been%20Marked.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Movement ID", Int64.Type}, {"SOP Type", type text}, {"Date_time", type datetime}}),
				    #"Inserted Time" = Table.AddColumn(#"Changed Type", "Time", each DateTime.Time([Date_time]), type time),
				    #"Extracted Date" = Table.TransformColumns(#"Inserted Time",{{"Date_time", DateTime.Date, type date}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Extracted Date",{{"Movement ID", type text}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

