{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"mcleod_historic_orders\",\"pcs_orders\",\"pcs_movements\",\"pcs_employees\",\"pcs_dispatchers\",\"pcs_orders_dispatchers\",\"stop_historic\",\"users\",\"pay_schedule\",\"sop_issues\",\"behaviors\",\"behavior_goals\",\"margin_load_count_goals\",\"overdue_check_calls\",\"dnc\",\"stop\",\"rev_codes\",\"customer_margin_goal\",\"customer\",\"healthy_pipeline_goals\",\"pcs_customers\",\"custmers_pcs_sync\",\"RefreshCutOffDate\",\"orders\",\"mcleod_historic_movement\",\"MovementCutOffNumber\",\"mcleod_historic_driver_extra_pay\",\"mcleod_historic_movement_order\",\"movement_order\",\"historic_parade_orders\",\"historic_behaviors\",\"historic_callins\",\"movements\",\"driver_extra_pay\",\"Calendar\",\"crm_stages\",\"employees\",\"job_history\",\"salesperson_key\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"parade_orders\",\"carrier_key\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\",\"callins\",\"crt_movement_data\",\"lane\",\"daily_number_override\",\"wolf_pack\",\"account_rep\",\"observed_holidays\",\"Parameter3\",\"Transform Sample File (3)\",\"Sample File (3)\",\"Transform File (3)\",\"Parameter4\",\"Transform Sample File (4)\",\"Sample File (4)\",\"Transform File (4)\",\"behavior_key\",\"dispatcher_key\",\"crm\",\"division_key\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "pcs_employees",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblEntities = ExpData_A{[Schema=\"dbo\",Item=\"tblEntities\"]}[Data],\r",
          "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_tblEntities,{\"EntCode\", \"IDNo\"})\r",
          "in\r",
          "    #\"Removed Other Columns\""
        ],
        "kind": "m",
        "lineageTag": "39e8c686-36a5-4395-8f7d-7ba2923fe445",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "pcs_dispatchers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblUserList = ExpData_A{[Schema=\"dbo\",Item=\"tblUserList\"]}[Data],\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(dbo_tblUserList,{\"UserPassword\", \"OffCode\", \"DefOff\", \"CatCode\", \"MsgInterval\", \"PollerYN\", \"NotifyCode\", \"LiveUpdateYN\", \"Registration\", \"AlertsA\", \"AlertsD\", \"AlertsM\", \"QCUserName\", \"QCPassword\", \"QCSubscriberID\", \"QCPollInterval\", \"ShowWelcomeYN\", \"DefChkPrt\", \"DefInvPrt\", \"DefBOLPrt\", \"SignPath\", \"DefDocPrt\", \"AgentYN\", \"AlertsCC\", \"MsgIntervalLoads\", \"MsgIntervalEntries\", \"RemoteYN\", \"BackgroundImg\", \"AutoRefreshScreensYN\", \"AutoRefreshReportsYN\", \"ReportStartRange\", \"ReportAllowInactivesYN\", \"DirectPhone\", \"DivCode\", \"DefDiv\", \"TeamName\", \"DefBOLStyle\", \"EmailServer\", \"EmailPassword\", \"EmailServerSSL\", \"EmailServerPort\", \"UseCompDefMailYN\", \"p2\", \"p3\", \"p4\", \"PWUpdate\", \"PWFailedAttempts\", \"TempPWIssued\", \"ITSIntegrationID\", \"DAT_UserName\", \"DAT_PW\", \"DAT_TokenPrimary\", \"DAT_TokenSecondary\", \"DAT_LastCall\", \"DisplayLargeFonts\", \"RestrictAdminYN\", \"DeptMgrYN\", \"SalespersonYN\", \"FBTokenID\", \"PowBI_OpYN\", \"PowBI_DispYN\", \"PowBI_FinYN\", \"CameraYN\", \"Cam_AccelYN\", \"Cam_TurnsYN\", \"Cam_ShockYN\", \"Cam_PanicYN\", \"Cam_BreaksYN\"}),\r",
          "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns\",{{\"EmpIDNo\", Order.Ascending}}),\r",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Sorted Rows\", {\"EmpIDNo\"}, pcs_employees, {\"IDNo\"}, \"PCS Employes\", JoinKind.LeftOuter),\r",
          "    #\"Expanded PCS Employes\" = Table.ExpandTableColumn(#\"Merged Queries\", \"PCS Employes\", {\"EntCode\"}, {\"EntCode\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Expanded PCS Employes\", each ([EntCode] <> null)),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"EmpIDNo\", type text}})\r",
          "in\r",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "7263a1e3-ed95-495e-bb1f-ed2f6d3cddf4",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "pcs_orders_dispatchers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblLoads = ExpData_A{[Schema=\"dbo\",Item=\"tblLoads\"]}[Data],\r",
          "    #\"Filtered Rows\" = Table.SelectRows(dbo_tblLoads, each ([Status] = \"Arrived\")),\r",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"LoadID\", \"DispUser\"}),\r",
          "    #\"Added Prefix\" = Table.TransformColumns(#\"Removed Other Columns\", {{\"LoadID\", each \"PCS\" & Text.From(_, \"en-US\"), type text}})\r",
          "in\r",
          "    #\"Added Prefix\""
        ],
        "kind": "m",
        "lineageTag": "eec84fe6-96ff-40d2-a66a-32cf38eb315b",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "stop_historic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_stop = Source{[Schema=\"dbo\",Item=\"stop\"]}[Data],\r",
          "    #\"Filtered Stops Pre RefreshCutOffDate\" = Table.SelectRows(dbo_stop, each [sched_arrive_early] < RefreshCutOffDate),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Stops Pre RefreshCutOffDate\",{\"company_id\", \"address2\", \"appointment_status_id\", \"appt_contact_name\", \"hub\", \"cases\", \"confirmed\", \"contact_name\", \"dist_from_prev\", \"dist_from_prev_um\", \"driver_load_unload\", \"edi_code\", \"edi_loc_code\", \"eta\", \"eta_distance\", \"eta_late\", \"eta_oor\", \"google_place_id\", \"inbound_status\", \"late_eta_colorcode\", \"late_route_status\", \"manifest_fgp_uid\", \"manifest_reg_uid\", \"move_dist_from_preassign\", \"move_dist_from_preassign_um\", \"move_dist_from_previous\", \"move_dist_from_previous_um\", \"operational_status\", \"orig_sched_early\", \"orig_sched_late\", \"pallets_dropped\", \"pallets_picked_up\", \"phone\", \"planned_arrival_time\", \"ponum\", \"prior_uncleared_stops\", \"projected_arrival\", \"rate_dist_from_previous\", \"rate_dist_from_previous_um\", \"refno\", \"requested_service\", \"seal\", \"service_date\", \"showas_address\", \"showas_address2\", \"showas_city_id\", \"showas_city_name\", \"showas_location_id\", \"showas_location_name\", \"showas_state\", \"showas_zip_code\", \"signed_for_name\", \"txl_uid\", \"volume\", \"volume_um\", \"weight\", \"weight_um\", \"ic_stop_id\", \"grouped_id\", \"payment_code_reviewed\", \"trimble_place_id\"}),\r",
          "    #\"Inserted actual_arrival_time\" = Table.AddColumn(#\"Removed Columns\", \"actual_arrival_time\", each DateTime.Time([actual_arrival]), type time),\r",
          "    #\"Inserted actual_departure_time\" = Table.AddColumn(#\"Inserted actual_arrival_time\", \"actual_departure_time\", each DateTime.Time([actual_departure]), type time),\r",
          "    #\"Inserted sched_arrive_early_time\" = Table.AddColumn(#\"Inserted actual_departure_time\", \"sched_arrive_early_time\", each DateTime.Time([sched_arrive_early]), type time),\r",
          "    #\"Inserted sched_arrive_late_time\" = Table.AddColumn(#\"Inserted sched_arrive_early_time\", \"sched_arrive_late_time\", each DateTime.Time([sched_arrive_late]), type time),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted sched_arrive_late_time\",{{\"actual_arrival\", type date}, {\"actual_departure\", type date}, {\"sched_arrive_early\", type date}, {\"sched_arrive_late\", type date}})\r",
          "in\r",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "b3dd5e3a-6047-4487-aedf-02870170447d",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "pcs_orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblLoads = ExpData_A{[Schema=\"dbo\",Item=\"tblLoads\"]}[Data],\r",
          "    #\"Filtered Rows\" = Table.SelectRows(dbo_tblLoads, each ([Status] = \"Arrived\")),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"TotalSeats\", \"TotalTariff\", \"TotalAsWeight\", \"TotalSpace\", \"SealNo\", \"RateType\", \"RatingUnits\", \"RateDiscount\", \"DiscountAmt\", \"TotalAcc\", \"TotalCom\", \"Rate\", \"txtNotes\", \"SelectYN\", \"TripID\", \"MasterLoad\", \"TailgateYN\", \"UserName\", \"InvSelect\", \"InvUser\", \"InvoiceID\", \"InvoiceDate\", \"LoadClass\", \"OfficeCode\", \"IO\", \"Container\", \"Chassis\", \"Notify\", \"NotifyTime\", \"LFD\", \"RRP\", \"LE\", \"JobID\", \"ChassisPU\", \"ChassisDel\", \"BookingNo\", \"VesselName\", \"ShipperID\", \"ShipAddress\", \"ShipPhone\", \"ShipContact\", \"ShipRef\", \"ShipZone\", \"ConsigneeID\", \"ConsAddress\", \"ConsPhone\", \"ConsContact\", \"ConsRef\", \"ConsZone\", \"DropDate\", \"DropID\", \"DropName\", \"DropAddress\", \"DropCity\", \"DropSt\", \"DropZip\", \"XStopsYN\", \"RateMatrix\", \"RateMatrixAcc\", \"CarrierName\", \"UnitNumber\", \"TruckNumber\", \"TrailerNumber1\", \"TrailerNumber2\", \"ReqTemp\", \"Pallets\", \"PalletsPU\", \"PalletsPUDam\", \"PalletsPUVar\", \"PalletsDel\", \"PalletsDelDam\", \"PalletsDelVar\", \"PalletExchange\", \"HazardousYN\", \"FundsType\", \"DZone\", \"BillToName\", \"BillToRef\", \"LastTraceDate\", \"LastTracePos\", \"ETA\", \"FrtConYN\", \"VarianceYN\", \"SaveQuoteYN\", \"ReleaseNumber\", \"LdClearedYN\", \"EDI1\", \"EDI2\", \"EDI3\", \"EDI4\", \"EDI5\", \"AvailPU\", \"AvailDel\", \"ComValue\", \"BrokerageNotes\", \"PreBillYN\", \"MinRateYN\", \"LegTrackingYN\", \"WebPosted\", \"CarrierRate\", \"WebActiveLoad\", \"TotalComF\", \"TotalAccF\", \"TotalRevenueF\", \"DiscountAmtF\", \"RateF\", \"SatStatus\", \"ChargeVAT\", \"SteamshipLine\", \"PortOfDischarge\", \"ContainerTerm\", \"RejectYN\", \"RejectDate\", \"EquipmentX\", \"LFDX\", \"RateSource\", \"RateMatrixCom\", \"MileageSys\", \"MileageMeth\", \"DropRetDate\", \"DropRetTime\", \"CarrierComment\", \"SignedForBy\", \"ClosedBorderYN\", \"RBSentDT\", \"RBSentBy\", \"RBSentTo\", \"QuoteExpires\", \"SOID\", \"AgentBatchID\", \"EDIRefs\", \"DispSelect\", \"StartTrace\", \"EndTrace\", \"CarrierRateAcc\", \"CarrierRateAccName\", \"QRIDNo\", \"PendingYN\", \"ResponseType\", \"ResponseDT\", \"ResponseUser\", \"QRDocYN\", \"QREmail\", \"QRPhone\", \"QRContact\", \"QuoteID\", \"DelOptions\", \"TeamName\", \"ContainerTermLoc\", \"ChassisPULoc\", \"ChassisDelLoc\", \"IntOrigName\", \"IntOrigAddress\", \"IntOrigCity\", \"IntOrigSt\", \"IntOrigZip\", \"IntOrigZone\", \"IntOrigPhone\", \"IntOrigContact\", \"IntOrigRef\", \"IntDestName\", \"IntDestAddress\", \"IntDestCity\", \"IntDestSt\", \"IntDestZip\", \"IntDestZone\", \"IntDestPhone\", \"IntDestContact\", \"IntDestRef\", \"MacroPointOrderID\", \"DAT_AssetID\", \"WebPostedBy\", \"DropTrailerID1\", \"DropTrailerID2\", \"CarrierRev\", \"SatStatusDT\", \"CarrierPayType\", \"CarrierPayRate\", \"CarrierPayYN\", \"LastSendX6\", \"InvHoldYN\", \"SteamshipCode\", \"NextResID\", \"PreloadTrailerID1\", \"PreloadTrailerID2\", \"XTRemoveYN\", \"ContOwnerID\", \"ChasOwnerID\", \"RateWareYN\", \"LastX6Sent\", \"ContainerST\", \"ChassisST\", \"LastFTUpdate\", \"DistDateQ\", \"TimeRem\", \"LastSendFourKites\", \"TTYN\", \"Status\", \"LoadType\", \"DispUser\", \"DriverName\"}),\r",
          "    #\"Added Prefix\" = Table.TransformColumns(#\"Removed Columns\", {{\"LoadID\", each \"PCS\" & Text.From(_, \"en-US\"), type text}}),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Prefix\",{{\"LoadID\", \"id\"}, {\"DateReceived\", \"order_entered_date\"}, {\"PickupDate\", \"shipper_sched_early_date\"}, {\"PickupTime\", \"shipper_sched_early_time\"}, {\"PUWindow\", \"shipper_sched_late_time\"}, {\"DeliveryDate\", \"consignee_sched_early_date\"}, {\"DeliveryTime\", \"consignee_sched_early_time\"}, {\"DelWindow\", \"consignee_sched_late_time\"}, {\"MilesBilled\", \"bill_distance\"}, {\"TotalPieces\", \"pieces\"}, {\"TotalWeight\", \"weight\"}, {\"TotalRevenue\", \"freight_charge\"}, {\"Equipment\", \"equipment_type_id\"}, {\"ShipName\", \"shipper_location_name\"}, {\"ShipCity\", \"shipper_city_name\"}, {\"ShipSt\", \"shipper_state\"}, {\"ShipZip\", \"shipper_zip_code\"}, {\"ConsName\", \"consignee_location_name\"}, {\"ConsCity\", \"consignee_city_name\"}, {\"ConsSt\", \"consignee_state\"}, {\"ConsZip\", \"consignee_zip_code\"}, {\"Salesperson\", \"salesperson_id\"}, {\"Commodity\", \"commodity\"}}),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"order_entered_date\", type date}, {\"shipper_sched_early_date\", type date}, {\"shipper_sched_early_time\", type time}, {\"shipper_sched_late_time\", type time}, {\"consignee_sched_early_date\", type date}, {\"consignee_sched_early_time\", type time}, {\"consignee_sched_late_time\", type time}, {\"freight_charge\", Currency.Type}, {\"salesperson_id\", type text}}),\r",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"salesperson_id\"}, pcs_dispatchers, {\"EmpIDNo\"}, \"tblUserList\", JoinKind.LeftOuter),\r",
          "    #\"Expanded tblUserList\" = Table.ExpandTableColumn(#\"Merged Queries\", \"tblUserList\", {\"eMailAdd\"}, {\"tblUserList.eMailAdd\"}),\r",
          "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded tblUserList\",{\"salesperson_id\"}),\r",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns1\",{{\"tblUserList.eMailAdd\", \"salesperson_id\"}}),\r",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns1\",\"tcampbell@bridgelogisticsinc.com\",\"CAMPFAO1\",Replacer.ReplaceText,{\"salesperson_id\"}),\r",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"BSOLORIA@BRIDGELOGISTICSINC.COM\",\"SOLOCLOH\",Replacer.ReplaceText,{\"salesperson_id\"}),\r",
          "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"jmarot@bridgelogisticsinc.com\",\"MAROHAOH\",Replacer.ReplaceText,{\"salesperson_id\"}),\r",
          "    #\"Merged Queries1\" = Table.NestedJoin(#\"Replaced Value2\", {\"BillToID\"}, pcs_customers, {\"IDNo\"}, \"pcs_customers\", JoinKind.LeftOuter),\r",
          "    #\"Expanded pcs_customers\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"pcs_customers\", {\"EntCode\"}, {\"pcs_customers.EntCode\"}),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Expanded pcs_customers\",{{\"pcs_customers.EntCode\", Text.Trim, type text}}),\r",
          "    //start merging entity codes for matching\r",
          "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Trimmed Text\",\"V5978\",\"V6064\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"V37123\",\"V18661\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"V26458\",\"V18025\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"V24526\",\"V38482\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"V24303\",\"V20643\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"V18231\",\"V20643\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value8\",\"V12320\",\"V6978\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value10\",\"V10210\",\"V10208\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value12\",\"v11634\",\"V7430\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Merged Queries2\" = Table.NestedJoin(#\"Replaced Value11\", {\"pcs_customers.EntCode\"}, custmers_pcs_sync, {\"prev_code\"}, \"customer\", JoinKind.LeftOuter),\r",
          "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Merged Queries2\",\"V17061\",\"V11634\",Replacer.ReplaceText,{\"pcs_customers.EntCode\"}),\r",
          "    #\"Expanded customer\" = Table.ExpandTableColumn(#\"Replaced Value9\", \"customer\", {\"id\"}, {\"customer.id\"}),\r",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Expanded customer\",{{\"customer.id\", \"customer.id_old\"}}),\r",
          "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns2\", \"customer_id\", each if [pcs_customers.EntCode] = \"V11634\" then \"PARIDUIA\" else [customer.id_old]),\r",
          "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"customer.id_old\", \"BillToID\", \"pcs_customers.EntCode\"}),\r",
          "    #\"Added Custom\" = Table.AddColumn(#\"Removed Columns2\", \"status\", each \"D\"),\r",
          "    #\"Inserted First Characters\" = Table.AddColumn(#\"Added Custom\", \"consignee_3_digit_zip_code\", each Text.Start([consignee_zip_code], 3), type text),\r",
          "    #\"Inserted First Characters1\" = Table.AddColumn(#\"Inserted First Characters\", \"shipper_3_digit_zip_code\", each Text.Start([shipper_zip_code], 3), type text),\r",
          "    //Start Add Lane\r",
          "    #\"Trimmed Text1\" = Table.TransformColumns(#\"Inserted First Characters1\",{{\"shipper_city_name\", Text.Trim, type text}, {\"shipper_state\", Text.Trim, type text}, {\"consignee_city_name\", Text.Trim, type text}, {\"consignee_state\", Text.Trim, type text}}),\r",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Trimmed Text1\", \"shipper_city_name\", \"shipper_city_name - Copy\"),\r",
          "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Duplicated Column\", \"shipper_state\", \"shipper_state - Copy\"),\r",
          "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Duplicated Column1\", \"consignee_city_name\", \"consignee_city_name - Copy\"),\r",
          "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Duplicated Column2\", \"consignee_state\", \"consignee_state - Copy\"),\r",
          "    #\"Merged Columns\" = Table.CombineColumns(#\"Duplicated Column3\",{\"shipper_city_name - Copy\", \"shipper_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Shipper\"),\r",
          "    #\"Merged Columns1\" = Table.CombineColumns(#\"Merged Columns\",{\"consignee_city_name - Copy\", \"consignee_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Consignee\"),\r",
          "    //End Add Lane\r",
          "    #\"Merged Columns2\" = Table.CombineColumns(#\"Merged Columns1\",{\"Shipper\", \"Consignee\"},Combiner.CombineTextByDelimiter(\" - \", QuoteStyle.None),\"lane\")\r",
          "in\r",
          "    #\"Merged Columns2\""
        ],
        "kind": "m",
        "lineageTag": "4f815021-5764-4bb3-8b46-a88a5802f2ae",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "mcleod_historic_orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"bl-appdb\"),\r",
          "    lme = Source{[Name=\"lme\"]}[Data],\r",
          "    dbo_orders = lme{[Schema=\"dbo\",Item=\"orders\"]}[Data],\r",
          "    #\"Filtered Orders Pre RefreshCutOFfDate\" = Table.SelectRows(dbo_orders, each [ordered_date] < RefreshCutOffDate),\r",
          "    //Start General Data Transformation\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Orders Pre RefreshCutOFfDate\",{\"company_id\", \"actual_reefer_profile\", \"agency_id\", \"agent_payee_id\", \"allow_relay\", \"autorate_status\", \"booking_no\", \"booking_number\", \"brk_qual_profile\", \"broker_location_id\", \"brokerage_workflow_id\", \"cbp_crossing_date\", \"cbp_crossing_location_id\", \"cbp_crossing_reason\", \"cbsa_crossing_date\", \"cbsa_crossing_location_id\", \"cbsa_crossing_reason\", \"cc_fuel_revenue\", \"cc_fuel_revenue_c\", \"cc_fuel_revenue_d\", \"cc_fuel_revenue_n\", \"cc_fuel_revenue_r\", \"cc_net_revenue\", \"cc_net_revenue_c\", \"cc_net_revenue_d\", \"cc_net_revenue_n\", \"cc_net_revenue_r\", \"cc_pro_nbr\", \"cobroker_location_id\", \"collection_method\", \"com_setpnt_temp\", \"com_setpnt_temp_um\", \"commitment_id\", \"container\", \"container_planned\", \"container_type_id\", \"controlling_carrier_code\", \"copy_from_company\", \"copy_from_order_id\", \"copy_to_company\", \"copy_to_order_id\", \"ctrl_party_id\", \"cube\", \"curr_movement_id\", \"cust_order_no\", \"declared_val\", \"def_move_type\", \"default_match_id\", \"dim_height\", \"dim_length\", \"dim_surcharge\", \"dim_surcharge_c\", \"dim_surcharge_d\", \"dim_surcharge_n\", \"dim_surcharge_r\", \"dim_width\", \"dispatch_opt\", \"dl_team_reqd\", \"dray_del_date\", \"dray_del_pay\", \"dray_del_pay_c\", \"dray_del_pay_d\", \"dray_del_pay_n\", \"dray_del_pay_r\", \"dray_del_payee\", \"dray_del_xfer_dt\", \"dray_pu_date\", \"dray_pu_pay\", \"dray_pu_pay_c\", \"dray_pu_pay_d\", \"dray_pu_pay_n\", \"dray_pu_pay_r\", \"dray_pu_payee\", \"dray_pu_xfer_dt\", \"eir1_no\", \"eir2_no\", \"est_tolls\", \"est_tolls_c\", \"est_tolls_d\", \"est_tolls_n\", \"est_tolls_r\", \"excise_disable_update\", \"excise_taxable\", \"excisetax_total\", \"excisetax_total_c\", \"excisetax_total_d\", \"excisetax_total_n\", \"excisetax_total_r\", \"force_assign\", \"forwd_location_id\", \"free_days\", \"freight_charge_c\", \"freight_charge_d\", \"freight_charge_r\", \"high_value\", \"hold_reason\", \"image_is_present\", \"import_export\", \"include_split_point\", \"intelliset\", \"invoice_recv_date\", \"is_autorate_dist\", \"is_container\", \"is_dedicated\", \"is_local_mile\", \"is_requested\", \"jag_carrier_id\", \"jag_cost_rate_id\", \"ldport_location_id\", \"linear_feet_avail\", \"loadboard\", \"ltl\", \"markup_flat\", \"markup_flat_c\", \"markup_flat_d\", \"markup_flat_n\", \"markup_flat_r\", \"markup_percent\", \"master_order_id\", \"master_sequence\", \"next_rebill\", \"nte_lp_num\", \"nte_lp_qual\", \"operational_status\", \"optiset\", \"optimize\", \"order_mode\", \"order_value_c\", \"order_value_d\", \"order_value_n\", \"order_value_r\", \"orig_dest_rate_id\", \"otherchargetotal_c\", \"otherchargetotal_d\", \"otherchargetotal_n\", \"otherchargetotal_r\", \"pallets_required\", \"pay_gross_d\", \"pay_gross_n\", \"pay_gross_r\", \"planning_comment\", \"pnn_callback\", \"pnn_comment\", \"pnn_comment2\", \"pnn_post_type\", \"pnn_rate\", \"pay_gross\", \"pay_gross_c\", \"pick_up_no\", \"pnn_rate_type\", \"pnn_trailer_length\", \"pnn_trailer_width\", \"ponum\", \"port\", \"port_of_discharge\", \"preload_trailer_id\", \"preloaded\", \"rate_currency_type\", \"rate_id\", \"rate_min_weight\", \"rate_min_weight_um\", \"rate_unit_desc\", \"recurring_order_id\", \"reply_transmitted\", \"requesting_company\", \"return_temp\", \"return_temp_um\", \"return_temp_var\", \"return_temp_var_um\", \"revenue_share_method\", \"sail_date\", \"seal_number\", \"seg_alloc_code\", \"setpoint_temp\", \"setpoint_temp_um\", \"setpoint_var\", \"setpoint_var_um\", \"ship_status_to_edi\", \"shipment_id\", \"shipstatus2edi_dt\", \"ss_location_id\", \"subject_order_status\", \"subject_order_void_date\", \"swap\", \"teams_required\", \"temperature_max_um\", \"temperature_min_um\", \"total_charge_c\", \"total_charge_d\", \"total_charge_n\", \"total_charge_r\", \"totalcharge_and_excisetax_c\", \"totalcharge_and_excisetax_d\", \"totalcharge_and_excisetax_n\", \"totalcharge_and_excisetax_r\", \"tractor_type\", \"vessel\", \"vessel_cutoff_date\", \"bill_distance_um\", \"billing_empty_distance\", \"billing_empty_distance_um\", \"billing_loaded_distance\", \"billing_loaded_distance_um\", \"bol_note\", \"bol_recv_date\", \"external_invoiceno\", \"freight_charge_n\", \"load_date\", \"ordered_by\", \"ordered_method\", \"placard_required\", \"rate\", \"rate_type\", \"rate_units\", \"ready_to_bill\", \"totalcharge_and_excisetax\", \"weight_um\", \"xferred2billing\", \"xferred2billing_dt\", \"lock_miles\", \"is_auto_tonu\", \"floor_loaded_freight\", \"equipment_type_options\", \"ic_movement_from\", \"ic_company_from\", \"is_intercompany\", \"rate_source\", \"ic_order_from\", \"ordered_by_id\", \"pnn_loadboard_user_id\", \"voided_load_transmitted_dt\", \"voided_load_transmitted\", \"total_charge\"}),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"blnum\", \"customer_po\"}, {\"consignee_refno\", \"bol\"}, {\"ordered_date\", \"order_entered_date\"}, {\"otherchargetotal\", \"other_charges_total\"}, {\"salesperson\", \"salesperson_id\"}}),\r",
          "    #\"Inserted order_entered_time\" = Table.AddColumn(#\"Renamed Columns\", \"order_entered_time\", each DateTime.Time([order_entered_date]), type time),\r",
          "    //End General Data Transformation\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted order_entered_time\",{{\"bill_date\", type date}, {\"freight_charge\", Currency.Type}, {\"order_entered_date\", type date}, {\"other_charges_total\", Currency.Type}}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([status] = \"D\" or [status] = \"P\")),\r",
          "    //Start add shipper and consignee data\r",
          "    #\"Merged stop table shipper\" = Table.NestedJoin(#\"Filtered Rows\", {\"shipper_stop_id\"}, stop, {\"id\"}, \"stop\", JoinKind.LeftOuter),\r",
          "    #\"Expanded stop\" = Table.ExpandTableColumn(#\"Merged stop table shipper\", \"stop\", {\"city_name\", \"location_name\", \"sched_arrive_early\", \"sched_arrive_late\", \"state\", \"zip_code\", \"sched_arrive_early_time\", \"sched_arrive_late_time\"}, {\"stop.city_name\", \"stop.location_name\", \"stop.sched_arrive_early\", \"stop.sched_arrive_late\", \"stop.state\", \"stop.zip_code\", \"stop.sched_arrive_early_time\", \"stop.sched_arrive_late_time\"}),\r",
          "    #\"Renamed shipper data\" = Table.RenameColumns(#\"Expanded stop\",{{\"stop.city_name\", \"shipper_city_name\"}, {\"stop.location_name\", \"shipper_location_name\"}, {\"stop.sched_arrive_early\", \"shipper_sched_early_date\"}, {\"stop.sched_arrive_late\", \"shipper_sched_late_date\"}, {\"stop.state\", \"shipper_state\"}, {\"stop.zip_code\", \"shipper_zip_code\"}, {\"stop.sched_arrive_early_time\", \"shipper_sched_early_time\"}, {\"stop.sched_arrive_late_time\", \"shipper_sched_late_time\"}}),\r",
          "    #\"Merged stop table consignee\" = Table.NestedJoin(#\"Renamed shipper data\", {\"consignee_stop_id\"}, stop, {\"id\"}, \"stop\", JoinKind.LeftOuter),\r",
          "    #\"Expanded stop1\" = Table.ExpandTableColumn(#\"Merged stop table consignee\", \"stop\", {\"city_id\", \"city_name\", \"location_name\", \"sched_arrive_early\", \"sched_arrive_late\", \"state\", \"zip_code\", \"sched_arrive_early_time\", \"sched_arrive_late_time\"}, {\"stop.city_id\", \"stop.city_name\", \"stop.location_name\", \"stop.sched_arrive_early\", \"stop.sched_arrive_late\", \"stop.state\", \"stop.zip_code\", \"stop.sched_arrive_early_time\", \"stop.sched_arrive_late_time\"}),\r",
          "    //End add shipper and consignee data\r",
          "    #\"Renamed consignee data\" = Table.RenameColumns(#\"Expanded stop1\",{{\"stop.city_id\", \"consignee_city_id\"}, {\"stop.city_name\", \"consignee_city_name\"}, {\"stop.location_name\", \"consignee_location_name\"}, {\"stop.sched_arrive_early\", \"consignee_sched_early_date\"}, {\"stop.sched_arrive_late\", \"consignee_sched_late_date\"}, {\"stop.state\", \"consignee_state\"}, {\"stop.zip_code\", \"consignee_zip_code\"}, {\"stop.sched_arrive_early_time\", \"consignee_sched_early_time\"}, {\"stop.sched_arrive_late_time\", \"consignee_sched_late_time\"}}),\r",
          "    #\"Inserted First Characters\" = Table.AddColumn(#\"Renamed consignee data\", \"shipper_3_digit_zip_code\", each Text.Start([shipper_zip_code], 3), type text),\r",
          "    #\"Inserted First Characters1\" = Table.AddColumn(#\"Inserted First Characters\", \"consignee_3_digit_zip_code\", each Text.Start([consignee_zip_code], 3), type text),\r",
          "    //Start Add Lane\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Inserted First Characters1\",{{\"shipper_city_name\", Text.Trim, type text}, {\"shipper_state\", Text.Trim, type text}, {\"consignee_city_name\", Text.Trim, type text}, {\"consignee_state\", Text.Trim, type text}}),\r",
          "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Trimmed Text\", \"shipper_city_name\", \"shipper_city_name - Copy\"),\r",
          "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Duplicated Column\", \"shipper_state\", \"shipper_state - Copy\"),\r",
          "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Duplicated Column1\", \"consignee_city_name\", \"consignee_city_name - Copy\"),\r",
          "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Duplicated Column2\", \"consignee_state\", \"consignee_state - Copy\"),\r",
          "    #\"Merged Columns\" = Table.CombineColumns(#\"Duplicated Column3\",{\"shipper_city_name - Copy\", \"shipper_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Shipper\"),\r",
          "    #\"Merged Columns1\" = Table.CombineColumns(#\"Merged Columns\",{\"consignee_city_name - Copy\", \"consignee_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Consignee\"),\r",
          "    //End Add Lane\r",
          "    #\"Merged Columns2\" = Table.CombineColumns(#\"Merged Columns1\",{\"Shipper\", \"Consignee\"},Combiner.CombineTextByDelimiter(\" - \", QuoteStyle.None),\"lane\")\r",
          "in\r",
          "    #\"Merged Columns2\""
        ],
        "kind": "m",
        "lineageTag": "ecc7d6f2-89e7-440c-8625-c2621e2e918e",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "RefreshCutOffDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2024, 9, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "af39c097-cda3-4307-8194-af7487559d9a",
        "queryGroup": "Parameters"
      },
      {
        "name": "MovementCutOffNumber",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "147110 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7b1d95af-7d84-440e-87b8-e089fa08fe15",
        "queryGroup": "Parameters"
      },
      {
        "name": "pcs_customers",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblEntities = ExpData_A{[Schema=\"dbo\",Item=\"tblEntities\"]}[Data],\r",
          "    #\"Filtered Rows\" = Table.SelectRows(dbo_tblEntities, each ([EntType] = \"Customer\"))\r",
          "in\r",
          "    #\"Filtered Rows\""
        ],
        "kind": "m",
        "lineageTag": "6fb223ea-a1b1-4fd2-80a5-bd2e6b261197",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "custmers_pcs_sync",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = customer,\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([prev_code] <> null)),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Filtered Rows\",{{\"prev_code\", Text.Trim, type text}})\r",
          "in\r",
          "    #\"Trimmed Text\""
        ],
        "kind": "m",
        "lineageTag": "a4b6f7c8-ff94-4b99-86ff-1f06b522aaae",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "pcs_movements",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Databases(\"blsql\"),\r",
          "    ExpData_A = Source{[Name=\"ExpData_A\"]}[Data],\r",
          "    dbo_tblLoadDispatch = ExpData_A{[Schema=\"dbo\",Item=\"tblLoadDispatch\"]}[Data],\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(dbo_tblLoadDispatch,{\"TripID\", \"UnitID\", \"UnitNumber\", \"DriverID\", \"CoDriverID\", \"CoDriverName\", \"TruckID\", \"TruckNumber\", \"TrailerID1\", \"TrailerNumber1\", \"TrailerID2\", \"TrailerNumber2\", \"CarrierID\", \"CarrierName\", \"PayCode\", \"PayType\", \"TotalPay\", \"EMI\", \"EMO\", \"EmptyRate\", \"RevShare\", \"PUCus\", \"PUZone\", \"DropDate\", \"DropCus\", \"DropName\", \"DropAddress\", \"DropCity\", \"DropState\", \"DropZip\", \"DropZone\", \"DropTimeIn\", \"DropTimeOut\", \"DelCus\", \"DelZone\", \"AccTimeIn\", \"AccTimeOut\", \"CoDriverPay\", \"BackupDate\", \"BackupRecYN\", \"BatchID\", \"SelectedYN\", \"txtNotes\", \"EntCode\", \"PayMatrix\", \"InputUser\", \"InputDate\", \"InputTime\", \"Activity_ctr_Cont\", \"Activity_ctr_Chassis\", \"LoadClass\", \"PayUnits\", \"CarrierRef\", \"CarrierContact\", \"LastAction\", \"ChassisNo\", \"AccSplitID\", \"ContainerNo\", \"LoadAccID\", \"PUAddress\", \"DelAddress\", \"PaySource\", \"MainDispID\", \"DropRetDate\", \"DropRetTime\", \"AgentBatchID\", \"FuelMatrixID\", \"OwnerID\", \"CurCode\", \"DriverPayF\", \"ActDateO\", \"ActTimeInO\", \"ActTimeOutO\", \"ActDateD\", \"ActTimeInD\", \"ActTimeOutD\", \"DispHours\", \"TrailerID3\", \"TrailerNumber3\", \"DelOptions\", \"PullOptionC\", \"PullOptionX\", \"DPLocC\", \"DPLocX\", \"DPDateC\", \"DPDateX\", \"DPTimeInC\", \"DPTimeOutC\", \"DPTimeInX\", \"DPTimeOutX\", \"ActDPDateC\", \"ActDPDateX\", \"ActDPTimeInC\", \"ActDPTimeOutC\", \"ActDPTimeInX\", \"ActDPTimeOutX\", \"LinkedOutbound\", \"DPContainer\", \"DPChassis\", \"EmptyPullYN\", \"ChassisPULoc\", \"ChassisPUDate\", \"ChassisPUTimeIn\", \"ChassisPUTimeOut\", \"ChassisDelLoc\", \"ChassisDelDate\", \"ChassisDelTimeIn\", \"ChassisDelTimeOut\", \"ActChassisPUDate\", \"ActChassisPUTimeIn\", \"ActChassisPUTimeOut\", \"ActChassisDelDate\", \"ActChassisDelTimeIn\", \"ActChassisDelTimeOut\", \"ChassisOption\", \"IntEmptyPayType\", \"LateReason\", \"EDIStatusCode\", \"EDIPostBy\", \"EDIPostDate\", \"IntEmptyPayMatrix\", \"PrevVersionYN\", \"MacroPointOrderID\", \"DropTrailerID1\", \"DropTrailerID2\", \"TrailerCharge\", \"AllowRejectYN\", \"PreloadTrailer1YN\", \"PreloadTrailer2YN\", \"AutoDispatchYN\", \"AutoSendSatYN\", \"DropTrailer1YN\", \"DropTrailer2YN\", \"RejectedDT\", \"StreetTurnYN\", \"IMLHRate\", \"IMFuelRate\", \"IMInsRate\", \"IMLHAmt\", \"IMFuelAmt\", \"IMInsAmt\", \"PUName\", \"PUCity\", \"PUState\", \"PUZip\", \"PUTimeIn\", \"PUTimeOut\", \"DelName\", \"DelCity\", \"DelState\", \"DelZip\", \"DelDate\", \"DelTimeIn\", \"DelTimeOut\", \"Status\", \"PUDate\", \"DispatchDate\", \"DispatchTime\", \"DriverPay\", \"DispatchCode\", \"DriverName\"}),\r",
          "    #\"Added Prefix\" = Table.TransformColumns(#\"Removed Columns\", {{\"LoadID\", each \"PCS\" & Text.From(_, \"en-US\"), type text}}),\r",
          "    #\"Added Prefix1\" = Table.TransformColumns(#\"Added Prefix\", {{\"IDNo\", each \"PCS\" & Text.From(_, \"en-US\"), type text}}),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Prefix1\",{{\"LoadID\", \"order_id\"}, {\"IDNo\", \"id\"}, {\"PayRate\", \"override_pay_amt\"}, {\"Miles\", \"move_distance\"}}),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"override_pay_amt\", Currency.Type}}),\r",
          "    #\"Merged Queries\" = Table.NestedJoin(#\"Changed Type\", {\"order_id\"}, pcs_orders_dispatchers, {\"LoadID\"}, \"pcs_orders_dispatchers\", JoinKind.LeftOuter),\r",
          "    #\"Expanded pcs_orders_dispatchers\" = Table.ExpandTableColumn(#\"Merged Queries\", \"pcs_orders_dispatchers\", {\"DispUser\"}, {\"DispUser\"}),\r",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Expanded pcs_orders_dispatchers\",{{\"DispUser\", \"dispatcher_user_id\"}}),\r",
          "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"status\", each \"D\"),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Added Custom\",{{\"dispatcher_user_id\", Text.Trim, type text}}),\r",
          "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"dispatcher_user_id\", Text.Upper, type text}})\r",
          "in\r",
          "    #\"Uppercased Text\""
        ],
        "kind": "m",
        "lineageTag": "56cf4560-8d4b-40d6-953a-3445982b331f",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "mcleod_historic_movement",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_movement = Source{[Schema=\"dbo\",Item=\"movement\"]}[Data],\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_movement,{{\"id\", type number}}),\r",
          "    #\"filtered movements pre MovmentCuttOFfNumber\" = Table.SelectRows(#\"Changed Type\", each [id] < MovementCutOffNumber),\r",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"filtered movements pre MovmentCuttOFfNumber\",{{\"id\", type text}}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"company_id\", \"authorized\", \"average_broker_rating\", \"booking_no\", \"br_details_link\", \"br_status_link\", \"br_track_interval\", \"br_track_status\", \"br_tracking_id\", \"br_vendor\", \"broker_avail_tract\", \"brokerage\", \"carrier_contact\", \"carrier_email\", \"carrier_fuel_pay_rate_id\", \"carrier_lane_rate_id\", \"carrier_override_user\", \"carrier_phone\", \"carrier_rate_id\", \"chassis\", \"checkcall_sched_id\", \"container\", \"container_returned\", \"container_status\", \"controlling_carrier_code\", \"dedicated_order_id\", \"est_tolls\", \"est_tolls_c\", \"est_tolls_d\", \"est_tolls_n\", \"est_tolls_r\", \"exclude_movement\", \"fleet_manager\", \"freight_matching_override\", \"fuel_distance_um\", \"fuel_tax_exempt\", \"hubtran_approved_inv_date\", \"hubtran_ok2pay_date\", \"integrated_carrier_search\", \"is_container\", \"is_dray\", \"is_local_mile\", \"linked_id\", \"linked_sequence\", \"loaded\", \"locked_user_id\", \"ltl\", \"ltl_staging_wrs_uid\", \"macropoint_status\", \"manifest_empty_distance\", \"manifest_estimated_arrival\", \"manifest_estimated_depart\", \"manifest_id\", \"manifest_loaded_distance\", \"manifest_reg_uid\", \"manifest_spots_capacity\", \"manifest_spots_consumed\", \"manifest_weight_capacity\", \"manifest_weight_consumed\", \"max_buy_c\", \"max_buy_d\", \"max_buy_n\", \"max_buy_r\", \"max_pay_method\", \"max_pay_units\", \"missed_call_sent\", \"fuel_distance\", \"move_distance_um\", \"movement_type\", \"must_respond_by\", \"next_sched_call\", \"operational_status\", \"operations_user\", \"override_crny_type\", \"override_driver_id\", \"override_driver_nm\", \"override_drvr_cell\", \"override_drvr_email\", \"override_max_pay\", \"override_max_pay_c\", \"override_max_pay_d\", \"override_max_pay_n\", \"override_max_pay_r\", \"override_pay_amt_c\", \"override_pay_amt_d\", \"override_pay_amt_n\", \"override_pay_amt_r\", \"override_paye_rate\", \"override_targetpay_c\", \"override_targetpay_d\", \"override_targetpay_n\", \"override_targetpay_r\", \"override_unit_desc\", \"override_units\", \"pay_distance\", \"pay_distance_um\", \"placard_required\", \"priority\", \"pro_nbr\", \"rate_alert_basis\", \"rate_alert_date\", \"rate_alert_days\", \"rate_alert_hours\", \"rate_alert_minutes\", \"rate_confirm_template\", \"rate_confirmation_sent_date\", \"rate_confirmation_status\", \"rate_expiration_basis\", \"rate_expiration_date\", \"rate_expiration_days\", \"rate_expiration_hours\", \"rate_expiration_minutes\", \"rdy_pickup_date\", \"recurring_movement_id\", \"reminder_sent\", \"required_vendor\", \"reserved\", \"return_date\", \"seg_alloc_code\", \"ss_location_id\", \"target_extra_stop_pay\", \"target_extra_stop_pay_c\", \"target_extra_stop_pay_d\", \"target_extra_stop_pay_n\", \"target_extra_stop_pay_r\", \"target_fuel_surcharge_pay\", \"target_pay_c\", \"target_pay_d\", \"target_pay_n\", \"target_pay_r\", \"target_pay_method\", \"target_pay_units\", \"target_rate_id\", \"time_to_send_msg\", \"tracking_request_status\", \"trailer_rent_pct\", \"trip_lease\", \"trip_mgt_recalc_datetime\", \"trip_mgt_tracking_id\", \"triumphpay_exclude\", \"trp_uid\", \"unlock_time\", \"waterfall_flood_time\", \"waterfall_in_progress\", \"xferred2fueltax\", \"xferred2fueltaxdt\", \"xmit_accepted\", \"xmitted2driver\", \"zmit_trip\", \"require_tracking\", \"ts_borrowing_company\", \"ts_commodity\", \"ts_movement_id\", \"tracking_duration_ext\", \"tracking_notify_email\", \"shpmt_ident_type\", \"shpmt_ident_value\", \"override_driver2_nm\", \"ic_company_to\", \"load_booking_source\", \"override_drvr2_email\", \"track_start_date\", \"br_track_vehicle_id\", \"br_track_status_desc\", \"pending_carrier_type\", \"shipper_email\", \"carrier_override_carrier\", \"pending_carrier_name\", \"override_driver2_id\", \"carrier_empty_from_city_id\", \"shipper_notify_frequency\", \"pending_carrier_nbr\", \"ic_order_to\", \"digital_booking\", \"is_intercompany\", \"override_drvr2_cell\", \"carrier_tractor\", \"carrier_trailer\", \"equipment_group_id\", \"empty2next_order\", \"eform_rate_confirmation\", \"override_pay_rate\", \"preassign_sequence\", \"carrier_trailer_type\", \"pending_payee_id\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([status] <> \"V\")),\r",
          "    //start replacing teams with parade\r",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"team17\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"team16\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"team15\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"team14\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"team13\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"team12\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"team10\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"team9\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"team8\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"team7\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"team6\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"team5\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"team4\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"team3\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"team2\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"team1\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"cdispatch\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    //end replace teams with parade\r",
          "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"cbt\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Replaced Value17\",{{\"dispatcher_user_id\", Text.Trim, type text}}),\r",
          "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"dispatcher_user_id\", Text.Upper, type text}})\r",
          "in\r",
          "    #\"Uppercased Text\""
        ],
        "kind": "m",
        "lineageTag": "913af15e-8ef1-470b-a516-92c5e6d44a04",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "mcleod_historic_driver_extra_pay",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_driver_extra_pay = Source{[Schema=\"dbo\",Item=\"driver_extra_pay\"]}[Data],\r",
          "    #\"Filtered Pay pre RefreshCutOffDate\" = Table.SelectRows(dbo_driver_extra_pay, each [amount_d] < RefreshCutOffDate),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Pay pre RefreshCutOffDate\",{\"company_id\", \"amount_c\", \"amount_d\", \"amount_n\", \"amount_r\", \"carrier_rate_id\", \"descr\", \"detention_hist_pay_id\", \"driver_id\", \"fuel_surcharge_pay\", \"jag_rate_id\", \"order_id\", \"rate\", \"reference_no\", \"rev_uid\", \"transaction_date\", \"units\"})\r",
          "in\r",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "c2f81b9b-4fbb-45cc-baa7-0086b2f2998d",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "mcleod_historic_movement_order",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_movement_order = Source{[Schema=\"dbo\",Item=\"movement_order\"]}[Data],\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_movement_order,{{\"movement_id\", type number}}),\r",
          "    #\"Filtered Pre MovementCutOffNumber\" = Table.SelectRows(#\"Changed Type\", each [movement_id] < MovementCutOffNumber),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Pre MovementCutOffNumber\",{\"company_id\", \"id\", \"on_at_move_dest\", \"on_at_move_origin\", \"planned_manifest_id\"})\r",
          "in\r",
          "    #\"Removed Columns\""
        ],
        "kind": "m",
        "lineageTag": "98afc80b-1ced-4813-84ff-49fa95dcea19",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "movement_order",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_movement_order = Source{[Schema=\"dbo\",Item=\"movement_order\"]}[Data],\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_movement_order,{{\"movement_id\", type number}}),\r",
          "    #\"Filtered >= MovementCutOffNumber\" = Table.SelectRows(#\"Changed Type\", each [movement_id] >= MovementCutOffNumber),\r",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered >= MovementCutOffNumber\",{{\"movement_id\", type text}}),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"company_id\", \"id\", \"on_at_move_dest\", \"on_at_move_origin\", \"planned_manifest_id\"}),\r",
          "    #\"Appended Query\" = Table.Combine({#\"Removed Columns\", mcleod_historic_movement_order}),\r",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Appended Query\",{{\"movement_id\", type text}}),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type2\",{{\"movement_id\", Text.Trim, type text}})\r",
          "in\r",
          "    #\"Trimmed Text\""
        ],
        "kind": "m",
        "lineageTag": "32c1816d-fe91-435a-8362-5ffc4dd06ca1",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "59e49c03-a356-4cef-87fc-37914b4d1cd5",
        "queryGroup": "Transform File from historic_parade_orders\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Excel.Workbook(Parameter1, null, true),\r",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "1fbdd36a-69da-4bdd-8d07-bdf16a9c249c",
        "queryGroup": "Transform File from historic_parade_orders"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Folder Path\", \"Attributes\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each Text.Contains([Folder Path], \"02 BL-Areas/bridge_iq/Data Sets/Parade/parade_orders_api_files\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "3619b482-2bf8-4f12-915b-aab38357cf1f",
        "queryGroup": "Transform File from historic_parade_orders\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "        Source = Excel.Workbook(Parameter1, null, true),",
          "        Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "9bb2a554-9b20-411a-b1b6-ea04113e9d7c",
        "queryGroup": "Transform File from historic_parade_orders\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f0b8ebc3-304f-43e6-bbee-db250c156091",
        "queryGroup": "Transform File from parade_orders\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Excel.Workbook(Parameter2, null, true),\r",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "b142244a-63e0-49ba-9f70-76864dbaf607",
        "queryGroup": "Transform File from parade_orders"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Folder Path\", \"Attributes\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each Text.Contains([Folder Path], \"02 BL-Areas/bridge_iq/Data Sets/Parade/parade_orders_api_files\")),\r",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r",
          "    Navigation1 = #\"Filtered Hidden Files1\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "c286de1c-fe54-4fb7-9c49-86bf12c129db",
        "queryGroup": "Transform File from parade_orders\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "        Source = Excel.Workbook(Parameter2, null, true),",
          "        Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "bf0440a7-90f6-460f-9fbc-c2f0a8fce758",
        "queryGroup": "Transform File from parade_orders\\Helper Queries"
      },
      {
        "name": "historic_parade_orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Folder Path\", \"Attributes\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each Text.Contains([Folder Path], \"02 BL-Areas/bridge_iq/Data Sets/Parade/parade_orders_api_files\")),\r",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r",
          "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),\r",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Transform File\"}),\r",
          "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"id\", Int64.Type}, {\"reference_id\", type text}, {\"created_at\", type datetime}, {\"archived_at\", type datetime}, {\"src_city\", type text}, {\"src_state\", type text}, {\"src_date\", type date}, {\"src_postal_code\", type text}, {\"dst_city\", type text}, {\"dst_state\", type text}, {\"dst_date\", type date}, {\"dst_postal_code\", type text}, {\"num_stops\", Int64.Type}, {\"equipment\", type text}, {\"trailer_type\", type text}, {\"rate_customer\", type number}, {\"first_load\", type logical}, {\"customer_id\", type text}, {\"revenue_code\", Int64.Type}, {\"team_name\", type any}, {\"rep_email\", type text}, {\"rep_name\", type text}, {\"carrier_manager\", type text}, {\"category\", type text}, {\"conversion_category\", type text}, {\"partner\", type text}, {\"margin_amount\", type number}, {\"margin_pct\", type number}, {\"carrier_name\", type text}, {\"dot_number\", Int64.Type}, {\"mc_number\", Int64.Type}, {\"carrier_rate\", type number}}),\r",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"rate_customer\", Currency.Type}, {\"margin_amount\", Currency.Type}}),\r",
          "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"reference_id\", Order.Ascending}}),\r",
          "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Sorted Rows\", {{\"reference_id\", each Text.AfterDelimiter(_, \"-\"), type text}}),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Extracted Text After Delimiter\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Blank Rows\",{{\"reference_id\", \"movement_id\"}}),\r",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each ([category] <> \"outside_parade\") and ([conversion_category] <> \"Manually Assigned\")),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows1\", {\"id\"}),\r",
          "    #\"Filtered orders before RefreshCutOffDate\" = Table.SelectRows(#\"Removed Duplicates\", each [created_at] < RefreshCutOffDate),\r",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered orders before RefreshCutOffDate\", each [conversion_category] <> null and [conversion_category] <> \"\")\r",
          "in\r",
          "    #\"Filtered Rows2\""
        ],
        "kind": "m",
        "lineageTag": "95446394-12c9-44d4-bfbc-ea7f8fb2d92d",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "historic_callins",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_callin = Source{[Schema=\"dbo\",Item=\"callin\"]}[Data],\r",
          "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_callin,{\"entered_by\", \"entered_date\", \"movement_status\", \"payee_id\", \"initiated_type\", \"movement_id\"}),\r",
          "    #\"Filtered callins before RefreshCutOffDate\" = Table.SelectRows(#\"Removed Other Columns\", each [entered_date] < RefreshCutOffDate),\r",
          "    #\"Inserted Time\" = Table.AddColumn(#\"Filtered callins before RefreshCutOffDate\", \"Time\", each DateTime.Time([entered_date]), type time),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Time\",{{\"Time\", \"entered_time\"}}),\r",
          "    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"entered_date\", DateTime.Date, type date}}),\r",
          "    #\"Calculated Start of Hour\" = Table.TransformColumns(#\"Extracted Date\",{{\"entered_time\", Time.StartOfHour, type time}})\r",
          "in\r",
          "    #\"Calculated Start of Hour\""
        ],
        "kind": "m",
        "lineageTag": "56bd229e-e47a-4149-814e-6b72b080d909",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "dnc",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/DNC/DNC.xlsx\"), null, true),\r",
          "    dnc_Table = Source{[Item=\"dnc\",Kind=\"Table\"]}[Data],\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(dnc_Table,{{\"DNC\", type text}}),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Changed Type\")\r",
          "in\r",
          "    #\"Removed Duplicates\""
        ],
        "kind": "m",
        "lineageTag": "404f9e09-a9e5-41cf-8435-ee73acb35e66"
      },
      {
        "name": "Parameter3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (3)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (3)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c5b8bf0c-fa84-413d-a472-27c7814f3c56",
        "queryGroup": "Transform File from behaviors\\Helper Queries"
      },
      {
        "name": "Transform Sample File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Excel.Workbook(Parameter3, null, true),\r",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "04305715-2431-48aa-84c3-4fffc150748a",
        "queryGroup": "Transform File from behaviors"
      },
      {
        "name": "Sample File (3)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/02 BL-Areas/bridge_iq/Data Sets/behaviors_api_files/\")),\r",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "fc6fe0e2-27aa-48a4-8d3b-f19ba57636e6",
        "queryGroup": "Transform File from behaviors\\Helper Queries"
      },
      {
        "name": "Transform File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter3 as binary) => let",
          "        Source = Excel.Workbook(Parameter3, null, true),",
          "        Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b594b25c-1827-4acd-ae47-d19aae6df491",
        "queryGroup": "Transform File from behaviors\\Helper Queries"
      },
      {
        "name": "Parameter4",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (4)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (4)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "50f5d478-8d0f-4752-923f-22e5b5b84184",
        "queryGroup": "Transform File from historic_behaviors\\Helper Queries"
      },
      {
        "name": "Transform Sample File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Excel.Workbook(Parameter4, null, true),\r",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "40157f7e-dcc8-4409-9d8f-b835b60dc51f",
        "queryGroup": "Transform File from historic_behaviors"
      },
      {
        "name": "Sample File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/02 BL-Areas/bridge_iq/Data Sets/behaviors_api_files/\")),\r",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r",
          "    Navigation1 = #\"Filtered Hidden Files1\"{0}[Content]\r",
          "in\r",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "6c753d56-0e08-4fa7-8bde-cdf69a56d0ac",
        "queryGroup": "Transform File from historic_behaviors\\Helper Queries"
      },
      {
        "name": "Transform File (4)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter4 as binary) => let",
          "        Source = Excel.Workbook(Parameter4, null, true),",
          "        Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "96187a1f-dd5c-48bf-9faa-843e6b5cd850",
        "queryGroup": "Transform File from historic_behaviors\\Helper Queries"
      },
      {
        "name": "historic_behaviors",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/02 BL-Areas/bridge_iq/Data Sets/behaviors_api_files/\")),\r",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r",
          "    #\"Filtered Hidden Files2\" = Table.SelectRows(#\"Filtered Hidden Files1\", each [Attributes]?[Hidden]? <> true),\r",
          "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files2\", \"Transform File (4)\", each #\"Transform File (4)\"([Content])),\r",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),\r",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (4)\"}),\r",
          "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (4)\", Table.ColumnNames(#\"Transform File (4)\"(#\"Sample File (4)\"))),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"id\", Int64.Type}, {\"date\", type datetime}, {\"author_id\", type any}, {\"mail_activity_type_id\", type text}, {\"model\", type text}, {\"res_id\", Int64.Type}}),\r",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true),\r",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Source.Name\"}),\r",
          "    #\"Extracted Text Between Delimiters\" = Table.TransformColumns(#\"Removed Columns\", {{\"author_id\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}, {\"mail_activity_type_id\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}}),\r",
          "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Extracted Text Between Delimiters\", {{\"author_id\", null}}),\r",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Replaced Errors\", each ([model] <> \"gamification.badge.user\") and ([author_id] <> null and [author_id] <> \"OdooBot\" and [author_id] <> \"Portal User Template\")),\r",
          "    #\"Inserted Time\" = Table.AddColumn(#\"Filtered Rows2\", \"Time\", each DateTime.Time([date]), type time),\r",
          "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Time\",{{\"date\", \"Behavior Date\"}, {\"Time\", \"Behavior Time\"}}),\r",
          "    #\"Filtered Rows3\" = Table.SelectRows(#\"Renamed Columns2\", each [Behavior Date] < RefreshCutOffDate),\r",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows3\",{{\"Behavior Date\", type date}}),\r",
          "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Changed Type1\", \"Start of Month\", each Date.StartOfMonth([Behavior Date]), type date)\r",
          "in\r",
          "    #\"Inserted Start of Month\""
        ],
        "kind": "m",
        "lineageTag": "797f4845-cadf-4720-8f56-c0abeae60b99",
        "queryGroup": "Historic Tables"
      },
      {
        "name": "users",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Sql.Database(\"bl-appdb\", \"lme\"),\r",
          "    dbo_users = Source{[Schema=\"dbo\",Item=\"users\"]}[Data],\r",
          "    #\"Filtered Rows\" = Table.SelectRows(dbo_users, each ([web_user_type] = \"U\")),\r",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Filtered Rows\",{\"revenue_code_id\", \"id\"}),\r",
          "    #\"Uppercased Text\" = Table.TransformColumns(#\"Removed Other Columns\",{{\"id\", Text.Upper, type text}}),\r",
          "    #\"Trimmed Text\" = Table.TransformColumns(#\"Uppercased Text\",{{\"id\", Text.Trim, type text}}),\r",
          "    #\"Cleaned Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"id\", Text.Clean, type text}})\r",
          "in\r",
          "    #\"Cleaned Text\""
        ],
        "kind": "m",
        "lineageTag": "b0d9ea90-2639-4ad1-97d0-43f2699756a9"
      },
      {
        "name": "parade_orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),\r",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Folder Path\", \"Attributes\"}),\r",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each Text.Contains([Folder Path], \"02 BL-Areas/bridge_iq/Data Sets/Parade/parade_orders_api_files\")),\r",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),\r",
          "    #\"Filtered Hidden Files2\" = Table.SelectRows(#\"Filtered Hidden Files1\", each [Attributes]?[Hidden]? <> true),\r",
          "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files2\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),\r",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Transform File (2)\"}),\r",
          "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),\r",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"id\", Int64.Type}, {\"reference_id\", type text}, {\"created_at\", type datetime}, {\"archived_at\", type datetime}, {\"src_city\", type text}, {\"src_state\", type text}, {\"src_date\", type date}, {\"src_postal_code\", type text}, {\"dst_city\", type text}, {\"dst_state\", type text}, {\"dst_date\", type date}, {\"dst_postal_code\", type text}, {\"num_stops\", Int64.Type}, {\"equipment\", type text}, {\"trailer_type\", type text}, {\"rate_customer\", type number}, {\"first_load\", type logical}, {\"customer_id\", type text}, {\"revenue_code\", Int64.Type}, {\"team_name\", type any}, {\"rep_email\", type text}, {\"rep_name\", type text}, {\"carrier_manager\", type text}, {\"category\", type text}, {\"conversion_category\", type text}, {\"partner\", type text}, {\"margin_amount\", type number}, {\"margin_pct\", type number}, {\"carrier_name\", type text}, {\"dot_number\", Int64.Type}, {\"mc_number\", Int64.Type}, {\"carrier_rate\", type number}}),\r",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"rate_customer\", Currency.Type}, {\"margin_amount\", Currency.Type}}),\r",
          "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type1\",{{\"reference_id\", Order.Ascending}}),\r",
          "    #\"Extracted Text After Delimiter\" = Table.TransformColumns(#\"Sorted Rows\", {{\"reference_id\", each Text.AfterDelimiter(_, \"-\"), type text}}),\r",
          "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Extracted Text After Delimiter\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),\r",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Blank Rows\",{{\"reference_id\", \"movement_id\"}}),\r",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Renamed Columns\", each ([category] <> \"outside_parade\" and [category] <> \"unsuccessful_quote\")),\r",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows1\", each ([category] <> \"digital_visit\")),\r",
          "    #\"Removed Duplicates\" = Table.Distinct(#\"Filtered Rows2\", {\"id\"}),\r",
          "    #\"Filtered Rows3\" = Table.SelectRows(#\"Removed Duplicates\", each [conversion_category] <> null and [conversion_category] <> \"\"),\r",
          "    #\"Filtered Orders on or after RefreshCutOffDate\" = Table.SelectRows(#\"Filtered Rows3\", each [created_at] >= RefreshCutOffDate),\r",
          "    #\"Appended Query\" = Table.Combine({#\"Filtered Orders on or after RefreshCutOffDate\", historic_parade_orders})\r",
          "in\r",
          "    #\"Appended Query\""
        ],
        "kind": "m",
        "lineageTag": "61f23af1-ed35-407d-a264-f6699d7ceacf"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Historic Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transform File from parade_orders"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from parade_orders\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from historic_parade_orders"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from historic_parade_orders\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "Transform File from behaviors"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from behaviors\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "8"
          }
        ],
        "folder": "Transform File from historic_behaviors"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from historic_behaviors\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_053b8f94-8098-4d5e-a426-d4389e96c71f",
        "fromColumn": "customer_id",
        "fromTable": "orders",
        "toColumn": "id",
        "toTable": "customer"
      },
      {
        "name": "1a296592-bd9b-5ee9-30cc-28baec10127b",
        "fromColumn": "movement_id",
        "fromTable": "driver_extra_pay",
        "toColumn": "id",
        "toTable": "movements"
      },
      {
        "name": "bd2189aa-abd5-78e7-2b7c-f0db9b14f31b",
        "fromColumn": "dest_stop_id",
        "fromTable": "movements",
        "isActive": false,
        "toColumn": "id",
        "toTable": "stop"
      },
      {
        "name": "3b645fbf-1a85-2d14-049b-7ea5a3187aca",
        "fromColumn": "order_id",
        "fromTable": "movements",
        "isActive": false,
        "toColumn": "id",
        "toTable": "stop"
      },
      {
        "name": "7850b1cc-8ad4-c1b1-ddf4-55b266d0bf32",
        "fromColumn": "shipper_stop_id",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "id",
        "toTable": "stop"
      },
      {
        "name": "779f5544-eab0-74a9-bad6-7588d81e623d",
        "fromColumn": "consignee_stop_id",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "id",
        "toTable": "stop"
      },
      {
        "name": "3acc3c4a-a03f-acb8-6429-bc08c3d9bf1e",
        "fromColumn": "contract_date",
        "fromTable": "customer",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "ed39f098-0988-1390-cb41-aafd2ff3537d",
        "fromColumn": "entered_date",
        "fromTable": "customer",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "8674efd5-c23a-c89b-43b8-adac6699e63d",
        "fromColumn": "bill_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "2daff771-7d65-d317-4dfb-942714730a84",
        "fromColumn": "consignee_sched_early_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "e113a5d4-cb52-a27d-5df9-75dfbebd863c",
        "fromColumn": "consignee_sched_late_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "d4ef4df2-bec2-44d5-bf6e-66c89dcd2ef0",
        "fromColumn": "order_entered_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "d11a4704-dac2-0387-6936-11ef3940a42d",
        "fromColumn": "shipper_sched_early_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "6b0103e2-c302-0a04-0c64-8af2b256a7c8",
        "fromColumn": "shipper_sched_late_date",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "0d2ecadc-7c8b-269f-ab4b-de1268e2f483",
        "fromColumn": "actual_arrival",
        "fromTable": "stop",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "0e69daf2-bef4-86e2-aa09-108aee33b91b",
        "fromColumn": "actual_departure",
        "fromTable": "stop",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "6276f072-a3ee-c1fc-c4b1-517b88c7d59d",
        "fromColumn": "sched_arrive_early",
        "fromTable": "stop",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "26526cb0-a937-b319-65ae-48a780fa9edf",
        "fromColumn": "sched_arrive_late",
        "fromTable": "stop",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "ee862cd5-5016-c8ea-874c-0c51d814e93d",
        "fromColumn": "invoice_recv_date",
        "fromTable": "movements",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "e526fd1e-adf0-5eaa-b7c5-c3c82cd0431d",
        "fromColumn": "xfer2settle_date",
        "fromTable": "movements",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "efc58c67-909a-4b4a-19d0-a4d56e096825",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "order_id",
        "fromTable": "movements",
        "toColumn": "id",
        "toTable": "orders"
      },
      {
        "name": "cf2fcd5c-1981-15d2-963c-fc1252ddd9e2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ID",
        "fromTable": "job_history",
        "toColumn": "ID",
        "toTable": "employees"
      },
      {
        "name": "04840b3e-b994-2416-ad39-09cad95d7e06",
        "fromColumn": "Termination Date",
        "fromTable": "employees",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "b6f3886a-3dcf-572c-d056-6ad29fb6613c",
        "fromColumn": "Hire Date",
        "fromTable": "employees",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "5dac4df4-6467-9e38-1076-e4ffeb26879b",
        "fromColumn": "Job End Date",
        "fromTable": "job_history",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "4b385713-6fc9-5a64-8cd4-91ebf08a6205",
        "fromColumn": "Job Start Date",
        "fromTable": "job_history",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "54fc379f-b1bb-4bc1-0bbd-47442371291d",
        "fromColumn": "Hire Date",
        "fromTable": "salesperson_key",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "4a96cf76-d46c-91c7-0346-12330f400b79",
        "fromColumn": "Termination Date",
        "fromTable": "salesperson_key",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "8714dc3c-4744-58cf-30fd-cc1bd116d520",
        "fromColumn": "entered_date",
        "fromTable": "callins",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "9c9f9ee7-aadc-8abf-19fa-be24e4230ebf",
        "fromColumn": "movement_id",
        "fromTable": "callins",
        "toColumn": "id",
        "toTable": "movements"
      },
      {
        "name": "abba11bd-b68c-b7d9-b958-9f2db5bacd1f",
        "fromColumn": "Movement ID",
        "fromTable": "overdue_check_calls",
        "toColumn": "id",
        "toTable": "movements"
      },
      {
        "name": "c40037d6-e2b6-dcf7-3efd-bb935c17f1ee",
        "fromColumn": "Check Call Date",
        "fromTable": "overdue_check_calls",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "fe94c6fe-a585-40a4-20ea-f103928fcb09",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Movement ID",
        "fromTable": "crt_movement_data",
        "toColumn": "id",
        "toTable": "movements"
      },
      {
        "name": "fc5fc8e4-1849-d3ac-b3fe-598abd29f064",
        "fromColumn": "Avail Time",
        "fromTable": "crt_movement_data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "9add36d8-90b6-034d-1044-57c66973ec3b",
        "fromColumn": "Covered Time",
        "fromTable": "crt_movement_data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "dd525f85-0cde-3300-3159-dc880be07c34",
        "fromColumn": "Give Back Time ",
        "fromTable": "crt_movement_data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "761c2141-951b-0a3d-6e7c-70396138b4a2",
        "fromColumn": "Load Board Time",
        "fromTable": "crt_movement_data",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "f84bceea-6db2-2507-b712-d1cba07d870b",
        "fromColumn": "lane",
        "fromTable": "orders",
        "toColumn": "lane",
        "toTable": "lane"
      },
      {
        "name": "7de0ad41-c2eb-d29c-91b4-6eeba6627d01",
        "fromColumn": "Order ID",
        "fromTable": "crt_movement_data",
        "isActive": false,
        "toColumn": "id",
        "toTable": "orders"
      },
      {
        "name": "c8de8f41-77b3-7a78-50c4-d71de15d7c08",
        "fromColumn": "Month",
        "fromTable": "margin_load_count_goals",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "0a840ca3-82a7-107f-ba07-a21e792bf8cd",
        "fromColumn": "Salesperson Name",
        "fromTable": "margin_load_count_goals",
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "328ffb62-6ce8-4861-9f4b-2ef8226436f6",
        "fromColumn": "Observed Holidays",
        "fromTable": "observed_holidays",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ed26f4c3-9c62-405b-8c3b-c81747750938"
      },
      {
        "name": "67d7b0ce-f052-2db3-febd-64c18d2d5c79",
        "fromColumn": "salesperson_id",
        "fromTable": "orders",
        "toColumn": "McLeod Salesperson Code",
        "toTable": "salesperson_key"
      },
      {
        "name": "260fb3f0-b8a2-161b-022b-537a60bcbdf7",
        "fromColumn": "Month",
        "fromTable": "daily_number_override",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "AutoDetected_4fbcf0da-778d-42c0-b6de-b0fa0815d61f",
        "fromColumn": "mail_activity_type_id",
        "fromTable": "behaviors",
        "toColumn": "mail_activity_type_id",
        "toTable": "behavior_key"
      },
      {
        "name": "79d43f6d-21f5-48c0-7149-f61c8dec3df9",
        "fromColumn": "BehaviorID",
        "fromTable": "behavior_goals",
        "toColumn": "mail_activity_type_id",
        "toTable": "behavior_key"
      },
      {
        "name": "17e42020-4ded-1485-8b71-a2518685d1c0",
        "fromColumn": "Behavior Date",
        "fromTable": "behaviors",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "61279972-cef0-62c0-7673-008ec56b0e64",
        "fromColumn": "Month",
        "fromTable": "behavior_goals",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "30fc2257-db24-5b7f-69f4-4cac84f7474f",
        "fromColumn": "Salesperson",
        "fromTable": "behavior_goals",
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "4356cecc-3a49-50e0-30e2-1296be23ba81",
        "fromColumn": "author_id",
        "fromTable": "behaviors",
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "8577c885-ec16-806b-b3e5-2a66ee2d2afe",
        "fromColumn": "Month",
        "fromTable": "customer_margin_goal",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "0e539d6e-244b-340b-1d2e-74a2accdfa2e",
        "fromColumn": "Customer Code",
        "fromTable": "customer_margin_goal",
        "toColumn": "id",
        "toTable": "customer"
      },
      {
        "name": "a2468aca-e09d-24fe-5861-daa212106492",
        "fromColumn": "Salesperson",
        "fromTable": "customer_margin_goal",
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "AutoDetected_8e587438-2a6b-4588-b4c6-9e458e209910",
        "fromColumn": "Stage",
        "fromTable": "healthy_pipeline_goals",
        "toColumn": "Stage Name",
        "toTable": "crm_stages"
      },
      {
        "name": "3e8afa0a-dbfe-d267-4bad-71cf3030a35c",
        "fromColumn": "Saleperson Name",
        "fromTable": "healthy_pipeline_goals",
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "e7de55f3-7932-fa99-43dd-f343443de0d7",
        "fromColumn": "Start of Month",
        "fromTable": "behaviors",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "887cd992-832e-9981-0f13-f18c3c4a0adf",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Movement ID",
        "fromTable": "sop_issues",
        "toColumn": "id",
        "toTable": "movements"
      },
      {
        "name": "6a4aa77d-52ca-87fc-c347-8193c089f98a",
        "fromColumn": "Date_time",
        "fromTable": "sop_issues",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "22881cbf-eb4e-4f66-afd5-a0ec21a1eb7c",
        "fromColumn": "Hire Date",
        "fromTable": "dispatcher_key",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_602d0dc9-a979-4162-a15e-cf937935b0b7"
      },
      {
        "name": "89783f8c-5a09-40cd-8fe0-005c7da2b54b",
        "fromColumn": "Termination Date",
        "fromTable": "dispatcher_key",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7e773c2c-a1bd-4f2f-b9f7-efdc6b4a7c73"
      },
      {
        "name": "1f5bca13-1055-607a-5967-aaf6ba56bc12",
        "fromColumn": "dispatcher_user_id",
        "fromTable": "movements",
        "isActive": false,
        "toColumn": "McLeod User Code",
        "toTable": "dispatcher_key"
      },
      {
        "name": "f4b6e82a-2bfa-abb2-305e-7bbc5143fe43",
        "fromColumn": "entered_user_id",
        "fromTable": "orders",
        "isActive": false,
        "toColumn": "McLeod User Code",
        "toTable": "dispatcher_key"
      },
      {
        "name": "e5251930-485b-f0d0-4926-3302f3aa7a0a",
        "fromColumn": "entered_by",
        "fromTable": "callins",
        "isActive": false,
        "toColumn": "McLeod User Code",
        "toTable": "dispatcher_key"
      },
      {
        "name": "fadb546c-038f-7c1d-63cf-70dbeb142463",
        "fromColumn": "salesperson_id",
        "fromTable": "customer",
        "isActive": false,
        "toColumn": "McLeod Salesperson Code",
        "toTable": "salesperson_key"
      },
      {
        "name": "14e715b2-e8b7-477d-bad8-c42bd7a42ed5",
        "fromColumn": "Commission Month",
        "fromTable": "pay_schedule",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5204cc32-7744-4162-bd7a-37c8843dcd5c"
      },
      {
        "name": "5e94ac41-9664-4dd5-8b2a-ee99b5b474b1",
        "fromColumn": "Pay Date",
        "fromTable": "pay_schedule",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_984f2224-97c9-4ff5-8864-d5ee44b7d514"
      },
      {
        "name": "b0b1455c-2476-6b04-ba9a-c6e74e62876a",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "toColumn": "Commission Month",
        "toTable": "pay_schedule"
      },
      {
        "name": "7862f466-b445-a26d-b65e-f39667eca0f3",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "isActive": false,
        "toColumn": "Pay Date",
        "toTable": "pay_schedule"
      },
      {
        "name": "646c1a80-76eb-d026-541d-f24cb7513861",
        "fromColumn": "users.revenue_code_id",
        "fromTable": "salesperson_key",
        "toColumn": "rev_code_id",
        "toTable": "rev_codes"
      },
      {
        "name": "f5de2138-734f-d1f0-c3e9-1e4db079f31c",
        "fromColumn": "user_id",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Name",
        "toTable": "salesperson_key"
      },
      {
        "name": "82c544f0-1454-b8bc-6636-53d24c9c968d",
        "fromColumn": "res_id",
        "fromTable": "behaviors",
        "toColumn": "id",
        "toTable": "crm"
      },
      {
        "name": "0f21aa1b-6b85-8918-e339-9d77cc645f4e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "x_studio_mcleod_code",
        "fromTable": "crm",
        "toColumn": "id",
        "toTable": "customer"
      },
      {
        "name": "505e4f7a-91da-3795-4f6c-0ce71fe9a849",
        "fromColumn": "Stage",
        "fromTable": "crm",
        "toColumn": "Stage Name",
        "toTable": "crm_stages"
      },
      {
        "name": "3b1e061c-a5ff-e2d1-f792-0655bae1a0fe",
        "fromColumn": "activity_date_deadline",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "e3d150d3-95a8-be74-fb25-f8dbed528f15",
        "fromColumn": "date_open",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "381bfd96-8b6a-75a1-cbd3-a66ebf4bc532",
        "fromColumn": "Last Stage Change",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "f0de3666-daea-391d-95c0-9e626b3fd4ac",
        "fromColumn": "x_studio_enrichment_date",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "5bcae216-568f-9183-68ca-54fcb10620d3",
        "fromColumn": "x_studio_lead_passed_date",
        "fromTable": "crm",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "5ecbe4d8-a96b-f32b-3c0f-b5a97190a921",
        "fromColumn": "override_payee_id",
        "fromTable": "movements",
        "toColumn": "id",
        "toTable": "carrier_key"
      },
      {
        "name": "AutoDetected_c95c3e67-b4b1-4b4b-8a21-220baa5e0198",
        "fromColumn": "Division",
        "fromTable": "job_history",
        "toColumn": "Division",
        "toTable": "division_key"
      },
      {
        "name": "74d5951a-5976-dd47-ee9d-179d8dafcd2f",
        "fromColumn": "Devision",
        "fromTable": "salesperson_key",
        "isActive": false,
        "toColumn": "Division",
        "toTable": "division_key"
      },
      {
        "name": "1959e8d0-2212-ed49-38cb-7604b93b7428",
        "fromColumn": "ID",
        "fromTable": "job_history",
        "toColumn": "ID",
        "toTable": "salesperson_key"
      },
      {
        "name": "cf8a66c6-ea49-e82b-8531-36f405b7ac81",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ID",
        "fromTable": "employees",
        "toColumn": "ID",
        "toTable": "dispatcher_key"
      },
      {
        "name": "c068525c-5985-47a0-a2fb-8f38a5e05167",
        "fromColumn": "Hand over",
        "fromTable": "crt_movement_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5d529210-5800-429f-b2e3-388a81d360f9"
      },
      {
        "name": "1b268b65-e261-470c-8a0d-ca966e3223f0",
        "fromColumn": "Ship date at Avail",
        "fromTable": "crt_movement_data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_67948750-4a55-4170-865e-d76c6427f063"
      },
      {
        "name": "b7086df5-a15e-acff-d67c-d6cd33ee67fa",
        "fromColumn": "wolf_pack",
        "fromTable": "account_rep",
        "toColumn": "wolf_pack",
        "toTable": "wolf_pack"
      },
      {
        "name": "ff88e45c-e612-46ba-ab09-9a3fade68d98",
        "fromColumn": "account_rep",
        "fromTable": "rev_codes",
        "toColumn": "account_rep",
        "toTable": "account_rep"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_e2c46345-9a3a-40bb-ae4b-e3de83b68f6a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6c3bb3fb-7b5d-4274-9d4e-e1248ab9b4bb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "94d16981-47d6-4a12-b679-60a15a81adaa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a2bffae0-dcee-469a-9fc3-284290409d83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3afaeb38-8673-4836-aa75-1bfe2132552e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "c92f4d77-7244-4d15-b64a-4fcb7e7ed13e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "975122a3-f0a4-40c2-8cd3-9905dbc0e4a8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1d1d3d1c-fa00-46f4-8973-24e323810c82",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0584f17d-a3d9-46d4-8630-86b276dee385",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ba7889b4-2bf2-4edb-b269-96f9e206d526",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6461c2d1-3738-45f1-b388-7322d40769dd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6b605355-e8d7-47d5-baa2-4a35ae237e1f",
                "ordinal": 3
              }
            ],
            "lineageTag": "ba91ed87-3acd-4977-ae79-32a0e079a4f3"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f469d362-f628-474e-a2a9-3b6d1ffad511",
        "partitions": [
          {
            "name": "DateTableTemplate_e2c46345-9a3a-40bb-ae4b-e3de83b68f6a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "stop",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "actual_arrival",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9ef4b83e-107f-4d5b-8219-dfc77985e9a0",
            "sourceColumn": "actual_arrival",
            "summarizeBy": "none"
          },
          {
            "name": "actual_departure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "293412a0-bf03-4826-8a97-1a81079f6504",
            "sourceColumn": "actual_departure",
            "summarizeBy": "none"
          },
          {
            "name": "address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6adf536-0d64-4049-b9cb-fb4e2b7c21ce",
            "sourceColumn": "address",
            "summarizeBy": "none"
          },
          {
            "name": "appt_required",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b13783ca-5bed-4105-a1c6-9e462586caf7",
            "sourceColumn": "appt_required",
            "summarizeBy": "none"
          },
          {
            "name": "city_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1bc276e1-1a39-4b1a-8aa8-2728fddc3773",
            "sourceColumn": "city_id",
            "summarizeBy": "sum"
          },
          {
            "name": "city_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9224492-5ca3-41b2-9d65-50294df8851e",
            "sourceColumn": "city_name",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a0d9d49-dd12-4e28-8e95-dd506031ddc7",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "21935e7d-cb68-49b5-a964-c5973162f4eb",
            "sourceColumn": "latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "location_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7e09021-9d78-46ed-8dfa-ab3c36eab7e0",
            "sourceColumn": "location_id",
            "summarizeBy": "none"
          },
          {
            "name": "location_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87eabea0-fa60-4044-b247-608203a525dd",
            "sourceColumn": "location_name",
            "summarizeBy": "none"
          },
          {
            "name": "longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b288303-c5a3-441a-b56d-715dfa896c8b",
            "sourceColumn": "longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "movement_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15b95255-a95d-4fc8-9d47-c75b7eceafea",
            "sourceColumn": "movement_id",
            "summarizeBy": "none"
          },
          {
            "name": "movement_sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dfd5a8c4-fb75-4f59-88b6-88cae35d48be",
            "sourceColumn": "movement_sequence",
            "summarizeBy": "sum"
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b478b71-b124-4352-9f90-a0a2a6900144",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f215497-bae3-4a80-ba97-5c3da84c26e0",
            "sourceColumn": "order_sequence",
            "summarizeBy": "sum"
          },
          {
            "name": "sched_arrive_early",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fc6012aa-e2cc-4aec-a09d-a2a3a02fe890",
            "sourceColumn": "sched_arrive_early",
            "summarizeBy": "none"
          },
          {
            "name": "sched_arrive_late",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8530f8b5-73d3-460b-a721-ad343fc21d57",
            "sourceColumn": "sched_arrive_late",
            "summarizeBy": "none"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e620a96a-943e-4e4d-bb7a-f68f5368bd54",
            "sourceColumn": "state",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "640d19de-58ab-474a-a91b-e3238802af05",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "stop_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e0a8995-6d9d-4c81-8a65-24f6eab50d33",
            "sourceColumn": "stop_type",
            "summarizeBy": "none"
          },
          {
            "name": "zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d791d6c9-6fa2-428e-a0a4-648163a2cc09",
            "sourceColumn": "zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "zone_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a16067ee-c856-4307-a0df-29403459c143",
            "sourceColumn": "zone_id",
            "summarizeBy": "none"
          },
          {
            "name": "actual_arrival_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "82b24748-fe8e-41cd-a0a9-18a22857365b",
            "sourceColumn": "actual_arrival_time",
            "summarizeBy": "none"
          },
          {
            "name": "actual_departure_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "fe8368d4-6f12-496d-b828-1c39ec0ace1a",
            "sourceColumn": "actual_departure_time",
            "summarizeBy": "none"
          },
          {
            "name": "sched_arrive_early_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "6f719216-dbb6-4dc5-b0fd-67427613bde4",
            "sourceColumn": "sched_arrive_early_time",
            "summarizeBy": "none"
          },
          {
            "name": "sched_arrive_late_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "0346c9b7-6f65-40b3-b421-796db62d9f5d",
            "sourceColumn": "sched_arrive_late_time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "64234da3-1a77-453d-a2c0-eefc98a8f918",
        "partitions": [
          {
            "name": "stop",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_stop = Source{[Schema=\"dbo\",Item=\"stop\"]}[Data],",
                "    #\"Filtered Stops Post RefresshCutOffDate\" = Table.SelectRows(dbo_stop, each [sched_arrive_early] >= RefreshCutOffDate),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Stops Post RefresshCutOffDate\",{\"company_id\", \"address2\", \"appointment_status_id\", \"appt_contact_name\", \"hub\", \"cases\", \"confirmed\", \"contact_name\", \"dist_from_prev\", \"dist_from_prev_um\", \"driver_load_unload\", \"edi_code\", \"edi_loc_code\", \"eta\", \"eta_distance\", \"eta_late\", \"eta_oor\", \"google_place_id\", \"inbound_status\", \"late_eta_colorcode\", \"late_route_status\", \"manifest_fgp_uid\", \"manifest_reg_uid\", \"move_dist_from_preassign\", \"move_dist_from_preassign_um\", \"move_dist_from_previous\", \"move_dist_from_previous_um\", \"operational_status\", \"orig_sched_early\", \"orig_sched_late\", \"pallets_dropped\", \"pallets_picked_up\", \"phone\", \"planned_arrival_time\", \"ponum\", \"prior_uncleared_stops\", \"projected_arrival\", \"rate_dist_from_previous\", \"rate_dist_from_previous_um\", \"refno\", \"requested_service\", \"seal\", \"service_date\", \"showas_address\", \"showas_address2\", \"showas_city_id\", \"showas_city_name\", \"showas_location_id\", \"showas_location_name\", \"showas_state\", \"showas_zip_code\", \"signed_for_name\", \"txl_uid\", \"volume\", \"volume_um\", \"weight\", \"weight_um\", \"ic_stop_id\", \"grouped_id\", \"payment_code_reviewed\", \"trimble_place_id\"}),",
                "    #\"Inserted actual_arrival_time\" = Table.AddColumn(#\"Removed Columns\", \"actual_arrival_time\", each DateTime.Time([actual_arrival]), type time),",
                "    #\"Inserted actual_departure_time\" = Table.AddColumn(#\"Inserted actual_arrival_time\", \"actual_departure_time\", each DateTime.Time([actual_departure]), type time),",
                "    #\"Inserted sched_arrive_early_time\" = Table.AddColumn(#\"Inserted actual_departure_time\", \"sched_arrive_early_time\", each DateTime.Time([sched_arrive_early]), type time),",
                "    #\"Inserted sched_arrive_late_time\" = Table.AddColumn(#\"Inserted sched_arrive_early_time\", \"sched_arrive_late_time\", each DateTime.Time([sched_arrive_late]), type time),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted sched_arrive_late_time\",{{\"actual_arrival\", type date}, {\"actual_departure\", type date}, {\"sched_arrive_early\", type date}, {\"sched_arrive_late\", type date}}),",
                "    #\"Appended Query\" = Table.Combine({#\"Changed Type\", stop_historic})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "address1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "405261b4-5527-4b91-a36b-f9098cc3987b",
            "sourceColumn": "address1",
            "summarizeBy": "none"
          },
          {
            "name": "average_pay_days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cbc3ba3d-6291-49ff-870c-15f96efe8933",
            "sourceColumn": "average_pay_days",
            "summarizeBy": "sum"
          },
          {
            "name": "bill_due_days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35353f72-9792-472a-a60e-ad7993b70c17",
            "sourceColumn": "bill_due_days",
            "summarizeBy": "sum"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f07047-614b-4898-8889-d73fe2d4e180",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "city_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee772063-c592-457f-aa6b-4afef607f479",
            "sourceColumn": "city_id",
            "summarizeBy": "sum"
          },
          {
            "name": "credit_limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "88053ca8-8607-4de6-b5f1-f400fc8cd0b5",
            "sourceColumn": "credit_limit",
            "summarizeBy": "sum"
          },
          {
            "name": "credit_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7472fbe3-da0f-4a08-8048-ea39ea9845a8",
            "sourceColumn": "credit_status",
            "summarizeBy": "none"
          },
          {
            "name": "d_and_b_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2b59c0c-b8fe-4bdf-bf51-6174e7065e34",
            "sourceColumn": "d_and_b_code",
            "summarizeBy": "none"
          },
          {
            "name": "d_and_b_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d5ab538-2945-401b-92e4-8b2227de1f1c",
            "sourceColumn": "d_and_b_number",
            "summarizeBy": "none"
          },
          {
            "name": "tax_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d43b519f-b773-4aa4-a68e-a4c83eda6838",
            "sourceColumn": "tax_id",
            "summarizeBy": "none"
          },
          {
            "name": "entered_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4452d5a4-02e8-43f0-9ec8-633ab461e62a",
            "sourceColumn": "entered_date",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50d07ea9-4884-4dc2-87b2-29bd78afcc3b",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "is_active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a97dd9d-0467-4607-8ab4-939aafd62d9a",
            "sourceColumn": "is_active",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8190aad3-fae7-4f38-8aa3-1d1836e0e17d",
            "sourceColumn": "latitude",
            "summarizeBy": "sum"
          },
          {
            "name": "longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8cd09e1a-840c-485b-9d66-026f44c1e69b",
            "sourceColumn": "longitude",
            "summarizeBy": "sum"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a42806e3-c262-4ebf-9882-9cc989fec2f0",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "prev_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "428e0960-1dff-4d4d-b5e8-4137055a054e",
            "sourceColumn": "prev_code",
            "summarizeBy": "none"
          },
          {
            "name": "salesperson_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a047402b-f6d8-47c2-a267-1b1341972b22",
            "sourceColumn": "salesperson_id",
            "summarizeBy": "none"
          },
          {
            "name": "state_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d2c5dad-4195-413b-abf2-b5609130a312",
            "sourceColumn": "state_id",
            "summarizeBy": "none"
          },
          {
            "name": "zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "401508b0-b270-48c6-a47a-f942a3308061",
            "sourceColumn": "zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "zone_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64b1f733-d375-4436-84bb-ed1bbac6aa64",
            "sourceColumn": "zone_id",
            "summarizeBy": "none"
          },
          {
            "name": "contract_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "8fa99a42-a5f4-4b86-a7a4-5d404ca5bd0e",
            "sourceColumn": "contract_date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ac556894-2d76-4b17-a7fb-97f07f433a0e",
        "partitions": [
          {
            "name": "customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_customer = Source{[Schema=\"dbo\",Item=\"customer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_customer,{\"company_id\", \"activity_count\", \"activity_start_date\", \"add_empty_distance_occ\", \"add_finance_charge\", \"address2\", \"allow_inc_in_frt\", \"auto_rate\", \"available_template\", \"average_bill\", \"average_bill_c\", \"average_bill_d\", \"average_bill_n\", \"average_bill_r\", \"balance\", \"balance_c\", \"balance_d\", \"balance_n\", \"balance_r\", \"benchmark_ctg_uid\", \"benchmark_tar_uid\", \"bill_format_flag\", \"bill_template\", \"bill_transfer_when\", \"billed_loads\", \"blanket_buy_tariff_id\", \"blanket_sell_tariff_id\", \"bl_logo\", \"bl_logo_name\", \"bridge_id\", \"brokerage_filter\", \"business_hours\", \"business_number\", \"buy_tariff_id\", \"category\", \"cert_of_ins_date\", \"charge_detention\", \"chassis_chargeby\", \"chassis_freedays\", \"chassis_rate\", \"chassis_rate_c\", \"chassis_rate_d\", \"chassis_rate_n\", \"chassis_rate_r\", \"coll_thresh_pd1\", \"coll_thresh_pd1_c\", \"coll_thresh_pd1_d\", \"coll_thresh_pd1_n\", \"coll_thresh_pd1_r\", \"coll_thresh_pd2\", \"coll_thresh_pd2_c\", \"coll_thresh_pd2_d\", \"coll_thresh_pd2_n\", \"coll_thresh_pd2_r\", \"coll_thresh_pd3\", \"coll_thresh_pd3_c\", \"coll_thresh_pd3_d\", \"coll_thresh_pd3_n\", \"coll_thresh_pd3_r\", \"coll_thresh_pd4\", \"coll_thresh_pd4_c\", \"coll_thresh_pd4_d\", \"coll_thresh_pd4_n\", \"coll_thresh_pd4_r\", \"collections_id\", \"collections_ok\", \"confidence_level\", \"container_chargeby\", \"container_freedays\", \"container_rate\", \"container_rate_c\", \"container_rate_d\", \"container_rate_n\", \"container_rate_r\", \"contract_cbc\", \"contract_ccc\", \"contract_gbc\", \"contract_gcc\", \"contract_sbc\", \"contract_scc\", \"controlling_carrier_code\", \"conversion_date\", \"cost_ctg_uid\", \"cost_tar_uid\", \"covered_template\", \"cp_logo\", \"cp_logo_name\", \"credit_application\", \"credit_check_date\", \"credit_limit_c\", \"credit_limit_d\", \"credit_limit_n\", \"credit_limit_r\", \"credit_warning_pct\", \"ctg_uid\", \"currency_type\", \"cust_stmt_template\", \"d_and_b_date\", \"days_between_calls\", \"deadhead_target\", \"ded_last_fixed_cost_billdt\", \"dedicated_cycle\", \"dedicated_revenue_code_id\", \"dedicated_seg_alloc_code\", \"dedicated_start_day\", \"dedicated_template\", \"def_rate_confirm_temp\", \"delivered_template\", \"departure_date_at\", \"distance_method\", \"distance_profile\", \"distance_source\", \"distance_type\", \"driver_load\", \"empty_distance_charge_id\", \"empty_distance_rate\", \"enable_notifications\", \"enforce_dep_dates\", \"excise_taxable\", \"expected_close\", \"extend_rates\", \"factor_percent\", \"factor_receivables\", \"factoring_id\", \"fak_profile_id\", \"fourkites_customer_id\", \"fuel_amount\", \"fuel_base_price\", \"fuel_credit\", \"fuel_method\", \"fuel_percent\", \"fuel_price_region\", \"fuel_surcharge_id\", \"fuel_surchg_enddt\", \"fuel_surchg_strtdt\", \"fuel_variance\", \"global_detention\", \"google_place_id\", \"gp_exclude\", \"gp_exported\", \"grace_period\", \"high_balance\", \"high_balance_c\", \"high_balance_d\", \"high_balance_n\", \"high_balance_r\", \"include_by_date\", \"include_empty_distance\", \"include_fuel_surcharge\", \"include_split_point\", \"is_consignee\", \"is_distribution_center\", \"is_drop_yard\", \"is_geocoded\", \"is_pallets_required\", \"is_shipper\", \"is_trailer_pool_required\", \"jaguar_id\", \"last_bill_date\", \"last_fin_charge_dt\", \"last_pay_date\", \"last_ship_date\", \"location_id\", \"macropoint_requestor_id\", \"main_phone\", \"manual_exchange\", \"mark_plan_id\", \"max_pay_percent\", \"misc_bill_template\", \"monthly_order_goal\", \"motor_carrier_id\", \"next_call_date\", \"next_rec_call\", \"nxt_action_code_id\", \"nxt_action_date\", \"operations_user\", \"order_count\", \"order_detail_at\", \"order_start_date\", \"p44_profile_id\", \"paid_loads\", \"pay_days_date\", \"pay_days_orders\", \"payee_id\", \"pd0_alert\", \"pd1_np_auto\", \"pd1_sp_auto\", \"pd1_sp_thresh\", \"pd1_sp_thresh_c\", \"pd1_sp_thresh_d\", \"pd1_sp_thresh_n\", \"pd1_sp_thresh_r\", \"pd2_np_auto\", \"pd2_sp_auto\", \"pd2_sp_thresh\", \"pd2_sp_thresh_c\", \"pd2_sp_thresh_d\", \"pd2_sp_thresh_n\", \"pd2_sp_thresh_r\", \"pd3_np_auto\", \"pd3_sp_auto\", \"pd3_sp_thresh\", \"pd3_sp_thresh_c\", \"pd3_sp_thresh_d\", \"pd3_sp_thresh_n\", \"pd3_sp_thresh_r\", \"pd4_np_auto\", \"pd4_sp_auto\", \"pd4_sp_thresh\", \"pd4_sp_thresh_c\", \"pd4_sp_thresh_d\", \"pd4_sp_thresh_n\", \"pd4_sp_thresh_r\", \"plc_uid\", \"post_summary_dtl\", \"potential\", \"potential_c\", \"potential_d\", \"potential_n\", \"potential_r\", \"primary_agency\", \"primary_commodity_id\", \"primary_contact\", \"primary_sort\", \"primary_trailer_type\", \"print_containers\", \"progress_template\", \"prospect_type_id\", \"quebec_number\", \"quote_days_to_expire\", \"rate_override_nmfc_code\", \"reassign_profile_id\", \"rec_call_days\", \"remarks\", \"revenue\", \"revenue_c\", \"revenue_d\", \"revenue_n\", \"revenue_r\", \"revenue_start_date\", \"sales_manager_id\", \"sales_status_id\", \"search_city\", \"search_state_id\", \"search_zip_code\", \"secondary_sort\", \"sell_tariff_id\", \"service_fail_cons\", \"service_fail_drop\", \"service_fail_pick\", \"service_fail_ship\", \"service_failures\", \"service_failures_review\", \"sic_code\", \"start_date\", \"summary_billing\", \"summary_template\", \"tar_uid\", \"target_profit\", \"tenfour_customer_id\", \"type_of\", \"use_local_mile\", \"vm_part_update\", \"waterfall_lead_time\", \"waterfall_notify_email\", \"waterfall_process\", \"website_url\", \"wf_queue\", \"require_tracking\", \"required_vendor\", \"disable_automatic_tracking\", \"tracking_hours_prior\", \"bankyacct\", \"bankyname\", \"bankyphone\", \"bankycsz\", \"bankyadd\", \"wf_bwop\", \"wf_auto_renbill\", \"wf_autobill\", \"wf_ab_po_chk\", \"display_ysplit_stops\", \"waterfall_auto_route_guides\", \"display_eta\", \"cust_requestor_load_id\", \"trimble_place_id\", \"is_intercompany\", \"ic_company_id\", \"shipment_ident_type\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"dot_number\", \"tax_id\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"entered_date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "orders",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "bill_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "19c8c8d1-414d-4777-afb3-afe8e8ac0cf4",
            "sourceColumn": "bill_date",
            "summarizeBy": "none"
          },
          {
            "name": "bill_distance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd0b7e33-599c-4223-b831-792339ac1362",
            "sourceColumn": "bill_distance",
            "summarizeBy": "sum"
          },
          {
            "name": "billing_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dddd2300-6977-4d12-8fc2-73a17faad6c3",
            "sourceColumn": "billing_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_po",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a62a3bd-20f0-48c0-abe3-a02c955850a2",
            "sourceColumn": "customer_po",
            "summarizeBy": "none"
          },
          {
            "name": "bol_received",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aec9fb56-65ea-40db-bd9b-63ffdea76b14",
            "sourceColumn": "bol_received",
            "summarizeBy": "none"
          },
          {
            "name": "commodity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7acb004-e01d-4766-a097-e9fabcf24a4f",
            "sourceColumn": "commodity",
            "summarizeBy": "none"
          },
          {
            "name": "commodity_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19d6fe85-d8c4-418c-8047-dfb5c982e25f",
            "sourceColumn": "commodity_id",
            "summarizeBy": "none"
          },
          {
            "name": "bol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d3dc956-e392-4b3c-bf5d-a2f8b579a141",
            "sourceColumn": "bol",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_stop_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a885f73-200b-4372-b95f-857be338fc75",
            "sourceColumn": "consignee_stop_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a389d148-0c96-4c67-a170-9853c3955508",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "entered_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "279e38e3-9eae-4e4d-8a17-21eb5ed9d914",
            "sourceColumn": "entered_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "equipment_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "843075e8-bf8a-48ef-a5c0-d20cdb5bf2d6",
            "sourceColumn": "equipment_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "extra_deliveries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd596653-d7b6-4e0e-a54d-c3a6ded9a29e",
            "sourceColumn": "extra_deliveries",
            "summarizeBy": "sum"
          },
          {
            "name": "extra_pickups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52b57ad3-2a00-4072-ae93-a0b46184f926",
            "sourceColumn": "extra_pickups",
            "summarizeBy": "sum"
          },
          {
            "name": "freight_charge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "721c0cee-da14-477d-ac49-a38b8c34c3b9",
            "sourceColumn": "freight_charge",
            "summarizeBy": "sum"
          },
          {
            "name": "hazmat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "094a66d8-43de-42f3-9204-bbd7cda021f0",
            "sourceColumn": "hazmat",
            "summarizeBy": "none"
          },
          {
            "name": "hazmat_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d80b6e92-703b-48f3-ad85-91fc22706e9c",
            "sourceColumn": "hazmat_code",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6067274-d93c-481e-9248-e2fb8d480f7f",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "on_hold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e82559aa-6b31-4560-b852-4f186d7c03ef",
            "sourceColumn": "on_hold",
            "summarizeBy": "none"
          },
          {
            "name": "operations_user",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab0c9eec-ff05-4521-9cd9-c72121526898",
            "sourceColumn": "operations_user",
            "summarizeBy": "none"
          },
          {
            "name": "order_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21a4a619-7413-47d5-ac64-5e6985983238",
            "sourceColumn": "order_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0db44e6f-bce6-4c6b-b725-c23f330ff00b",
            "sourceColumn": "order_value",
            "summarizeBy": "sum"
          },
          {
            "name": "order_entered_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6308c6ae-434c-42be-865d-44cf9a7a7922",
            "sourceColumn": "order_entered_date",
            "summarizeBy": "none"
          },
          {
            "name": "other_charges_total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ae28246c-66ca-4b52-8639-09304efac25e",
            "sourceColumn": "other_charges_total",
            "summarizeBy": "sum"
          },
          {
            "name": "pieces",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "37c4e511-4f1f-499c-805b-89f9cb2693f9",
            "sourceColumn": "pieces",
            "summarizeBy": "sum"
          },
          {
            "name": "revenue_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c523dabb-a0d1-4050-8f06-42d821cbe67e",
            "sourceColumn": "revenue_code_id",
            "summarizeBy": "none"
          },
          {
            "name": "round_trip",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c0a91ac-cb67-4e78-972e-d9d66e06c35d",
            "sourceColumn": "round_trip",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_stop_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50703542-3555-4232-b830-9422d7d7392a",
            "sourceColumn": "shipper_stop_id",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db059299-f288-4c03-ac92-ddbd2c74a1b1",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "subject_order_number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd7c2755-13c9-43f4-bb58-a4fd2af765cd",
            "sourceColumn": "subject_order_number",
            "summarizeBy": "none"
          },
          {
            "name": "temperature_max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "64082df9-8725-48e2-9948-c73ff825ab80",
            "sourceColumn": "temperature_max",
            "summarizeBy": "sum"
          },
          {
            "name": "temperature_min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b20e0ef-c84d-49c9-bac9-a82215a79167",
            "sourceColumn": "temperature_min",
            "summarizeBy": "sum"
          },
          {
            "name": "weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "568038e4-4c69-4f36-a9f4-63891bd81542",
            "sourceColumn": "weight",
            "summarizeBy": "sum"
          },
          {
            "name": "is_tonu",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e8235a6-4c90-4323-9067-9d00747bebf6",
            "sourceColumn": "is_tonu",
            "summarizeBy": "none"
          },
          {
            "name": "notify_when_covered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aea1a36c-4afb-43c4-b7bd-afe7d9d2ee18",
            "sourceColumn": "notify_when_covered",
            "summarizeBy": "none"
          },
          {
            "name": "salesperson_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21fce3f1-f25f-40f1-a041-771bd1cd12bd",
            "sourceColumn": "salesperson_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_entered_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "2e46c30c-d580-4752-853e-1606eacf7ad2",
            "sourceColumn": "order_entered_time",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_city_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0480828e-28b9-48ba-bfe0-f2afb352f63b",
            "sourceColumn": "shipper_city_name",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_location_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbb71902-1efc-4dd0-81df-56926517c566",
            "sourceColumn": "shipper_location_name",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_sched_early_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "597c5c6b-67c0-4e83-af5e-35a3c066afd4",
            "sourceColumn": "shipper_sched_early_date",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_sched_late_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "fa2c7349-7227-48bd-ba4f-0390562db6d1",
            "sourceColumn": "shipper_sched_late_date",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "108d5112-70f3-40ac-abca-96c94f9e34d6",
            "sourceColumn": "shipper_state",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "349b3c2f-9f80-47d7-9e13-6eedf85f4e4c",
            "sourceColumn": "shipper_zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_sched_early_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "360123df-4f90-4e32-b59a-5f8830a286a4",
            "sourceColumn": "shipper_sched_early_time",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_sched_late_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c9b31a67-2385-4d30-bc4c-17f8ec0c9cd3",
            "sourceColumn": "shipper_sched_late_time",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_city_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b45041d8-e36f-4201-bc3a-266910745efb",
            "sourceColumn": "consignee_city_id",
            "summarizeBy": "sum"
          },
          {
            "name": "consignee_city_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "358eefa8-57ae-444c-a755-20d529475d99",
            "sourceColumn": "consignee_city_name",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_location_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f9b5455-2755-4305-af03-09168ca94a44",
            "sourceColumn": "consignee_location_name",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_sched_early_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "4f89daa2-5d28-4b04-9ff9-07ea39716239",
            "sourceColumn": "consignee_sched_early_date",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_sched_late_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "58875f0a-4cc3-40fd-9177-0ad9069ec8bc",
            "sourceColumn": "consignee_sched_late_date",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "768b74e2-6bf5-4f04-a57a-a443ce44a309",
            "sourceColumn": "consignee_state",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d568ea3-9585-4ae0-92e4-4f9c6c39ca69",
            "sourceColumn": "consignee_zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_sched_early_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "6c4583d1-3cf9-4dda-8f1f-afb92533e941",
            "sourceColumn": "consignee_sched_early_time",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_sched_late_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "77829831-f6d3-4f22-affc-4c850673ec6c",
            "sourceColumn": "consignee_sched_late_time",
            "summarizeBy": "none"
          },
          {
            "name": "shipper_3_digit_zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd907732-0003-496f-8c3e-cad726c16e70",
            "sourceColumn": "shipper_3_digit_zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "consignee_3_digit_zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a0c6f92-1467-4124-b194-dc824374dc66",
            "sourceColumn": "consignee_3_digit_zip_code",
            "summarizeBy": "none"
          },
          {
            "name": "lane",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "277452ed-3e1e-495b-9fc0-6c0ad261a194",
            "sourceColumn": "lane",
            "summarizeBy": "none"
          },
          {
            "name": "linear_feet_brlo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "70864f03-34de-4bcc-9038-5b8e25ec49b6",
            "sourceColumn": "linear_feet_brlo",
            "summarizeBy": "sum"
          },
          {
            "name": "pallets_how_many",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d47d3435-5b10-4b3e-81ec-8fa6ac0c0374",
            "sourceColumn": "pallets_how_many",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "616850d9-b6a2-4b0e-99f2-f3ebcab5b217",
        "partitions": [
          {
            "name": "orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"bl-appdb\"),",
                "    lme = Source{[Name=\"lme\"]}[Data],",
                "    dbo_orders = lme{[Schema=\"dbo\",Item=\"orders\"]}[Data],",
                "    #\"Filtered Orders on or after RefreshCutOFfDate\" = Table.SelectRows(dbo_orders, each [ordered_date] >= RefreshCutOffDate),",
                "    //Start General Data Transformation",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Orders on or after RefreshCutOFfDate\",{\"company_id\", \"actual_reefer_profile\", \"agency_id\", \"agent_payee_id\", \"allow_relay\", \"autorate_status\", \"booking_no\", \"booking_number\", \"brk_qual_profile\", \"broker_location_id\", \"brokerage_workflow_id\", \"cbp_crossing_date\", \"cbp_crossing_location_id\", \"cbp_crossing_reason\", \"cbsa_crossing_date\", \"cbsa_crossing_location_id\", \"cbsa_crossing_reason\", \"cc_fuel_revenue\", \"cc_fuel_revenue_c\", \"cc_fuel_revenue_d\", \"cc_fuel_revenue_n\", \"cc_fuel_revenue_r\", \"cc_net_revenue\", \"cc_net_revenue_c\", \"cc_net_revenue_d\", \"cc_net_revenue_n\", \"cc_net_revenue_r\", \"cc_pro_nbr\", \"cobroker_location_id\", \"collection_method\", \"com_setpnt_temp\", \"com_setpnt_temp_um\", \"commitment_id\", \"container\", \"container_planned\", \"container_type_id\", \"controlling_carrier_code\", \"copy_from_company\", \"copy_from_order_id\", \"copy_to_company\", \"copy_to_order_id\", \"ctrl_party_id\", \"cube\", \"curr_movement_id\", \"cust_order_no\", \"declared_val\", \"def_move_type\", \"default_match_id\", \"dim_height\", \"dim_length\", \"dim_surcharge\", \"dim_surcharge_c\", \"dim_surcharge_d\", \"dim_surcharge_n\", \"dim_surcharge_r\", \"dim_width\", \"dispatch_opt\", \"dl_team_reqd\", \"dray_del_date\", \"dray_del_pay\", \"dray_del_pay_c\", \"dray_del_pay_d\", \"dray_del_pay_n\", \"dray_del_pay_r\", \"dray_del_payee\", \"dray_del_xfer_dt\", \"dray_pu_date\", \"dray_pu_pay\", \"dray_pu_pay_c\", \"dray_pu_pay_d\", \"dray_pu_pay_n\", \"dray_pu_pay_r\", \"dray_pu_payee\", \"dray_pu_xfer_dt\", \"eir1_no\", \"eir2_no\", \"est_tolls\", \"est_tolls_c\", \"est_tolls_d\", \"est_tolls_n\", \"est_tolls_r\", \"excise_disable_update\", \"excise_taxable\", \"excisetax_total\", \"excisetax_total_c\", \"excisetax_total_d\", \"excisetax_total_n\", \"excisetax_total_r\", \"force_assign\", \"forwd_location_id\", \"free_days\", \"freight_charge_c\", \"freight_charge_d\", \"freight_charge_r\", \"high_value\", \"hold_reason\", \"image_is_present\", \"import_export\", \"include_split_point\", \"intelliset\", \"invoice_recv_date\", \"is_autorate_dist\", \"is_container\", \"is_dedicated\", \"is_local_mile\", \"is_requested\", \"jag_carrier_id\", \"jag_cost_rate_id\", \"ldport_location_id\", \"linear_feet_avail\", \"loadboard\", \"ltl\", \"markup_flat\", \"markup_flat_c\", \"markup_flat_d\", \"markup_flat_n\", \"markup_flat_r\", \"markup_percent\", \"master_order_id\", \"master_sequence\", \"next_rebill\", \"nte_lp_num\", \"nte_lp_qual\", \"operational_status\", \"optiset\", \"optimize\", \"order_mode\", \"order_value_c\", \"order_value_d\", \"order_value_n\", \"order_value_r\", \"orig_dest_rate_id\", \"otherchargetotal_c\", \"otherchargetotal_d\", \"otherchargetotal_n\", \"otherchargetotal_r\", \"pallets_required\", \"pay_gross_d\", \"pay_gross_n\", \"pay_gross_r\", \"planning_comment\", \"pnn_callback\", \"pnn_comment\", \"pnn_comment2\", \"pnn_post_type\", \"pnn_rate\", \"pay_gross\", \"pay_gross_c\", \"pick_up_no\", \"pnn_rate_type\", \"pnn_trailer_length\", \"pnn_trailer_width\", \"ponum\", \"port\", \"port_of_discharge\", \"preload_trailer_id\", \"preloaded\", \"rate_currency_type\", \"rate_id\", \"rate_min_weight\", \"rate_min_weight_um\", \"rate_unit_desc\", \"recurring_order_id\", \"reply_transmitted\", \"requesting_company\", \"return_temp\", \"return_temp_um\", \"return_temp_var\", \"return_temp_var_um\", \"revenue_share_method\", \"sail_date\", \"seal_number\", \"seg_alloc_code\", \"setpoint_temp\", \"setpoint_temp_um\", \"setpoint_var\", \"setpoint_var_um\", \"ship_status_to_edi\", \"shipment_id\", \"shipstatus2edi_dt\", \"ss_location_id\", \"subject_order_status\", \"subject_order_void_date\", \"swap\", \"teams_required\", \"temperature_max_um\", \"temperature_min_um\", \"total_charge_c\", \"total_charge_d\", \"total_charge_n\", \"total_charge_r\", \"totalcharge_and_excisetax_c\", \"totalcharge_and_excisetax_d\", \"totalcharge_and_excisetax_n\", \"totalcharge_and_excisetax_r\", \"tractor_type\", \"vessel\", \"vessel_cutoff_date\", \"bill_distance_um\", \"billing_empty_distance\", \"billing_empty_distance_um\", \"billing_loaded_distance\", \"billing_loaded_distance_um\", \"bol_note\", \"bol_recv_date\", \"external_invoiceno\", \"freight_charge_n\", \"load_date\", \"ordered_by\", \"ordered_method\", \"placard_required\", \"rate\", \"rate_type\", \"rate_units\", \"ready_to_bill\", \"totalcharge_and_excisetax\", \"weight_um\", \"xferred2billing\", \"xferred2billing_dt\", \"lock_miles\", \"is_auto_tonu\", \"floor_loaded_freight\", \"equipment_type_options\", \"ic_movement_from\", \"ic_company_from\", \"is_intercompany\", \"rate_source\", \"ic_order_from\", \"ordered_by_id\", \"pnn_loadboard_user_id\", \"voided_load_transmitted_dt\", \"voided_load_transmitted\", \"total_charge\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"blnum\", \"customer_po\"}, {\"consignee_refno\", \"bol\"}, {\"ordered_date\", \"order_entered_date\"}, {\"otherchargetotal\", \"other_charges_total\"}, {\"salesperson\", \"salesperson_id\"}}),",
                "    #\"Inserted order_entered_time\" = Table.AddColumn(#\"Renamed Columns\", \"order_entered_time\", each DateTime.Time([order_entered_date]), type time),",
                "    //End General Data Transformation",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted order_entered_time\",{{\"bill_date\", type date}, {\"freight_charge\", Currency.Type}, {\"order_entered_date\", type date}, {\"other_charges_total\", Currency.Type}}),",
                "    //Start add shipper and consignee data",
                "    #\"Merged stop table shipper\" = Table.NestedJoin(#\"Changed Type\", {\"shipper_stop_id\"}, stop, {\"id\"}, \"stop\", JoinKind.LeftOuter),",
                "    #\"Expanded stop\" = Table.ExpandTableColumn(#\"Merged stop table shipper\", \"stop\", {\"city_name\", \"location_name\", \"sched_arrive_early\", \"sched_arrive_late\", \"state\", \"zip_code\", \"sched_arrive_early_time\", \"sched_arrive_late_time\"}, {\"stop.city_name\", \"stop.location_name\", \"stop.sched_arrive_early\", \"stop.sched_arrive_late\", \"stop.state\", \"stop.zip_code\", \"stop.sched_arrive_early_time\", \"stop.sched_arrive_late_time\"}),",
                "    #\"Renamed shipper data\" = Table.RenameColumns(#\"Expanded stop\",{{\"stop.city_name\", \"shipper_city_name\"}, {\"stop.location_name\", \"shipper_location_name\"}, {\"stop.sched_arrive_early\", \"shipper_sched_early_date\"}, {\"stop.sched_arrive_late\", \"shipper_sched_late_date\"}, {\"stop.state\", \"shipper_state\"}, {\"stop.zip_code\", \"shipper_zip_code\"}, {\"stop.sched_arrive_early_time\", \"shipper_sched_early_time\"}, {\"stop.sched_arrive_late_time\", \"shipper_sched_late_time\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed shipper data\", each ([status] <> \"V\")),",
                "    #\"Merged stop table consignee\" = Table.NestedJoin(#\"Filtered Rows\", {\"consignee_stop_id\"}, stop, {\"id\"}, \"stop\", JoinKind.LeftOuter),",
                "    #\"Expanded stop1\" = Table.ExpandTableColumn(#\"Merged stop table consignee\", \"stop\", {\"city_id\", \"city_name\", \"location_name\", \"sched_arrive_early\", \"sched_arrive_late\", \"state\", \"zip_code\", \"sched_arrive_early_time\", \"sched_arrive_late_time\"}, {\"stop.city_id\", \"stop.city_name\", \"stop.location_name\", \"stop.sched_arrive_early\", \"stop.sched_arrive_late\", \"stop.state\", \"stop.zip_code\", \"stop.sched_arrive_early_time\", \"stop.sched_arrive_late_time\"}),",
                "    //End add shipper and consignee data",
                "    #\"Renamed consignee data\" = Table.RenameColumns(#\"Expanded stop1\",{{\"stop.city_id\", \"consignee_city_id\"}, {\"stop.city_name\", \"consignee_city_name\"}, {\"stop.location_name\", \"consignee_location_name\"}, {\"stop.sched_arrive_early\", \"consignee_sched_early_date\"}, {\"stop.sched_arrive_late\", \"consignee_sched_late_date\"}, {\"stop.state\", \"consignee_state\"}, {\"stop.zip_code\", \"consignee_zip_code\"}, {\"stop.sched_arrive_early_time\", \"consignee_sched_early_time\"}, {\"stop.sched_arrive_late_time\", \"consignee_sched_late_time\"}}),",
                "    //Start add 3 digit zip",
                "    #\"Inserted First Characters\" = Table.AddColumn(#\"Renamed consignee data\", \"shipper_3_digit_zip_code\", each Text.Start([shipper_zip_code], 3), type text),",
                "    //End add 3 digit zip",
                "    #\"Inserted First Characters1\" = Table.AddColumn(#\"Inserted First Characters\", \"consignee_3_digit_zip_code\", each Text.Start([consignee_zip_code], 3), type text),",
                "    //Start Add Lane",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Inserted First Characters1\",{{\"shipper_city_name\", Text.Trim, type text}, {\"shipper_state\", Text.Trim, type text}, {\"consignee_city_name\", Text.Trim, type text}, {\"consignee_state\", Text.Trim, type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Trimmed Text\", \"shipper_city_name\", \"shipper_city_name - Copy\"),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Duplicated Column\", \"shipper_state\", \"shipper_state - Copy\"),",
                "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Duplicated Column1\", \"consignee_city_name\", \"consignee_city_name - Copy\"),",
                "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Duplicated Column2\", \"consignee_state\", \"consignee_state - Copy\"),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Duplicated Column3\",{\"shipper_city_name - Copy\", \"shipper_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Shipper\"),",
                "    #\"Merged Columns1\" = Table.CombineColumns(#\"Merged Columns\",{\"consignee_city_name - Copy\", \"consignee_state - Copy\"},Combiner.CombineTextByDelimiter(\", \", QuoteStyle.None),\"Consignee\"),",
                "    //End Add Lane",
                "    #\"Merged Columns2\" = Table.CombineColumns(#\"Merged Columns1\",{\"Shipper\", \"Consignee\"},Combiner.CombineTextByDelimiter(\" - \", QuoteStyle.None),\"lane\"),",
                "    ",
                "    #\"Appended Query\" = Table.Combine({#\"Merged Columns2\", mcleod_historic_orders, pcs_orders})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "movements",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "brokerage_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c04d5d89-981a-499e-9e4c-9526b4364e19",
            "sourceColumn": "brokerage_status",
            "summarizeBy": "none"
          },
          {
            "name": "dest_stop_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51838280-c0c9-41e4-b588-c1f572284b38",
            "sourceColumn": "dest_stop_id",
            "summarizeBy": "none"
          },
          {
            "name": "dispatcher_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a012ce0-7317-42a0-a02e-a2bacae5a258",
            "sourceColumn": "dispatcher_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6982983d-8e5c-4ef1-81dc-399a58169917",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "invoice_recv_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "80cdb262-6904-4b05-97ad-3d39f04399c3",
            "sourceColumn": "invoice_recv_date",
            "summarizeBy": "none"
          },
          {
            "name": "max_buy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "e808aa27-9356-4003-9c04-4010d6d2603c",
            "sourceColumn": "max_buy",
            "summarizeBy": "sum"
          },
          {
            "name": "move_distance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f3d49253-18e9-4a53-ac52-5ce4a17c2048",
            "sourceColumn": "move_distance",
            "summarizeBy": "sum"
          },
          {
            "name": "origin_stop_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3855a3d-ff5c-4ec3-9b6e-693829c2f15b",
            "sourceColumn": "origin_stop_id",
            "summarizeBy": "none"
          },
          {
            "name": "override_pay_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "a43b099e-4dca-4c78-8ca7-f937511c001b",
            "sourceColumn": "override_pay_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "override_payee_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96b618d5-96c2-445b-be68-224136aec231",
            "sourceColumn": "override_payee_id",
            "summarizeBy": "none"
          },
          {
            "name": "override_targetpay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "4e60199c-c1b0-44cf-8a27-0dff23b32ec3",
            "sourceColumn": "override_targetpay",
            "summarizeBy": "sum"
          },
          {
            "name": "override_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad8b12df-f0ad-4535-b38c-15b8db9d830d",
            "sourceColumn": "override_type",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f103b99-a5b7-48f0-bb60-13a6b75812bd",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "target_pay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "528d4647-afa8-4918-a35c-f05269eb57a9",
            "sourceColumn": "target_pay",
            "summarizeBy": "sum"
          },
          {
            "name": "xfer2settle_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3d02172a-c0e9-442d-9766-324cef059eea",
            "sourceColumn": "xfer2settle_date",
            "summarizeBy": "none"
          },
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c84edc2-64e7-41b7-bfa6-1e333c258c1f",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "sequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb3c47e8-42ed-471b-b37c-3b21657577cf",
            "sourceColumn": "sequence",
            "summarizeBy": "sum"
          },
          {
            "name": "dnc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "751a058d-ec39-485f-a40d-f9fcda0b3d14",
            "sourceColumn": "dnc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4d68b890-a71e-49b5-b4ab-a9a72c28eef7",
        "partitions": [
          {
            "name": "movements",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_movement = Source{[Schema=\"dbo\",Item=\"movement\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_movement,{{\"id\", type number}}),",
                "    #\"filtered movements >= MovmentCuttOFfNumber\" = Table.SelectRows(#\"Changed Type\", each [id] >= MovementCutOffNumber),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"filtered movements >= MovmentCuttOFfNumber\",{{\"id\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"company_id\", \"authorized\", \"average_broker_rating\", \"booking_no\", \"br_details_link\", \"br_status_link\", \"br_track_interval\", \"br_track_status\", \"br_tracking_id\", \"br_vendor\", \"broker_avail_tract\", \"brokerage\", \"carrier_contact\", \"carrier_email\", \"carrier_fuel_pay_rate_id\", \"carrier_lane_rate_id\", \"carrier_override_user\", \"carrier_phone\", \"carrier_rate_id\", \"chassis\", \"checkcall_sched_id\", \"container\", \"container_returned\", \"container_status\", \"controlling_carrier_code\", \"dedicated_order_id\", \"est_tolls\", \"est_tolls_c\", \"est_tolls_d\", \"est_tolls_n\", \"est_tolls_r\", \"exclude_movement\", \"fleet_manager\", \"freight_matching_override\", \"fuel_distance_um\", \"fuel_tax_exempt\", \"hubtran_approved_inv_date\", \"hubtran_ok2pay_date\", \"integrated_carrier_search\", \"is_container\", \"is_dray\", \"is_local_mile\", \"linked_id\", \"linked_sequence\", \"loaded\", \"locked_user_id\", \"ltl\", \"ltl_staging_wrs_uid\", \"macropoint_status\", \"manifest_empty_distance\", \"manifest_estimated_arrival\", \"manifest_estimated_depart\", \"manifest_id\", \"manifest_loaded_distance\", \"manifest_reg_uid\", \"manifest_spots_capacity\", \"manifest_spots_consumed\", \"manifest_weight_capacity\", \"manifest_weight_consumed\", \"max_buy_c\", \"max_buy_d\", \"max_buy_n\", \"max_buy_r\", \"max_pay_method\", \"max_pay_units\", \"missed_call_sent\", \"fuel_distance\", \"move_distance_um\", \"movement_type\", \"must_respond_by\", \"next_sched_call\", \"operational_status\", \"operations_user\", \"override_crny_type\", \"override_driver_id\", \"override_driver_nm\", \"override_drvr_cell\", \"override_drvr_email\", \"override_max_pay\", \"override_max_pay_c\", \"override_max_pay_d\", \"override_max_pay_n\", \"override_max_pay_r\", \"override_pay_amt_c\", \"override_pay_amt_d\", \"override_pay_amt_n\", \"override_pay_amt_r\", \"override_paye_rate\", \"override_targetpay_c\", \"override_targetpay_d\", \"override_targetpay_n\", \"override_targetpay_r\", \"override_unit_desc\", \"override_units\", \"pay_distance\", \"pay_distance_um\", \"placard_required\", \"priority\", \"pro_nbr\", \"rate_alert_basis\", \"rate_alert_date\", \"rate_alert_days\", \"rate_alert_hours\", \"rate_alert_minutes\", \"rate_confirm_template\", \"rate_confirmation_sent_date\", \"rate_confirmation_status\", \"rate_expiration_basis\", \"rate_expiration_date\", \"rate_expiration_days\", \"rate_expiration_hours\", \"rate_expiration_minutes\", \"rdy_pickup_date\", \"recurring_movement_id\", \"reminder_sent\", \"required_vendor\", \"reserved\", \"return_date\", \"seg_alloc_code\", \"ss_location_id\", \"target_extra_stop_pay\", \"target_extra_stop_pay_c\", \"target_extra_stop_pay_d\", \"target_extra_stop_pay_n\", \"target_extra_stop_pay_r\", \"target_fuel_surcharge_pay\", \"target_pay_c\", \"target_pay_d\", \"target_pay_n\", \"target_pay_r\", \"target_pay_method\", \"target_pay_units\", \"target_rate_id\", \"time_to_send_msg\", \"tracking_request_status\", \"trailer_rent_pct\", \"trip_lease\", \"trip_mgt_recalc_datetime\", \"trip_mgt_tracking_id\", \"triumphpay_exclude\", \"trp_uid\", \"unlock_time\", \"waterfall_flood_time\", \"waterfall_in_progress\", \"xferred2fueltax\", \"xferred2fueltaxdt\", \"xmit_accepted\", \"xmitted2driver\", \"zmit_trip\", \"require_tracking\", \"ts_borrowing_company\", \"ts_commodity\", \"ts_movement_id\", \"tracking_duration_ext\", \"tracking_notify_email\", \"shpmt_ident_type\", \"shpmt_ident_value\", \"override_driver2_nm\", \"ic_company_to\", \"load_booking_source\", \"override_drvr2_email\", \"track_start_date\", \"br_track_vehicle_id\", \"br_track_status_desc\", \"pending_carrier_type\", \"shipper_email\", \"carrier_override_carrier\", \"pending_carrier_name\", \"override_driver2_id\", \"carrier_empty_from_city_id\", \"shipper_notify_frequency\", \"pending_carrier_nbr\", \"ic_order_to\", \"digital_booking\", \"is_intercompany\", \"override_drvr2_cell\", \"carrier_tractor\", \"carrier_trailer\", \"equipment_group_id\", \"empty2next_order\", \"eform_rate_confirmation\", \"override_pay_rate\", \"preassign_sequence\", \"carrier_trailer_type\", \"pending_payee_id\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each ([status] <> \"V\")),",
                "   //start replacing teams with parade",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Filtered Rows\",\"team17\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"team16\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"team15\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"team14\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"team13\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"team12\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"team10\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"team9\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"team8\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"team7\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"team6\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"team5\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"team4\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"team3\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"team2\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"team1\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"cdispatch\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    //end replace teams with parade",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Replaced Value16\",\"cbt\",\"parade\",Replacer.ReplaceText,{\"dispatcher_user_id\"}),",
                "    #\"Trimmed Text1\" = Table.TransformColumns(#\"Replaced Value17\",{{\"dispatcher_user_id\", Text.Trim, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text1\",{{\"dispatcher_user_id\", Text.Upper, type text}}),",
                "    #\"Appended Query\" = Table.Combine({#\"Uppercased Text\", mcleod_historic_movement}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Appended Query\",{{\"id\", Text.Trim, type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Trimmed Text\", {\"id\"}, movement_order, {\"movement_id\"}, \"movement_order\", JoinKind.LeftOuter),",
                "    #\"Expanded movement_order\" = Table.ExpandTableColumn(#\"Merged Queries\", \"movement_order\", {\"order_id\", \"sequence\"}, {\"order_id\", \"sequence\"}),",
                "    #\"Appended Query1\" = Table.Combine({#\"Expanded movement_order\", pcs_movements}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Appended Query1\",{{\"invoice_recv_date\", type date}, {\"xfer2settle_date\", type date}, {\"target_pay\", Currency.Type}, {\"override_targetpay\", Currency.Type}, {\"override_pay_amt\", Currency.Type}, {\"max_buy\", Currency.Type}}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Changed Type2\", {\"id\"}, parade_orders, {\"movement_id\"}, \"parade_orders\", JoinKind.LeftOuter),",
                "    #\"Expanded parade_orders\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"parade_orders\", {\"id\"}, {\"parade_orders.id\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded parade_orders\",{{\"dispatcher_user_id\", \"dispatcher_user_id_old\"}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Renamed Columns\", \"dispatcher_user_id\", each if [parade_orders.id] = null then [dispatcher_user_id_old] else \"parade\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"parade_orders.id\", \"dispatcher_user_id_old\"}),",
                "    #\"Merged Queries2\" = Table.NestedJoin(#\"Removed Columns1\", {\"id\"}, dnc, {\"DNC\"}, \"dnc\", JoinKind.LeftOuter),",
                "    #\"Expanded dnc\" = Table.ExpandTableColumn(#\"Merged Queries2\", \"dnc\", {\"DNC\"}, {\"dnc.DNC\"}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Expanded dnc\", \"dnc\", each if [dnc.DNC] = null then false else true),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Conditional Column1\",{{\"dnc\", type logical}}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Changed Type3\",{\"dnc.DNC\"})",
                "in",
                "    #\"Removed Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "driver_extra_pay",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c45fddd7-bf52-42f4-b281-4501e5d8718a",
            "sourceColumn": "amount",
            "summarizeBy": "sum"
          },
          {
            "name": "deduct_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cad87a6f-65b6-4f27-8931-b9b7ac9147da",
            "sourceColumn": "deduct_code_id",
            "summarizeBy": "none"
          },
          {
            "name": "entered_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "603048e4-4c69-4c42-bb41-a7ceb8b03014",
            "sourceColumn": "entered_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e4cab39-5a0f-497b-ac4f-9744f5c59126",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "movement_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a636f33-44fb-417f-8e47-7c46767d602b",
            "sourceColumn": "movement_id",
            "summarizeBy": "none"
          },
          {
            "name": "payee_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85b660ed-4389-4fa6-98d5-c3960ee67c2a",
            "sourceColumn": "payee_id",
            "summarizeBy": "none"
          },
          {
            "name": "short_desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd0fc931-98ba-4ff7-a54b-deec305f9951",
            "sourceColumn": "short_desc",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2ebdc404-318f-4cf1-accc-1504a5c41207",
        "partitions": [
          {
            "name": "driver_extra_pay",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_driver_extra_pay = Source{[Schema=\"dbo\",Item=\"driver_extra_pay\"]}[Data],",
                "    #\"Filtered Pay post RefreshCutOfDate\" = Table.SelectRows(dbo_driver_extra_pay, each [amount_d] >= RefreshCutOffDate),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Pay post RefreshCutOfDate\",{\"company_id\", \"amount_c\", \"amount_d\", \"amount_n\", \"amount_r\", \"carrier_rate_id\", \"descr\", \"detention_hist_pay_id\", \"driver_id\", \"fuel_surcharge_pay\", \"jag_rate_id\", \"order_id\", \"rate\", \"reference_no\", \"rev_uid\", \"transaction_date\", \"units\"}),",
                "    #\"Appended Query\" = Table.Combine({#\"Removed Columns\", mcleod_historic_driver_extra_pay})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "8c8cd0ec-bc3a-497c-8890-727a55c10611",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ebb95aa5-5e0f-4c35-92d8-0fafa766588b",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fc3964d-1c86-48a9-8188-68259c733be2",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f47f69c1-ff67-4e2f-89d8-5290e3b12366",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterNmb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24fe33b4-7940-4d34-a726-e55a50ba02eb",
            "sourceColumn": "QuarterNmb",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8287fd0f-b28c-4d24-bb40-08429d66461a",
            "sortByColumn": "MonthNmb",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "MonthAbv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e97bbfd-3c3e-4fda-b6f9-d12336fca1ef",
            "sortByColumn": "MonthNmb",
            "sourceColumn": "MonthAbv",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNmb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e2df293-236d-4167-aa97-27899fa85f79",
            "sourceColumn": "MonthNmb",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e6153bd8-2b9c-4f9e-8481-d0b1e326eee3",
            "sourceColumn": "Week of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Week of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec41ace3-8053-410f-b7e1-a0aa2140a693",
            "sourceColumn": "Week of Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82e401e4-81e2-40eb-90cd-427d900bca55",
            "sourceColumn": "Day of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "997f426f-f5ce-43a5-8ef2-8850a375bd30",
            "sourceColumn": "Day of Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccc72e4a-d3ac-464d-ac0b-84de114d234d",
            "sourceColumn": "Day of Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9da35ee3-b43a-45a0-9a4e-af097f1575fe",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Is Past",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6d1b380f-221b-4d89-aaf7-b3bc2dbd9e53",
            "sourceColumn": "Is Past",
            "summarizeBy": "none"
          },
          {
            "name": "Month / Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18f8eb3b-bc2c-4a60-88cd-5c27079058e7",
            "sourceColumn": "Month / Year",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8a73e23-6bcf-4cf0-84ca-5f0ae725ac1a",
            "sourceColumn": "Day of Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Week / Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a34020b1-473b-4db1-b090-a14e7fcca899",
            "sourceColumn": "Week / Year",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "600e226d-a54e-4344-b9f4-7773fea19639",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "c583c9ce-20dd-43b3-818e-c9d8da9a588a",
        "measures": [
          {
            "name": "Calendar General",
            "expression": "FORMAT(MIN('Calendar'[Date]),\"General Number\")",
            "lineageTag": "060c64c1-9345-4648-a1bf-10a163a011b3"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    //Variables",
                "    StartDate = #date(2001,1,1),",
                "    EndDate = #date(2025,12,31),",
                "    Duration = Duration.Days(Duration.From(EndDate-StartDate))+1,",
                "    Today = DateTime.Date(DateTime.LocalNow()),",
                "",
                "    //Date Columns",
                "    Dates = List.Dates(StartDate,Duration,#duration(1,0,0,0)),",
                "    #\"Converted to Table\" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Changed Type\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Inserted Start of Month\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Year\", \"Quarter\", each \"Q\"&Text.From(Date.QuarterOfYear([Date]))),",
                "    #\"Inserted QuarterNmb\" = Table.AddColumn(#\"Inserted Quarter\", \"QuarterNmb\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted QuarterNmb\", \"Month Name\", each Date.MonthName([Date]), type text),",
                "    #\"Inserted MonthAbv\" = Table.AddColumn(#\"Inserted Month Name\", \"MonthAbv\", each Text.Start(Date.MonthName([Date]),3), type text),",
                "    #\"Inserted MonthNmb\" = Table.AddColumn(#\"Inserted MonthAbv\", \"MonthNmb\", each Date.Month([Date]), Int64.Type),",
                "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted MonthNmb\", \"Week of Year\", each Date.WeekOfYear([Date]), Int64.Type),",
                "    #\"Inserted Week of Month\" = Table.AddColumn(#\"Inserted Week of Year\", \"Week of Month\", each Date.WeekOfMonth([Date]), Int64.Type),",
                "    #\"Inserted Day of Year\" = Table.AddColumn(#\"Inserted Week of Month\", \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),",
                "    #\"Inserted Day of Month\" = Table.AddColumn(#\"Inserted Day of Year\", \"Day of Month\", each Date.Day([Date]), Int64.Type),",
                "    #\"Inserted Day of Week\" = Table.AddColumn(#\"Inserted Day of Month\", \"Day of Week\", each Date.DayOfWeek([Date]), Int64.Type),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Day of Week\", \"Day Name\", each Date.DayOfWeekName([Date]), type text),",
                "    #\"Inserted Is Past\" = Table.AddColumn(#\"Inserted Day Name\", \"Is Past\", each [Date]<Today),",
                "    #\"Changed Is Past to True False\" = Table.TransformColumnTypes(#\"Inserted Is Past\",{{\"Is Past\", type logical}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Is Past to True False\", \"Month / Year\", each Date.ToText([Date], \"MMM/yyyy\")),",
                "    #\"Added Day of Quarter\" = Table.AddColumn(#\"Added Custom\", \"Day of Quarter\", each Date.DayOfYear(Date.From([Date])) - Date.DayOfYear(Date.From(Date.StartOfQuarter([Date]))) + 1),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Added Day of Quarter\", \"Week of Year\", \"Week of Year - Copy\"),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Duplicated Column\", \"Year\", \"Year - Copy\"),",
                "    #\"Merged Columns\" = Table.CombineColumns(Table.TransformColumnTypes(#\"Duplicated Column1\", {{\"Week of Year - Copy\", type text}, {\"Year - Copy\", type text}}, \"en-US\"),{\"Week of Year - Copy\", \"Year - Copy\"},Combiner.CombineTextByDelimiter(\"/\", QuoteStyle.None),\"Week / Year\"),",
                "    #\"Inserted Start of Week\" = Table.AddColumn(#\"Merged Columns\", \"Start of Week\", each Date.StartOfWeek([Date]), type date)",
                "in",
                "    #\"Inserted Start of Week\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "measures_",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "cb8739f6b6f74399b74587f43495ffe2"
          },
          {
            "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
            "value": "{\"Expression\":\"\"}"
          }
        ],
        "columns": [
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "746e082c-433f-4c69-8ea2-18b07c8517b2",
            "sourceColumn": "[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4f6dad67-79ad-4db3-9aa7-ea35ff6c1845",
        "measures": [
          {
            "name": "Sum of freight_charges",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Revenue Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(orders[freight_charge]),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "89d17990-2077-45c7-af5c-49710ca0fdc8"
          },
          {
            "name": "Sum of other_charges",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Revenue Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(orders[other_charges_total]),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "5f9abf81-2be6-48b2-9799-922feb050f30"
          },
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Revenue Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sum of freight_charges]+[Sum of other_charges],",
              "    FILTER(movements,movements[status]<>\"A\"),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")",
              ""
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "39ae93b5-50d6-453e-80c8-dbbb58f43df7"
          },
          {
            "name": "Sum of override_pay_amt",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pay Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(movements[override_pay_amt]),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "lineageTag": "4afe6d8c-348c-4f5f-9fa1-593d24fa27a4"
          },
          {
            "name": "Sum of driver_extra_pay",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pay Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(driver_extra_pay[amount]),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "lineageTag": "6be686a6-e220-4dff-91a4-141b0da5ca73"
          },
          {
            "name": "Total Carrier Pay",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Pay Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sum of driver_extra_pay]+[Sum of override_pay_amt],",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "lineageTag": "c7c5f213-a346-4367-8717-3924d6ef52da"
          },
          {
            "name": "Margin",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue]-[Total Carrier Pay],",
              "    movements[status]<>\"A\"",
              "    ,USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3491f4d3-9764-45b7-a60b-c17891311500"
          },
          {
            "name": "Staff Turnover",
            "description": "Counts the Rows of the Employee Table whose termination date are >= min(date), termination date <= max(date), and termination date are not blank",
            "displayFolder": "HR",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(employees),",
              "    FILTER(VALUES(employees[Termination Date]),employees[Termination Date]>=MIN('calendar'[Date])),",
              "    FILTER(employees,employees[Termination Date]<=MAX('calendar'[Date])),",
              "    employees[Termination Date]<>BLANK()",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3f85f56a-a39f-40ee-82a3-6960eea53eb9"
          },
          {
            "name": "Avg Monthy Head Count",
            "displayFolder": "HR",
            "expression": [
              "",
              "AVERAGEX(",
              "    SUMMARIZE(",
              "        'Calendar',",
              "        'Calendar'[Month / Year],",
              "        \"avg head count\",[Current Staff]",
              "    ),",
              "    [avg head count]",
              ")"
            ],
            "lineageTag": "24b21e8e-4c91-4e76-9c0a-d36e34fee514"
          },
          {
            "name": "Current Staff",
            "displayFolder": "HR",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(employees),",
              "    FILTER(VALUES(employees[Hire Date]),employees[Hire Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(employees[Termination Date]), OR(employees[Termination Date] >= MIN('calendar'[Date]), ISBLANK(employees[Termination Date])))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7f4fea41-84eb-4da1-a4e5-10b82bc756e7"
          },
          {
            "name": "Turnover Rate",
            "displayFolder": "HR",
            "expression": "DIVIDE([Staff Turnover],[Avg Monthy Head Count])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "44b3bc15-cc1c-4413-9ff3-e30f06a285e8"
          },
          {
            "name": "Turnover Rate 12 Months Prior",
            "displayFolder": "HR",
            "expression": "CALCULATE([Turnover Rate],DATEADD('Calendar'[Date],-12,MONTH))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "84493348-e95a-4075-aece-f38c8f0aead7"
          },
          {
            "name": "Turnover YOY Variance",
            "displayFolder": "HR",
            "expression": "[Turnover Rate]-[Turnover Rate 12 Months Prior]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a3afd5ea-9c53-4cd1-9707-cef0c1a8d083"
          },
          {
            "name": "Avg Monthly Staff Turnover",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "HR",
            "expression": [
              "",
              "AVERAGEX(",
              "    SUMMARIZE(",
              "        'Calendar',",
              "        'Calendar'[Month / Year],",
              "        \"avg staff turnover\",[Staff Turnover]",
              "    ),",
              "    [avg staff turnover]",
              ")"
            ],
            "lineageTag": "4d740f20-09f9-4b84-9bb0-7cc7705ad68e"
          },
          {
            "name": "Avg Monthly Turnover Rate",
            "displayFolder": "HR",
            "expression": "DIVIDE([Avg Monthly Staff Turnover],[Avg Monthy Head Count])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02a7ca5f-d396-4f11-884c-fe49f1305636"
          },
          {
            "name": "Average Monthly Turnover Rate 12 Months Prior",
            "displayFolder": "HR",
            "expression": "CALCULATE([Avg Monthly Turnover Rate],DATEADD('Calendar'[Date],-12,MONTH))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "13ea2ec0-3823-4fb7-aa81-01ad79e4b0f4"
          },
          {
            "name": "Average Monthly YOY Variance",
            "displayFolder": "HR",
            "expression": "[Avg monthly turnover Rate]-[Average Monthly Turnover Rate 12 Months Prior]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fb19c866-be07-47d3-b40e-8dbc4753e4d7"
          },
          {
            "name": "Total Turnover Last 30 days",
            "displayFolder": "HR",
            "expression": "DIVIDE([Staff Turnover Last 30 Days],[Current Staff Last 30 Days])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cf1e053e-55f5-48f8-a774-fa2363abc66e"
          },
          {
            "name": "Staff Turnover Last 30 Days",
            "displayFolder": "HR",
            "expression": [
              "",
              "CALCULATE( COUNTROWS(employees),",
              "    FILTER( VALUES(employees[Termination Date]), employees[Termination Date]>= (TODAY()-30)),",
              "        employees[Termination Date]<>BLANK(),",
              "    FILTER(employees,employees[Termination Date]<=TODAY()))"
            ],
            "formatString": "0",
            "lineageTag": "64796ec6-6b55-45a7-8df6-97b6ee60b46c"
          },
          {
            "name": "Current Staff Last 30 Days",
            "displayFolder": "HR",
            "expression": [
              "",
              "CALCULATE( COUNTROWS(employees),",
              "    FILTER(VALUES(employees[Hire Date]),employees[Hire Date] <= TODAY()),",
              "    FILTER( VALUES( employees[Termination Date]), OR( employees[Termination Date]>=(TODAY()-30),ISBLANK(employees[Termination Date]))))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6461da47-61c5-4590-9b18-723ef98fe1f5"
          },
          {
            "name": "Turnover 60-30 Days Ago",
            "displayFolder": "HR",
            "expression": [
              "",
              "Var Twoma = ",
              "CALCULATE( COUNTROWS(employees),",
              "    FILTER( VALUES( employees[Termination Date]), employees[Termination Date]>= (TODAY()-60)),",
              "        employees[Termination Date]<>BLANK(),",
              "    FILTER(employees,employees[Termination Date]<=TODAY()-30))",
              "",
              "Var HeadCount2ma =  ",
              "CALCULATE( COUNTROWS(employees),",
              "    FILTER(VALUES(employees[Hire Date]),employees[Hire Date] <= TODAY()-30),",
              "    FILTER( VALUES( employees[Termination Date]), OR( employees[Termination Date]>=(TODAY()-60),ISBLANK(employees[Termination Date]))))",
              "Var Turnover60to30daysAgo = DIVIDE(Twoma,HeadCount2ma)",
              "",
              "RETURN",
              "Turnover60to30daysAgo"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "edee7803-0364-4c4b-935c-72af59f7347f"
          },
          {
            "name": "Turnover Rate variance 60-30 and 30-today",
            "displayFolder": "HR",
            "expression": "[Total Turnover Last 30 days]-[Turnover 60-30 Days Ago]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6157deea-5af5-43f7-ab18-cd548bcb7fa7"
          },
          {
            "name": "Employees Hires",
            "displayFolder": "HR",
            "expression": [
              "",
              "CALCULATE( COUNTROWS(employees),",
              "    FILTER(VALUES(employees[Hire Date]),employees[Hire Date] <= MAX('Calendar'[Date])),",
              "    FILTER( VALUES( employees[Hire Date]), employees[Hire Date]>=MIN('Calendar'[Date])))"
            ],
            "formatString": "0",
            "lineageTag": "4910a8b9-24b3-42d7-9ca6-8314b8f73dba"
          },
          {
            "name": "Hires 1MA",
            "displayFolder": "HR",
            "expression": "CALCULATE([Employees Hires],DATEADD('Calendar'[Date],-1,MONTH))",
            "formatString": "0",
            "lineageTag": "8b95fa9b-1965-4c32-bc57-090b9f66bbb5"
          },
          {
            "name": "Hires Vs Hires 1MA Variance",
            "displayFolder": "HR",
            "expression": "[Employees Hires]-[Hires 1MA]",
            "formatString": "0",
            "lineageTag": "ccb2c481-c962-4d98-8fff-547fa2ee9c46"
          },
          {
            "name": "Hires 2MA",
            "displayFolder": "HR",
            "expression": "CALCULATE([Employees Hires],DATEADD('Calendar'[Date],-2,MONTH))",
            "formatString": "0",
            "lineageTag": "3bd4bd75-c274-4c0c-876b-1e68d17cc48a"
          },
          {
            "name": "Hires 2MA Vs Hires 1MA Variance",
            "displayFolder": "HR",
            "expression": "[Hires 1MA]-[Hires 2MA]",
            "formatString": "0",
            "lineageTag": "0d3df909-9f69-47f7-8154-31b1c42a38e2"
          },
          {
            "name": "45 Day Review",
            "displayFolder": "HR\\Check Ins",
            "expression": "MIN(employees[Hire Date])+45",
            "formatString": "Short Date",
            "lineageTag": "172b1ef2-2cac-43f6-9c29-dc0e18a4a509"
          },
          {
            "name": "1 Month Into SDR",
            "displayFolder": "HR\\Check Ins",
            "expression": [
              "",
              "Var IfBefore15th = MIN(employees[Hire Date])+122",
              "Var IfAfter15th = MIN(employees[Hire Date])+136",
              "Var start_date_day_of_month = DAY(MIN(employees[Hire Date]))",
              "Var IFS = IF(start_date_day_of_month<15,IfBefore15th,IfAfter15th)",
              "",
              "RETURN",
              "IFS"
            ],
            "formatString": "Short Date",
            "lineageTag": "2b048199-89b7-40a6-a333-8329aaa3a48a"
          },
          {
            "name": "1 Month Into D Team",
            "displayFolder": "HR\\Check Ins",
            "expression": [
              "",
              "Var IfUnder15 = MIN(employees[Hire Date])+213",
              "Var IfAfter15 =MIN(employees[Hire Date])+227",
              "Var start_date_day_of_month = DAY(MIN(employees[Hire Date]))",
              "Var IFS = IF(start_date_day_of_month<15,IfUnder15,IfAfter15)",
              "",
              "Return",
              "IFS"
            ],
            "formatString": "Short Date",
            "lineageTag": "76938b93-0cab-4366-b94b-9b6aa87f34e3"
          },
          {
            "name": "D-Team Move Date",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "Var job_history_d_team_date = ",
              "    CALCULATE(",
              "        MIN(job_history[Job Start Date]),",
              "        FILTER(job_history,job_history[Division]=\"Development Team Sales\"))",
              "Var sdr_date_plus_90 =[SDR Move Date]+100",
              "Var estemate_of_d_team_move_date= CEILING(EOMONTH(sdr_date_plus_90,-1)-1,7)+2",
              "",
              "Var ifs = ",
              "    IF(job_history_d_team_date=BLANK(),",
              "    estemate_of_d_team_move_date,",
              "    job_history_d_team_date",
              "    )",
              "",
              "RETURN",
              "FORMAT(ifs,\"Short Date\")"
            ],
            "lineageTag": "cb27c10a-85f5-46fc-b8c1-eb7f6b33eb82"
          },
          {
            "name": "Henry Move Date",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "Var job_history_henry_date = ",
              "    CALCULATE(",
              "        MIN(job_history[Job Start Date]),",
              "        FILTER(job_history,job_history[Division]=\"Logistics Advisor Sales (Formerly Henry)\"))",
              "Var Dteam_date_plus_90 =[D-Team Move Date]+100",
              "Var estemate_of_henry_move_date= CEILING(EOMONTH(Dteam_date_plus_90,-1)-1,7)+2",
              "",
              "Var ifs = ",
              "    IF(job_history_henry_date=BLANK(),",
              "    EDATE(estemate_of_henry_move_date, 3),",
              "    job_history_henry_date - 1",
              "    )",
              "",
              "Var ifs_plus_6_months = EDATE(estemate_of_henry_move_date, 3)",
              "",
              "RETURN",
              "FORMAT(ifs,\"Short Date\")"
            ],
            "lineageTag": "9e50448b-7070-4aea-8bf5-4238b9fb76d8"
          },
          {
            "name": "LA Move Date color",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "",
              "var LA = CONTAINSSTRING(min(employees[Devision]),\"Logistics Advisor Sales\")",
              "VAR IFS = IF(LA = TRUE,1,0)",
              "",
              "RETURN",
              "IFS"
            ],
            "formatString": "0",
            "lineageTag": "92c48fc4-72d9-4870-aa26-500a9ab2577c"
          },
          {
            "name": "Ops Team Move Date",
            "displayFolder": "HR\\Move Dates",
            "expression": "SUM(employees[Hire Date])+14",
            "formatString": "Short Date",
            "lineageTag": "cfcd1c60-9853-4860-826b-d020ea0080b7"
          },
          {
            "name": "SDR Move Date",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "Var job_history_sdr_date = ",
              "    CALCULATE(",
              "        MIN(job_history[Job Start Date]),",
              "        FILTER(job_history,job_history[Division]=\"SDR Team\"))",
              "Var hire_date_plus_90 = MIN(employees[Hire Date])+90",
              "Var first_monday_of_hire_plus_90 = CEILING(EOMONTH(hire_date_plus_90,-1)-1,7)+2",
              "Var first_monday_of_next_month = CEILING(EOMONTH(hire_date_plus_90,-0)-1,7)+2",
              "Var employee_start_day_of_month = DAY(MIN(employees[Hire Date]))",
              "Var estamate_of_sdr_move_date = ",
              "    IF(employee_start_day_of_month>15,",
              "    first_monday_of_next_month,",
              "    first_monday_of_hire_plus_90",
              "    )",
              "Var ifs = ",
              "    IF(job_history_sdr_date=BLANK(),",
              "    estamate_of_sdr_move_date,",
              "    job_history_sdr_date",
              "    )",
              "",
              "RETURN",
              "FORMAT(ifs,\"Short Date\")"
            ],
            "lineageTag": "eb84ecc1-09f5-45f5-8e43-77dfb52ae922"
          },
          {
            "name": "Ops Move Date color",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "",
              "VAR OPS = CONTAINSSTRING(min(employees[Devision]),\"CRT\")",
              "VAR IFS = IF(OPS = TRUE,1,0)",
              "",
              "RETURN",
              "IFS"
            ],
            "formatString": "0",
            "lineageTag": "aefaa231-2640-4693-8651-522f6a239055"
          },
          {
            "name": "SDR Move Date color",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "",
              "VAR SDR =CONTAINSSTRING(min(employees[Devision]),\"SDR\")",
              "VAR IFS = IF(SDR = TRUE,1,0)",
              "",
              "RETURN",
              "IFS"
            ],
            "formatString": "0",
            "lineageTag": "bb1dbbcd-506c-4916-9220-e69080250954"
          },
          {
            "name": "D-Team Move Date color",
            "displayFolder": "HR\\Move Dates",
            "expression": [
              "",
              "",
              "var dteam = CONTAINSSTRING(min(employees[Devision]),\"Development Team\")",
              "VAR IFS = IF(dteam = TRUE,1,0)",
              "",
              "RETURN",
              "IFS"
            ],
            "formatString": "0",
            "lineageTag": "c3103726-c85a-4789-8119-103a5a4e8749"
          },
          {
            "name": "Current Carrier Booking Team",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date]))),",
              "    FILTER(job_history,job_history[Division]=\"CRT-Booking\"))"
            ],
            "formatString": "0",
            "lineageTag": "37af42d0-1cf4-4736-9874-ace293c6c112"
          },
          {
            "name": "Count of Movements Booked",
            "displayFolder": "Movement Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(movements[id]),",
              "    movements[status]<>\"A\",",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date]),",
              "    USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "9a92c758-8ba8-4423-a380-55402b47cdf1"
          },
          {
            "name": "Count of orders covered",
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(orders[id]),",
              "    movements[status]<>\"A\",",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ebc9309e-c0e2-478d-8534-2f3bb96fc500"
          },
          {
            "name": "NFM",
            "expression": [
              "",
              "IF(",
              "    OR(",
              "    CONTAINSSTRING(",
              "        MIN(orders[commodity]),",
              "        \"ALUMINUM\"),",
              "    OR(",
              "        CONTAINSSTRING(",
              "        MIN(orders[commodity]),",
              "        \"ALUMINIUM\"),",
              "       OR(",
              "         CONTAINSSTRING(",
              "            MIN(orders[commodity]),",
              "            \"BRASS\"),",
              "            CONTAINSSTRING(",
              "                MIN(orders[commodity]),",
              "                \"copper\")",
              "       )",
              "    )",
              "    )",
              "    =TRUE(),1,0)"
            ],
            "formatString": "0",
            "lineageTag": "bfd2434a-f31c-4d5d-ac33-c298f525ce2f"
          },
          {
            "name": "Count of Trackable Movements",
            "description": "Count of Movements Booked that are greater then 50 miles and the order type is FTL, BW, or PARTIAL",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": [
              "",
              "Var count_ftl = ",
              "    CALCULATE(",
              "        DISTINCTCOUNT(movements[id]),",
              "        movements[status]<>\"A\",",
              "        orders[order_type_id]=\"FTL\",",
              "        orders[bill_distance]>50,",
              "        USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date]),",
              "        USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              "    )",
              "Var count_bw = ",
              "    CALCULATE(",
              "        DISTINCTCOUNT(movements[id]),",
              "        movements[status]<>\"A\",",
              "        orders[order_type_id]=\"BW\",",
              "        orders[bill_distance]>50,",
              "        USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date]),",
              "        USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              "    )",
              "        ",
              "Var count_partials =",
              "    CALCULATE(",
              "        DISTINCTCOUNT(movements[id]),",
              "        movements[status]<>\"A\",",
              "        orders[order_type_id]=\"PARTIAL\",",
              "        orders[bill_distance]>50,",
              "        USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date]),",
              "        USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              "    )",
              "",
              "Var count_of_trackable_movements = count_ftl+count_bw+count_partials",
              "",
              "RETURN",
              "count_of_trackable_movements"
            ],
            "formatString": "0",
            "lineageTag": "c307429e-78d5-4ff6-9520-469c4a7cd9a8"
          },
          {
            "name": "Count of movements with 3 or more pings",
            "description": "The distinct count of callin movements that were entered by loadmaster and has at least one tracking ping",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(callins[movement_id]),",
              "    FILTER(GROUPBY(callins,callins[movement_id]),[Count of tracking pings]>=3),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date]),",
              "    USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code]",
              "))"
            ],
            "formatString": "0",
            "lineageTag": "df5754d3-b223-4231-bb8a-39def543c971"
          },
          {
            "name": "Count of tracking pings",
            "description": "Count of callins that were entered by loadmaster",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": "CALCULATE([Count of Callins],callins[entered_by]=\"loadmaster\")",
            "formatString": "0",
            "lineageTag": "d3d0a73b-eeb1-4a55-9c16-c4d20e38a90e"
          },
          {
            "name": "Count of Callins",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(callins),",
              "    USERELATIONSHIP(callins[entered_date],'Calendar'[Date]),",
              "    USERELATIONSHIP(callins[entered_by],dispatcher_key[McLeod User Code])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "745f6c52-bce7-4aed-a430-abd1d9155a54"
          },
          {
            "name": "Percentage Of movement with 3 or more pings",
            "description": "Divides count of movements with 3 or more ping by count of trackable movements",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": "DIVIDE([Count of movements with 3 or more pings],[Count of Trackable Movements])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "06663e34-2ac5-4c2d-b23e-2f4cdab296d3"
          },
          {
            "name": "Date Diff order_entered_date vs shipper_sched_early_date",
            "expression": [
              "",
              "//CALCULATE(",
              "    DATEDIFF(MIN(orders[order_entered_date]),MIN(orders[shipper_sched_early_date]),DAY)//,",
              "    //FILTER(orders,orders[order_entered_date]>=MIN('Calendar'[Date])),",
              "    //ILTER(orders,orders[order_entered_date]<=MAX('Calendar'[Date]))",
              "//)"
            ],
            "formatString": "0",
            "lineageTag": "1859b08e-036c-4f3d-9186-8e213722335d"
          },
          {
            "name": "Date Diff Avail time vs shipper_sched_early_date",
            "expression": "DATEDIFF(MIN(crt_movement_data[Avail Time]),MIN(orders[shipper_sched_early_date]),DAY)",
            "formatString": "0",
            "lineageTag": "a19ead59-399d-4cc4-81fd-897c3024e0b9"
          },
          {
            "name": "Median Days Between enterd date and ship datea",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MEDIANX(orders,[Date Diff order_entered_date vs shipper_sched_early_date])",
            "lineageTag": "bf444e09-38a4-4f81-8c72-1f59b76f2e49"
          },
          {
            "name": "Movements Passed During Date Range",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(crt_movement_data[Movement ID]),",
              "    FILTER(orders,orders[shipper_sched_early_date]>=MIN('Calendar'[Date])),",
              "    FILTER(orders,orders[shipper_sched_early_date]<=MAX('Calendar'[Date]))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ddd39222-cbdb-4e56-b194-734028683608"
          },
          {
            "name": "Margin Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": [
              "CALCULATE(",
              "    SUM(margin_load_count_goals[Margin Goal]),",
              "    USERELATIONSHIP(margin_load_count_goals[Month],'Calendar'[Date])",
              ")",
              ""
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "55363ec6-7790-4d0d-8a43-73c298dc5628"
          },
          {
            "name": "Margin per day Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": [
              "",
              "Var workingdays = ",
              "    NETWORKDAYS(",
              "        STARTOFMONTH('Calendar'[Date]),",
              "        ENDOFMONTH('Calendar'[Date]),",
              "        1,",
              "        observed_holidays)",
              "Var months_margin_goal = CALCULATE([Margin Goal],REMOVEFILTERS('calendar'[Date]))",
              "Var override_mpdg = CALCULATE([Override margin goal],REMOVEFILTERS('calendar'[Date]))",
              "Var mpd = DIVIDE(months_margin_goal,workingdays)",
              "",
              "Var override_blank = IF(override_mpdg=0,mpd,override_mpdg)",
              "",
              "Var wolf_pack_switch = SWITCH(TRUE(),SELECTEDVALUE(wolf_pack[wolf_pack])=BLANK(),override_blank,mpd)",
              "",
              "Var mpdg = SWITCH(TRUE(),SELECTEDVALUE(salesperson_key[Name])=BLANK(),wolf_pack_switch,mpd)",
              "",
              "Return",
              "mpdg"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "3c153d48-ca5a-4d48-985d-cdb795469f1a"
          },
          {
            "name": "Override margin goal",
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": "SUM(daily_number_override[Margin Number])",
            "formatString": "0",
            "lineageTag": "58b95798-7025-4b5f-b506-d04cbc04c4ea"
          },
          {
            "name": "Best Margin Month Ever",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    MAXX(",
              "        GROUPBY('calendar','calendar'[Month / Year]),",
              "        [Margin]),",
              "        REMOVEFILTERS('calendar'[Year]),",
              "        REMOVEFILTERS('calendar'[Month Name])",
              ")"
            ],
            "lineageTag": "daef51bf-c98d-4a88-b79f-8f3c7b345729"
          },
          {
            "name": "Margin vs Margin Goal Gauge Max",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Margin Vs Margin Goal Target]*1.2"
            ],
            "lineageTag": "745cec3f-21ab-43c5-b78f-9f250e7f422a"
          },
          {
            "name": "Margin Vs Margin Goal Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "expression": [
              "",
              "Var workingdays = ",
              "    NETWORKDAYS(",
              "        STARTOFMONTH('Calendar'[Date]),",
              "        ENDOFMONTH('Calendar'[Date]),",
              "        1,",
              "        observed_holidays)",
              "Var months_margin_goal = CALCULATE([Margin Goal],REMOVEFILTERS('calendar'[Date]))",
              "Var override_mpdg = CALCULATE([Override margin goal],REMOVEFILTERS('calendar'[Date]))",
              "Var mpd = DIVIDE(months_margin_goal,workingdays)",
              "",
              "Var override_blank = IF(override_mpdg=0,mpd,override_mpdg)",
              "",
              "Var wolf_pack_switch = SWITCH(TRUE(),SELECTEDVALUE(wolf_pack[wolf_pack])=BLANK(),override_blank,mpd)",
              "",
              "Var mpdg = SWITCH(TRUE(),SELECTEDVALUE(salesperson_key[Name])=BLANK(),wolf_pack_switch,mpd)",
              "Var margin_vs_margin_goal_taget = mpdg*workingdays",
              "",
              "Return",
              "margin_vs_margin_goal_taget"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "966f15fa-987f-4b97-9482-70a30dd385aa"
          },
          {
            "name": "Load Count Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": [
              "",
              "Var margin_per_order_LM = CALCULATE([Margin Per Order],DATEADD('calendar'[Date],-1,MONTH))",
              "Var load_count_goal = DIVIDE([Margin Goal],margin_per_order_LM)",
              "Var ifs= ",
              "    IF(margin_per_order_LM=0,5,load_count_goal)",
              "",
              "Return ",
              "ifs"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2a86da4e-c9e9-4e86-9b72-e31c6127ff29"
          },
          {
            "name": "Margin Per Order",
            "displayFolder": "Sales Measures",
            "expression": "DIVIDE([Margin], [Count of orders covered])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "1e92098d-807f-401d-8b48-026cdf35c733"
          },
          {
            "name": "Load Count Vs Load Count Goal Target",
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": [
              "",
              "Var margin_per_order_LM = CALCULATE([Margin Per Order],DATEADD('calendar'[Date],-  1,MONTH))",
              "Var load_count_goal = DIVIDE([Margin Vs Margin Goal Target],margin_per_order_LM)",
              "Var ifs= ",
              "    IF(margin_per_order_LM=0,5,load_count_goal)",
              "",
              "Return ",
              "ifs"
            ],
            "formatString": "0",
            "lineageTag": "704d7233-1d7c-45f8-bfcf-191b95d7ba85"
          },
          {
            "name": "Load Count Vs Load Count Goal Guage Max",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": [
              "",
              "IF(",
              "    [Best Count of Orders Month Ever]<=[Load Count Vs Load Count Goal Target],",
              "    [Load Count Vs Load Count Goal Target],",
              "    [Best Count of Orders Month Ever]",
              ")"
            ],
            "lineageTag": "9db04751-8d6c-420e-94b4-920d257f54ae"
          },
          {
            "name": "Margin Per Order Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Measures",
            "expression": "AVERAGE(margin_load_count_goals[Margin Per Order Goal])",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "63a8de8b-8087-47f7-a15c-70f504db55bb"
          },
          {
            "name": "Margin Per Order Vs Margin Per Order Guage Max",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Sales Measures",
            "expression": "[Margin Per Order Goal]*1.2",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "6aba0cbd-4108-449d-b002-60f0d64d4642"
          },
          {
            "name": "Margin %",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE([Margin],[Total Revenue]),",
              "    movements[status]<>\"A\",",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "60d83be5-356c-48e2-afb8-950ca6a8f0d6"
          },
          {
            "name": "Avg Margin % Goal",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": "AVERAGE(margin_load_count_goals[Margin % Goal])",
            "lineageTag": "25b26eda-8482-4b31-b474-39dd05f20b67"
          },
          {
            "name": "Margin % vs Margin % Gaol Guage Max",
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": "[Avg Margin % Goal]*1.2",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52135639-0ea4-4a21-b50b-d3cda46d34ab"
          },
          {
            "name": "Count of Behaviors (Start of Month)",
            "displayFolder": "Behavior Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(behaviors[id]),",
              "    USERELATIONSHIP(behaviors[Start of Month],'Calendar'[Date]),",
              "    USERELATIONSHIP(behaviors[author_id],salesperson_key[Name])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "508c3248-8bb5-49b4-aa0b-b1b8441be78a"
          },
          {
            "name": "Behavior Goal",
            "displayFolder": "Behavior Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(behavior_goals[Goal]),",
              "    USERELATIONSHIP(behaviors[Behavior Date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d9fa1a26-27a0-4cdf-91c4-74dae6b80875"
          },
          {
            "name": "Behavior Progress",
            "displayFolder": "Behavior Measures",
            "expression": [
              "",
              "VAR behavior_progress = ",
              "CALCULATE(",
              "    DIVIDE([Count of Behaviors (Start of Month)],[Behavior Goal]),",
              "    USERELATIONSHIP(behaviors[Behavior Date],'Calendar'[Date]),",
              "    USERELATIONSHIP(behaviors[author_id],salesperson_key[Name])",
              ")",
              "VAR ifs = ",
              "    IF(behavior_progress=0,0,",
              "    IF(behavior_progress>=1,1,",
              "    behavior_progress)",
              "    )   ",
              "",
              "RETURN",
              "ifs"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9425cfaf-692b-4c97-be0b-9419a7facb61"
          },
          {
            "name": "Customer Margin Goal",
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(customer_margin_goal[Margin Goal]),",
              "    FILTER(customer_margin_goal,customer_margin_goal[Month]>=MIN('Calendar'[Date])),",
              "    FILTER(customer_margin_goal,customer_margin_goal[Month]<=MAX('Calendar'[Date]))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8a792569-588e-4c4e-bd17-d3cb5ef75342"
          },
          {
            "name": "Customer Margin vs Customer Margin Goal Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": "if([Customer Margin Goal]<=0,BLANK(),[Margin]-[Customer Margin Goal])",
            "lineageTag": "438d88b1-8efa-4ed8-bfa5-327e8f10a2b2"
          },
          {
            "name": "Last Ship Date",
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX(orders[shipper_sched_early_date]),",
              "    FILTER(movements,movements[status]<>\"A\")",
              ")"
            ],
            "formatString": "Short Date",
            "lineageTag": "4ddeeb99-9208-43d3-9de0-e78a3a002678"
          },
          {
            "name": "Days Since Last Shipment",
            "displayFolder": "Operations Measures",
            "expression": "DATEDIFF([Last Ship Date],TODAY(),DAY)",
            "formatString": "0",
            "lineageTag": "cd2518a5-1971-4101-b5d5-a517690f5c58"
          },
          {
            "name": "Days since Last Stage Update",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              " DATEDIFF(",
              "    MAX(crm[Last Stage Change]),TODAY(),DAY)"
            ],
            "formatString": "0",
            "lineageTag": "ecc086f7-a6d4-4e6c-b109-8712f700c70f"
          },
          {
            "name": "Last Behavior Date",
            "displayFolder": "CRM Measures",
            "expression": "MAX(behaviors[Behavior Date])",
            "formatString": "Short Date",
            "lineageTag": "9de3f64a-8161-47da-8c52-3bc6064fa7f6"
          },
          {
            "name": "Days since last Behaivor",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": "DATEDIFF([Last Behavior Date],TODAY(),DAY)",
            "formatString": "0",
            "lineageTag": "939bbb4f-4255-422a-8b62-c12028881045"
          },
          {
            "name": "Days Over Due",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              "Var next_behavior_deadline = MAX(crm[activity_date_deadline])",
              "Var days_over_due = DATEDIFF(next_behavior_deadline,TODAY(),DAY)",
              "",
              "Return ",
              "days_over_due"
            ],
            "formatString": "0",
            "lineageTag": "b3661191-11ac-461a-a125-be02d2b1eafa"
          },
          {
            "name": "Days since Last Shipment is over 120",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              "Var at_risk = IF([Days Since Last Shipment]>120,1,0)",
              "Var ifs = ",
              "    IF(MIN(crm[Stage])=\"Customer\",at_risk,",
              "    IF(MIN(crm[Stage])=\"1-3 Loads\",at_risk,0))",
              "",
              "",
              "return",
              "ifs"
            ],
            "formatString": "0",
            "lineageTag": "3793a2a6-a34b-4e02-85bd-cbb0c0bb76e4"
          },
          {
            "name": "Days since last stage update is one of the reasons at risk reason",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              "Var prospect_at_risk = if([Days since Last Stage Update]>90,1,0)",
              "Var pipeline_at_risk = IF([Days since Last Stage Update]>60,1,0)",
              "Var ifs = ",
              "    IF(MIN(crm[Stage])=\"Customer\",0,",
              "    IF(MIN(crm[Stage])=\"Working\",prospect_at_risk,",
              "    IF(MIN(crm[Stage])=\"No For Now\",prospect_at_risk,",
              "    IF(MIN(crm[Stage])=\"Qualified\",pipeline_at_risk,",
              "    IF(MIN(crm[Stage])=\"Quoted\",pipeline_at_risk,",
              "    IF(MIN(crm[Stage])=\"Credit App\",pipeline_at_risk,",
              "    IF(MIN(crm[Stage])=\"1-3 Loads\",pipeline_at_risk,0)))))))",
              "",
              "Return",
              "ifs"
            ],
            "formatString": "0",
            "lineageTag": "42d46d32-f0e6-41df-b84d-8c3cfdc8b2a9"
          },
          {
            "name": "Days Since Last Behavior is one of the reason for at risk",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              "Var opportunity_at_risk = IF([Days since last Behaivor]>60,1,0)",
              "Var working_at_risk = IF([Days since last Behaivor]>60,1,0)",
              "Var no_for_now_at_risk = IF([Days since last Behaivor]>90,1,0)",
              "",
              "Var Ifs = ",
              "    IF(MIN(crm[Stage])=\"Qualified\",opportunity_at_risk,",
              "    IF(MIN(crm[Stage])=\"Quoted\",opportunity_at_risk,",
              "    IF(MIN(crm[Stage])=\"Credit App\", opportunity_at_risk,",
              "    IF(MIN(crm[Stage])=\"1-3 Loads\",opportunity_at_risk,",
              "    IF(MIN(crm[Stage])=\"Customer\",opportunity_at_risk,",
              "    IF(MIN(crm[Stage])=\"Working\",working_at_risk,",
              "    IF(MIN(crm[Stage])=\"No For Now\",no_for_now_at_risk,0)))))))",
              "",
              "Return",
              "Ifs"
            ],
            "formatString": "0",
            "lineageTag": "d2fccc3b-65d6-4647-81ff-6908557e9873"
          },
          {
            "name": "Days since last Salesperson Update",
            "displayFolder": "CRM Measures",
            "expression": "DATEDIFF(MAX(crm[date_open]),TODAY(),DAY)",
            "formatString": "0",
            "lineageTag": "cfbd7a5c-e9af-4629-a9f9-e6c37a23dfdc"
          },
          {
            "name": "Count at Risk (inactive relationship)",
            "displayFolder": "CRM Measures\\At Risk Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(crm[id]),",
              "    FILTER(crm,crm[At Risk]=\"TRUE\"),",
              "    FILTER(crm,crm[user_id]<>BLANK()),",
              "    USERELATIONSHIP(crm[user_id],salesperson_key[Name])",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "81759a22-7856-45de-82cd-a68019cf40d6"
          },
          {
            "name": "Count CRM Ids (inactive relationship)",
            "displayFolder": "CRM Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(crm[id]),",
              "    USERELATIONSHIP(crm[user_id],salesperson_key[Name])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "19e37e8b-c64b-48e0-b627-934b7174ffa5"
          },
          {
            "name": "Healthy Pipeline Goal",
            "displayFolder": "CRM Measures",
            "expression": "SUM(healthy_pipeline_goals[Healthy #])",
            "formatString": "0",
            "lineageTag": "e0a10483-e230-4010-bcb6-233162a58619"
          },
          {
            "name": "Margin MTD",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD(",
              "    [Margin],",
              "    'Calendar'[Date],'Calendar'[Day of Month]<DAY(TODAY())),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              "    )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "e2f3473a-04fe-48ca-9ca3-788630877152"
          },
          {
            "name": "Count of Orders Covered MTD",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Month To Date",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD(",
              "    [Count of orders covered],",
              "    'Calendar'[Date],'Calendar'[Day of Month]<DAY(TODAY())),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "02f71283-e287-4086-8bc8-d6c66a160475"
          },
          {
            "name": "Count of Orders Covered MTD 1MA",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Month To Date\\Months Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count of Orders Covered MTD],",
              "    DATEADD('Calendar'[Date],-1,MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3395a581-5b2a-4bcf-b3e0-e332ab68d6f6"
          },
          {
            "name": "Margin MTD 1MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date\\Months Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margin MTD],",
              "    DATEADD('Calendar'[Date],-1,MONTH)",
              ")"
            ],
            "lineageTag": "6a78951f-d159-4bf4-88c0-ec8a055e80fb"
          },
          {
            "name": "Count of Orders Covered MTD MOM diff",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Month over Month",
            "expression": "[Count of Orders Covered MTD]-[Count of Orders Covered MTD 1MA]",
            "formatString": "0",
            "lineageTag": "98c65d90-b4d4-4af1-bcfe-02d7f06db6c1"
          },
          {
            "name": "Margin MTD MOM Variance",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date\\Month over Month",
            "expression": "[Margin MTD]-[Margin MTD 1MA]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b7ea4c06-ed51-4878-8892-8289c5f07532"
          },
          {
            "name": "Customers Served",
            "description": [
              "Count the Distinct customer id values in the order table during a filtered time",
              "***any time you use this measure you must filter move status to not contain \"A\")***"
            ],
            "displayFolder": "Behavior Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(orders[customer_id]),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8937494c-6a1b-4e84-aa53-089ae43da266"
          },
          {
            "name": "Customer Served 90 days before max date",
            "displayFolder": "Behavior Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(orders[customer_id]),",
              "    FILTER(movements,movements[status]<>\"A\"),",
              "    FILTER(orders,orders[shipper_sched_early_date]<=MAX('Calendar'[Date])),",
              "    FILTER(orders,orders[shipper_sched_early_date]>=(MAX('Calendar'[Date])-90))",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "3be00b8e-0192-495c-83db-113ec47d3dfb"
          },
          {
            "name": "Margin MTD 1YA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date\\Years Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margin MTD],",
              "    DATEADD('Calendar'[Date],-1,YEAR)",
              ")"
            ],
            "lineageTag": "7d3c9624-3107-4862-844d-9cf3817805e9"
          },
          {
            "name": "Count of Orders Covered MTD 1YA",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Month To Date\\Years Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count of Orders Covered MTD],",
              "    DATEADD('Calendar'[Date],-1,YEAR)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "611ccfe9-33a5-44e9-84f7-8adc0ae062a4"
          },
          {
            "name": "Margin QTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Quarter To Date",
            "expression": [
              "",
              "VAR today_doq = ",
              "    CALCULATE(",
              "        MIN('Calendar'[Day of Quarter]),",
              "        'Calendar'[Date]=TODAY()",
              "    )",
              "VAR margin_qtd = ",
              "    TOTALQTD(",
              "        [Margin],",
              "        'Calendar'[Date],",
              "        'Calendar'[Day of Quarter]<today_doq",
              "    )",
              "",
              "RETURN",
              "margin_qtd"
            ],
            "lineageTag": "ee10562b-be25-4017-81db-38b25e35defa"
          },
          {
            "name": "Count of Orders Covered QTD",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Quarter To Date",
            "expression": [
              "",
              "Var today_doq = ",
              "    CALCULATE(",
              "        MIN('calendar'[Day of Quarter]),",
              "        'calendar'[Date]=TODAY()",
              "    )",
              "",
              "Var load_count_qtd = ",
              "    TOTALQTD(",
              "        [Count of Orders Covered],",
              "        'calendar'[Date],",
              "        'calendar'[Day of Quarter]<today_doq",
              "    )",
              "",
              "Return ",
              "load_count_qtd"
            ],
            "formatString": "0",
            "lineageTag": "558e2a81-0e76-4f52-8cea-67309659d92f"
          },
          {
            "name": "Count of Orders Covered QTD 1QA",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Quarter To Date\\Quarters Ago",
            "expression": [
              "",
              "VAR today_doq = ",
              "    CALCULATE(",
              "        MIN('Calendar'[Day of Quarter]),",
              "        'Calendar'[Date]=TODAY()",
              "    )",
              "    ",
              "Var soq_1qa =",
              "    CALCULATE(",
              "        STARTOFQUARTER('Calendar'[Date]),",
              "        DATEADD('Calendar'[Date],-1,QUARTER)",
              "    )",
              "",
              "VAR qtd_date_1_qa = soq_1qa+today_doq-1",
              "",
              "VAR count_of_orders_1_qa = ",
              "    CALCULATE(",
              "        [Count of orders covered],",
              "        'Calendar'[Date]>=soq_1qa,",
              "        'Calendar'[Date]<qtd_date_1_qa",
              "    )",
              "",
              "RETURN",
              "count_of_orders_1_qa"
            ],
            "formatString": "0",
            "lineageTag": "8cb0ba1f-3282-46bc-9ed7-808320879c6d"
          },
          {
            "name": "Count of Orders Covered QTD 4QA",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Quarter To Date\\Quarters Ago",
            "expression": [
              "",
              "VAR today_doq = ",
              "    CALCULATE(",
              "        MIN('Calendar'[Day of Quarter]),",
              "        'Calendar'[Date]=TODAY()",
              "    )",
              "    ",
              "Var soq_4qa =",
              "    CALCULATE(",
              "        STARTOFQUARTER('Calendar'[Date]),",
              "        DATEADD('Calendar'[Date],-4,QUARTER)",
              "    )",
              "",
              "VAR qtd_date_4_qa = soq_4qa+today_doq-1",
              "",
              "VAR load_count_4qa =",
              "    CALCULATE(",
              "        [Count of orders covered],",
              "        'Calendar'[Date]>=soq_4qa,",
              "        'Calendar'[Date]<qtd_date_4_qa",
              "    )",
              "",
              "RETURN",
              "load_count_4qa"
            ],
            "formatString": "0",
            "lineageTag": "f10af020-daac-40fe-a4de-39f4b82dad2c"
          },
          {
            "name": "Margin QTD 1QA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Quarter To Date\\Quarter Ago",
            "expression": [
              "",
              "VAR today_doq = ",
              "    CALCULATE(",
              "        MIN('Calendar'[Day of Quarter]),",
              "        'Calendar'[Date]=TODAY()",
              "    )",
              "    ",
              "Var soq_1qa =",
              "    CALCULATE(",
              "        STARTOFQUARTER('Calendar'[Date]),",
              "        DATEADD('Calendar'[Date],-1,QUARTER)",
              "    )",
              "",
              "VAR qtd_date_1_qa = soq_1qa+today_doq-1",
              "",
              "VAR margin_qtd_1qa = ",
              "    CALCULATE(",
              "        [Margin],",
              "        'Calendar'[Date]>=soq_1qa,",
              "        'Calendar'[Date]<qtd_date_1_qa",
              "    )",
              "",
              "RETURN",
              "margin_qtd_1qa"
            ],
            "lineageTag": "fa414730-b854-417c-8ca2-d272873b7212"
          },
          {
            "name": "Margin QTD 4QA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Quarter To Date\\Quarter Ago",
            "expression": [
              "",
              "VAR today_doq = ",
              "    CALCULATE(",
              "        MIN('Calendar'[Day of Quarter]),",
              "        'Calendar'[Date]=TODAY()",
              "    )",
              "    ",
              "Var soq_4qa =",
              "    CALCULATE(",
              "        STARTOFQUARTER('Calendar'[Date]),",
              "        DATEADD('Calendar'[Date],-4,QUARTER)",
              "    )",
              "",
              "VAR qtd_date_4_qa = soq_4qa+today_doq-1",
              "",
              "VAR margin_4qa = ",
              "    CALCULATE(",
              "        [Margin],",
              "        'Calendar'[Date]>=soq_4qa,",
              "        'Calendar'[Date]<qtd_date_4_qa",
              "    )",
              "",
              "RETURN",
              "margin_4qa"
            ],
            "lineageTag": "2bc66d87-9e99-4447-b996-c8b492e70d0d"
          },
          {
            "name": "Margin QTD QOQ Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Quarter To Date\\Years over Year",
            "expression": "[Margin QTD]-[Margin QTD 1QA]",
            "lineageTag": "4f7d0439-0e1f-43d4-9a23-4141be5697b7"
          },
          {
            "name": "Count of Orders Covered QTD QOQ diff",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Quarter To Date\\Quarter over Quarter",
            "expression": "[Count of Orders Covered QTD]-[Count of Orders Covered QTD 1QA]",
            "formatString": "0",
            "lineageTag": "eaec4336-bee2-4f26-96c2-b39111bb8949"
          },
          {
            "name": "Margin YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Year To Date",
            "expression": [
              "",
              "Var today_doy = ",
              "    CALCULATE(",
              "        MIN('calendar'[Day of Year]),",
              "        'calendar'[Date]=TODAY()",
              "    )",
              "",
              "Var margin_ytd = ",
              "    TOTALYTD(",
              "        [Margin],",
              "        'calendar'[Date],'calendar'[Day of Year]<today_doy",
              "    )",
              "",
              "Return",
              "margin_ytd"
            ],
            "lineageTag": "1d0e2f56-6933-40e9-99e1-045825ad447d"
          },
          {
            "name": "Margin YTD 1YA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Year To Date\\Years Ago",
            "expression": "CALCULATE([Margin YTD],DATEADD('calendar'[Date],-1,YEAR))",
            "lineageTag": "9aab8f33-2937-4a2d-9ae3-114d1d16dec9"
          },
          {
            "name": "Margin YTD YOY Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Year To Date\\Year over Year",
            "expression": "[Margin YTD]-[Margin YTD 1YA] ",
            "lineageTag": "8716c284-daf4-47db-980f-f24010fd28ee"
          },
          {
            "name": "Count of Orders Covered YTD 1YA",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Year To Date\\Years Ago",
            "expression": [
              "",
              "CALCULATE(",
              "    [Count of Orders Covered YTD],",
              "    DATEADD('calendar'[Date],-1,YEAR))"
            ],
            "lineageTag": "1e3a88fc-c1c7-43b6-968e-5fdf0d31b3b8"
          },
          {
            "name": "Count of Orders Covered YTD",
            "displayFolder": "Operations Measures\\Count of Orders\\To Date Measures\\Year To Date",
            "expression": [
              "",
              "Var today_doy = ",
              "    CALCULATE(",
              "        MIN('calendar'[Day of Year]),'calendar'[Date]=TODAY())",
              "",
              "Var load_count_ytd = ",
              "    TOTALYTD([Count of Orders Covered],",
              "    'calendar'[Date],'calendar'[Day of Year]<today_doy)",
              "",
              "Return",
              "load_count_ytd"
            ],
            "formatString": "0",
            "lineageTag": "3f3d7cef-9b5d-4cf5-987f-7fab625bbb96"
          },
          {
            "name": "Working Days",
            "displayFolder": "Calendar Measures",
            "expression": [
              "",
              "    NETWORKDAYS(",
              "        MIN('calendar'[Date]),",
              "        MAX('calendar'[Date]),",
              "        1,",
              "        observed_holidays)"
            ],
            "formatString": "0",
            "lineageTag": "d70e9109-84ce-476d-8bd6-0e54ffa3d32c"
          },
          {
            "name": "Working days Elapsed",
            "displayFolder": "Calendar Measures",
            "expression": [
              "",
              "If(DAY(TODAY())=1,0,",
              "    NETWORKDAYS(",
              "        MIN('Calendar'[Date]),",
              "        TODAY()-1,",
              "        1,",
              "        observed_holidays))"
            ],
            "formatString": "0",
            "lineageTag": "d3c241c2-0579-48e7-88dd-48fb8c0c0bef"
          },
          {
            "name": "Working Day Of Month",
            "displayFolder": "Calendar Measures",
            "expression": [
              "",
              "VAR start_of_month = STARTOFMONTH('Calendar'[Date])",
              "",
              "VAR working_day_of_month = ",
              "    NETWORKDAYS(start_of_month,MIN('Calendar'[Date]),1,observed_holidays)",
              "",
              "RETURN",
              "working_day_of_month"
            ],
            "formatString": "0",
            "lineageTag": "3dfc50b0-8122-4d21-9f46-a8b74b093e65"
          },
          {
            "name": "Avg Behavior Progress",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Behavior Measures",
            "expression": "AVERAGEX(behavior_goals,[Behavior Progress])",
            "lineageTag": "5a7365af-9f5b-4554-af04-b12bda13cd22"
          },
          {
            "name": "Behavior Points",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BWS\\Sales",
            "expression": [
              "",
              "VAR max_points_pre_july24 = 30",
              "",
              "var behavior_points_pre_july_24 = ",
              "    IF([Avg Behavior Progress]=0,0,",
              "    IF([Avg Behavior Progress]>=1,max_points_pre_july24,",
              "    [Avg Behavior Progress]*max_points_pre_july24",
              "    ))",
              "",
              "var max_points_post_after_july24 = 20",
              "",
              "var behavior_points_after_july24 = ",
              "    IF([Avg Behavior Progress]=0,0,",
              "    IF([Avg Behavior Progress]>=1,max_points_post_after_july24,",
              "    [Avg Behavior Progress]*max_points_post_after_july24",
              "    ))",
              "",
              "var behavior_points = ",
              "    IF(MIN('calendar'[Date])>=45474,behavior_points_after_july24,behavior_points_pre_july_24)",
              "",
              "return",
              "behavior_points"
            ],
            "lineageTag": "d5d7311d-0c6e-443a-a358-862de785a164"
          },
          {
            "name": "Sales Margin Points",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BWS\\Sales",
            "expression": [
              "",
              "",
              "VAR max_points_pre_july24 = 30",
              "VAR max_points_after_july_24 = 80",
              "VAR margin_progress = ",
              "    DIVIDE(",
              "        [Margin],",
              "        [Margin Goal]",
              "    )",
              "VAR margin_points_pre_july24 =",
              "IF(margin_progress=0,0,",
              "    IF(margin_progress>=1,max_points_pre_july24,",
              "    margin_progress*max_points_pre_july24)",
              ")",
              "VAR margin_points_after_july24 =",
              "IF(margin_progress=0,0,",
              "    IF(margin_progress>=1,max_points_after_july_24,",
              "    margin_progress*max_points_after_july_24)",
              ")",
              "VAR margin_points = ",
              "IF(",
              "    MIN(",
              "        'calendar'[Date])>=45474,",
              "        margin_points_after_july24,",
              "        margin_points_pre_july24",
              ")",
              "RETURN",
              "margin_points"
            ],
            "lineageTag": "366d5a3d-12a2-4d90-a7fa-49cd1c2a1174"
          },
          {
            "name": "Total Sales BWS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BWS\\Sales",
            "expression": "[Behavior Points]+[Sales Margin Points]",
            "lineageTag": "f4bce828-460a-4b85-bd63-dbd1d5cf8925"
          },
          {
            "name": "Avg Sales BWS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BWS\\Sales",
            "expression": [
              "",
              "AVERAGEX(",
              "    GROUPBY(",
              "        salesperson_key,salesperson_key[Name]),",
              "        [Total Sales BWS]",
              ")"
            ],
            "lineageTag": "e044a4d4-e160-491b-999a-542cc460a39c"
          },
          {
            "name": "Best Count of Orders Month Ever",
            "expression": [
              "",
              "CALCULATE(",
              "    MAXX(",
              "        GROUPBY('calendar','calendar'[Month / Year]),",
              "        [Count of Orders Covered]),",
              "        REMOVEFILTERS('calendar'[Year]),",
              "        REMOVEFILTERS('calendar'[Month Name])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "af59b05b-5558-4cb4-998d-ac18cbb73e75"
          },
          {
            "name": "ship_scheduled_early_date use filter",
            "expression": "CALCULATE(MIN(orders[shipper_sched_early_date]),USERELATIONSHIP('orders'[shipper_sched_early_date],'Calendar'[Date]))",
            "formatString": "General Date",
            "lineageTag": "8ef32bc1-e416-4a0c-a8aa-1b54a4e5e03a"
          },
          {
            "name": "Current Sales",
            "displayFolder": "HR",
            "expression": [
              "",
              "",
              "Var current_sales = ",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date])))",
              ")",
              "",
              "Var current_d_team = ",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date]))),",
              "    FILTER(job_history,job_history[Division] IN {\"Development Team\",\"Development Team Sales\"})",
              ")",
              "",
              "Var current_logistics_advisor = ",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date]))),",
              "    FILTER(job_history,job_history[Division]=\"Logistics Advisor Sales (Formerly Henry)\")",
              ")",
              "",
              "Var current_Sr_logistics_advisor = ",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date]))),",
              "    FILTER(job_history,job_history[Division]=\"Sr. Logistics Advisor Sales\")",
              ")",
              "",
              "Var devision_logistics_advisor = SWITCH(TRUE(),SELECTEDVALUE(division_key[Division]) = (\"Logistics Advisor Sales (Formerly Henry)\"),current_logistics_advisor,current_Sr_logistics_advisor)",
              "Var devision_d_team = SWITCH(TRUE(),SELECTEDVALUE(division_key[Division]) IN {\"Development Team\",\"Development Team Sales\"},current_d_team,devision_logistics_advisor)",
              "Var devision_blank = SWITCH(TRUE(),SELECTEDVALUE(division_key[Division])=BLANK(),current_sales,devision_d_team)",
              "",
              "RETURN",
              "devision_blank"
            ],
            "formatString": "0",
            "lineageTag": "8c52c57f-8be2-4a63-bb16-583ee6d08bcc"
          },
          {
            "name": "Max Trackable Movements Grouped by dispatcher",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": [
              "",
              "    CALCULATE(",
              "        MAXX(",
              "            GROUPBY(employees,employees[Name]),",
              "            [Count of Trackable Movements])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "8f162413-852d-402c-9d25-253c72ef8813"
          },
          {
            "name": "Max trackable Movements grouped by day",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": [
              "",
              "    CALCULATE(",
              "        MAXX(",
              "            GROUPBY('calendar','calendar'[Date]),",
              "            [Count of Trackable Movements]))"
            ],
            "formatString": "0",
            "lineageTag": "826c46a5-8a6c-4fe0-ad2e-727c2254d6b2"
          },
          {
            "name": "Count of SOPCAR Issues",
            "displayFolder": "Operations Measures\\SOP",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(sop_issues),",
              "    sop_issues[Movement ID],",
              "    sop_issues[SOP Type]= \"SOPCAR\",",
              "    USERELATIONSHIP(sop_issues[Date_time],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "06099b06-b567-4df5-ac37-307c760a22b6"
          },
          {
            "name": "Count of SOPP Issues",
            "displayFolder": "Operations Measures\\SOP",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(sop_issues),",
              "    sop_issues[Movement ID],",
              "    sop_issues[SOP Type]= \"SOPP\",",
              "    USERELATIONSHIP(sop_issues[Date_time],'Calendar'[Date]),",
              "    USERELATIONSHIP(orders[entered_user_id],dispatcher_key[McLeod User Code])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "958dcfad-b5a3-4618-a8f1-c2e4c598c810"
          },
          {
            "name": "Count of movements with 3 or more pings test",
            "displayFolder": "Movement Measures\\Callins Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTAX(",
              "    callins,",
              "    DISTINCTCOUNT(callins[movement_id])),",
              "    callins[entered_by]=\"loadmaster\")"
            ],
            "formatString": "0",
            "lineageTag": "4941b666-49d4-47e0-8193-4752cf31b7aa"
          },
          {
            "name": "Count of SOPD Issues",
            "displayFolder": "Operations Measures\\SOP",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(sop_issues),",
              "    sop_issues[Movement ID],",
              "    sop_issues[SOP Type]= \"SOPD\",",
              "    USERELATIONSHIP(sop_issues[Date_time],'Calendar'[Date]),",
              "    USERELATIONSHIP(orders[entered_user_id],dispatcher_key[McLeod User Code]))"
            ],
            "formatString": "0",
            "lineageTag": "106146c5-55dc-453b-ab38-14b62ff74db1"
          },
          {
            "name": "Count of Overdue Check Calls",
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(overdue_check_calls),",
              "    USERELATIONSHIP(overdue_check_calls[Check Call Date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "743224af-0c45-4273-8398-82d1cc673e7c"
          },
          {
            "name": "Current Carrier Tracking Team",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(job_history),",
              "    FILTER(VALUES(job_history[Job Start Date]),job_history[Job Start Date] <= MAX('calendar'[Date])),",
              "    FILTER(VALUES(job_history[Job End Date]), OR(job_history[Job End Date] >= MIN('calendar'[Date]), ISBLANK(job_history[Job End Date]))),",
              "    FILTER(job_history,job_history[Division]=\"CRT-Track and Trace\"))"
            ],
            "formatString": "0",
            "lineageTag": "71cd02e2-6da4-4121-977d-e41a58ebf14b"
          },
          {
            "name": "Margin per Dispatcher",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margin],",
              "    USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code]))"
            ],
            "lineageTag": "45a905e5-9524-4417-8991-3362af84ecc1"
          },
          {
            "name": "Margin per Order (Dispatcher)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margin Per Order],",
              "    USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              "    )"
            ],
            "lineageTag": "562c8d18-0a35-470c-9078-900cd3f084b3"
          },
          {
            "name": "Margin % per Dispatcher",
            "displayFolder": "Operations Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    [Margin %],",
              "    USERELATIONSHIP(movements[dispatcher_user_id],dispatcher_key[McLeod User Code])",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4e428cdd-0f19-4d35-83bd-c0d27bbf5aab"
          },
          {
            "name": "Overdue Check Calls vs Count of Check Calls",
            "displayFolder": "Operations Measures",
            "expression": "DIVIDE([Count of Overdue Check Calls],[Count of Callins])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "578a3e5e-bf61-4a2d-bf8b-3ae093d1c9d7"
          },
          {
            "name": "Commission Rate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "",
              "VAR new_commission_jan = ",
              "    IF([Margin Vs Margin Goal Variance]>=0,",
              "    [Standard Commission Rate],",
              "    [Strike One Commissions]",
              "    )",
              "",
              "VAR new_commission_feb = ",
              "    IF([Margin Vs Margin Goal Variance]>=0,[Standard Commission Rate],",
              "    IF([Margin Vs Margin Goal 1MA]>=0,[Strike One Commissions],",
              "    IF([Margin Vs Margin Goal 2MA]>=0,[Strike One Commissions],",
              "    [Strike Two Commissions])))",
              "",
              "VAR new_commission =  ",
              "IF([Margin Vs Margin Goal Variance]>=0,[Standard Commission Rate],",
              "    IF([Margin Vs Margin Goal 1MA]>=0,[Strike One Commissions],",
              "    IF([Margin Vs Margin Goal 2MA]>=0,[Strike Two Commissions],",
              "    [Strike Three Commissions]",
              ")))",
              "",
              "VAR ifs = ",
              "    IF(Max('Calendar'[Date]) < 45658, [Standard Commission Rate],",
              "    IF(MIN('Calendar'[Date]) >= 45689 && MAX('Calendar'[Date]) <= 45716,new_commission_feb,",
              "    IF(MIN('Calendar'[Date]) >= 45658 && MAX('Calendar'[Date]) <= 45688,new_commission_jan,",
              "    new_commission))",
              "    )",
              "",
              "",
              "RETURN",
              "ifs"
            ],
            "isHidden": true,
            "lineageTag": "c9b4ce9d-b212-41d3-8b92-8640f89d3c41"
          },
          {
            "name": "Margin Vs Margin Goal Variance",
            "displayFolder": "Sales Measures\\Sales Goals\\Margin",
            "expression": "[Margin]-[Margin Goal]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "2361c828-7356-4d14-8a9c-b6835eee2164"
          },
          {
            "name": "Margin Vs Margin Goal 1MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "CALCULATE( ",
              "    [Margin Vs Margin Goal Variance],",
              "    DATEADD('Calendar'[Date],-1,MONTH)",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "badea8ac-28cc-460b-a63e-6565293c1147"
          },
          {
            "name": "Margin Vs Margin Goal 2MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "CALCULATE( ",
              "    [Margin Vs Margin Goal Variance],",
              "    DATEADD('Calendar'[Date],-2,MONTH)",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "bd03f181-fcb7-4159-a884-b0f22ca9120d"
          },
          {
            "name": "Margin Vs Margin Goal 3MA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "CALCULATE( ",
              "    [Margin Vs Margin Goal Variance],",
              "    DATEADD('Calendar'[Date],-3,MONTH)",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "859ed77a-a9f4-47cf-8d90-c0e605509945"
          },
          {
            "name": "Commission Strikes",
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "",
              "VAR new_commission_strikes_jan = ",
              "    IF([Margin Vs Margin Goal Variance]>=0,0,1)",
              "",
              "VAR new_commission_strikes_feb = ",
              "    IF([Margin Vs Margin Goal Variance]>=0,BLANK(),",
              "    IF([Margin Vs Margin Goal 1MA]>=0,1,2)",
              "    )",
              "",
              "VAR new_commission_strikes = ",
              "    IF([Margin Vs Margin Goal Variance]>=0,BLANK(),",
              "    IF([Margin Vs Margin Goal 1MA]>=0,1,",
              "    IF([Margin Vs Margin Goal 2MA]>=0,2,",
              "    3",
              "    )))",
              "",
              "VAR ifs = ",
              "    IF(MAX('Calendar'[Date]) < 45658, BLANK(),",
              "    IF(MIN('Calendar'[Date]) >= 45689 && MAX('Calendar'[Date]) <= 45716, new_commission_strikes_feb,",
              "    IF(MIN('Calendar'[Date]) >= 45658 && MAX('Calendar'[Date]) <= 45688, new_commission_strikes_jan,",
              "    new_commission_strikes)",
              "    )",
              ")",
              "",
              "RETURN",
              "ifs"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9dd2a6a1-196e-440d-98f0-051f14a34a0d"
          },
          {
            "name": "Commission Deductions",
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "[Commission Rate]-[Standard Commission Rate]"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "lineageTag": "682e22f9-9fba-446e-a8af-6f98fd661e0c"
          },
          {
            "name": "Strike One Commissions",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "IF([Margin]>=200000,42676+(([Margin]-199999)*.29),",
              "    IF([Margin]>=150000,29426+(([Margin]-149999)*.265),",
              "    IF([Margin]>=100000,17426+(([Margin]-99999)*.24),",
              "    IF([Margin]>=50000,6676+(([Margin]-49999)*.215),",
              "    IF([Margin]>=20000,1725+(([Margin]-19999)*.165),",
              "    IF([Margin]>=15000,1025+(([Margin]-14999)*.14),",
              "    IF([Margin]>=10000,450+(([Margin]-9999)*.115),",
              "    IF([Margin]>=5000,(([Margin]-4999)*.0),BLANK()",
              "))))))))"
            ],
            "isHidden": true,
            "lineageTag": "3a6d5e4e-dee1-482e-ae8a-c2f5f1e2d3ea"
          },
          {
            "name": "Strike Two Commissions",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "IF([Margin]>=200000,41701+(([Margin]-199999)*.285),",
              "    IF([Margin]>=150000,28701+(([Margin]-149999)*.26),",
              "    IF([Margin]>=100000,16951+(([Margin]-99999)*.235),",
              "    IF([Margin]>=50000,6450+(([Margin]-49999)*.21),",
              "    IF([Margin]>=20000,1650+(([Margin]-19999)*.16),",
              "    IF([Margin]>=15000,975+(([Margin]-14999)*.135),",
              "    IF([Margin]>=10000,425+(([Margin]-9999)*.11),",
              "    IF([Margin]>=5000,(([Margin]-4999)*.085),BLANK()",
              "))))))))"
            ],
            "isHidden": true,
            "lineageTag": "44a287f0-0edd-4fd5-9f43-6b7afba79847"
          },
          {
            "name": "Strike Three Commissions",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "    IF([Margin]>=200000,40726+(([Margin]-199999)*.28),",
              "    IF([Margin]>=150000,27976+(([Margin]-149999)*.255),",
              "    IF([Margin]>=100000,16476+(([Margin]-99999)*.23),",
              "    IF([Margin]>=50000,6225+(([Margin]-49999)*.205),",
              "    IF([Margin]>=20000,1575+(([Margin]-19999)*.155),",
              "    IF([Margin]>=15000,925+(([Margin]-14999)*.13),",
              "    IF([Margin]>=10000,400+(([Margin]-9999)*.0105),",
              "    IF([Margin]>=5000,(([Margin]-4999)*.08),BLANK()",
              "))))))))"
            ],
            "isHidden": true,
            "lineageTag": "cabdbae3-add5-48f2-8a1d-09951fbaa9da"
          },
          {
            "name": "Standard Commission Rate",
            "displayFolder": "Comission Measures",
            "expression": [
              "",
              "    IF([Margin]>=200000,44626+(([Margin]-199999)*.3),",
              "    IF([Margin]>=150000,30876+(([Margin]-149999)*.275),",
              "    IF([Margin]>=100000,18376+(([Margin]-99999)*.25),",
              "    IF([Margin]>=50000,7126+(([Margin]-49999)*.225),",
              "    IF([Margin]>=20000,1875+(([Margin]-19999)*.175),",
              "    IF([Margin]>=15000,1125+(([Margin]-14999)*.15),",
              "    IF([Margin]>=10000,500+(([Margin]-9999)*.125),",
              "    IF([Margin]>=5000,(([Margin]-4999)*.1),BLANK()",
              "    ))))))))"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "isHidden": true,
            "lineageTag": "a456ebca-df22-469c-8fc2-7f49c5e4cbb3"
          },
          {
            "name": "10% Commission",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Comission Measures",
            "expression": "[Margin]*.1",
            "isHidden": true,
            "lineageTag": "a841ab9d-e69e-4100-82e5-e7cdf98e2bc9"
          },
          {
            "name": "Margin MTD Goal",
            "displayFolder": "Sales Measures\\Sales Goals",
            "expression": [
              "",
              "VAR workingdays =",
              "    NETWORKDAYS(",
              "        STARTOFMONTH('Calendar'[Date]),",
              "        ENDOFMONTH('Calendar'[Date]),",
              "        1,",
              "        observed_holidays",
              "    )",
              "",
              "VAR months_margin_goal = CALCULATE([Margin Goal],REMOVEFILTERS('Calendar'[Date]))",
              "VAR override_mpdg = CALCULATE([Override margin goal],REMOVEFILTERS('Calendar'[Date]))",
              "VAR mpd = DIVIDE(months_margin_goal, workingdays)",
              "Var mpdg_wolf_pack = ",
              "    SWITCH(TRUE(),SELECTEDVALUE(wolf_pack[wolf_pack])=BLANK(),override_mpdg*[Working days Elapsed],mpd*[Working days Elapsed])",
              "",
              "Var mpdg = SWITCH(TRUE(),SELECTEDVALUE(salesperson_key[Name])=BLANK(),mpdg_wolf_pack,mpd*[Working days Elapsed])",
              "",
              "RETURN",
              "mpdg"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "797239d8-1e2c-4255-952b-497e5063d0fb"
          },
          {
            "name": "Count of SOPP and SOPD",
            "displayFolder": "Operations Measures\\SOP",
            "expression": [
              "",
              "VAR count_sop = ",
              "CALCULATE(",
              "    [Count of SOPD Issues]+[Count of SOPP Issues],",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")",
              "",
              "VAR ifs = ",
              "IF(count_sop>=1,count_sop,0)",
              "",
              "RETURN",
              "ifs"
            ],
            "formatString": "0",
            "lineageTag": "336b0fed-4a4b-4f02-baf1-b8a6a12114d7"
          },
          {
            "name": "Count of DNC",
            "displayFolder": "Operations Measures\\DNC",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(movements[id]),",
              "    movements[dnc]=TRUE(),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d44ba655-752c-4034-a726-23641e6a4bea"
          },
          {
            "name": "DNC %",
            "displayFolder": "Operations Measures\\DNC",
            "expression": [
              "",
              "DIVIDE(",
              "    [Count of DNC],",
              "    [Count of Movements Booked]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "49a1de4f-0a01-4e1d-96fb-e678577e4301"
          },
          {
            "name": "Count of Movements Booked All Time",
            "displayFolder": "Movement Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT(movements[id]),",
              "    movements[status]<>\"A\"",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "43bbf707-aa19-44e8-b5f0-a73ff1c88905"
          },
          {
            "name": "Margin % MTD",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": "DIVIDE([Margin MTD],[Revenue MTD])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "54d01cc9-49a6-4ddf-b2ff-759ee0bbbbe8"
          },
          {
            "name": "Revenue MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Revenue Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    TOTALMTD([Total Revenue],'Calendar'[Date],'Calendar'[Day of Month]<DAY(TODAY())),",
              "    movements[status]<>\"A\",",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "33d49d6c-e03b-457d-bade-b34e38e7f3ac"
          },
          {
            "name": "Average Margin Per Day MTD",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": [
              "",
              "",
              "Var Margin_MTD = ",
              "CALCULATE(TOTALMTD([Margin],'calendar'[Date],",
              "    'calendar'[Day of Month]<DAY(TODAY())),",
              "    USERELATIONSHIP(orders[shipper_sched_early_date],'Calendar'[Date])",
              ")",
              "var Working_days_Elapsed = ",
              "CALCULATE(",
              "    If(DAY(TODAY())=1,0,",
              "    NETWORKDAYS(",
              "        MIN('Calendar'[Date]),",
              "        TODAY()-1,",
              "        1,",
              "        observed_holidays))",
              ")",
              "var avg_ = ",
              "CALCULATE(",
              "    DIVIDE(Margin_MTD, Working_days_Elapsed),",
              "    movements[Status] <> \"A\",",
              "    FILTER(",
              "       'Calendar',",
              "        YEAR('Calendar'[Date]) = YEAR(TODAY()) && MONTH('Calendar'[Date]) = MONTH(TODAY()) && Day('Calendar'[Date]) = Day(TODAY())",
              "   )",
              ")",
              "",
              "RETURN",
              "avg_"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "6b676cc6-e76d-4c5f-a3b1-4db3e89ba430"
          },
          {
            "name": "Average Margin per day MTD vs margin today goal",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": "[Average Margin Per Day MTD] - [Margin per day Goal]",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "19e5489a-2cae-46aa-8cb7-8e35b9f04d61"
          },
          {
            "name": "Forcasted Margin this month",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": "[Margin MTD]+([Average Margin Per Day MTD]*[Working Days Left])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "792fec62-f76b-4e35-983c-4574ea0617c3"
          },
          {
            "name": "Working Days Left",
            "displayFolder": "Calendar Measures",
            "expression": "[Working Days]-[Working days Elapsed]",
            "formatString": "0",
            "lineageTag": "b6e7fd4e-1fbc-489c-bad3-400fee14bcc1"
          },
          {
            "name": "Margin Per Order MTD",
            "displayFolder": "Sales Measures\\Margin\\To Date Measures\\Month To Date",
            "expression": "DIVIDE([Margin MTD], [Count of Orders Covered MTD])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "a56f26f4-ca3a-4715-8b87-275e4ff9d407"
          },
          {
            "name": "Is Working Day",
            "displayFolder": "Calendar Measures",
            "expression": [
              "",
              "Var is_working_day = IF([Working Days]=1,1,0)",
              " ",
              "Return",
              "is_working_day"
            ],
            "formatString": "0",
            "lineageTag": "5a7993dc-cd42-47e0-bc17-6c98a2f529e4"
          }
        ],
        "partitions": [
          {
            "name": "measures_",
            "mode": "import",
            "source": {
              "expression": "Row(\"Column\", BLANK())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "employees",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "595a83f4-be85-4628-930e-9705642f27be",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "319cc0a3-0162-40a8-b1d2-bcd25493776b",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "84ac5d0f-335d-42ba-8fcf-7b863236da2d",
            "sourceColumn": "Hire Date",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "ba39365c-82ec-407a-9eb9-89361d5c4c5e",
            "sourceColumn": "Termination Date",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27d247f-08ca-4751-a124-204ffc2f3c93",
            "sourceColumn": "Reporting to",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cfad7d5-e787-48ef-a301-68652a5a0c11",
            "sourceColumn": "Termination Type",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a2c042b-99f5-4586-836c-63599438893b",
            "sourceColumn": "Termination Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Regrettable or non- regrettable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d909b33d-1979-4c69-838e-94b9c648bc64",
            "sourceColumn": "Regrettable or non- regrettable",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c51d0d6d-9f77-4742-a0c6-2e2c92baae4b",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod User Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "968822be-0c75-4e31-b879-be73a12a3838",
            "sourceColumn": "McLeod User Code",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod Salesperson Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce9790e5-0c2b-48da-9045-15f6d6db0568",
            "sourceColumn": "McLeod Salesperson Code",
            "summarizeBy": "none"
          },
          {
            "name": "Work Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "800c7104-8411-4729-b462-89a6fdd48e07",
            "sourceColumn": "Work Email",
            "summarizeBy": "none"
          },
          {
            "name": "Devision",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14f71c30-2c67-440e-ae0d-88f41617a8f2",
            "sourceColumn": "Devision",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98f6287c-d0d0-468a-ae10-d8249190eafc",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "users.revenue_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dabc049a-562c-4e2c-be44-78e318143a31",
            "sourceColumn": "users.revenue_code_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0af26c3a-e69f-4de1-a4d5-3c1431c72fc3",
        "partitions": [
          {
            "name": "employees",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Bamboo/Employees.xlsx\"), null, true),",
                "    employees_Table = Source{[Item=\"employees\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(employees_Table,{{\"ID\", Int64.Type}, {\"Name\", type text}, {\"Prefered Name\", type text}, {\"Hire Date\", type date}, {\"Termination Date\", type any}, {\"Reporting to\", type text}, {\"Termination Type\", type text}, {\"Termination Reason\", type text}, {\"Regrettable or non- regrettable\", type text}, {\"Job Title\", type text}, {\"McLeod User Code\", type text}, {\"McLeod Salesperson Code\", type text}, {\"Work Email\", type text}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"Name\", Splitter.SplitTextByDelimiter(\",\", QuoteStyle.Csv), {\"Name.1\", \"Name.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Name.1\", type text}, {\"Name.2\", type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type1\",{{\"Name.2\", Text.Trim, type text}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Trimmed Text\", \"First Name\", each if [Prefered Name] = null then [Name.2] else [Prefered Name]),",
                "    #\"Merged Columns\" = Table.CombineColumns(#\"Added Conditional Column\",{\"First Name\", \"Name.1\"},Combiner.CombineTextByDelimiter(\" \", QuoteStyle.None),\"Name\"),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Merged Columns\",{\"Name.2\", \"Prefered Name\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"0000-00-00\",\"\",Replacer.ReplaceValue,{\"Termination Date\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Termination Date\", type date}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type2\",\"Development Team Sales\",\"Development Team\",Replacer.ReplaceText,{\"Devision\"}),",
                "    #\"Trimmed Text1\" = Table.TransformColumns(#\"Replaced Value1\",{{\"McLeod User Code\", Text.Trim, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text1\",{{\"McLeod User Code\", Text.Upper, type text}}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Uppercased Text\", {\"McLeod User Code\"}, users, {\"id\"}, \"users\", JoinKind.LeftOuter),",
                "    #\"Expanded users\" = Table.ExpandTableColumn(#\"Merged Queries\", \"users\", {\"revenue_code_id\"}, {\"users.revenue_code_id\"})",
                "in",
                "    #\"Expanded users\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "job_history",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Row ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f658e0f1-8ec7-4eb8-acf5-e2c794cd3f55",
            "sourceColumn": "Row ID",
            "summarizeBy": "none"
          },
          {
            "name": "Job Start Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ba069a4e-fc85-4e8c-bcfc-6375f5ddf34f",
            "sourceColumn": "Job Start Date",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c31a1fe-3fd7-4fa6-814f-178371f72d28",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97c171f1-aaab-4092-ab4b-65bd9f1b9d80",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc674c11-ac19-41a9-a1fa-cd422e8f3457",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e29e9659-fbf1-435b-bb34-02a3905fb30a",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "Reports To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d800929d-f0c5-45f8-9a12-e9842bc6b367",
            "sourceColumn": "Reports To",
            "summarizeBy": "none"
          },
          {
            "name": "Mcleod Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2d208af-b93d-4bef-bcfe-77d2728118a6",
            "sourceColumn": "Mcleod Code",
            "summarizeBy": "none"
          },
          {
            "name": "Work Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d74a9ac1-78d5-494c-a808-d9c5560a8580",
            "sourceColumn": "Work Email",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod Salesperson Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "324094b8-cf3d-4253-8aae-248ff783aaf7",
            "sourceColumn": "McLeod Salesperson Code",
            "summarizeBy": "none"
          },
          {
            "name": "Job End Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b89583cb-3bda-4fa9-aaf6-85ac70902499",
            "sourceColumn": "Job End Date",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0d8addef-5917-4ed8-92a6-3a017ca615e0",
        "partitions": [
          {
            "name": "job_history",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Bamboo/Job%20History.xlsx\"), null, true),",
                "    job_history_Table = Source{[Item=\"job_history\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(job_history_Table,{{\"Row ID\", type text}, {\"Name\", type text}, {\"Prefered Name\", type text}, {\"Job Start Date\", type date}, {\"ID\", Int64.Type}, {\"Division\", type text}, {\"Department\", type text}, {\"Job Title\", type text}, {\"Reports To\", type text}, {\"Mcleod Code\", type text}, {\"Work Email\", type text}, {\"McLeod Salesperson Code\", type text}, {\"End Date\", type date}, {\"TerminationDate\", type any}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type\", \"Job End Date\", each if [End Date] = null then [TerminationDate] else [End Date]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"End Date\", \"TerminationDate\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"0000-00-00\",\"\",Replacer.ReplaceValue,{\"Job End Date\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Replaced Value\",{\"Name\", \"Prefered Name\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"Job End Date\", type date}}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type1\",\"Development Team Sales\",\"Development Team\",Replacer.ReplaceText,{\"Division\"})",
                "in",
                "    #\"Replaced Value1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "salesperson_key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9604a2b2-aa41-4174-b3da-154975a1be4a",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98419ef0-1280-485f-a37b-86cce530e3dd",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e30b5f3b-2efd-4427-bf8f-0ad6da3d97e6",
            "sourceColumn": "Hire Date",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9fb98dc-f51e-4be0-afe7-2e4ae29dd4fe",
            "sourceColumn": "Termination Date",
            "summarizeBy": "none"
          },
          {
            "name": "Reporting to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf9be6b8-0cae-483b-9c08-fe8d9c90ced8",
            "sourceColumn": "Reporting to",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ca1f297-005f-4438-a607-77aed72456e0",
            "sourceColumn": "Termination Type",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e132bfff-7656-4049-9f03-189e7f9aaeed",
            "sourceColumn": "Termination Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Regrettable or non- regrettable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cda6b0af-31a6-4209-92ed-03e3180dfa32",
            "sourceColumn": "Regrettable or non- regrettable",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27e0e1bd-38f0-46e3-b253-17db0af75503",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod User Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc442f1d-9ccf-4dca-b83f-b282a82c03f7",
            "sourceColumn": "McLeod User Code",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod Salesperson Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53a4c289-8979-4760-8edb-e8bea9870eda",
            "sourceColumn": "McLeod Salesperson Code",
            "summarizeBy": "none"
          },
          {
            "name": "Work Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e1cabe6-f81b-4f46-8a9f-3a277c5b8f28",
            "sourceColumn": "Work Email",
            "summarizeBy": "none"
          },
          {
            "name": "Devision",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f54f8a60-a70f-409e-bc33-6b53d881d415",
            "sourceColumn": "Devision",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8eb0d92-3391-4e01-8dc2-51c7b5075c4e",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "users.revenue_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e601ddc-2e98-43d2-b236-7af85d2515c8",
            "sourceColumn": "users.revenue_code_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6d941d5-ebfa-4572-8487-a51694d36762",
        "partitions": [
          {
            "name": "salesperson_key",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = employees,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([McLeod Salesperson Code] <> null)),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Filtered Rows\",{{\"Name\", Text.Trim, type text}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Trimmed Text\",{{\"Name\", Text.Upper, type text}, {\"Reporting to\", Text.Upper, type text}})",
                "in",
                "    #\"Uppercased Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "callins",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "entered_by",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7192a89e-e73f-449d-be09-d34f7e396979",
            "sourceColumn": "entered_by",
            "summarizeBy": "none"
          },
          {
            "name": "entered_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "64ebbfeb-8149-4837-8189-06880901d32f",
            "sourceColumn": "entered_date",
            "summarizeBy": "none"
          },
          {
            "name": "movement_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2c52169-1c2f-44ab-80c7-c248371922a7",
            "sourceColumn": "movement_status",
            "summarizeBy": "none"
          },
          {
            "name": "payee_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b2c3a56-f074-450c-bca7-405ef3c5b9e4",
            "sourceColumn": "payee_id",
            "summarizeBy": "none"
          },
          {
            "name": "initiated_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7212ceae-b271-428e-8741-f7aa7630c2ea",
            "sourceColumn": "initiated_type",
            "summarizeBy": "none"
          },
          {
            "name": "entered_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "defe8dc0-a917-400e-8017-5c5347c3fb4e",
            "sourceColumn": "entered_time",
            "summarizeBy": "none"
          },
          {
            "name": "movement_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ac4c678-3d1c-4c3b-945d-92cdff20c650",
            "sourceColumn": "movement_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c3b14ccd-e8ea-4e24-b354-916b8bbb278e",
        "partitions": [
          {
            "name": "callins",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_callin = Source{[Schema=\"dbo\",Item=\"callin\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_callin,{\"entered_by\", \"entered_date\", \"movement_status\", \"payee_id\", \"initiated_type\", \"movement_id\"}),",
                "    #\"Filtered callins on or after RefreshCutOffDate\" = Table.SelectRows(#\"Removed Other Columns\", each [entered_date] >= RefreshCutOffDate),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Filtered callins on or after RefreshCutOffDate\", \"Time\", each DateTime.Time([entered_date]), type time),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Time\",{{\"Time\", \"entered_time\"}}),",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Renamed Columns\",{{\"entered_date\", DateTime.Date, type date}}),",
                "    #\"Calculated Start of Hour\" = Table.TransformColumns(#\"Extracted Date\",{{\"entered_time\", Time.StartOfHour, type time}}),",
                "    #\"Appended Query\" = Table.Combine({#\"Calculated Start of Hour\", historic_callins})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "overdue_check_calls",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Movement ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8a76a86-b7c3-405d-a7c0-ba36581d1822",
            "sourceColumn": "Movement ID",
            "summarizeBy": "none"
          },
          {
            "name": "Check Call Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b235ee04-a990-4b30-b4f0-ac50f2fc5e88",
            "sourceColumn": "Check Call Date",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc81b937-6f9b-44a3-87ea-88357ca05a7c",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Check Call Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "7cef9885-de41-431f-b40a-92deb33f1b09",
            "sourceColumn": "Check Call Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "73748e9d-e1aa-4e29-8ff2-44f74b188960",
        "partitions": [
          {
            "name": "overdue_check_calls",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Overdue%20Check%20Call/Overdue%20Check%20Calls.xlsx\"), null, true),",
                "    overdue_check_calls_Table = Source{[Item=\"overdue_check_calls\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(overdue_check_calls_Table,{{\"Movement ID\", type text}, {\"Check Call Time\", type datetime}, {\"Status\", type any}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type\", {\"Check Call Time\"}),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Removed Errors\", \"Time\", each DateTime.Time([Check Call Time]), type time),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Inserted Time\",{{\"Check Call Time\", \"Check Call Date\"}, {\"Time\", \"Check Call Time\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Check Call Date\", type date}}),",
                "    #\"Calculated Start of Hour\" = Table.TransformColumns(#\"Changed Type1\",{{\"Check Call Time\", Time.StartOfHour, type time}})",
                "in",
                "    #\"Calculated Start of Hour\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "crt_movement_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "302a13db-06dd-44df-86a6-9a96c85c718f",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Movement ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85129e74-b8c2-4c2f-bce4-a6d3bfee11be",
            "sourceColumn": "Movement ID",
            "summarizeBy": "none"
          },
          {
            "name": "Avail #",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "10f4beb7-2b3c-4a06-88d1-37251f54cd51",
            "sourceColumn": "Avail #",
            "summarizeBy": "sum"
          },
          {
            "name": "Avail Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "301703ca-8c68-454b-8202-359163ccf9a1",
            "sourceColumn": "Avail Time",
            "summarizeBy": "none"
          },
          {
            "name": "Load Board Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a6df69f5-a636-4592-bd72-e044a5751a56",
            "sourceColumn": "Load Board Time",
            "summarizeBy": "none"
          },
          {
            "name": "Give Back Time ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "390d3c5d-08fd-4d22-86da-7f46b2a6cc76",
            "sourceColumn": "Give Back Time ",
            "summarizeBy": "none"
          },
          {
            "name": "Covered Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f4b628c0-340d-41fb-a31b-db09e341b6dd",
            "sourceColumn": "Covered Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start Max Pay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "efaac8cf-8490-4fe3-8285-6e78a92ef98d",
            "sourceColumn": "Start Max Pay",
            "summarizeBy": "sum"
          },
          {
            "name": "End Max Pay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5eb6d0d2-7a0c-4c00-8e7c-e055402777dc",
            "sourceColumn": "End Max Pay",
            "summarizeBy": "sum"
          },
          {
            "name": "Carrier Offers before LB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "322e5003-98d4-4bf5-b3d2-e192d181cefe",
            "sourceColumn": "Carrier Offers before LB",
            "summarizeBy": "sum"
          },
          {
            "name": "Carrier Offers",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e09ecfbc-8083-4e42-aee3-b6571eb6ac85",
            "sourceColumn": "Carrier Offers",
            "summarizeBy": "sum"
          },
          {
            "name": "Ship date at Avail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "94100550-fe9c-4957-a3a6-8a5ac841f0d6",
            "sourceColumn": "Ship date at Avail",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_67948750-4a55-4170-865e-d76c6427f063"
                },
                "isDefault": true,
                "relationship": "1b268b65-e261-470c-8a0d-ca966e3223f0"
              }
            ]
          },
          {
            "name": "Hand over",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1c7d0730-ceb7-4ff6-b56a-ccedbfdce394",
            "sourceColumn": "Hand over",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5d529210-5800-429f-b2e3-388a81d360f9"
                },
                "isDefault": true,
                "relationship": "c068525c-5985-47a0-a2fb-8f38a5e05167"
              }
            ]
          }
        ],
        "lineageTag": "6fb9b42f-de18-477c-8b98-344a1312204f",
        "partitions": [
          {
            "name": "crt_movement_data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Carrier_Dispatch_Movement_data_New/Carrier_Dispatch_Movement_data_New.xlsx\"), null, true),",
                "    CRT_DATA_Table = Source{[Item=\"CRT_DATA\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(CRT_DATA_Table,{{\"Order ID\", type text}, {\"Movement ID\", type text}, {\"Avail #\", Int64.Type}, {\"Avail Time\", type datetime}, {\"Load Board Time\", type datetime}, {\"Give Back Time \", type datetime}, {\"Covered Time\", type datetime}, {\"Start Max Pay\", type number}, {\"End Max Pay\", Int64.Type}, {\"Carrier Offers before LB\", Int64.Type}, {\"Carrier Offers\", Int64.Type}, {\"Unique ID\", type text}}),",
                "    #\"Added Prefix\" = Table.TransformColumns(#\"Changed Type\", {{\"Order ID\", each \"0\" & _, type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Prefix\",{\"Unique ID\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "lane",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "lane",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edbd3dbd-dfe5-4437-b9b0-041387b7fe49",
            "sourceColumn": "lane",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7bc0b0c0-f527-406e-9f68-57b6dddde0c5",
        "partitions": [
          {
            "name": "lane",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = orders,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"lane\"}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Removed Other Columns\",{{\"lane\", Text.Upper, type text}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Uppercased Text\",{{\"lane\", Text.Trim, type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Trimmed Text\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "margin_load_count_goals",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Salesperson Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "980dc038-a26d-4d78-84a9-ac722f14846a",
            "sourceColumn": "Salesperson Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bc068d44-af09-4ceb-9ec8-47e9316bd4fe",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Margin Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "61fc996b-901b-4f4b-96b6-5ca0ccad3f84",
            "sourceColumn": "Margin Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Load Count Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cdb9c0ee-a3a7-4d49-b8da-718ebe85070f",
            "sourceColumn": "Load Count Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin Per Order Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "cbe6a68d-f97d-4b7b-851b-751c2543a3c6",
            "sourceColumn": "Margin Per Order Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin % Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "61f4b55e-9a63-4aba-991f-d4ce778c4008",
            "sourceColumn": "Margin % Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24064e78-7ddc-45f3-84da-9bec1f1186de",
            "sourceColumn": "Column7",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9b67fda5-3b12-423b-9032-0dd4db6d6344",
        "partitions": [
          {
            "name": "margin_load_count_goals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx\"), null, true),",
                "    MarginLoadCountGoals_Sheet = Source{[Item=\"MarginLoadCountGoals\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(MarginLoadCountGoals_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Salesperson Name\", type text}, {\"Month\", type date}, {\"Margin Goal\", Int64.Type}, {\"Load Count Goal\", Int64.Type}}),",
                "    #\"Uppercased Text\" = Table.TransformColumns(#\"Changed Type\",{{\"Salesperson Name\", Text.Upper, type text}}),",
                "    #\"Uppercased Text1\" = Table.TransformColumns(#\"Uppercased Text\",{{\"Salesperson Name\", Text.Upper, type text}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Uppercased Text1\",{{\"Margin Goal\", Currency.Type}, {\"Margin Per Order Goal\", Currency.Type}, {\"Margin % Goal\", Percentage.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "daily_number_override",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ae92692c-fd61-4987-b864-f285dc43a9fb",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Margin Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aab2f59d-8899-4b88-a6b7-6b0c555a2ca8",
            "sourceColumn": "Margin Number",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "45fdfe2a-47d4-4b73-9ae1-78f6485bc2ab",
        "partitions": [
          {
            "name": "daily_number_override",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx\"), null, true),",
                "    daily_number_override_Table = Source{[Item=\"daily_number_override\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(daily_number_override_Table,{{\"Month\", type date}, {\"Margin Number\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "rev_codes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "rev_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2230ad6f-cfb5-49a1-bf18-467e042069f9",
            "sourceColumn": "rev_code_id",
            "summarizeBy": "none"
          },
          {
            "name": "account_rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0ff67e-b1df-4476-bec0-edbcf640fc55",
            "sourceColumn": "account_rep",
            "summarizeBy": "none"
          },
          {
            "name": "wolf_pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ad6eb3c-3623-4b2f-8b63-c360fa9b8131",
            "sourceColumn": "wolf_pack",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3cdc5a80-c6b4-41b3-9dbd-2c2e43274b14",
        "partitions": [
          {
            "name": "rev_codes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Teams.xlsx\"), null, true),",
                "    rev_codes_Table = Source{[Item=\"rev_codes\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(rev_codes_Table,{{\"rev_code_id\", Int64.Type}, {\"account_rep\", type text}, {\"wolf_pack\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "wolf_pack",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "wolf_pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb69e4f1-04ac-459e-ac9c-696190c30644",
            "sourceColumn": "wolf_pack",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "958b89fd-1535-4e40-a583-7db4a312b458",
        "partitions": [
          {
            "name": "wolf_pack",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = rev_codes,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"wolf_pack\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Removed Blank Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "account_rep",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "account_rep",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9691f65a-55a2-4762-8be3-441afd733b41",
            "sourceColumn": "account_rep",
            "summarizeBy": "none"
          },
          {
            "name": "wolf_pack",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f458540d-a20b-4d85-9993-336ee3af8c7b",
            "sourceColumn": "wolf_pack",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "642ea876-02df-49cf-bf2d-b661b2941b01",
        "partitions": [
          {
            "name": "account_rep",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = rev_codes,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"account_rep\", \"wolf_pack\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Duplicates\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Removed Blank Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "observed_holidays",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Observed Holidays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "59f7896e-f5c5-4828-a3f3-44e63bbaa70b",
            "sourceColumn": "Observed Holidays",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ed26f4c3-9c62-405b-8c3b-c81747750938"
                },
                "isDefault": true,
                "relationship": "328ffb62-6ce8-4861-9f4b-2ef8226436f6"
              }
            ]
          }
        ],
        "lineageTag": "f7c87e41-1186-4900-8b88-98adeba2d71b",
        "partitions": [
          {
            "name": "observed_holidays",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Observed%20Holidays.xlsx\"), null, true),",
                "    observed_holidays_Table = Source{[Item=\"observed_holidays\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(observed_holidays_Table,{{\"Observed Holidays\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ed26f4c3-9c62-405b-8c3b-c81747750938",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b801229d-8bf5-41b2-81ce-6389edd2638c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "64243f1f-9ca4-495a-b6bc-c7531c18e66a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "3c1df502-ec6d-4fc3-91c0-5e59c018d367",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e70d443b-0863-4f06-a4ec-606198fae5e9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "678fe09c-6708-46ba-aeb7-c0182b400aa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9416b4ed-473d-4950-9e6b-9cd5ea2208f6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bf290d54-776e-447f-bbf9-69df7f32f138",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fabb8a8e-6582-4197-8990-9b32c2024ef8",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9b5153fc-8759-49c6-a9fd-245f554e21b3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f2e37966-3066-4c1d-844d-bb696a305b65",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3c0bb456-e74e-4c18-9130-1b3b8854d4b6",
                "ordinal": 3
              }
            ],
            "lineageTag": "8ff32bf8-9a37-4b07-a0aa-b968b04577be"
          }
        ],
        "isHidden": true,
        "lineageTag": "b1bbf5e8-2393-4217-ad8e-0b656b17560f",
        "partitions": [
          {
            "name": "LocalDateTable_ed26f4c3-9c62-405b-8c3b-c81747750938",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('observed_holidays'[Observed Holidays])), 1, 1), Date(Year(MAX('observed_holidays'[Observed Holidays])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "behaviors",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49fef3ee-bae6-4c16-9849-9133c9425716",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "Behavior Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3b713923-edab-47f4-a7a9-3e18797873b7",
            "sourceColumn": "Behavior Date",
            "summarizeBy": "none"
          },
          {
            "name": "author_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0e02d84-d40c-40f7-8f6c-66b132f18faf",
            "sourceColumn": "author_id",
            "summarizeBy": "none"
          },
          {
            "name": "mail_activity_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a61e477d-f216-40de-9b84-ec97d394ae48",
            "sourceColumn": "mail_activity_type_id",
            "summarizeBy": "none"
          },
          {
            "name": "model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c210c876-5e78-4a7a-aeac-29d4091dd37f",
            "sourceColumn": "model",
            "summarizeBy": "none"
          },
          {
            "name": "res_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb66fbc3-3b19-4494-86f5-efcfefdfc4ff",
            "sourceColumn": "res_id",
            "summarizeBy": "none"
          },
          {
            "name": "Behavior Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "c0ed21ad-ce4e-4070-b405-204aff66961a",
            "sourceColumn": "Behavior Time",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "15107117-0e45-4d66-8667-9adc52a0af8e",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0efa026f-8530-438d-a169-afe186397b78",
        "partitions": [
          {
            "name": "behaviors",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam\", [ApiVersion = 15]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each Text.Contains([Folder Path], \"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/02 BL-Areas/bridge_iq/Data Sets/behaviors_api_files/\")),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (3)\", each #\"Transform File (3)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (3)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (3)\", Table.ColumnNames(#\"Transform File (3)\"(#\"Sample File (3)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"id\", Int64.Type}, {\"date\", type datetime}, {\"author_id\", type any}, {\"mail_activity_type_id\", type text}, {\"model\", type text}, {\"res_id\", Int64.Type}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"Source.Name\"}),",
                "    #\"Extracted Text Between Delimiters\" = Table.TransformColumns(#\"Removed Columns\", {{\"author_id\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}, {\"mail_activity_type_id\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}}),",
                "    #\"Replaced Errors\" = Table.ReplaceErrorValues(#\"Extracted Text Between Delimiters\", {{\"author_id\", null}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Replaced Errors\", each ([model] <> \"gamification.badge.user\") and ([author_id] <> null and [author_id] <> \"OdooBot\" and [author_id] <> \"Portal User Template\")),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Filtered Rows2\", \"Time\", each DateTime.Time([date]), type time),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Inserted Time\",{{\"date\", \"Behavior Date\"}, {\"Time\", \"Behavior Time\"}}),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Renamed Columns2\", each [Behavior Date] >= RefreshCutOffDate),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows3\",{{\"Behavior Date\", type date}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Changed Type1\", \"Start of Month\", each Date.StartOfMonth([Behavior Date]), type date),",
                "    #\"Appended Query\" = Table.Combine({#\"Inserted Start of Month\", historic_behaviors})",
                "in",
                "    #\"Appended Query\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "behavior_key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "mail_activity_type_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75d3cd52-6b82-47c4-92d5-114a22a623c5",
            "sourceColumn": "mail_activity_type_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aafa2cf9-54f9-4dbf-a436-c8f4b18b186a",
        "partitions": [
          {
            "name": "behavior_key",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = behaviors,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"mail_activity_type_id\"}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Other Columns\", {\"mail_activity_type_id\"}),",
                "    #\"Removed Blank Rows\" = Table.SelectRows(#\"Removed Errors\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Blank Rows\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "behavior_goals",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Salesperson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377c5a59-68c1-4636-9bb7-364eb7813682",
            "sourceColumn": "Salesperson",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "84b63e0d-c663-43a9-a083-ce3bdaa8e293",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "BehaviorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05cb2d2a-c55f-4215-b3dd-1d94a77514f1",
            "sourceColumn": "BehaviorID",
            "summarizeBy": "none"
          },
          {
            "name": "Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85edcf64-c9f4-4525-bfcd-d12d4e3d0759",
            "sourceColumn": "Goal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e52fd5f3-a7fc-49f9-9be5-ddf09795ef92",
        "partitions": [
          {
            "name": "behavior_goals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx\"), null, true),",
                "    BehaviorGoals_Sheet = Source{[Item=\"BehaviorGoals\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(BehaviorGoals_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Salesperson\", type text}, {\"Month\", type date}, {\"Behavior\", type text}, {\"Goal\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Behavior\", \"BehaviorID\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each true)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "customer_margin_goal",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef2e0f62-e615-4966-8a62-0cbd8478e489",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a6ad13e-aaaf-4d66-8838-743810a398aa",
            "sourceColumn": "Customer Code",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f043f0b3-d6ca-4dbb-9756-c54f431901b0",
            "sourceColumn": "Salesperson",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8b660e38-c8fa-4f86-9975-277f1d79ce7d",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Margin Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2657af3-1095-4fab-bfed-372cf2d5dd3e",
            "sourceColumn": "Margin Goal",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin % Goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "589c88d0-8df7-445a-801b-1f2305d072e8",
            "sourceColumn": "Margin % Goal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0f9a6602-f51b-4faf-8f34-4c900a783ae6",
        "partitions": [
          {
            "name": "customer_margin_goal",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx\"), null, true),",
                "    customer_margin_goal_Table = Source{[Item=\"customer_margin_goal\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(customer_margin_goal_Table,{{\"Customer\", type text}, {\"Salesperson\", type text}, {\"Month\", type date}, {\"Margin Goal\", Int64.Type}, {\"Margin % Goal\", type number}}),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(#\"Changed Type\", \"Customer\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"Customer.1\", \"Customer.2\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"Customer.1\", type text}, {\"Customer.2\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"Customer.1\", \"Customer Name\"}, {\"Customer.2\", \"Customer Code\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "crm_stages",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "630a3f49-43f5-4b8c-96eb-8434269c285d",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          },
          {
            "name": "Stage Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "12c05801-f4f2-4d91-895b-f6426805c0f6",
            "sortByColumn": "Order",
            "sourceColumn": "Stage Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3fe647cf-f0e9-4ca1-931e-2f3de372b7cb",
        "partitions": [
          {
            "name": "crm_stages",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"Lc89D4IwEIDhv3LpjIkVP0clIQ4EdTAOhKHSio3Ya/oR/r5nYXyfS3u5pmGcZexilYGrQ29VFzxrs4atiCsc4SxMr00PpYs6pElOkwe6D2nqNXWNUKKDGsdEG6KTkFDOT7bUdxMwdm/xHNS0YUd4i2LQL61kkn0SDHMeKAunpA5wtDYRX5LxRQ4VCjl9w/8HFNEH/CrH2vYH\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, #\"Stage Name\" = _t])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "healthy_pipeline_goals",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Saleperson Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc79a5be-df43-4aa1-b9e0-96180bf1b1f9",
            "sourceColumn": "Saleperson Name",
            "summarizeBy": "none"
          },
          {
            "name": "Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b188823-885a-4dc1-aea2-6f91d83edd20",
            "sourceColumn": "Stage",
            "summarizeBy": "none"
          },
          {
            "name": "Healthy #",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "45182cbb-d26f-4661-b1a2-25dea23ecdbb",
            "sourceColumn": "Healthy #",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "cb9522ca-5231-4a40-836b-34657a1cbc76",
        "partitions": [
          {
            "name": "healthy_pipeline_goals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx\"), null, true),",
                "    HealthyPipelineGoals_Table = Source{[Item=\"HealthyPipelineGoals\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(HealthyPipelineGoals_Table,{{\"Saleperson Name\", type text}, {\"Stage\", type text}, {\"Healthy #\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "sop_issues",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Movement ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdc81be9-2c92-4f75-aa28-3ca4d830ee81",
            "sourceColumn": "Movement ID",
            "summarizeBy": "none"
          },
          {
            "name": "SOP Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c35dc264-ef1a-421f-b0d4-2a9887911f83",
            "sourceColumn": "SOP Type",
            "summarizeBy": "none"
          },
          {
            "name": "Date_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b8774774-7d5b-434c-8c51-d46d7276051b",
            "sourceColumn": "Date_time",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "6f0ea4a2-a36b-42d9-9c54-11586b2a6a73",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "09e1a60e-cb2b-4eed-98f2-15161c3da2e7",
        "partitions": [
          {
            "name": "sop_issues",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/SOP%20Has%20Been%20Marked/SOP%20Has%20Been%20Marked.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Movement ID\", Int64.Type}, {\"SOP Type\", type text}, {\"Date_time\", type datetime}}),",
                "    #\"Inserted Time\" = Table.AddColumn(#\"Changed Type\", \"Time\", each DateTime.Time([Date_time]), type time),",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Inserted Time\",{{\"Date_time\", DateTime.Date, type date}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Extracted Date\",{{\"Movement ID\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dispatcher_key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac26ec4e-e6c1-437d-adc5-d422998c1f10",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10f13f45-4150-4246-967f-96e8b1fa128c",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Hire Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "84962da2-41aa-4525-a361-54bd2a131ce3",
            "sourceColumn": "Hire Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_602d0dc9-a979-4162-a15e-cf937935b0b7"
                },
                "isDefault": true,
                "relationship": "22881cbf-eb4e-4f66-afd5-a0ec21a1eb7c"
              }
            ]
          },
          {
            "name": "Termination Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "180a1027-c792-43b3-9b95-fa90c6902143",
            "sourceColumn": "Termination Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7e773c2c-a1bd-4f2f-b9f7-efdc6b4a7c73"
                },
                "isDefault": true,
                "relationship": "89783f8c-5a09-40cd-8fe0-005c7da2b54b"
              }
            ]
          },
          {
            "name": "Reporting to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a30925f9-3e25-4873-8f0b-58e8383c642e",
            "sourceColumn": "Reporting to",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "220b7152-7966-4db2-bd41-68075996bb94",
            "sourceColumn": "Termination Type",
            "summarizeBy": "none"
          },
          {
            "name": "Termination Reason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "569856d1-27ab-4cce-9a69-def1250793cf",
            "sourceColumn": "Termination Reason",
            "summarizeBy": "none"
          },
          {
            "name": "Regrettable or non- regrettable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6737f2b4-5098-44c5-8511-db0e9553b7aa",
            "sourceColumn": "Regrettable or non- regrettable",
            "summarizeBy": "none"
          },
          {
            "name": "Job Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7eb80008-0538-415c-aac2-d63ff007f32f",
            "sourceColumn": "Job Title",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod User Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efd2d279-ac7c-4627-a24a-543bc4588f9c",
            "sourceColumn": "McLeod User Code",
            "summarizeBy": "none"
          },
          {
            "name": "McLeod Salesperson Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2220481a-2f8e-4ab0-bbe9-89a5252ec393",
            "sourceColumn": "McLeod Salesperson Code",
            "summarizeBy": "none"
          },
          {
            "name": "Work Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18c42962-98d4-479b-ab57-70b042e79fcf",
            "sourceColumn": "Work Email",
            "summarizeBy": "none"
          },
          {
            "name": "Devision",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e68814c-8e5e-4214-a4e2-df8a47ea733c",
            "sourceColumn": "Devision",
            "summarizeBy": "none"
          },
          {
            "name": "Department",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec08ed91-bb2b-4bc3-ae18-151d36d68bac",
            "sourceColumn": "Department",
            "summarizeBy": "none"
          },
          {
            "name": "users.revenue_code_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "671118c3-d10c-474e-97e0-9e6cbabf1ef7",
            "sourceColumn": "users.revenue_code_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ff69ace9-66a1-4c1b-b797-0305f2b98a1b",
        "partitions": [
          {
            "name": "dispatcher_key",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = employees,",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([McLeod User Code] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_602d0dc9-a979-4162-a15e-cf937935b0b7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4269117b-04c1-4f7d-9bc2-f7bf523e29cb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "81d0a97b-8a77-4549-90f9-e82c18fd0160",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1379ea74-d3a4-40bb-8a26-f03ad56184db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "89fd3690-e1b3-4935-9ebb-a577952d2533",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d5428c39-5ec1-4222-818f-9d7cc553075c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e0d02321-09a4-4f12-b03a-e78ae7985f9d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "94b210af-2ec3-4164-bd73-93acabc2884d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "504d69f7-6bab-404f-b94b-73630a2fd015",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5011589d-1b63-42fe-9f16-440f178653e3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "528eeaa1-b2dd-472c-b7df-cced498189ff",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4b3d144e-2cf2-4df6-8a10-9e79076d52a3",
                "ordinal": 3
              }
            ],
            "lineageTag": "9954fc4d-ed1e-46c7-a689-baeb3cb0b4f6"
          }
        ],
        "isHidden": true,
        "lineageTag": "c6fc0886-51b6-44eb-82b2-f1b249b1ff90",
        "partitions": [
          {
            "name": "LocalDateTable_602d0dc9-a979-4162-a15e-cf937935b0b7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dispatcher_key'[Hire Date])), 1, 1), Date(Year(MAX('dispatcher_key'[Hire Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7e773c2c-a1bd-4f2f-b9f7-efdc6b4a7c73",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d5560378-4542-48a5-8e96-5eacd19b218a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ff39078e-a8ff-49e2-b8b3-e5c53b03f81f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "039bccc2-5256-49a2-93de-86cc8c603670",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d58e8824-f43d-462e-b36c-70cf86151ad3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "f93c4d1a-78e0-4eb0-92a3-fabe67094f40",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "928fe426-9745-484e-b686-baeaf986a480",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a8ef8cf9-0e22-4423-8676-90b7fce61928",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a9c37163-4e1a-460b-9806-857b4ccd492e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "86e54f3b-ef0a-419c-8fbe-df3aa963b69f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d14b7668-2b4b-4e4e-b286-868a4461e81f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "86848010-f4ba-4cd2-b0cd-355b79005983",
                "ordinal": 3
              }
            ],
            "lineageTag": "35c4a0be-501b-4a65-bdc8-fdc39ae446c2"
          }
        ],
        "isHidden": true,
        "lineageTag": "2a6c1a48-e74b-4a4d-b3de-32a280a07aa8",
        "partitions": [
          {
            "name": "LocalDateTable_7e773c2c-a1bd-4f2f-b9f7-efdc6b4a7c73",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dispatcher_key'[Termination Date])), 1, 1), Date(Year(MAX('dispatcher_key'[Termination Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "pay_schedule",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Pay Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7a9f4b34-0a96-4f3a-a625-b9e9dd3ebe6b",
            "sourceColumn": "Pay Period",
            "summarizeBy": "sum"
          },
          {
            "name": "Commission Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f0ad40fd-6cf3-477d-9b7a-879313f15dd9",
            "sourceColumn": "Commission Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5204cc32-7744-4162-bd7a-37c8843dcd5c"
                },
                "isDefault": true,
                "relationship": "14e715b2-e8b7-477d-bad8-c42bd7a42ed5"
              }
            ]
          },
          {
            "name": "Pay Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "02c6ebfb-de32-4185-9fd8-9123bfd4199e",
            "sourceColumn": "Pay Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_984f2224-97c9-4ff5-8864-d5ee44b7d514"
                },
                "isDefault": true,
                "relationship": "5e94ac41-9664-4dd5-8b2a-ee99b5b474b1"
              }
            ]
          }
        ],
        "lineageTag": "443d23cd-1878-4ce2-b1f0-cb97d81400f1",
        "partitions": [
          {
            "name": "pay_schedule",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Commission%20Payroll%20Schedule.xlsx\"), null, true),",
                "    BasePlusCommissionNewStructure_Table = Source{[Item=\"BasePlusCommissionNewStructure\",Kind=\"Table\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(BasePlusCommissionNewStructure_Table,{{\"Pay Period\", Int64.Type}, {\"Commission Month\", type text}, {\"Pay Date\", type date}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Commission Month\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5204cc32-7744-4162-bd7a-37c8843dcd5c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b5358e97-8f0d-4f6d-a4b8-0f390098dc4e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9d51355c-b6a6-4c95-a7b7-b9fce846c62c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "842f3abe-a4e4-494a-9e6b-6360278e4252",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "163ba412-5ee8-4fbf-845a-14379204b1f6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3886a1e4-4b10-4d76-ab7a-0e06ddc6deae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "126df904-5417-4d2d-b416-895ed198b09e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1c1c8a9d-3447-43a4-b846-48c8bc811017",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b6e5f747-03b6-4ab2-b701-9e44d659277e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "322be130-56c0-4dcf-b190-14560b1470b9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fedcbc80-8068-43c7-a102-3a2245ccb1cb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "99729849-0b7a-4269-ba3b-b623a7b2c7a8",
                "ordinal": 3
              }
            ],
            "lineageTag": "20efdcbb-0e5a-49de-92c4-aba52a5dcdda"
          }
        ],
        "isHidden": true,
        "lineageTag": "2b43412f-5054-4211-a5ec-e2502eaae78e",
        "partitions": [
          {
            "name": "LocalDateTable_5204cc32-7744-4162-bd7a-37c8843dcd5c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('pay_schedule'[Commission Month])), 1, 1), Date(Year(MAX('pay_schedule'[Commission Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_984f2224-97c9-4ff5-8864-d5ee44b7d514",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7c226f44-bc69-4fb8-9210-d52864e73b3c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cf41d087-6d35-43bc-ae69-9b4e51ef1f97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4c3a7d94-bbe2-48ee-90c6-3477dca82d6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "893c51dc-cc82-4bd9-9b4f-dc4204272390",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0afc22db-b017-45bb-b129-76856099a766",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6961ad4b-27bb-494e-a644-45f3a78d318a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "31a2615c-b367-44db-afa0-8ca612746393",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "19ae51ff-9def-41eb-b7ad-ee6116da58da",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b10900fb-5d61-42db-9ce8-8f127a05381f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9fb81a1d-6c2b-4c14-ac5c-fe4acadc3e84",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "310db59b-e1e8-4267-ba55-281efd662cec",
                "ordinal": 3
              }
            ],
            "lineageTag": "53863f3b-5c22-4f4f-833a-f9695d911316"
          }
        ],
        "isHidden": true,
        "lineageTag": "7eb778c3-d124-4690-94be-014fe8b29869",
        "partitions": [
          {
            "name": "LocalDateTable_984f2224-97c9-4ff5-8864-d5ee44b7d514",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('pay_schedule'[Pay Date])), 1, 1), Date(Year(MAX('pay_schedule'[Pay Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "crm",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "538af23a-32a1-4905-99cb-fc02a4076674",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "partner_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c342305-befa-40f6-8f24-f999e0275dbf",
            "sourceColumn": "partner_id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82c4faec-6742-4913-b04c-3b8a9c9ca07b",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_mcleod_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e853fd5d-61a3-46cf-a0ff-100623c90454",
            "sourceColumn": "x_studio_mcleod_code",
            "summarizeBy": "none"
          },
          {
            "name": "user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b79e549d-6e71-4b63-9b46-287f7f86a2df",
            "sourceColumn": "user_id",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_sdr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f83f9536-855b-4cd8-b961-3f53978a545a",
            "sourceColumn": "x_studio_sdr",
            "summarizeBy": "none"
          },
          {
            "name": "activity_date_deadline",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9808314c-62c6-4854-806a-3e1dc05d1af7",
            "sourceColumn": "activity_date_deadline",
            "summarizeBy": "none"
          },
          {
            "name": "date_open",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4a93491e-cf52-4268-a5d2-5832c4efb92e",
            "sourceColumn": "date_open",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_do_not_move",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b30e6499-7afa-4b61-80ee-1e4dd312a3a2",
            "sourceColumn": "x_studio_do_not_move",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_lead_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb198dbc-b49f-4fa7-9238-915c2378c69d",
            "sourceColumn": "x_studio_lead_type",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_originally_passed_to",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98dc6be6-04ba-40eb-b0fd-0da4989587e8",
            "sourceColumn": "x_studio_originally_passed_to",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_lead_passed_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cbdfb664-1786-40a6-aa3f-b54b99b0bf2d",
            "sourceColumn": "x_studio_lead_passed_date",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_enrichment_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "06037bb5-cf63-424d-bf8d-41073c8d8097",
            "sourceColumn": "x_studio_enrichment_date",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10787a78-8861-4a20-98d7-1493120ed95b",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_revenue_range",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "854c2afa-b3ee-4dc6-9b5e-fc9069be05f8",
            "sourceColumn": "x_studio_revenue_range",
            "summarizeBy": "none"
          },
          {
            "name": "x_studio_primary_industry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55d82ce9-ddc5-4ee7-8aaa-9e064b7037c7",
            "sourceColumn": "x_studio_primary_industry",
            "summarizeBy": "none"
          },
          {
            "name": "state_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89d32111-399b-444f-99a8-e09699ed8cd9",
            "sourceColumn": "state_id",
            "summarizeBy": "none"
          },
          {
            "name": "phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "478a1e20-c309-4962-9018-994051868f88",
            "sourceColumn": "phone",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bce60713-a850-4182-ba21-62448f7a8391",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "user_login",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ca675eb-4945-4ddd-a8c4-015f6ef59d98",
            "sourceColumn": "user_login",
            "summarizeBy": "none"
          },
          {
            "name": "Stage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e500af9f-59b8-47b6-a5fa-45330aa0027d",
            "sourceColumn": "Stage",
            "summarizeBy": "none"
          },
          {
            "name": "Last Stage Change",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4d454f42-a8ee-4cbb-aa6f-63ede13320d1",
            "sourceColumn": "Last Stage Change",
            "summarizeBy": "none"
          },
          {
            "name": "At Risk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "Var Working = ",
              "    IF([Days since Last Salesperson Update]<7,\"False\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Since Last Stage Update]>90,\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "Var NoForNow = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Since Last Stage Update]>90,\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since last Behaivor]>90,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "Var Qualified = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Since Last Stage Update]>60,\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "    ",
              "Var Quoted = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Since Last Stage Update]>60,\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "Var CreditApp = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Since Last Stage Update]>60,\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "Var OneToThree = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since Last Shipment]>120,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "Var Customer = ",
              "    IF([Days since Last Salesperson Update]<7,\"FALSE\",",
              "    IF(crm[activity_date_deadline]=BLANK(),\"TRUE\",",
              "    IF([Days Over Due]>14,\"TRUE\",",
              "    IF([Days since Last Shipment]>120,\"TRUE\",",
              "    IF([Days since last Behaivor]>60,\"TRUE\",",
              "    \"FALSE\")))))",
              "",
              "",
              "Var AtRisk =",
              "    IF(CRM[Stage]=\"Working\",Working,",
              "    IF(CRM[Stage]=\"No For Now\",NoForNow,",
              "    IF(CRM[Stage]=\"Qualified\",Qualified,",
              "    IF(CRM[Stage]=\"Quoted\",Quoted,",
              "    IF(CRM[Stage]=\"Credit App\",CreditApp,",
              "    IF(CRM[Stage]=\"1-3 Loads\",OneToThree,",
              "    IF(CRM[Stage]=\"Customer\",Customer,",
              "",
              "    \"FALSE\")))))))",
              "",
              "Return",
              "AtRisk"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2f304527-0231-4bc8-9101-1e86f075fd4e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "deee83fc-4184-4d0b-8229-32031f2212a8",
        "partitions": [
          {
            "name": "crm",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/CRM/crm.xlsx\"), null, true),",
                "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Extracted Text Between Delimiters\" = Table.TransformColumns(#\"Promoted Headers\", {{\"user_id\", each Text.BetweenDelimiters(Text.From(_, \"en-US\"), \"'\", \"'\"), type text}, {\"stage_id\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}, {\"x_studio_primary_industry\", each Text.BetweenDelimiters(Text.From(_, \"en-US\"), \"'\", \"'\"), type text}, {\"state_id\", each Text.BetweenDelimiters(Text.From(_, \"en-US\"), \"'\", \"'\"), type text}, {\"x_stage_id\", each Text.BetweenDelimiters(Text.From(_, \"en-US\"), \"'\", \"'\"), type text}}),",
                "    #\"Extracted Text Between Delimiters1\" = Table.TransformColumns(#\"Extracted Text Between Delimiters\", {{\"partner_id\", each Text.BetweenDelimiters(_, \"[\", \",\"), type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Extracted Text Between Delimiters1\",false,null,Replacer.ReplaceValue,{\"x_studio_mcleod_code\", \"x_studio_sdr\", \"stage_id\", \"date_last_stage_update\", \"activity_date_deadline\", \"date_open\", \"x_studio_lead_type\", \"x_studio_originally_passed_to\", \"x_studio_lead_passed_date\", \"x_studio_enrichment_date\", \"city\", \"x_studio_revenue_range\"}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Replaced Value\", \"Stage\", each if [type] = \"lead\" then [x_stage_id] else [stage_id]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Conditional Column\",{\"stage_id\", \"x_stage_id\"}),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Removed Columns\", \"Last Stage Change\", each if [type] = \"lead\" then [x_date_last_prospect_stage_change] else [date_last_stage_update]),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Added Conditional Column1\",{\"date_last_stage_update\", \"x_date_last_prospect_stage_change\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"date_open\", type datetime}, {\"Last Stage Change\", type datetime}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Changed Type\",{{\"Last Stage Change\", type date}, {\"x_studio_enrichment_date\", type date}, {\"date_open\", type date}, {\"activity_date_deadline\", type date}}),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Changed Type1\", {\"partner_id\"}),",
                "    #\"Extracted Text Between Delimiters2\" = Table.TransformColumns(#\"Removed Errors\", {{\"x_studio_sdr\", each Text.BetweenDelimiters(_, \"'\", \"'\"), type text}}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Extracted Text Between Delimiters2\",{{\"x_studio_lead_passed_date\", type date}}),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type2\",{{\"user_id\", Text.Trim, type text}})",
                "in",
                "    #\"Trimmed Text\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "carrier_key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "address1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7071f5f6-b183-4985-bfcc-e9b45d46dfa3",
            "sourceColumn": "address1",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "929d7294-f315-4b89-9d8f-c32ae64823fd",
            "sourceColumn": "city",
            "summarizeBy": "none"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9da5d9a9-bb78-4b91-905b-159234b0fc2e",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b1b7a83-8339-4a12-8af9-010096adecbb",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b95024b2-1b2e-4eb6-9a17-6adfd8f642e0",
            "sourceColumn": "state",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c9d921a-88ee-4224-b8f9-838f1c583a3b",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "zip_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43deb3a0-72fa-40c0-a74b-81c586cecb3d",
            "sourceColumn": "zip_code",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d46e93c2-0fe7-447c-aa96-63a09c700d0e",
        "partitions": [
          {
            "name": "carrier_key",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"bl-appdb\", \"lme\"),",
                "    dbo_payee = Source{[Schema=\"dbo\",Item=\"payee\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_payee,{\"address1\", \"city\", \"id\", \"name\", \"state\", \"status\", \"zip_code\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "division_key",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41f47a6e-5b33-4e98-80f2-3802913cd79e",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1b8dd742-2d76-4e50-88d9-4317989076d3",
        "partitions": [
          {
            "name": "division_key",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = job_history,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Division\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\"),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Removed Duplicates\", {\"Division\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Errors\", each ([Division] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5d529210-5800-429f-b2e3-388a81d360f9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f351a076-0313-437d-8969-a9b0140bb10e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c722446d-27f7-41e1-be84-0aa9a646250b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1e8bd4b8-fd81-487e-b1dd-6c0b036ffa2c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a5ed135a-78d3-4378-92d8-54eba757fe2f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6eca778e-ea35-4dd8-8dc3-b99b872e11a7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9fe6f924-d870-4e7e-969d-19cd7ffb3735",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9cc9ffdc-2f6b-49f8-bdfb-f2d4aff93a79",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ea5c3024-33dc-41d8-a484-581a3eb8e3ce",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "0ceed20d-f398-40a6-b282-c5e6239f9aa6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2f3a2d0b-1a0e-4240-abcd-f35e002d7c2b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "077b24e8-6db8-4f9a-8cf6-c907914cac07",
                "ordinal": 3
              }
            ],
            "lineageTag": "ffe3f727-117a-41aa-b0f9-06b7c88b55ef"
          }
        ],
        "isHidden": true,
        "lineageTag": "cd62981a-35dd-4f22-92fb-70280c4ac959",
        "partitions": [
          {
            "name": "LocalDateTable_5d529210-5800-429f-b2e3-388a81d360f9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('crt_movement_data'[Hand over])), 1, 1), Date(Year(MAX('crt_movement_data'[Hand over])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_67948750-4a55-4170-865e-d76c6427f063",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ffd816d5-eafa-4ebf-afaf-d8aedb19ddfb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "313790a8-ebe1-49d7-9637-85457a56f093",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "39fbb9d8-a86e-4a2a-8c14-d4094fc7daf7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c9cfbbb6-a30c-4fce-bb7f-ba32bbb8d541",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8ed42515-bfb7-488e-869c-74565166e897",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8b4b3235-1589-4880-82a5-82f71b03cc84",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1dbbb01e-c341-430a-b9d7-f56b36380a10",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bfbdb139-9ed8-4958-9e98-873f3fe5c9a4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "420dee65-90a6-4f6e-9e93-8cc796a291e4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ce97faac-8551-4e0c-b470-4fbc133c9cab",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2baa847a-0eb5-40d3-bcb2-77c8d5d61c79",
                "ordinal": 3
              }
            ],
            "lineageTag": "b378e1b6-75db-4fd2-a168-cadaa84142a1"
          }
        ],
        "isHidden": true,
        "lineageTag": "382e80cb-ce8d-4ef3-a920-00cfc6d03702",
        "partitions": [
          {
            "name": "LocalDateTable_67948750-4a55-4170-865e-d76c6427f063",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('crt_movement_data'[Ship date at Avail])), 1, 1), Date(Year(MAX('crt_movement_data'[Ship date at Avail])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}