table behavior_goals
	lineageTag: e52fd5f3-a7fc-49f9-9be5-ddf09795ef92

	column Salesperson
		dataType: string
		lineageTag: 377c5a59-68c1-4636-9bb7-364eb7813682
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84b63e0d-c663-43a9-a083-ce3bdaa8e293
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BehaviorID
		dataType: string
		lineageTag: 05cb2d2a-c55f-4215-b3dd-1d94a77514f1
		summarizeBy: none
		sourceColumn: BehaviorID

		annotation SummarizationSetBy = Automatic

	column Goal
		dataType: int64
		formatString: 0
		lineageTag: 85edcf64-c9f4-4525-bfcd-d12d4e3d0759
		summarizeBy: sum
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

	partition behavior_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    BehaviorGoals_Sheet = Source{[Item="BehaviorGoals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(BehaviorGoals_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Salesperson", type text}, {"Month", type date}, {"Behavior", type text}, {"Goal", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Behavior", "BehaviorID"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

