table 'Employee Photos'
	lineageTag: fa3f0a45-a866-4212-b83d-72c09c64efd0

	column Id
		dataType: string
		lineageTag: 14d9f7a2-0d6f-44b0-a666-419fed37d709
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column EmployeeName
		dataType: string
		lineageTag: a100b8e2-c33c-4b51-acc0-98406b19eccd
		summarizeBy: none
		sourceColumn: EmployeeName

		annotation SummarizationSetBy = Automatic

	column 'File.ServerRelativeUrl'
		dataType: string
		lineageTag: 0ebe54d3-a78a-4463-bb66-86a76e9a5c5e
		summarizeBy: none
		sourceColumn: File.ServerRelativeUrl

		annotation SummarizationSetBy = Automatic

	column 'Image URL' = ```
			"https://bridgelogisticsinc.sharepoint.com/"&'Employee Photos'[File.ServerRelativeUrl] 
			```
		lineageTag: 829b956e-3688-413a-ab22-cd81651d5f9c
		dataCategory: ImageUrl
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ffl_lineup.team'
		dataType: string
		lineageTag: 55b1a7a4-0677-4023-9227-18665328a2b8
		summarizeBy: none
		sourceColumn: ffl_lineup.team

		annotation SummarizationSetBy = Automatic

	partition 'Employee Photos' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://bridgelogisticsinc.sharepoint.com/sites/BusinessIntelligence", [Implementation=null, ApiVersion=15]),
				    #"cfff0858-6804-4082-9dbd-341b13fe1fa6" = Source{[Id="cfff0858-6804-4082-9dbd-341b13fe1fa6"]}[Items],
				    #"Removed Other Columns" = Table.SelectColumns(#"cfff0858-6804-4082-9dbd-341b13fe1fa6",{"Id", "EmployeeName", "File"}),
				    #"Expanded File" = Table.ExpandRecordColumn(#"Removed Other Columns", "File", {"ServerRelativeUrl"}, {"File.ServerRelativeUrl"}),
				    #"Merged Queries" = Table.FuzzyNestedJoin(#"Expanded File", {"EmployeeName"}, ffl_lineup, {"employee_name"}, "ffl_lineup", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=false]),
				    #"Expanded ffl_lineup" = Table.ExpandTableColumn(#"Merged Queries", "ffl_lineup", {"team"}, {"ffl_lineup.team"})
				in
				    #"Expanded ffl_lineup"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

