table pay_schedule
	lineageTag: 443d23cd-1878-4ce2-b1f0-cb97d81400f1

	column 'Pay Period'
		dataType: int64
		formatString: 0
		lineageTag: 7a9f4b34-0a96-4f3a-a625-b9e9dd3ebe6b
		summarizeBy: sum
		sourceColumn: Pay Period

		annotation SummarizationSetBy = Automatic

	column 'Commission Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f0ad40fd-6cf3-477d-9b7a-879313f15dd9
		summarizeBy: none
		sourceColumn: Commission Month

		variation Variation
			isDefault
			relationship: 14e715b2-e8b7-477d-bad8-c42bd7a42ed5
			defaultHierarchy: LocalDateTable_5204cc32-7744-4162-bd7a-37c8843dcd5c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pay Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 02c6ebfb-de32-4185-9fd8-9123bfd4199e
		summarizeBy: none
		sourceColumn: Pay Date

		variation Variation
			isDefault
			relationship: 5e94ac41-9664-4dd5-8b2a-ee99b5b474b1
			defaultHierarchy: LocalDateTable_984f2224-97c9-4ff5-8864-d5ee44b7d514.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition pay_schedule = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Commission%20Payroll%20Schedule.xlsx"), null, true),
				    BasePlusCommissionNewStructure_Table = Source{[Item="BasePlusCommissionNewStructure",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(BasePlusCommissionNewStructure_Table,{{"Pay Period", Int64.Type}, {"Commission Month", type text}, {"Pay Date", type date}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Commission Month", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

