table transitioned_accounts
	lineageTag: 897dda26-edf0-4451-988c-251a5ccbd845

	column 'Customer ID'
		dataType: string
		lineageTag: 53ac2278-1edf-4ebe-8496-75ff34a74ca5
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Change Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: eb07aa88-7b3f-4375-b078-d61de250861f
		summarizeBy: none
		sourceColumn: Change Date

		annotation SummarizationSetBy = Automatic

	partition transitioned_accounts = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Salesperon%20Change/Salesperson%20Change.xlsx"), null, true),
				    salesperson_change_Table = Source{[Item="salesperson_change",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(salesperson_change_Table,{{"Customer ID", type text}, {"Change Date", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

