table crm_stages
	lineageTag: 3fe647cf-f0e9-4ca1-931e-2f3de372b7cb

	column Order
		dataType: string
		lineageTag: 630a3f49-43f5-4b8c-96eb-8434269c285d
		summarizeBy: none
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Stage Name'
		dataType: string
		lineageTag: 12c05801-f4f2-4d91-895b-f6426805c0f6
		summarizeBy: none
		sourceColumn: Stage Name
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition crm_stages = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Lc89D4IwEIDhv3LpjIkVP0clIQ4EdTAOhKHSio3Ya/oR/r5nYXyfS3u5pmGcZexilYGrQ29VFzxrs4atiCsc4SxMr00PpYs6pElOkwe6D2nqNXWNUKKDGsdEG6KTkFDOT7bUdxMwdm/xHNS0YUd4i2LQL61kkn0SDHMeKAunpA5wtDYRX5LxRQ4VCjl9w/8HFNEH/CrH2vYH", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, #"Stage Name" = _t])
				in
				    Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

