table healthy_pipeline_goals
	lineageTag: cb9522ca-5231-4a40-836b-34657a1cbc76

	column 'Saleperson Name'
		dataType: string
		lineageTag: fc79a5be-df43-4aa1-b9e0-96180bf1b1f9
		summarizeBy: none
		sourceColumn: Saleperson Name

		annotation SummarizationSetBy = Automatic

	column Stage
		dataType: string
		lineageTag: 8b188823-885a-4dc1-aea2-6f91d83edd20
		summarizeBy: none
		sourceColumn: Stage

		annotation SummarizationSetBy = Automatic

	column 'Healthy #'
		dataType: int64
		formatString: 0
		lineageTag: 45182cbb-d26f-4661-b1a2-25dea23ecdbb
		summarizeBy: sum
		sourceColumn: Healthy #

		annotation SummarizationSetBy = Automatic

	partition healthy_pipeline_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    HealthyPipelineGoals_Table = Source{[Item="HealthyPipelineGoals",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(HealthyPipelineGoals_Table,{{"Saleperson Name", type text}, {"Stage", type text}, {"Healthy #", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

