table behavior_goals
	lineageTag: e532f925-88db-4174-ae40-ae07e600369d

	column Salesperson
		dataType: string
		lineageTag: 7387133a-b8bc-43fe-bf66-c62a29b0c190
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3020ed2-330b-431a-990b-6dedbb6b93f2
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BehaviorID
		dataType: string
		lineageTag: 3ebaf21b-bab9-43d2-a367-b9cfe3155486
		summarizeBy: none
		sourceColumn: BehaviorID

		annotation SummarizationSetBy = Automatic

	column Goal
		dataType: int64
		formatString: 0
		lineageTag: 171ed716-db12-481a-a349-fce2a17eff39
		summarizeBy: sum
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

	partition behavior_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    BehaviorGoals_Sheet = Source{[Item="BehaviorGoals",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(BehaviorGoals_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Salesperson", type text}, {"Month", type date}, {"Behavior", type text}, {"Goal", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Behavior", "BehaviorID"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each true)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

