table carrier_dispatch_movement_data
	lineageTag: a38a15e7-6fb6-48f7-8307-30596cfd6e34

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: 09789d9a-a31f-4bda-bf85-66c53b3274e8
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Movement ID'
		dataType: int64
		formatString: 0
		lineageTag: b41653ff-57dc-44b1-a51e-9477faa1d594
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'Available Date Time'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: d9d1fe19-9a21-48fc-9424-8f155c9357a9
		summarizeBy: none
		sourceColumn: Available Date Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Covered Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 80575f38-ab77-4fc0-afcf-033afa27c34e
		summarizeBy: none
		sourceColumn: Covered Date Time

		annotation SummarizationSetBy = Automatic

	column 'Give Back Date Time'
		dataType: dateTime
		formatString: General Date
		lineageTag: 2c17b94a-0284-49f7-9a88-0318fa3dc9c3
		summarizeBy: none
		sourceColumn: Give Back Date Time

		annotation SummarizationSetBy = Automatic

	column 'Load Board Date Time'
		dataType: dateTime
		formatString: yyyy-mm-dd hh:nn:ss
		lineageTag: fb9ae9cc-b264-4b4a-b950-8f65eb6fb86a
		summarizeBy: none
		sourceColumn: Load Board Date Time

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Start Max Pay'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1dfe6b40-ae8c-4603-b120-71c99632ca14
		summarizeBy: sum
		sourceColumn: Start Max Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'End Max Pay'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 69f143d1-e80f-44b1-81e4-cac54cb72beb
		summarizeBy: sum
		sourceColumn: End Max Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Count of CarrierOffers'
		dataType: string
		lineageTag: 2de6ed47-a6ee-4657-8e46-a7974b2e9bf5
		summarizeBy: none
		sourceColumn: Count of CarrierOffers

		annotation SummarizationSetBy = Automatic

	column 'Number of Pass Backs'
		dataType: int64
		formatString: 0
		lineageTag: b2bf2cfe-ede7-41e6-82a6-e91f3c6669ad
		summarizeBy: sum
		sourceColumn: Number of Pass Backs

		annotation SummarizationSetBy = Automatic

	partition carrier_dispatch_movement_data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Carrier%20Dispatch%20Movement%20Data/Carrier%20Dispatch%20Movement%20Data.xlsx"), null, true),
				    movement_data_Table = Source{[Item="movement_data",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(movement_data_Table,{{"Order ID", Int64.Type}, {"Movement ID", Int64.Type}, {"Available Date Time", type datetime}, {"Covered Date Time", type datetime}, {"Give Back Date Time", type datetime}, {"Load Board Date Time", type datetime}, {"Start Max Pay", Int64.Type}, {"End Max Pay", Int64.Type}, {"Count of CarrierOffers", type any}, {"Number of Pass Backs", Int64.Type}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Start Max Pay", Currency.Type}, {"End Max Pay", Currency.Type}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

