table carrier_key
	lineageTag: 16945d3f-edc6-48f1-9bb6-1b874fa6b30a

	column 'Carrier ID'
		dataType: string
		lineageTag: 3fef20e0-c612-499e-899c-95d5d3e7eba7
		summarizeBy: none
		sourceColumn: Carrier ID

		annotation SummarizationSetBy = Automatic

	column 'Carrier Name'
		dataType: string
		lineageTag: eba82b52-1a1d-4964-9507-530f5cf5646f
		summarizeBy: none
		sourceColumn: Carrier Name

		annotation SummarizationSetBy = Automatic

	column 'Carrier Status'
		dataType: string
		lineageTag: 6aca6411-fae6-4ae3-b402-83967312f7dd
		summarizeBy: none
		sourceColumn: Carrier Status

		annotation SummarizationSetBy = Automatic

	column MCN
		dataType: string
		lineageTag: 5f9f678f-7e95-41c6-89c8-3170596d4710
		summarizeBy: none
		sourceColumn: MCN

		annotation SummarizationSetBy = Automatic

	partition carrier_key = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Databases("bl-mcbiserver", [TypedMeasureColumns=true, Implementation="2.0"]),
				    McLeodIQ_2019_Powerbroker = Source{[Name="McLeodIQ_2019_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker1 = McLeodIQ_2019_Powerbroker{[Id="McLeodIQ_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker2 = McLeodIQ_Powerbroker1{[Id="McLeodIQ_Powerbroker"]}[Data],
				    #"Added Items" = Cube.Transform(McLeodIQ_Powerbroker2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[Carrier]", {"[Carrier].[Carrier ID].[Carrier ID]", "[Carrier].[Carrier Name].[Carrier Name]", "[Carrier].[Carrier Status].[Carrier Status]", "[Carrier].[MC Number].[MC Number]"}, {"Carrier.Carrier ID", "Carrier.Carrier Name", "Carrier.Carrier Status", "Carrier.MC Number"}}
				        }),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Items",{{"Carrier.Carrier ID", "Carrier ID"}, {"Carrier.Carrier Name", "Carrier Name"}, {"Carrier.Carrier Status", "Carrier Status"}, {"Carrier.MC Number", "MCN"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns", {"MCN"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"Carrier ID"})
				in
				    #"Removed Duplicates1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

