table check_call_roller
	lineageTag: 975bb29b-68cf-40b5-bf41-d087f30804db

	column 'Movement ID'
		dataType: int64
		formatString: 0
		lineageTag: f03fc93f-5bd5-4bec-a77a-3852d694eb05
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'Scheduled Check Call Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 92b354bc-a43a-444e-9d43-ecc8c7a4fa5b
		summarizeBy: none
		sourceColumn: Scheduled Check Call Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pass / Fail'
		dataType: string
		lineageTag: ccffc4d4-d1b9-490f-b324-a8b12cfe2f75
		summarizeBy: none
		sourceColumn: Pass / Fail

		annotation SummarizationSetBy = Automatic

	column Reason
		dataType: string
		lineageTag: 46c62862-2002-4362-8a5d-9282c7b2fb40
		summarizeBy: none
		sourceColumn: Reason

		annotation SummarizationSetBy = Automatic

	column 'Scheduled Check Call Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: cc7abdcc-29ce-43d7-a8e4-ce4e819b1c72
		summarizeBy: none
		sourceColumn: Scheduled Check Call Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition check_call_roller = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Moved%20Check%20Calls/Check%20Call%20Pass%20or%20fail.xlsx"), null, true),
				    Check_Call_Table_Table = Source{[Item="Check_Call_Table",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Check_Call_Table_Table,{{"Movement ID", Int64.Type}, {"Date Time", type datetime}, {"Pass / Fail", type text}, {"Reason", type text}}),
				    #"Inserted Time" = Table.AddColumn(#"Changed Type", "Time", each DateTime.Time([Date Time]), type time),
				    #"Extracted Date" = Table.TransformColumns(#"Inserted Time",{{"Date Time", DateTime.Date, type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Extracted Date",{{"Date Time", "Scheduled Check Call Date"}, {"Time", "Scheduled Check Call Time"}}),
				    #"Calculated Start of Hour" = Table.TransformColumns(#"Renamed Columns",{{"Scheduled Check Call Time", Time.StartOfHour, type time}})
				in
				    #"Calculated Start of Hour"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

