table crm_stages
	lineageTag: de058a77-3f0c-45f1-92c0-e117edf37ae3

	column Order
		dataType: int64
		formatString: 0
		lineageTag: 7e571519-d057-4ba1-8769-877c23f8a44e
		summarizeBy: sum
		sourceColumn: Order

		annotation SummarizationSetBy = Automatic

	column 'Stage Name'
		dataType: string
		lineageTag: e5401c74-86b2-4818-99eb-9a347bdd0d04
		summarizeBy: none
		sourceColumn: Stage Name
		sortByColumn: Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition crm_stages = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/CRM/CRM%20Stages.xlsx"), null, true),
				    CRMStages_Table = Source{[Item="CRMStages",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(CRMStages_Table,{{"Order", Int64.Type}, {"Stage Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

