table job_history
	lineageTag: abd8ef60-9f2c-470f-a2e3-31fc24599578

	column 'Row ID'
		dataType: string
		lineageTag: 904aa817-4cca-4b75-8d4e-36c8f11291fb
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Job Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: accb1b2a-c512-4df7-b61d-1e7b48321792
		summarizeBy: none
		sourceColumn: Job Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID
		dataType: int64
		formatString: 0
		lineageTag: cbca5fcd-782e-4d6b-b5fc-c283645f28e9
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 75ed8b8f-162f-4707-93aa-6d4f13f257da
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 7c944ecb-9e78-4304-bfd7-5c4a8b8e6102
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: f722c561-dd42-4c64-8b66-999c34f412ad
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column 'Reports To'
		dataType: string
		lineageTag: e81aca67-60e4-4df1-a142-25ba3a509341
		summarizeBy: none
		sourceColumn: Reports To

		annotation SummarizationSetBy = Automatic

	column 'Mcleod Code'
		dataType: string
		lineageTag: ff3b6d9e-afa8-4354-816a-c95ef9673c4d
		summarizeBy: none
		sourceColumn: Mcleod Code

		annotation SummarizationSetBy = Automatic

	column 'Work Email'
		dataType: string
		lineageTag: 3bdb4262-9a10-4fcd-9cff-525ec1950523
		summarizeBy: none
		sourceColumn: Work Email

		annotation SummarizationSetBy = Automatic

	column 'McLeod Salesperson Code'
		dataType: string
		lineageTag: b85b596b-06d1-4f80-b1a2-01d8f990c28f
		summarizeBy: none
		sourceColumn: McLeod Salesperson Code

		annotation SummarizationSetBy = Automatic

	column 'Job End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: bedfec56-b565-4955-851c-b03ef9656fe8
		summarizeBy: none
		sourceColumn: Job End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition job_history = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Bamboo/Job%20History.xlsx"), null, true),
				    job_history_Table = Source{[Item="job_history",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(job_history_Table,{{"Row ID", type text}, {"Name", type text}, {"Prefered Name", type text}, {"Job Start Date", type date}, {"ID", Int64.Type}, {"Division", type text}, {"Department", type text}, {"Job Title", type text}, {"Reports To", type text}, {"Mcleod Code", type text}, {"Work Email", type text}, {"McLeod Salesperson Code", type text}, {"End Date", type date}, {"TerminationDate", type any}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Job End Date", each if [End Date] = null then [TerminationDate] else [End Date]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"End Date", "TerminationDate"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","0000-00-00","",Replacer.ReplaceValue,{"Job End Date"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value",{"Name", "Prefered Name"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"Job End Date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

