table overdue_check_calls
	lineageTag: 25edfc97-6e45-4857-9dce-35637529f18b

	column 'Movement ID'
		dataType: int64
		formatString: 0
		lineageTag: b8455d28-5078-4fa6-96c2-dacc9e5d30a3
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'Check Call Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: e94c091b-48f3-4883-a2c2-d007f253b7e6
		summarizeBy: none
		sourceColumn: Check Call Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Check Call time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: a78f8014-9b74-4060-9f45-7ad5188f290d
		summarizeBy: none
		sourceColumn: Check Call time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Status
		dataType: string
		lineageTag: 303d590b-af9c-4218-8bfc-81f00a4f7b82
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition overdue_check_calls = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/Overdue Check Call/")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (6)", each #"Transform File (6)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (6)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (6)", Table.ColumnNames(#"Transform File (6)"(#"Sample File (6)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"Movement ID", Int64.Type}, {"Check Call Time", type datetime}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Blank Rows",{"Source.Name"}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Removed Columns", {"Check Call Time"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Removed Errors", {{"Check Call Time", type text}}, "en-US"), "Check Call Time", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Check Call Time.1", "Check Call Time.2"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Split Column by Delimiter",{{"Check Call Time.1", "Check Call Date"}, {"Check Call Time.2", "Check Call time"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Check Call Date", type date}, {"Check Call time", type time}}),
				    #"Calculated Start of Hour" = Table.TransformColumns(#"Changed Type1",{{"Check Call time", Time.StartOfHour, type time}})
				in
				    #"Calculated Start of Hour"

	annotation PBI_ResultType = Table

