table pay_schedule
	lineageTag: 06a78adf-c706-4c53-aeac-e6eb9c0e2b81

	column 'Pay Period'
		dataType: int64
		formatString: 0
		lineageTag: 4d4b917a-b61f-4104-80cc-76cee4564507
		summarizeBy: sum
		sourceColumn: Pay Period

		annotation SummarizationSetBy = Automatic

	column 'Commission Month'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ea57e895-48e3-441b-8004-066557ca78f5
		summarizeBy: none
		sourceColumn: Commission Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pay Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2c235e1c-6c3f-41e6-ba5a-68e06f9beb21
		summarizeBy: none
		sourceColumn: Pay Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition pay_schedule = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Commission%20Payroll%20Schedule.xlsx"), null, true),
				    BasePlusCommissionNewStructure_Table = Source{[Item="BasePlusCommissionNewStructure",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(BasePlusCommissionNewStructure_Table,{{"Pay Period", Int64.Type}, {"Commission Month", type text}, {"Pay Date", type date}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"Commission Month", type date}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

