/// This Table contains the data from the Recruitment module in Odoo.
/// Direct Relationships:
/// 1 to * with behaviors_recruitment
/// * to 1 with recruiter_key
table recruitment
	lineageTag: ac3a3bb2-4066-482b-8ae0-10dbe4a4053e

	column id
		dataType: int64
		formatString: 0
		lineageTag: d13715d1-ca73-4caf-81db-b2ea3a16d95e
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 5962a396-d068-4d6c-9c62-4ab5b6b8c27e
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column job_id
		dataType: string
		lineageTag: 874fe3c8-eae4-4a3c-ba47-9f391b5947e1
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column stage_id
		dataType: string
		lineageTag: b864e57f-bd9e-47d0-a8cc-0fa758ecb061
		summarizeBy: none
		sourceColumn: stage_id

		annotation SummarizationSetBy = Automatic

	column user_id
		dataType: string
		lineageTag: e4af4f77-68f8-46e0-bda3-f02c671c4ac1
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column create_date
		dataType: dateTime
		formatString: General Date
		lineageTag: f1292bb7-36fc-41b5-b5c4-bdaf3f17dc51
		summarizeBy: none
		sourceColumn: create_date

		annotation SummarizationSetBy = Automatic

	column source_id
		dataType: string
		lineageTag: 9f610cf6-5d22-4c43-a551-ce62f9be4f2d
		summarizeBy: none
		sourceColumn: source_id

		annotation SummarizationSetBy = Automatic

	column active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 88466d37-c205-4ade-a6db-f6ed6927bdf1
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	column x_studio_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 31b95457-7eca-4ae2-bbc8-b3bd7a80dd9b
		summarizeBy: none
		sourceColumn: x_studio_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_team
		dataType: string
		lineageTag: 346458c9-4767-4e1c-9d87-c375187f0751
		summarizeBy: none
		sourceColumn: x_studio_team

		annotation SummarizationSetBy = Automatic

	column x_studio_sdr_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 48b3a7cd-f965-47da-8c5d-dda2da6775e1
		summarizeBy: none
		sourceColumn: x_studio_sdr_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_d_team_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e4988480-b41d-4144-8aa6-e1ac1523375b
		summarizeBy: none
		sourceColumn: x_studio_d_team_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_henry_start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd4b239b-c22f-4541-ac21-38de7d6534b6
		summarizeBy: none
		sourceColumn: x_studio_henry_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_mcleod_user_code
		dataType: string
		lineageTag: b91ffc97-bbba-4836-93a5-5ef1b8057601
		summarizeBy: none
		sourceColumn: x_studio_mcleod_user_code

		annotation SummarizationSetBy = Automatic

	column x_studio_mcleod_salesperson_code
		dataType: string
		lineageTag: e0a642c2-2875-4700-b01b-6b08fba47f58
		summarizeBy: none
		sourceColumn: x_studio_mcleod_salesperson_code

		annotation SummarizationSetBy = Automatic

	column x_studio_termination_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 688d7436-a920-4232-9411-389335abaaf3
		summarizeBy: none
		sourceColumn: x_studio_termination_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column x_studio_dat_license
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 04e04671-6e6f-417a-a6e9-732ebfa53795
		summarizeBy: none
		sourceColumn: x_studio_dat_license

		annotation SummarizationSetBy = Automatic

	column x_studio_bi_license
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0ed6c78b-895c-4590-9f0e-ecd4d1b73e1c
		summarizeBy: none
		sourceColumn: x_studio_bi_license

		annotation SummarizationSetBy = Automatic

	column x_studio_bamboo_employee_number
		dataType: int64
		formatString: 0
		lineageTag: eaa2bbd2-c0a2-4871-ada4-a712e8db40e9
		summarizeBy: sum
		sourceColumn: x_studio_bamboo_employee_number

		annotation SummarizationSetBy = Automatic

	partition recruitment = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Recruitment/recruitment_api.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    //start fixing dates and replaceing date errors
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"job_id", type any}, {"stage_id", type any}, {"user_id", type any}, {"create_date", type datetime}, {"source_id", type any}, {"active", type logical}, {"x_studio_start_date", type date}, {"x_studio_team", type any}, {"x_studio_sdr_start_date", type any}, {"x_studio_d_team_start_date", type date}, {"x_studio_henry_start_date", type date}, {"x_studio_mcleod_user_code", type any}, {"x_studio_mcleod_salesperson_code", type any}, {"x_studio_termination_date", type date}, {"x_studio_dat_license", type logical}, {"x_studio_bi_license", type logical}, {"x_studio_bamboo_employee_number", Int64.Type}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"x_studio_start_date", null}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Errors",{{"x_studio_sdr_start_date", type datetime}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Changed Type2",{{"x_studio_sdr_start_date", type date}}),
				    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Changed Type3", {{"x_studio_sdr_start_date", null}}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Replaced Errors2",{{"x_studio_d_team_start_date", type datetime}}),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Changed Type4",{{"x_studio_d_team_start_date", type date}}),
				    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Changed Type5", {{"x_studio_d_team_start_date", null}}),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Replaced Errors3",{{"x_studio_henry_start_date", type datetime}}),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Changed Type6",{{"x_studio_henry_start_date", type date}}),
				    #"Replaced Errors4" = Table.ReplaceErrorValues(#"Changed Type7", {{"x_studio_henry_start_date", null}}),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Replaced Errors4",{{"x_studio_termination_date", type datetime}}),
				    #"Changed Type9" = Table.TransformColumnTypes(#"Changed Type8",{{"x_studio_termination_date", type date}}),
				    //end fixing dates and replacing date errors
				    #"Replaced Errors5" = Table.ReplaceErrorValues(#"Changed Type9", {{"x_studio_termination_date", null}}),
				    #"Extracted Text Between Delimiters" = Table.TransformColumns(#"Replaced Errors5", {{"job_id", each Text.BetweenDelimiters(_, "'", "'"), type text}, {"stage_id", each Text.BetweenDelimiters(_, "'", "'"), type text}, {"user_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}, {"source_id", each Text.BetweenDelimiters(Text.From(_, "en-US"), "'", "'"), type text}}),
				    #"Replaced Errors6" = Table.ReplaceErrorValues(#"Extracted Text Between Delimiters", {{"job_id", null}}),
				    #"Replaced Errors7" = Table.ReplaceErrorValues(#"Replaced Errors6", {{"stage_id", null}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Errors7",{{"x_studio_mcleod_user_code", type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Changed Type1",{{"x_studio_mcleod_user_code", Text.Upper, type text}}),
				    #"Changed Type10" = Table.TransformColumnTypes(#"Uppercased Text",{{"x_studio_mcleod_salesperson_code", type text}}),
				    #"Uppercased Text1" = Table.TransformColumns(#"Changed Type10",{{"x_studio_mcleod_salesperson_code", Text.Upper, type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Uppercased Text1", each true)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

