table recruitment_goals
	lineageTag: b950a695-1299-40dd-98a8-8bb25b57b8b4

	column 'Recruiter Name'
		dataType: string
		lineageTag: 602f2ed3-3ede-49b2-b891-af2d27152367
		summarizeBy: none
		sourceColumn: Recruiter Name

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 985c2a0a-aa9c-4ba0-91cb-4a9c384f3f00
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Goal Name'
		dataType: string
		lineageTag: cbf39696-2a8f-4756-9922-ded59fb35daf
		summarizeBy: none
		sourceColumn: Goal Name

		annotation SummarizationSetBy = Automatic

	column Goal
		dataType: int64
		formatString: 0
		lineageTag: be5b2096-de7b-4bed-972b-775045b95623
		summarizeBy: sum
		sourceColumn: Goal

		annotation SummarizationSetBy = Automatic

	partition recruitment_goals = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BridgeRecruiting/Shared%20Documents/Recruiting%20Goals/Recruitment%20Goals.xlsx"), null, true),
				    #"Recruitment Goals New_Sheet" = Source{[Item="Recruitment Goals New",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Recruitment Goals New_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Recruiter Name", type text}, {"Month", type date}, {"Goal Name", type text}, {"Goal", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

