table base_or_commission_pay_schedule
	lineageTag: a49dfb0b-312d-4c5d-a904-92af073199f2

	column 'Pay Period'
		dataType: int64
		formatString: 0
		lineageTag: 74014a5e-6a6e-4c46-b595-c6fd97f790fb
		summarizeBy: sum
		sourceColumn: Pay Period

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b495a83a-a3fb-4b6c-8a68-25a5ed5cc1fb
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6112f1cb-c575-4081-8f63-a45ea51405c1
		summarizeBy: none
		sourceColumn: Start Date

		variation Variation
			isDefault
			relationship: 89b9f677-0816-4669-a8c8-f442ded8a523
			defaultHierarchy: LocalDateTable_310ea0fb-96f6-4c25-a836-603d2aed15cb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 83180333-2b1e-4a4a-b054-ba87658e7adb
		summarizeBy: none
		sourceColumn: End Date

		variation Variation
			isDefault
			relationship: 56ea0089-9c49-42ea-934c-3883f1cf6ec1
			defaultHierarchy: LocalDateTable_4c5727d3-5a15-421e-acb8-b9e496939202.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pay Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3a23f7bd-9237-4d7a-aa9e-220136ca07e3
		summarizeBy: none
		sourceColumn: Pay Date

		variation Variation
			isDefault
			relationship: 40e82423-55e3-47f2-83cf-eaed21ae2dd4
			defaultHierarchy: LocalDateTable_176a9bce-2631-41a8-9cfe-4ebe3e6ff622.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pay Period Visual Filter'
		dataType: string
		lineageTag: dccd6c43-5adf-4ac0-ae18-89043092a46b
		summarizeBy: none
		sourceColumn: Pay Period Visual Filter
		sortByColumn: 'Pay Date'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition base_or_commission_pay_schedule = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Commission%20Payroll%20Schedule.xlsx"), null, true),
				    base_or_commission_pay_schedule_Table = Source{[Item="base_or_commission_pay_schedule",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(base_or_commission_pay_schedule_Table,{{"Pay Period", Int64.Type}, {"Year", Int64.Type}, {"Start Date", type date}, {"End Date", type date}, {"Pay Date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Pay Period Visual Filter", each Text.From([Pay Period]) & " - " & Text.From([Pay Date]) & " ([" & Text.From([Start Date]) & "] - [" & Text.From([End Date]) & "])")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

