table job_history
	lineageTag: 0d8addef-5917-4ed8-92a6-3a017ca615e0

	column 'Row ID'
		dataType: string
		lineageTag: f658e0f1-8ec7-4eb8-acf5-e2c794cd3f55
		summarizeBy: none
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Job Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ba069a4e-fc85-4e8c-bcfc-6375f5ddf34f
		summarizeBy: none
		sourceColumn: Job Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 1c31a1fe-3fd7-4fa6-814f-178371f72d28
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 97c171f1-aaab-4092-ab4b-65bd9f1b9d80
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: cc674c11-ac19-41a9-a1fa-cd422e8f3457
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: e29e9659-fbf1-435b-bb34-02a3905fb30a
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column 'Reports To'
		dataType: string
		lineageTag: d800929d-f0c5-45f8-9a12-e9842bc6b367
		summarizeBy: none
		sourceColumn: Reports To

		annotation SummarizationSetBy = Automatic

	column 'Mcleod Code'
		dataType: string
		lineageTag: a2d208af-b93d-4bef-bcfe-77d2728118a6
		summarizeBy: none
		sourceColumn: Mcleod Code

		annotation SummarizationSetBy = Automatic

	column 'Work Email'
		dataType: string
		lineageTag: d74a9ac1-78d5-494c-a808-d9c5560a8580
		summarizeBy: none
		sourceColumn: Work Email

		annotation SummarizationSetBy = Automatic

	column 'McLeod Salesperson Code'
		dataType: string
		lineageTag: 324094b8-cf3d-4253-8aae-248ff783aaf7
		summarizeBy: none
		sourceColumn: McLeod Salesperson Code

		annotation SummarizationSetBy = Automatic

	column 'Job End Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b89583cb-3bda-4fa9-aaf6-85ac70902499
		summarizeBy: none
		sourceColumn: Job End Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition job_history = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Bamboo/Job%20History.xlsx"), null, true),
				    job_history_Table = Source{[Item="job_history",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(job_history_Table,{{"Row ID", type text}, {"Name", type text}, {"Prefered Name", type text}, {"Job Start Date", type date}, {"ID", Int64.Type}, {"Division", type text}, {"Department", type text}, {"Job Title", type text}, {"Reports To", type text}, {"Mcleod Code", type text}, {"Work Email", type text}, {"McLeod Salesperson Code", type text}, {"End Date", type date}, {"TerminationDate", type any}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "Job End Date", each if [End Date] = null then [TerminationDate] else [End Date]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"End Date", "TerminationDate"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","0000-00-00","",Replacer.ReplaceValue,{"Job End Date"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Replaced Value",{"Name", "Prefered Name"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"Job End Date", type date}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type1","Development Team Sales","Development Team",Replacer.ReplaceText,{"Division"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

