table account_rep
	lineageTag: 642ea876-02df-49cf-bf2d-b661b2941b01

	column account_rep
		dataType: string
		lineageTag: 9691f65a-55a2-4762-8be3-441afd733b41
		summarizeBy: none
		sourceColumn: account_rep

		annotation SummarizationSetBy = Automatic

	column wolf_pack
		dataType: string
		lineageTag: f458540d-a20b-4d85-9993-336ee3af8c7b
		summarizeBy: none
		sourceColumn: wolf_pack

		annotation SummarizationSetBy = Automatic

	partition account_rep = m
		mode: import
		source =
				let
				    Source = rev_codes,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"account_rep", "wolf_pack"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Removed Blank Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

