table behaviors_crm
	lineageTag: d1f202cb-d19a-45cf-830c-b0ee40637dba

	column id
		dataType: int64
		formatString: 0
		lineageTag: 6fef6eaf-0f33-476f-9397-62bf79ce1118
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column 'Behavior Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ddea93bb-511c-451d-aa33-4efd0250a656
		summarizeBy: none
		sourceColumn: Behavior Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Behavior Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: b2a5c7b9-5cbd-4fc1-a32a-03183ad575f5
		summarizeBy: none
		sourceColumn: Behavior Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column author_id
		dataType: string
		lineageTag: 74082a51-2c20-4a7e-8e9a-d5a51c41c070
		summarizeBy: none
		sourceColumn: author_id

		annotation SummarizationSetBy = Automatic

	column mail_activity_type_id
		dataType: string
		lineageTag: a11c4576-84a2-4444-8340-6fb524150253
		summarizeBy: none
		sourceColumn: mail_activity_type_id

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 92df256f-c9c3-4486-8b9d-d5a21ee0f153
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column res_id
		dataType: int64
		formatString: 0
		lineageTag: 41b29651-2b6a-48b8-a5ba-d81994fb4035
		summarizeBy: sum
		sourceColumn: res_id

		annotation SummarizationSetBy = Automatic

	partition behaviors_crm = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/behaviors_api_files/2021/" or [Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/behaviors_api_files/2022/" or [Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/behaviors_api_files/2023/" or [Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/behaviors_api_files/2024/")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Hidden Files1",{"Content", "Name"}),
				    #"Filtered Hidden Files2" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files2", "Transform File (4)", each #"Transform File (4)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (4)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (4)", Table.ColumnNames(#"Transform File (4)"(#"Sample File (4)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"id", Int64.Type}, {"date", type datetime}, {"author_id", type any}, {"mail_activity_type_id", type text}, {"model", type text}, {"res_id", Int64.Type}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each true),
				    #"Extracted Text Between Delimiters" = Table.TransformColumns(#"Filtered Rows1", {{"author_id", each Text.BetweenDelimiters(_, "'", "'"), type text}, {"mail_activity_type_id", each Text.BetweenDelimiters(_, "'", "'"), type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Extracted Text Between Delimiters", {{"author_id", null}}),
				    #"Filtered Rows2" = Table.SelectRows(#"Replaced Errors", each ([model] <> "gamification.badge.user") and ([author_id] <> null and [author_id] <> "OdooBot" and [author_id] <> "Portal User Template")),
				    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Filtered Rows2", {{"date", type text}}, "en-US"), "date", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"date.1", "date.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"date.1", type date}, {"date.2", type time}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type2",{{"date.1", "Behavior Date"}, {"date.2", "Behavior Time"}})
				in
				    #"Renamed Columns2"

	annotation PBI_ResultType = Table

