table callins
	lineageTag: c3b14ccd-e8ea-4e24-b354-916b8bbb278e

	column entered_by
		dataType: string
		lineageTag: 7192a89e-e73f-449d-be09-d34f7e396979
		summarizeBy: none
		sourceColumn: entered_by

		annotation SummarizationSetBy = Automatic

	column entered_date_time
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64ebbfeb-8149-4837-8189-06880901d32f
		summarizeBy: none
		sourceColumn: entered_date_time

		annotation SummarizationSetBy = Automatic

	column movement_status
		dataType: string
		lineageTag: b2c52169-1c2f-44ab-80c7-c248371922a7
		summarizeBy: none
		sourceColumn: movement_status

		annotation SummarizationSetBy = Automatic

	column payee_id
		dataType: string
		lineageTag: 2b2c3a56-f074-450c-bca7-405ef3c5b9e4
		summarizeBy: none
		sourceColumn: payee_id

		annotation SummarizationSetBy = Automatic

	column initiated_type
		dataType: string
		lineageTag: 7212ceae-b271-428e-8741-f7aa7630c2ea
		summarizeBy: none
		sourceColumn: initiated_type

		annotation SummarizationSetBy = Automatic

	column entered_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: defe8dc0-a917-400e-8017-5c5347c3fb4e
		summarizeBy: none
		sourceColumn: entered_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column movement_id
		dataType: string
		lineageTag: 3ac4c678-3d1c-4c3b-945d-92cdff20c650
		summarizeBy: none
		sourceColumn: movement_id

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: e05afb02-98b5-4baf-8220-678cfada4aa8
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 4e9d6882-f938-42a8-84e5-c5724a18263f
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e2b156db-f62d-4809-8d3c-c4c4b2f1ce70
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition callins = m
		mode: import
		source =
				let
				    Source = Sql.Database("bl-appdb", "lme"),
				    dbo_callin = Source{[Schema="dbo",Item="callin"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_callin,{"entered_by", "entered_date", "movement_status", "payee_id", "initiated_type", "movement_id", "city_name", "state"}),
				    #"Filtered callins on or after RefreshCutOffDate" = Table.SelectRows(#"Removed Other Columns", each [entered_date] >= RefreshCutOffDate),
				    #"Inserted Time" = Table.AddColumn(#"Filtered callins on or after RefreshCutOffDate", "Time", each DateTime.Time([entered_date]), type time),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Time",{{"Time", "entered_time"}, {"entered_date", "entered_date_time"}}),
				    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Date", each DateTime.Date([entered_date_time]), type date),
				    #"Calculated Start of Hour" = Table.TransformColumns(#"Inserted Date",{{"entered_time", Time.StartOfHour, type time}}),
				    #"Appended Query" = Table.Combine({#"Calculated Start of Hour", historic_callins})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

