table callins
	lineageTag: f8ce91d6-2304-4ad3-9cd9-62100b1227a4

	column 'Entered date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 016787e3-5c7f-4d6a-9e39-d6038e056844
		summarizeBy: none
		sourceColumn: Entered date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Entered by'
		dataType: string
		lineageTag: 30864c19-dc23-4f3d-ab50-c403cccb156a
		summarizeBy: none
		sourceColumn: Entered by

		annotation SummarizationSetBy = Automatic

	column 'Callin type'
		dataType: string
		lineageTag: 2286da3a-f302-44b3-b51a-afba842b31d8
		summarizeBy: none
		sourceColumn: Callin type

		annotation SummarizationSetBy = Automatic

	column Movement
		dataType: int64
		formatString: 0
		lineageTag: 67539b2a-ed4d-4a8f-a2ca-c09b60a09b3c
		summarizeBy: sum
		sourceColumn: Movement

		annotation SummarizationSetBy = Automatic

	column Carrier
		dataType: string
		lineageTag: fa2ea8fd-d2f0-41d1-8663-e324dc05d0d4
		summarizeBy: none
		sourceColumn: Carrier

		annotation SummarizationSetBy = Automatic

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: a0d17078-cb14-4481-8a6d-637c5a37ea8b
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition callins = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam", [ApiVersion = 15]),
				    #"Filtered Rows" = Table.SelectRows(Source, each ([Folder Path] = "https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared Documents/bridge_iq/Data Sets/Callins/2024/")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File (7)", each #"Transform File (7)"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File (7)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (7)", Table.ColumnNames(#"Transform File (7)"(#"Sample File (7)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"call_date_time", type datetimezone}, {"entered_by", type text}, {"initiated_type", type text}, {"movement_id", Int64.Type}, {"payee_id", type text}, {"id", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name", "id"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"call_date_time", type datetime}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"payee_id", "Carrier"}, {"movement_id", "Movement"}, {"initiated_type", "Callin type"}, {"entered_by", "Entered by"}, {"call_date_time", "Entered date"}}),
				    #"Inserted Time" = Table.AddColumn(#"Renamed Columns", "Time", each DateTime.Time([Entered date]), type time),
				    #"Extracted Date" = Table.TransformColumns(#"Inserted Time",{{"Entered date", DateTime.Date, type date}}),
				    #"Appended Query" = Table.Combine({#"Extracted Date", #"Old Callins"})
				in
				    #"Appended Query"

	annotation PBI_ResultType = Table

