table callins
	lineageTag: c3b14ccd-e8ea-4e24-b354-916b8bbb278e

	column entered_by
		dataType: string
		lineageTag: 7192a89e-e73f-449d-be09-d34f7e396979
		summarizeBy: none
		sourceColumn: entered_by

		annotation SummarizationSetBy = Automatic

	column entered_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 64ebbfeb-8149-4837-8189-06880901d32f
		summarizeBy: none
		sourceColumn: entered_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column movement_status
		dataType: string
		lineageTag: b2c52169-1c2f-44ab-80c7-c248371922a7
		summarizeBy: none
		sourceColumn: movement_status

		annotation SummarizationSetBy = Automatic

	column payee_id
		dataType: string
		lineageTag: 2b2c3a56-f074-450c-bca7-405ef3c5b9e4
		summarizeBy: none
		sourceColumn: payee_id

		annotation SummarizationSetBy = Automatic

	column initiated_type
		dataType: string
		lineageTag: 7212ceae-b271-428e-8741-f7aa7630c2ea
		summarizeBy: none
		sourceColumn: initiated_type

		annotation SummarizationSetBy = Automatic

	column entered_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: defe8dc0-a917-400e-8017-5c5347c3fb4e
		summarizeBy: none
		sourceColumn: entered_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column movement_id
		dataType: string
		lineageTag: 3ac4c678-3d1c-4c3b-945d-92cdff20c650
		summarizeBy: none
		sourceColumn: movement_id

		annotation SummarizationSetBy = Automatic

	partition callins = m
		mode: import
		source =
				let
				    Source = Sql.Database("bl-appdb", "lme"),
				    dbo_callin = Source{[Schema="dbo",Item="callin"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_callin,{"entered_by", "entered_date", "movement_status", "payee_id", "initiated_type", "movement_id"}),
				    #"Filtered callins on or after RefreshCutOffDate" = Table.SelectRows(#"Removed Other Columns", each [entered_date] >= RefreshCutOffDate),
				    #"Inserted Time" = Table.AddColumn(#"Filtered callins on or after RefreshCutOffDate", "Time", each DateTime.Time([entered_date]), type time),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Time",{{"Time", "entered_time"}}),
				    #"Extracted Date" = Table.TransformColumns(#"Renamed Columns",{{"entered_date", DateTime.Date, type date}}),
				    #"Appended Query" = Table.Combine({#"Extracted Date", historic_callins})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

