table customer
	lineageTag: ac556894-2d76-4b17-a7fb-97f07f433a0e

	column address1
		dataType: string
		lineageTag: 405261b4-5527-4b91-a36b-f9098cc3987b
		summarizeBy: none
		sourceColumn: address1

		annotation SummarizationSetBy = Automatic

	column average_pay_days
		dataType: double
		lineageTag: cbc3ba3d-6291-49ff-870c-15f96efe8933
		summarizeBy: sum
		sourceColumn: average_pay_days

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bill_due_days
		dataType: int64
		formatString: 0
		lineageTag: 35353f72-9792-472a-a60e-ad7993b70c17
		summarizeBy: sum
		sourceColumn: bill_due_days

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: a5f07047-614b-4898-8889-d73fe2d4e180
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column city_id
		dataType: int64
		formatString: 0
		lineageTag: ee772063-c592-457f-aa6b-4afef607f479
		summarizeBy: sum
		sourceColumn: city_id

		annotation SummarizationSetBy = Automatic

	column credit_limit
		dataType: double
		lineageTag: 88053ca8-8607-4de6-b5f1-f400fc8cd0b5
		summarizeBy: sum
		sourceColumn: credit_limit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column credit_status
		dataType: string
		lineageTag: 7472fbe3-da0f-4a08-8048-ea39ea9845a8
		summarizeBy: none
		sourceColumn: credit_status

		annotation SummarizationSetBy = Automatic

	column d_and_b_code
		dataType: string
		lineageTag: b2b59c0c-b8fe-4bdf-bf51-6174e7065e34
		summarizeBy: none
		sourceColumn: d_and_b_code

		annotation SummarizationSetBy = Automatic

	column d_and_b_number
		dataType: string
		lineageTag: 5d5ab538-2945-401b-92e4-8b2227de1f1c
		summarizeBy: none
		sourceColumn: d_and_b_number

		annotation SummarizationSetBy = Automatic

	column tax_id
		dataType: string
		lineageTag: d43b519f-b773-4aa4-a68e-a4c83eda6838
		summarizeBy: none
		sourceColumn: tax_id

		annotation SummarizationSetBy = Automatic

	column entered_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4452d5a4-02e8-43f0-9ec8-633ab461e62a
		summarizeBy: none
		sourceColumn: entered_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column id
		dataType: string
		lineageTag: 50d07ea9-4884-4dc2-87b2-29bd78afcc3b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: string
		lineageTag: 5a97dd9d-0467-4607-8ab4-939aafd62d9a
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 8190aad3-fae7-4f38-8aa3-1d1836e0e17d
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 8cd09e1a-840c-485b-9d66-026f44c1e69b
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column name
		dataType: string
		lineageTag: a42806e3-c262-4ebf-9882-9cc989fec2f0
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column prev_code
		dataType: string
		lineageTag: 428e0960-1dff-4d4d-b5e8-4137055a054e
		summarizeBy: none
		sourceColumn: prev_code

		annotation SummarizationSetBy = Automatic

	column salesperson_id
		dataType: string
		lineageTag: a047402b-f6d8-47c2-a267-1b1341972b22
		summarizeBy: none
		sourceColumn: salesperson_id

		annotation SummarizationSetBy = Automatic

	column state_id
		dataType: string
		lineageTag: 5d2c5dad-4195-413b-abf2-b5609130a312
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: string
		lineageTag: 401508b0-b270-48c6-a47a-f942a3308061
		summarizeBy: none
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column zone_id
		dataType: string
		lineageTag: 64b1f733-d375-4436-84bb-ed1bbac6aa64
		summarizeBy: none
		sourceColumn: zone_id

		annotation SummarizationSetBy = Automatic

	column contract_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8fa99a42-a5f4-4b86-a7a4-5d404ca5bd0e
		summarizeBy: none
		sourceColumn: contract_date

		annotation SummarizationSetBy = Automatic

	partition customer = m
		mode: import
		source =
				let
				    Source = Sql.Database("bl-appdb", "lme"),
				    dbo_customer = Source{[Schema="dbo",Item="customer"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_customer,{"company_id", "activity_count", "activity_start_date", "add_empty_distance_occ", "add_finance_charge", "address2", "allow_inc_in_frt", "auto_rate", "available_template", "average_bill", "average_bill_c", "average_bill_d", "average_bill_n", "average_bill_r", "balance", "balance_c", "balance_d", "balance_n", "balance_r", "benchmark_ctg_uid", "benchmark_tar_uid", "bill_format_flag", "bill_template", "bill_transfer_when", "billed_loads", "blanket_buy_tariff_id", "blanket_sell_tariff_id", "bl_logo", "bl_logo_name", "bridge_id", "brokerage_filter", "business_hours", "business_number", "buy_tariff_id", "category", "cert_of_ins_date", "charge_detention", "chassis_chargeby", "chassis_freedays", "chassis_rate", "chassis_rate_c", "chassis_rate_d", "chassis_rate_n", "chassis_rate_r", "coll_thresh_pd1", "coll_thresh_pd1_c", "coll_thresh_pd1_d", "coll_thresh_pd1_n", "coll_thresh_pd1_r", "coll_thresh_pd2", "coll_thresh_pd2_c", "coll_thresh_pd2_d", "coll_thresh_pd2_n", "coll_thresh_pd2_r", "coll_thresh_pd3", "coll_thresh_pd3_c", "coll_thresh_pd3_d", "coll_thresh_pd3_n", "coll_thresh_pd3_r", "coll_thresh_pd4", "coll_thresh_pd4_c", "coll_thresh_pd4_d", "coll_thresh_pd4_n", "coll_thresh_pd4_r", "collections_id", "collections_ok", "confidence_level", "container_chargeby", "container_freedays", "container_rate", "container_rate_c", "container_rate_d", "container_rate_n", "container_rate_r", "contract_cbc", "contract_ccc", "contract_gbc", "contract_gcc", "contract_sbc", "contract_scc", "controlling_carrier_code", "conversion_date", "cost_ctg_uid", "cost_tar_uid", "covered_template", "cp_logo", "cp_logo_name", "credit_application", "credit_check_date", "credit_limit_c", "credit_limit_d", "credit_limit_n", "credit_limit_r", "credit_warning_pct", "ctg_uid", "currency_type", "cust_stmt_template", "d_and_b_date", "days_between_calls", "deadhead_target", "ded_last_fixed_cost_billdt", "dedicated_cycle", "dedicated_revenue_code_id", "dedicated_seg_alloc_code", "dedicated_start_day", "dedicated_template", "def_rate_confirm_temp", "delivered_template", "departure_date_at", "distance_method", "distance_profile", "distance_source", "distance_type", "driver_load", "empty_distance_charge_id", "empty_distance_rate", "enable_notifications", "enforce_dep_dates", "excise_taxable", "expected_close", "extend_rates", "factor_percent", "factor_receivables", "factoring_id", "fak_profile_id", "fourkites_customer_id", "fuel_amount", "fuel_base_price", "fuel_credit", "fuel_method", "fuel_percent", "fuel_price_region", "fuel_surcharge_id", "fuel_surchg_enddt", "fuel_surchg_strtdt", "fuel_variance", "global_detention", "google_place_id", "gp_exclude", "gp_exported", "grace_period", "high_balance", "high_balance_c", "high_balance_d", "high_balance_n", "high_balance_r", "include_by_date", "include_empty_distance", "include_fuel_surcharge", "include_split_point", "is_consignee", "is_distribution_center", "is_drop_yard", "is_geocoded", "is_pallets_required", "is_shipper", "is_trailer_pool_required", "jaguar_id", "last_bill_date", "last_fin_charge_dt", "last_pay_date", "last_ship_date", "location_id", "macropoint_requestor_id", "main_phone", "manual_exchange", "mark_plan_id", "max_pay_percent", "misc_bill_template", "monthly_order_goal", "motor_carrier_id", "next_call_date", "next_rec_call", "nxt_action_code_id", "nxt_action_date", "operations_user", "order_count", "order_detail_at", "order_start_date", "p44_profile_id", "paid_loads", "pay_days_date", "pay_days_orders", "payee_id", "pd0_alert", "pd1_np_auto", "pd1_sp_auto", "pd1_sp_thresh", "pd1_sp_thresh_c", "pd1_sp_thresh_d", "pd1_sp_thresh_n", "pd1_sp_thresh_r", "pd2_np_auto", "pd2_sp_auto", "pd2_sp_thresh", "pd2_sp_thresh_c", "pd2_sp_thresh_d", "pd2_sp_thresh_n", "pd2_sp_thresh_r", "pd3_np_auto", "pd3_sp_auto", "pd3_sp_thresh", "pd3_sp_thresh_c", "pd3_sp_thresh_d", "pd3_sp_thresh_n", "pd3_sp_thresh_r", "pd4_np_auto", "pd4_sp_auto", "pd4_sp_thresh", "pd4_sp_thresh_c", "pd4_sp_thresh_d", "pd4_sp_thresh_n", "pd4_sp_thresh_r", "plc_uid", "post_summary_dtl", "potential", "potential_c", "potential_d", "potential_n", "potential_r", "primary_agency", "primary_commodity_id", "primary_contact", "primary_sort", "primary_trailer_type", "print_containers", "progress_template", "prospect_type_id", "quebec_number", "quote_days_to_expire", "rate_override_nmfc_code", "reassign_profile_id", "rec_call_days", "remarks", "revenue", "revenue_c", "revenue_d", "revenue_n", "revenue_r", "revenue_start_date", "sales_manager_id", "sales_status_id", "search_city", "search_state_id", "search_zip_code", "secondary_sort", "sell_tariff_id", "service_fail_cons", "service_fail_drop", "service_fail_pick", "service_fail_ship", "service_failures", "service_failures_review", "sic_code", "start_date", "summary_billing", "summary_template", "tar_uid", "target_profit", "tenfour_customer_id", "type_of", "use_local_mile", "vm_part_update", "waterfall_lead_time", "waterfall_notify_email", "waterfall_process", "website_url", "wf_queue", "require_tracking", "required_vendor", "disable_automatic_tracking", "tracking_hours_prior", "bankyacct", "bankyname", "bankyphone", "bankycsz", "bankyadd", "wf_bwop", "wf_auto_renbill", "wf_autobill", "wf_ab_po_chk", "display_ysplit_stops", "waterfall_auto_route_guides", "display_eta", "cust_requestor_load_id", "trimble_place_id", "is_intercompany", "ic_company_id", "shipment_ident_type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"dot_number", "tax_id"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"entered_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

