table daily_number_override
	lineageTag: 45fdfe2a-47d4-4b73-9ae1-78f6485bc2ab

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: ae92692c-fd61-4987-b864-f285dc43a9fb
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: a7804ea9-83e9-4dc2-80c4-110de2aa952a
			defaultHierarchy: LocalDateTable_1079eecc-82a9-4100-9db0-4cfb5a51a4a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Margin Number'
		dataType: int64
		formatString: 0
		lineageTag: aab2f59d-8899-4b88-a6b7-6b0c555a2ca8
		summarizeBy: sum
		sourceColumn: Margin Number

		annotation SummarizationSetBy = Automatic

	partition daily_number_override = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/SalesGoals/Shared%20Documents/Sales%20Goals.xlsx"), null, true),
				    daily_number_override_Table = Source{[Item="daily_number_override",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(daily_number_override_Table,{{"Month", type date}, {"Margin Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

