table employees
	lineageTag: 0af26c3a-e69f-4de1-a4d5-3c1431c72fc3

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 595a83f4-be85-4628-930e-9705642f27be
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 319cc0a3-0162-40a8-b1d2-bcd25493776b
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column 'Hire Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 84ac5d0f-335d-42ba-8fcf-7b863236da2d
		summarizeBy: none
		sourceColumn: Hire Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Termination Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ba39365c-82ec-407a-9eb9-89361d5c4c5e
		summarizeBy: none
		sourceColumn: Termination Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Reporting to'
		dataType: string
		lineageTag: f27d247f-08ca-4751-a124-204ffc2f3c93
		summarizeBy: none
		sourceColumn: Reporting to

		annotation SummarizationSetBy = Automatic

	column 'Termination Type'
		dataType: string
		lineageTag: 8cfad7d5-e787-48ef-a301-68652a5a0c11
		summarizeBy: none
		sourceColumn: Termination Type

		annotation SummarizationSetBy = Automatic

	column 'Termination Reason'
		dataType: string
		lineageTag: 4a2c042b-99f5-4586-836c-63599438893b
		summarizeBy: none
		sourceColumn: Termination Reason

		annotation SummarizationSetBy = Automatic

	column 'Regrettable or non- regrettable'
		dataType: string
		lineageTag: d909b33d-1979-4c69-838e-94b9c648bc64
		summarizeBy: none
		sourceColumn: Regrettable or non- regrettable

		annotation SummarizationSetBy = Automatic

	column 'Job Title'
		dataType: string
		lineageTag: c51d0d6d-9f77-4742-a0c6-2e2c92baae4b
		summarizeBy: none
		sourceColumn: Job Title

		annotation SummarizationSetBy = Automatic

	column 'McLeod User Code'
		dataType: string
		lineageTag: 968822be-0c75-4e31-b879-be73a12a3838
		summarizeBy: none
		sourceColumn: McLeod User Code

		annotation SummarizationSetBy = Automatic

	column 'McLeod Salesperson Code'
		dataType: string
		lineageTag: ce9790e5-0c2b-48da-9045-15f6d6db0568
		summarizeBy: none
		sourceColumn: McLeod Salesperson Code

		annotation SummarizationSetBy = Automatic

	column 'Work Email'
		dataType: string
		lineageTag: 800c7104-8411-4729-b462-89a6fdd48e07
		summarizeBy: none
		sourceColumn: Work Email

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: 98f6287c-d0d0-468a-ae10-d8249190eafc
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column 'users.revenue_code_id'
		dataType: string
		lineageTag: dabc049a-562c-4e2c-be44-78e318143a31
		summarizeBy: none
		sourceColumn: users.revenue_code_id

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: 047f73b6-c8df-46ea-9cab-1891d918e241
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	partition employees = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Bamboo/Employees.xlsx"), null, true),
				    employees_Table = Source{[Item="employees",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(employees_Table,{{"ID", Int64.Type}, {"Name", type text}, {"Prefered Name", type text}, {"Hire Date", type date}, {"Termination Date", type any}, {"Reporting to", type text}, {"Termination Type", type text}, {"Termination Reason", type text}, {"Regrettable or non- regrettable", type text}, {"Job Title", type text}, {"McLeod User Code", type text}, {"McLeod Salesperson Code", type text}, {"Work Email", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Name", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Name.1", "Name.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Name.1", type text}, {"Name.2", type text}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type1",{{"Name.2", Text.Trim, type text}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Trimmed Text", "First Name", each if [Prefered Name] = null then [Name.2] else [Prefered Name]),
				    #"Merged Columns" = Table.CombineColumns(#"Added Conditional Column",{"First Name", "Name.1"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Name"),
				    #"Removed Columns" = Table.RemoveColumns(#"Merged Columns",{"Name.2", "Prefered Name"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","0000-00-00","",Replacer.ReplaceValue,{"Termination Date"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value",{{"Termination Date", type date}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type2","Development Team Sales","Development Team",Replacer.ReplaceText,{"Division"}),
				    #"Trimmed Text1" = Table.TransformColumns(#"Replaced Value1",{{"McLeod User Code", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text1",{{"McLeod User Code", Text.Upper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Uppercased Text", {"McLeod User Code"}, users, {"id"}, "users", JoinKind.LeftOuter),
				    #"Expanded users" = Table.ExpandTableColumn(#"Merged Queries", "users", {"revenue_code_id"}, {"users.revenue_code_id"})
				in
				    #"Expanded users"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

