table highway_onboarded
	lineageTag: c96b9197-30a3-4f50-967c-56bd0bcb42ea

	column completed_at
		dataType: dateTime
		formatString: Short Date
		lineageTag: c1df0a21-fbb6-40e1-b78d-59d1ebb7b39b
		summarizeBy: none
		sourceColumn: completed_at

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Dispatcher
		dataType: string
		lineageTag: d8cf10d6-7d39-4bfc-8040-5122792e064a
		summarizeBy: none
		sourceColumn: Dispatcher

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: c49b4bb2-6aab-41fc-a9e0-c20c749bedb5
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column count
		dataType: int64
		formatString: 0
		lineageTag: 44d79304-e3b8-4f27-ae77-39378447397c
		summarizeBy: sum
		sourceColumn: count

		annotation SummarizationSetBy = Automatic

	column 'dispatcher_key.Team'
		dataType: string
		lineageTag: 62f7936c-bc90-4943-8700-594ccd363690
		summarizeBy: none
		sourceColumn: dispatcher_key.Team

		annotation SummarizationSetBy = Automatic

	partition highway_onboarded = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/bridge_iq/Data%20Sets/Highway%20Onbaorded.xlsx"), null, true),
				    #"Connection Count per User-2023-_Sheet" = Source{[Item="Connection Count per User-2024-",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Connection Count per User-2023-_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"completed_at", type date}, {"id", Int64.Type}, {"first_name", type text}, {"last_name", type text}, {"email", type text}, {"count", Int64.Type}}),
				    #"Merged Columns" = Table.CombineColumns(#"Changed Type",{"first_name", "last_name"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Merged"),
				    #"Renamed Columns" = Table.RenameColumns(#"Merged Columns",{{"Merged", "Dispatcher"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"id"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"completed_at", type date}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","Robert M. Briede Jr.","ROBERT BRIEDE",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Ty Grimes","Tyler Grimes",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Stanislaw Kasmer","Stan Kasmer",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Katie Palmer","Katherine Palmer",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Matt Singler","Matthew Singler",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Kathryn E Kaczmarek","Katie Kaczmarek",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Uppercased Text" = Table.TransformColumns(#"Replaced Value5",{{"Dispatcher", Text.Upper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Uppercased Text", {"Dispatcher"}, dispatcher_key, {"Dispatcher Name"}, "dispatcher_key", JoinKind.LeftOuter),
				    #"Expanded dispatcher_key" = Table.ExpandTableColumn(#"Merged Queries", "dispatcher_key", {"Team"}, {"dispatcher_key.Team"}),
				    #"Sorted Rows" = Table.Sort(#"Expanded dispatcher_key",{{"completed_at", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

