table movements
	lineageTag: cae9df8f-1cd9-408a-8fa4-aab0f7d1154d

	column 'Brokerage Status'
		dataType: string
		lineageTag: ea49bc2b-7634-4de6-af0d-d23cd04d7e89
		summarizeBy: none
		sourceColumn: Brokerage Status

		annotation SummarizationSetBy = Automatic

	column 'Delivery Actual Arrival Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2a9b9d8-e393-47a1-b98e-007579abf8aa
		summarizeBy: none
		sourceColumn: Delivery Actual Arrival Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Actual Arrival Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5b27ea37-5b17-4bcd-8ced-8201c0db89ca
		summarizeBy: none
		sourceColumn: Delivery Actual Arrival Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Delivery Actual Departure Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 86ab6059-c350-4ff4-8ad4-b9cb021b3a4f
		summarizeBy: none
		sourceColumn: Delivery Actual Departure Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Delivery Actual Departure Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: ba46cf7e-ba54-4f9a-b531-6393cb48c399
		summarizeBy: none
		sourceColumn: Delivery Actual Departure Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Move Status'
		dataType: string
		lineageTag: 35924aa3-592a-456f-8b0b-4bffff5931d2
		summarizeBy: none
		sourceColumn: Move Status

		annotation SummarizationSetBy = Automatic

	column 'Movement ID'
		dataType: int64
		formatString: 0
		lineageTag: c3f310e7-68d3-4e64-9411-36c7525db9f1
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 86732f5e-75d0-43c9-b50e-7b300bdaf8e3
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Ship Actual Arrival Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84910b8d-7ee4-4a63-875c-11dabd5ef0b0
		summarizeBy: none
		sourceColumn: Ship Actual Arrival Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Actual Arrival Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: b12373c6-e271-4107-8846-4c5ebdd992eb
		summarizeBy: none
		sourceColumn: Ship Actual Arrival Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Ship Actual Departure Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b18a5a68-b65a-429c-9878-59eb5b088ee8
		summarizeBy: none
		sourceColumn: Ship Actual Departure Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Actual Departure Date Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 20b6ff09-7dc2-41b1-9b2b-9536a2d38b1a
		summarizeBy: none
		sourceColumn: Ship Actual Departure Date Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Carrier ID'
		dataType: string
		lineageTag: bbae78c8-1097-4bbd-9290-f714df0ba2bf
		summarizeBy: none
		sourceColumn: Carrier ID

		annotation SummarizationSetBy = Automatic

	column 'Projected Total Carrier Pay'
		dataType: double
		lineageTag: cec8dfcf-0224-49f5-9d29-9e917d665669
		summarizeBy: sum
		sourceColumn: Projected Total Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Consignee City'
		dataType: string
		lineageTag: 8bce8dfe-a7a5-4fb6-ab5e-682d47f63a1a
		summarizeBy: none
		sourceColumn: Consignee City

		annotation SummarizationSetBy = Automatic

	column 'Consignee State'
		dataType: string
		lineageTag: bef42537-3c48-4d5c-82c4-bd44e75f02d8
		summarizeBy: none
		sourceColumn: Consignee State

		annotation SummarizationSetBy = Automatic

	column 'Consignee Zip'
		dataType: string
		lineageTag: f204b303-1c32-45c9-ad6c-5f76c29258e4
		summarizeBy: none
		sourceColumn: Consignee Zip

		annotation SummarizationSetBy = Automatic

	column 'Shipper City'
		dataType: string
		lineageTag: 057d3803-af11-49f8-8b2c-566dec84f89d
		summarizeBy: none
		sourceColumn: Shipper City

		annotation SummarizationSetBy = Automatic

	column 'Shipper State'
		dataType: string
		lineageTag: c19b1ffc-e85c-4c6c-9556-38277143699a
		summarizeBy: none
		sourceColumn: Shipper State

		annotation SummarizationSetBy = Automatic

	column 'Shipper Zip'
		dataType: string
		lineageTag: e4dd531c-3bb7-4ae9-833c-df016b3168ca
		summarizeBy: none
		sourceColumn: Shipper Zip

		annotation SummarizationSetBy = Automatic

	column 'Consignee 3 Digit Zip'
		dataType: string
		lineageTag: 84a0e297-2139-4751-9a5c-9975e2980f66
		summarizeBy: none
		sourceColumn: Consignee 3 Digit Zip

		annotation SummarizationSetBy = Automatic

	column 'Shipper 3 Digit Zip'
		dataType: string
		lineageTag: 506e7b8a-24af-4fbd-975c-12a50ea931cc
		summarizeBy: none
		sourceColumn: Shipper 3 Digit Zip

		annotation SummarizationSetBy = Automatic

	column 'Max Pay'
		dataType: double
		lineageTag: ad84a0d5-6338-4426-a4bc-c7dc80b7f4a2
		summarizeBy: sum
		sourceColumn: Max Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Projected Freight Carrier Pay'
		dataType: double
		lineageTag: 0326689d-0b60-4b97-a44d-b0c683d976d5
		summarizeBy: sum
		sourceColumn: Projected Freight Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Projected Other Carrier Pay'
		dataType: double
		lineageTag: e0ffefe6-9f0c-4a0d-b663-5986aa276120
		summarizeBy: sum
		sourceColumn: Projected Other Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Target Pay'
		dataType: double
		lineageTag: ceed4756-6382-4ed3-a359-99ec977d0172
		summarizeBy: sum
		sourceColumn: Target Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dispatcher Id'
		dataType: string
		lineageTag: 0802d286-e142-4336-bbd6-93589e459fbb
		summarizeBy: none
		sourceColumn: Dispatcher Id

		annotation SummarizationSetBy = Automatic

	column DNC
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e8e9b516-094a-4927-bca0-9f120c9c20c0
		summarizeBy: none
		sourceColumn: DNC

		annotation SummarizationSetBy = Automatic

	partition movements = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Databases("bl-mcbiserver", [TypedMeasureColumns=true, Implementation="2.0"]),
				    McLeodIQ_2019_Powerbroker = Source{[Name="McLeodIQ_2019_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker1 = McLeodIQ_2019_Powerbroker{[Id="McLeodIQ_Powerbroker"]}[Data],
				    McLeodIQ_Powerbroker2 = McLeodIQ_Powerbroker1{[Id="McLeodIQ_Powerbroker"]}[Data],
				    #"Added Items" = Cube.Transform(McLeodIQ_Powerbroker2,
				        {
				            {Cube.AddAndExpandDimensionColumn, "[Order]", {"[Order].[Brokerage Status].[Brokerage Status]", "[Order].[Delivery Actual Arrival Date].[Delivery Actual Arrival Date]", "[Order].[Delivery Actual Arrival Date Time].[Delivery Actual Arrival Date Time]", "[Order].[Delivery Actual Departure Date].[Delivery Actual Departure Date]", "[Order].[Delivery Actual Departure Date Time].[Delivery Actual Departure Date Time]", "[Order].[Dispatcher].[Dispatcher]", "[Order].[Move Status].[Move Status]", "[Order].[Movement ID].[Movement ID]", "[Order].[Order ID].[Order ID]", "[Order].[Ship Actual Arrival Date].[Ship Actual Arrival Date]", "[Order].[Ship Actual Arrival Date Time].[Ship Actual Arrival Date Time]", "[Order].[Ship Actual Departure Date].[Ship Actual Departure Date]", "[Order].[Ship Actual Departure Date Time].[Ship Actual Departure Date Time]"}, {"Order.Brokerage Status", "Order.Delivery Actual Arrival Date", "Order.Delivery Actual Arrival Date Time", "Order.Delivery Actual Departure Date", "Order.Delivery Actual Departure Date Time", "Order.Dispatcher", "Order.Move Status", "Order.Movement ID", "Order.Order ID", "Order.Ship Actual Arrival Date", "Order.Ship Actual Arrival Date Time", "Order.Ship Actual Departure Date", "Order.Ship Actual Departure Date Time"}},
				            {Cube.AddAndExpandDimensionColumn, "[Carrier]", {"[Carrier].[Carrier ID].[Carrier ID]"}, {"Carrier.Carrier ID"}},
				            {Cube.AddMeasureColumn, "Projected Total Carrier Pay", "[Measures].[Projected Total Carrier Pay]"},
				            {Cube.AddAndExpandDimensionColumn, "[Consignee]", {"[Consignee].[Consignee.Location City].[Consignee.Location City]", "[Consignee].[Consignee.Location State].[Consignee.Location State]", "[Consignee].[Consignee.Location Zip].[Consignee.Location Zip]"}, {"Consignee.Consignee.Location City", "Consignee.Consignee.Location State", "Consignee.Consignee.Location Zip"}},
				            {Cube.AddAndExpandDimensionColumn, "[Shipper]", {"[Shipper].[Shipper.Location City].[Shipper.Location City]", "[Shipper].[Shipper.Location State].[Shipper.Location State]", "[Shipper].[Shipper.Location Zip].[Shipper.Location Zip]"}, {"Shipper.Shipper.Location City", "Shipper.Shipper.Location State", "Shipper.Shipper.Location Zip"}},
				            {Cube.AddMeasureColumn, "Max Pay", "[Measures].[Max Pay]"},
				            {Cube.AddMeasureColumn, "Projected Freight Carrier Pay", "[Measures].[Projected Freight Carrier Pay]"},
				            {Cube.AddMeasureColumn, "Projected Other Carrier Pay", "[Measures].[Projected Other Carrier Pay]"},
				            {Cube.AddMeasureColumn, "Target Pay", "[Measures].[Target Pay]"}
				        }),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Items",{{"Order.Brokerage Status", "Brokerage Status"}, {"Order.Delivery Actual Arrival Date", "Delivery Actual Arrival Date"}, {"Order.Delivery Actual Arrival Date Time", "Delivery Actual Arrival Date Time"}, {"Order.Delivery Actual Departure Date", "Delivery Actual Departure Date"}, {"Order.Delivery Actual Departure Date Time", "Delivery Actual Departure Date Time"}, {"Order.Dispatcher", "Dispatcher"}, {"Order.Move Status", "Move Status"}, {"Order.Movement ID", "Movement ID"}, {"Order.Order ID", "Order ID"}, {"Order.Ship Actual Arrival Date", "Ship Actual Arrival Date"}, {"Order.Ship Actual Arrival Date Time", "Ship Actual Arrival Date Time"}, {"Order.Ship Actual Departure Date", "Ship Actual Departure Date"}, {"Order.Ship Actual Departure Date Time", "Ship Actual Departure Date Time"}, {"Carrier.Carrier ID", "Carrier ID"}, {"Consignee.Consignee.Location City", "Consignee City"}, {"Consignee.Consignee.Location State", "Consignee State"}, {"Consignee.Consignee.Location Zip", "Consignee Zip"}, {"Shipper.Shipper.Location City", "Shipper City"}, {"Shipper.Shipper.Location State", "Shipper State"}, {"Shipper.Shipper.Location Zip", "Shipper Zip"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Delivery Actual Arrival Date", type date}, {"Delivery Actual Arrival Date Time", type time}, {"Delivery Actual Departure Date", type date}, {"Delivery Actual Departure Date Time", type time}, {"Ship Actual Arrival Date", type date}, {"Ship Actual Arrival Date Time", type time}, {"Ship Actual Departure Date", type date}, {"Ship Actual Departure Date Time", type time}}),
				    #"Inserted First Characters" = Table.AddColumn(#"Changed Type", "First Characters", each Text.Start([Consignee Zip], 3), type text),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "Consignee 3 Digit Zip"}}),
				    #"Inserted First Characters1" = Table.AddColumn(#"Renamed Columns1", "First Characters", each Text.Start([Shipper Zip], 3), type text),
				    #"Renamed Columns2" = Table.RenameColumns(#"Inserted First Characters1",{{"First Characters", "Shipper 3 Digit Zip"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns2",{{"Movement ID", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type2", {"Movement ID"}, parade_orders, {"movement_id"}, "parade_orders", JoinKind.LeftOuter),
				    #"Expanded parade_orders" = Table.ExpandTableColumn(#"Merged Queries", "parade_orders", {"id"}, {"parade_orders.id"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Expanded parade_orders", "Dispatcher Id", each if [parade_orders.id] = null then [Dispatcher] else "parade"),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"Dispatcher", "parade_orders.id"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Removed Columns", {"Movement ID"}, dnc, {"DNC"}, "dnc", JoinKind.LeftOuter),
				    #"Expanded dnc" = Table.ExpandTableColumn(#"Merged Queries1", "dnc", {"DNC"}, {"dnc.DNC"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Expanded dnc", "DNC", each if [dnc.DNC] = null then false else true),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column1",{"dnc.DNC"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns1",{{"DNC", type logical}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type1", {"Movement ID"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

