table orders
	lineageTag: 616850d9-b6a2-4b0e-99f2-f3ebcab5b217

	column bill_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 19c8c8d1-414d-4777-afb3-afe8e8ac0cf4
		summarizeBy: none
		sourceColumn: bill_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column bill_distance
		dataType: double
		lineageTag: cd0b7e33-599c-4223-b831-792339ac1362
		summarizeBy: sum
		sourceColumn: bill_distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column billing_user_id
		dataType: string
		lineageTag: dddd2300-6977-4d12-8fc2-73a17faad6c3
		summarizeBy: none
		sourceColumn: billing_user_id

		annotation SummarizationSetBy = Automatic

	column blnum
		dataType: string
		lineageTag: 9a62a3bd-20f0-48c0-abe3-a02c955850a2
		summarizeBy: none
		sourceColumn: blnum

		annotation SummarizationSetBy = Automatic

	column bol_received
		dataType: string
		lineageTag: aec9fb56-65ea-40db-bd9b-63ffdea76b14
		summarizeBy: none
		sourceColumn: bol_received

		annotation SummarizationSetBy = Automatic

	column commodity
		dataType: string
		lineageTag: d7acb004-e01d-4766-a097-e9fabcf24a4f
		summarizeBy: none
		sourceColumn: commodity

		annotation SummarizationSetBy = Automatic

	column commodity_id
		dataType: string
		lineageTag: 19d6fe85-d8c4-418c-8047-dfb5c982e25f
		summarizeBy: none
		sourceColumn: commodity_id

		annotation SummarizationSetBy = Automatic

	column consignee_refno
		dataType: string
		lineageTag: 9d3dc956-e392-4b3c-bf5d-a2f8b579a141
		summarizeBy: none
		sourceColumn: consignee_refno

		annotation SummarizationSetBy = Automatic

	column consignee_stop_id
		dataType: string
		lineageTag: 0a885f73-200b-4372-b95f-857be338fc75
		summarizeBy: none
		sourceColumn: consignee_stop_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: a389d148-0c96-4c67-a170-9853c3955508
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column entered_user_id
		dataType: string
		lineageTag: 279e38e3-9eae-4e4d-8a17-21eb5ed9d914
		summarizeBy: none
		sourceColumn: entered_user_id

		annotation SummarizationSetBy = Automatic

	column equipment_type_id
		dataType: string
		lineageTag: 843075e8-bf8a-48ef-a5c0-d20cdb5bf2d6
		summarizeBy: none
		sourceColumn: equipment_type_id

		annotation SummarizationSetBy = Automatic

	column extra_deliveries
		dataType: int64
		formatString: 0
		lineageTag: cd596653-d7b6-4e0e-a54d-c3a6ded9a29e
		summarizeBy: sum
		sourceColumn: extra_deliveries

		annotation SummarizationSetBy = Automatic

	column extra_pickups
		dataType: int64
		formatString: 0
		lineageTag: 52b57ad3-2a00-4072-ae93-a0b46184f926
		summarizeBy: sum
		sourceColumn: extra_pickups

		annotation SummarizationSetBy = Automatic

	column freight_charge
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 721c0cee-da14-477d-ac49-a38b8c34c3b9
		summarizeBy: sum
		sourceColumn: freight_charge

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column hazmat
		dataType: string
		lineageTag: 094a66d8-43de-42f3-9204-bbd7cda021f0
		summarizeBy: none
		sourceColumn: hazmat

		annotation SummarizationSetBy = Automatic

	column hazmat_code
		dataType: string
		lineageTag: d80b6e92-703b-48f3-ad85-91fc22706e9c
		summarizeBy: none
		sourceColumn: hazmat_code

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: a6067274-d93c-481e-9248-e2fb8d480f7f
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column on_hold
		dataType: string
		lineageTag: e82559aa-6b31-4560-b852-4f186d7c03ef
		summarizeBy: none
		sourceColumn: on_hold

		annotation SummarizationSetBy = Automatic

	column operations_user
		dataType: string
		lineageTag: ab0c9eec-ff05-4521-9cd9-c72121526898
		summarizeBy: none
		sourceColumn: operations_user

		annotation SummarizationSetBy = Automatic

	column order_type_id
		dataType: string
		lineageTag: 21a4a619-7413-47d5-ac64-5e6985983238
		summarizeBy: none
		sourceColumn: order_type_id

		annotation SummarizationSetBy = Automatic

	column order_value
		dataType: double
		lineageTag: 0db44e6f-bce6-4c6b-b725-c23f330ff00b
		summarizeBy: sum
		sourceColumn: order_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ordered_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6308c6ae-434c-42be-865d-44cf9a7a7922
		summarizeBy: none
		sourceColumn: ordered_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column otherchargetotal
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ae28246c-66ca-4b52-8639-09304efac25e
		summarizeBy: sum
		sourceColumn: otherchargetotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column pieces
		dataType: int64
		lineageTag: 37c4e511-4f1f-499c-805b-89f9cb2693f9
		summarizeBy: sum
		sourceColumn: pieces

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column revenue_code_id
		dataType: string
		lineageTag: c523dabb-a0d1-4050-8f06-42d821cbe67e
		summarizeBy: none
		sourceColumn: revenue_code_id

		annotation SummarizationSetBy = Automatic

	column round_trip
		dataType: string
		lineageTag: 9c0a91ac-cb67-4e78-972e-d9d66e06c35d
		summarizeBy: none
		sourceColumn: round_trip

		annotation SummarizationSetBy = Automatic

	column shipper_stop_id
		dataType: string
		lineageTag: 50703542-3555-4232-b830-9422d7d7392a
		summarizeBy: none
		sourceColumn: shipper_stop_id

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: db059299-f288-4c03-ac92-ddbd2c74a1b1
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column subject_order_number
		dataType: string
		lineageTag: dd7c2755-13c9-43f4-bb58-a4fd2af765cd
		summarizeBy: none
		sourceColumn: subject_order_number

		annotation SummarizationSetBy = Automatic

	column temperature_max
		dataType: double
		lineageTag: 64082df9-8725-48e2-9948-c73ff825ab80
		summarizeBy: sum
		sourceColumn: temperature_max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column temperature_min
		dataType: double
		lineageTag: 1b20e0ef-c84d-49c9-bac9-a82215a79167
		summarizeBy: sum
		sourceColumn: temperature_min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weight
		dataType: double
		lineageTag: 568038e4-4c69-4f36-a9f4-63891bd81542
		summarizeBy: sum
		sourceColumn: weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_tonu
		dataType: string
		lineageTag: 6e8235a6-4c90-4323-9067-9d00747bebf6
		summarizeBy: none
		sourceColumn: is_tonu

		annotation SummarizationSetBy = Automatic

	column salesperson
		dataType: string
		lineageTag: 21fce3f1-f25f-40f1-a041-771bd1cd12bd
		summarizeBy: none
		sourceColumn: salesperson

		annotation SummarizationSetBy = Automatic

	column order_entered_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2e46c30c-d580-4752-853e-1606eacf7ad2
		summarizeBy: none
		sourceColumn: order_entered_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column shipper_city_name
		dataType: string
		lineageTag: 0480828e-28b9-48ba-bfe0-f2afb352f63b
		summarizeBy: none
		sourceColumn: shipper_city_name

		annotation SummarizationSetBy = Automatic

	column shipper_location_name
		dataType: string
		lineageTag: bbb71902-1efc-4dd0-81df-56926517c566
		summarizeBy: none
		sourceColumn: shipper_location_name

		annotation SummarizationSetBy = Automatic

	column shipper_sched_early_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 597c5c6b-67c0-4e83-af5e-35a3c066afd4
		summarizeBy: none
		sourceColumn: shipper_sched_early_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column shipper_sched_late_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fa2c7349-7227-48bd-ba4f-0390562db6d1
		summarizeBy: none
		sourceColumn: shipper_sched_late_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column shipper_state
		dataType: string
		lineageTag: 108d5112-70f3-40ac-abca-96c94f9e34d6
		summarizeBy: none
		sourceColumn: shipper_state

		annotation SummarizationSetBy = Automatic

	column shipper_zip_code
		dataType: string
		lineageTag: 349b3c2f-9f80-47d7-9e13-6eedf85f4e4c
		summarizeBy: none
		sourceColumn: shipper_zip_code

		annotation SummarizationSetBy = Automatic

	column shipper_sched_early_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 360123df-4f90-4e32-b59a-5f8830a286a4
		summarizeBy: none
		sourceColumn: shipper_sched_early_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column shipper_sched_late_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: c9b31a67-2385-4d30-bc4c-17f8ec0c9cd3
		summarizeBy: none
		sourceColumn: shipper_sched_late_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column consignee_city_id
		dataType: int64
		formatString: 0
		lineageTag: b45041d8-e36f-4201-bc3a-266910745efb
		summarizeBy: sum
		sourceColumn: consignee_city_id

		annotation SummarizationSetBy = Automatic

	column consignee_city_name
		dataType: string
		lineageTag: 358eefa8-57ae-444c-a755-20d529475d99
		summarizeBy: none
		sourceColumn: consignee_city_name

		annotation SummarizationSetBy = Automatic

	column consignee_location_name
		dataType: string
		lineageTag: 1f9b5455-2755-4305-af03-09168ca94a44
		summarizeBy: none
		sourceColumn: consignee_location_name

		annotation SummarizationSetBy = Automatic

	column consignee_sched_early_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4f89daa2-5d28-4b04-9ff9-07ea39716239
		summarizeBy: none
		sourceColumn: consignee_sched_early_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column consignee_sched_late_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 58875f0a-4cc3-40fd-9177-0ad9069ec8bc
		summarizeBy: none
		sourceColumn: consignee_sched_late_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column consignee_state
		dataType: string
		lineageTag: 768b74e2-6bf5-4f04-a57a-a443ce44a309
		summarizeBy: none
		sourceColumn: consignee_state

		annotation SummarizationSetBy = Automatic

	column consignee_zip_code
		dataType: string
		lineageTag: 9d568ea3-9585-4ae0-92e4-4f9c6c39ca69
		summarizeBy: none
		sourceColumn: consignee_zip_code

		annotation SummarizationSetBy = Automatic

	column consignee_sched_early_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6c4583d1-3cf9-4dda-8f1f-afb92533e941
		summarizeBy: none
		sourceColumn: consignee_sched_early_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column consignee_sched_late_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 77829831-f6d3-4f22-affc-4c850673ec6c
		summarizeBy: none
		sourceColumn: consignee_sched_late_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column shipper_3_digit_zip_code
		dataType: string
		lineageTag: cd907732-0003-496f-8c3e-cad726c16e70
		summarizeBy: none
		sourceColumn: shipper_3_digit_zip_code

		annotation SummarizationSetBy = Automatic

	column consignee_3_digit_zip_code
		dataType: string
		lineageTag: 3a0c6f92-1467-4124-b194-dc824374dc66
		summarizeBy: none
		sourceColumn: consignee_3_digit_zip_code

		annotation SummarizationSetBy = Automatic

	column lane
		dataType: string
		lineageTag: 277452ed-3e1e-495b-9fc0-6c0ad261a194
		summarizeBy: none
		sourceColumn: lane

		annotation SummarizationSetBy = Automatic

	column pallets_how_many
		dataType: int64
		formatString: 0
		lineageTag: d47d3435-5b10-4b3e-81ec-8fa6ac0c0374
		summarizeBy: sum
		sourceColumn: pallets_how_many

		annotation SummarizationSetBy = Automatic

	column bol_recv_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5c996698-e217-42d1-a421-9c83702af551
		summarizeBy: none
		sourceColumn: bol_recv_date

		variation Variation
			isDefault
			relationship: 9ee75757-9d7d-4c5d-bf3a-b3a04654cfd0
			defaultHierarchy: LocalDateTable_2a3d8ac1-aff0-4e32-a507-1f99a679e947.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ordered_method
		dataType: string
		lineageTag: fa046798-ce0f-46fb-9ce8-e17eb8df4839
		summarizeBy: none
		sourceColumn: ordered_method

		annotation SummarizationSetBy = Automatic

	column brlo_commission_paid
		dataType: double
		lineageTag: 16d72d2f-b03c-4d27-8da4-0921d7e86558
		summarizeBy: sum
		sourceColumn: brlo_commission_paid

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column brlo_commission_status
		dataType: string
		lineageTag: c68a57d5-7cf3-4d7d-a780-d906d63b1b05
		summarizeBy: none
		sourceColumn: brlo_commission_status

		annotation SummarizationSetBy = Automatic

	column brlo_commission_paid_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: e66c2ba6-5658-4f1b-a362-18b65b948797
		summarizeBy: none
		sourceColumn: brlo_commission_paid_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column linear_feet_brlo
		dataType: int64
		formatString: 0
		lineageTag: 2239afc2-ab9b-45f6-ba6c-af3f24ac0dbc
		summarizeBy: sum
		sourceColumn: linear_feet_brlo

		annotation SummarizationSetBy = Automatic

	partition orders = m
		mode: import
		source =
				let
				    Source = Sql.Database("bl-appdb", "lme"),
				    dbo_orders = Source{[Schema="dbo",Item="orders"]}[Data],
				    //Filtered Orders on or after RefreshCutOFfDate
				    #"Filtered Rows" = Table.SelectRows(dbo_orders, each [ordered_date] >= RefreshCutOffDate),
				    //Start General Data Transformation
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"bill_date", "bill_distance", "billing_user_id", "blnum", "bol_received", "bol_recv_date", "commodity", "commodity_id", "consignee_refno", "consignee_stop_id", "customer_id", "entered_user_id", "equipment_type_id", "extra_deliveries", "extra_pickups", "freight_charge", "hazmat", "hazmat_code", "id", "on_hold", "operations_user", "order_type_id", "order_value", "ordered_date", "ordered_method", "otherchargetotal", "pallets_how_many", "pieces", "revenue_code_id", "round_trip", "shipper_stop_id", "status", "subject_order_number", "temperature_max", "temperature_min", "weight", "is_tonu", "salesperson", "linear_feet_brlo", "brlo_commission_paid", "brlo_commission_status", "brlo_commission_paid_date"}),
				    #"Inserted order_entered_time" = Table.AddColumn(#"Removed Other Columns", "order_entered_time", each DateTime.Time([ordered_date]), type time),
				    #"Extracted Date" = Table.TransformColumns(#"Inserted order_entered_time",{{"ordered_date", DateTime.Date, type date}}),
				    //End General Data Transformation
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Date",{{"bill_date", type date}, {"bol_recv_date", type date}, {"freight_charge", Currency.Type}, {"otherchargetotal", Currency.Type}, {"brlo_commission_paid", Currency.Type}, {"brlo_commission_paid_date", type date}}),
				    //Start add shipper and consignee data
				    #"Merged stop table shipper" = Table.NestedJoin(#"Changed Type", {"shipper_stop_id"}, stop, {"id"}, "stop", JoinKind.LeftOuter),
				    #"Expanded stop" = Table.ExpandTableColumn(#"Merged stop table shipper", "stop", {"city_name", "location_name", "sched_arrive_early", "sched_arrive_late", "state", "zip_code", "sched_arrive_early_time", "sched_arrive_late_time"}, {"stop.city_name", "stop.location_name", "stop.sched_arrive_early", "stop.sched_arrive_late", "stop.state", "stop.zip_code", "stop.sched_arrive_early_time", "stop.sched_arrive_late_time"}),
				    #"Renamed shipper data" = Table.RenameColumns(#"Expanded stop",{{"stop.city_name", "shipper_city_name"}, {"stop.location_name", "shipper_location_name"}, {"stop.sched_arrive_early", "shipper_sched_early_date"}, {"stop.sched_arrive_late", "shipper_sched_late_date"}, {"stop.state", "shipper_state"}, {"stop.zip_code", "shipper_zip_code"}, {"stop.sched_arrive_early_time", "shipper_sched_early_time"}, {"stop.sched_arrive_late_time", "shipper_sched_late_time"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed shipper data", each ([status] <> "V")),
				    #"Merged stop table consignee" = Table.NestedJoin(#"Filtered Rows1", {"consignee_stop_id"}, stop, {"id"}, "stop", JoinKind.LeftOuter),
				    #"Expanded stop1" = Table.ExpandTableColumn(#"Merged stop table consignee", "stop", {"city_id", "city_name", "location_name", "sched_arrive_early", "sched_arrive_late", "state", "zip_code", "sched_arrive_early_time", "sched_arrive_late_time"}, {"stop.city_id", "stop.city_name", "stop.location_name", "stop.sched_arrive_early", "stop.sched_arrive_late", "stop.state", "stop.zip_code", "stop.sched_arrive_early_time", "stop.sched_arrive_late_time"}),
				    //End add shipper and consignee data
				    #"Renamed consignee data" = Table.RenameColumns(#"Expanded stop1",{{"stop.city_id", "consignee_city_id"}, {"stop.city_name", "consignee_city_name"}, {"stop.location_name", "consignee_location_name"}, {"stop.sched_arrive_early", "consignee_sched_early_date"}, {"stop.sched_arrive_late", "consignee_sched_late_date"}, {"stop.state", "consignee_state"}, {"stop.zip_code", "consignee_zip_code"}, {"stop.sched_arrive_early_time", "consignee_sched_early_time"}, {"stop.sched_arrive_late_time", "consignee_sched_late_time"}}),
				    //Start add 3 digit zip
				    #"Inserted First Characters" = Table.AddColumn(#"Renamed consignee data", "shipper_3_digit_zip_code", each Text.Start([shipper_zip_code], 3), type text),
				    //End add 3 digit zip
				    #"Inserted First Characters1" = Table.AddColumn(#"Inserted First Characters", "consignee_3_digit_zip_code", each Text.Start([consignee_zip_code], 3), type text),
				    //Start Add Lane
				    #"Trimmed Text" = Table.TransformColumns(#"Inserted First Characters1",{{"shipper_city_name", Text.Trim, type text}, {"shipper_state", Text.Trim, type text}, {"consignee_city_name", Text.Trim, type text}, {"consignee_state", Text.Trim, type text}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Trimmed Text", "shipper_city_name", "shipper_city_name - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "shipper_state", "shipper_state - Copy"),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "consignee_city_name", "consignee_city_name - Copy"),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Duplicated Column2", "consignee_state", "consignee_state - Copy"),
				    #"Merged Columns" = Table.CombineColumns(#"Duplicated Column3",{"shipper_city_name - Copy", "shipper_state - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Shipper"),
				    #"Merged Columns1" = Table.CombineColumns(#"Merged Columns",{"consignee_city_name - Copy", "consignee_state - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Consignee"),
				    //End Add Lane
				    #"Merged Columns2" = Table.CombineColumns(#"Merged Columns1",{"Shipper", "Consignee"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"lane"),
				    #"Appended Query" = Table.Combine({#"Merged Columns2", mcleod_historic_orders})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

