table overdue_check_calls
	lineageTag: 73748e9d-e1aa-4e29-8ff2-44f74b188960

	column 'Movement ID'
		dataType: string
		lineageTag: d8a76a86-b7c3-405d-a7c0-ba36581d1822
		summarizeBy: none
		sourceColumn: Movement ID

		annotation SummarizationSetBy = Automatic

	column 'Check Call Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b235ee04-a990-4b30-b4f0-ac50f2fc5e88
		summarizeBy: none
		sourceColumn: Check Call Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Status
		dataType: string
		lineageTag: cc81b937-6f9b-44a3-87ea-88357ca05a7c
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Check Call Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 7cef9885-de41-431f-b40a-92deb33f1b09
		summarizeBy: none
		sourceColumn: Check Call Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition overdue_check_calls = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/02%20BL-Areas/bridge_iq/Data%20Sets/Overdue%20Check%20Call/Overdue%20Check%20Calls.xlsx"), null, true),
				    overdue_check_calls_Table = Source{[Item="overdue_check_calls",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(overdue_check_calls_Table,{{"Movement ID", type text}, {"Check Call Time", type datetime}, {"Status", type any}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"Check Call Time"}),
				    #"Inserted Time" = Table.AddColumn(#"Removed Errors", "Time", each DateTime.Time([Check Call Time]), type time),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Time",{{"Check Call Time", "Check Call Date"}, {"Time", "Check Call Time"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Check Call Date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

