table parade_orders
	lineageTag: 63035850-137b-43a7-ad08-5d088d97b2fd

	column id
		dataType: int64
		formatString: 0
		lineageTag: dbc3e7c6-4521-496b-9083-7cec8eac3c74
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column movement_id
		dataType: string
		lineageTag: f6d105ac-864c-4520-93b3-fe891200a8aa
		summarizeBy: none
		sourceColumn: movement_id

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c88ddfe4-f6de-42fa-ab9d-c717980891ff
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 097ad856-9351-46aa-b401-0f8f89534195
			defaultHierarchy: LocalDateTable_1597a8f1-96f6-4a2b-a857-77839b7b4a1c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column archived_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 74f4fe2a-08f4-4442-a15b-e6eb94027159
		summarizeBy: none
		sourceColumn: archived_at

		variation Variation
			isDefault
			relationship: c77e1805-0e8d-40fc-bd42-713e4db26dd9
			defaultHierarchy: LocalDateTable_c8f1405c-b7f6-4839-9069-8149e1cde346.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column src_city
		dataType: string
		lineageTag: 07eb0520-b6e9-4a6a-bf46-9c3e874db02e
		summarizeBy: none
		sourceColumn: src_city

		annotation SummarizationSetBy = Automatic

	column src_state
		dataType: string
		lineageTag: 36209f1a-326a-4381-80bd-69f056dcb003
		summarizeBy: none
		sourceColumn: src_state

		annotation SummarizationSetBy = Automatic

	column src_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3a291356-ab9a-47c9-b8fb-75e65e11720a
		summarizeBy: none
		sourceColumn: src_date

		variation Variation
			isDefault
			relationship: 5566dd3a-ee1f-4176-a92b-c7aeee8c4529
			defaultHierarchy: LocalDateTable_b667b19a-6034-4038-803d-3ee895c62605.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column src_postal_code
		dataType: string
		lineageTag: 36adcf28-db8e-4e4d-b99b-74eb88842b73
		summarizeBy: none
		sourceColumn: src_postal_code

		annotation SummarizationSetBy = Automatic

	column dst_city
		dataType: string
		lineageTag: c706d94e-7e7b-4f35-8277-e56482fc2c4b
		summarizeBy: none
		sourceColumn: dst_city

		annotation SummarizationSetBy = Automatic

	column dst_state
		dataType: string
		lineageTag: 8f38f852-d091-45a7-92b6-772328ed983e
		summarizeBy: none
		sourceColumn: dst_state

		annotation SummarizationSetBy = Automatic

	column dst_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 84efb30d-b260-48c6-b5f1-df0206a614c4
		summarizeBy: none
		sourceColumn: dst_date

		variation Variation
			isDefault
			relationship: fbd3dd6c-f41c-4a4f-bdd7-fca190be9a60
			defaultHierarchy: LocalDateTable_6c1135c2-bb71-4f52-b967-ff64807a396e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column dst_postal_code
		dataType: string
		lineageTag: 3d09b4d8-8c21-48b5-96bf-4a4f171a8d17
		summarizeBy: none
		sourceColumn: dst_postal_code

		annotation SummarizationSetBy = Automatic

	column num_stops
		dataType: int64
		formatString: 0
		lineageTag: d695b8f6-b915-4dba-a1ff-c44676471cfc
		summarizeBy: sum
		sourceColumn: num_stops

		annotation SummarizationSetBy = Automatic

	column equipment
		dataType: string
		lineageTag: 9129fada-3832-40d5-bfb3-c772bffdc911
		summarizeBy: none
		sourceColumn: equipment

		annotation SummarizationSetBy = Automatic

	column trailer_type
		dataType: string
		lineageTag: 4b418631-53e8-435b-9c04-31e929d9f6bc
		summarizeBy: none
		sourceColumn: trailer_type

		annotation SummarizationSetBy = Automatic

	column rate_customer
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: acb7c066-838f-4c3c-8390-28c5c52e10d3
		summarizeBy: sum
		sourceColumn: rate_customer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column first_load
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 59cc9680-1963-4fdc-bbdd-340b4994e15f
		summarizeBy: none
		sourceColumn: first_load

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: cd5412b9-34af-4bb1-bf30-f6ad98be8aa5
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column revenue_code
		dataType: int64
		formatString: 0
		lineageTag: 6bd48adf-2749-435c-9352-f6ebdbea29d2
		summarizeBy: sum
		sourceColumn: revenue_code

		annotation SummarizationSetBy = Automatic

	column team_name
		dataType: string
		lineageTag: 287dd600-0fe0-448e-b906-f826937361f6
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column rep_email
		dataType: string
		lineageTag: 9fa11ec6-ab87-4196-94c1-00ab74cf1377
		summarizeBy: none
		sourceColumn: rep_email

		annotation SummarizationSetBy = Automatic

	column rep_name
		dataType: string
		lineageTag: 48551d90-b7a4-40f0-967a-aaa8c33cc733
		summarizeBy: none
		sourceColumn: rep_name

		annotation SummarizationSetBy = Automatic

	column carrier_manager
		dataType: string
		lineageTag: 9cadc211-6095-45ed-bded-2ecbcb331065
		summarizeBy: none
		sourceColumn: carrier_manager

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 75e2ed55-35e5-4b67-83c2-78f5ee19b9b3
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column conversion_category
		dataType: string
		lineageTag: 52adac3c-6a77-4e26-90f5-86cd9189c184
		summarizeBy: none
		sourceColumn: conversion_category

		annotation SummarizationSetBy = Automatic

	column partner
		dataType: string
		lineageTag: 8576be9d-e81b-4fd0-936e-32fcb4cced43
		summarizeBy: none
		sourceColumn: partner

		annotation SummarizationSetBy = Automatic

	column margin_amount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a9f68a07-10cf-48dc-88fc-dca44ef3f947
		summarizeBy: sum
		sourceColumn: margin_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column margin_pct
		dataType: double
		lineageTag: dbc66afe-ff4f-4435-8f1f-656a5fa9d5a7
		summarizeBy: sum
		sourceColumn: margin_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column carrier_name
		dataType: string
		lineageTag: 3dd21ec3-f095-4c30-8bbd-9fce318deb56
		summarizeBy: none
		sourceColumn: carrier_name

		annotation SummarizationSetBy = Automatic

	column dot_number
		dataType: int64
		formatString: 0
		lineageTag: 519569ca-2dac-4566-b215-f52fc549d06c
		summarizeBy: sum
		sourceColumn: dot_number

		annotation SummarizationSetBy = Automatic

	column mc_number
		dataType: int64
		formatString: 0
		lineageTag: 98f8aa8a-a97f-4b9b-a8c3-8bdab77ec0b2
		summarizeBy: sum
		sourceColumn: mc_number

		annotation SummarizationSetBy = Automatic

	column carrier_rate
		dataType: double
		lineageTag: 041e7c40-ef92-4032-9fab-93cfc6b33232
		summarizeBy: sum
		sourceColumn: carrier_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition parade_orders = m
		mode: import
		source =
				let
				    Source = SharePoint.Files("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam", [ApiVersion = 15]),
				    #"Reordered Columns" = Table.ReorderColumns(Source,{"Content", "Name", "Extension", "Date accessed", "Date modified", "Date created", "Folder Path", "Attributes"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each Text.Contains([Folder Path], "02 BL-Areas/bridge_iq/Data Sets/Parade/parade_orders_api_files")),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Filtered Rows", each [Attributes]?[Hidden]? <> true),
				    #"Filtered Hidden Files2" = Table.SelectRows(#"Filtered Hidden Files1", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files2", "Transform File (2)", each #"Transform File (2)"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File (2)"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File (2)", Table.ColumnNames(#"Transform File (2)"(#"Sample File (2)"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"id", Int64.Type}, {"reference_id", type text}, {"created_at", type datetime}, {"archived_at", type datetime}, {"src_city", type text}, {"src_state", type text}, {"src_date", type date}, {"src_postal_code", type text}, {"dst_city", type text}, {"dst_state", type text}, {"dst_date", type date}, {"dst_postal_code", type text}, {"num_stops", Int64.Type}, {"equipment", type text}, {"trailer_type", type text}, {"rate_customer", type number}, {"first_load", type logical}, {"customer_id", type text}, {"revenue_code", Int64.Type}, {"team_name", type any}, {"rep_email", type text}, {"rep_name", type text}, {"carrier_manager", type text}, {"category", type text}, {"conversion_category", type text}, {"partner", type text}, {"margin_amount", type number}, {"margin_pct", type number}, {"carrier_name", type text}, {"dot_number", Int64.Type}, {"mc_number", Int64.Type}, {"carrier_rate", type number}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"rate_customer", Currency.Type}, {"margin_amount", Currency.Type}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type1",{{"reference_id", Order.Ascending}}),
				    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Sorted Rows", {{"reference_id", each Text.AfterDelimiter(_, "-"), type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Extracted Text After Delimiter", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Blank Rows",{{"reference_id", "movement_id"}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns", each ([category] <> "outside_parade") and ([conversion_category] <> "Manually Assigned")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows1", {"id"}),
				    #"Filtered Orders on or after RefreshCutOffDate" = Table.SelectRows(#"Removed Duplicates", each [created_at] >= RefreshCutOffDate),
				    #"Appended Query" = Table.Combine({#"Filtered Orders on or after RefreshCutOffDate", historic_parade_orders})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

