table pcs_loads
	excludeFromModelRefresh
	lineageTag: d4e1c165-81d9-45ca-8a53-66f1a155ed20

	column 'Carrier Name'
		dataType: string
		lineageTag: bafb9091-32a2-4dbb-bb4e-83973b579048
		summarizeBy: none
		sourceColumn: Carrier Name

		annotation SummarizationSetBy = Automatic

	column 'Consignee City'
		dataType: string
		lineageTag: 0e5e1e1c-19c5-47e5-bdcb-e7c69feeaeaf
		summarizeBy: none
		sourceColumn: Consignee City

		annotation SummarizationSetBy = Automatic

	column 'Consignee Name'
		dataType: string
		lineageTag: 0ad9feb4-1ecb-4df7-b009-36239e3f4a4e
		summarizeBy: none
		sourceColumn: Consignee Name

		annotation SummarizationSetBy = Automatic

	column 'Consignee State'
		dataType: string
		lineageTag: a8c80e05-f927-4aa2-8b16-301c40168e1b
		summarizeBy: none
		sourceColumn: Consignee State

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: e93c611b-0d1b-4382-8dfa-41cebfd5e376
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9a88f39b-76b7-4fa1-9c76-b1135db9c741
		summarizeBy: none
		sourceColumn: Ship Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Commodity
		dataType: string
		lineageTag: f200c1e0-4d06-4d64-8bac-3c29660b5751
		summarizeBy: none
		sourceColumn: Commodity

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 3a64e14b-1084-4ada-af68-b04fb6815797
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Trailer Type'
		dataType: string
		lineageTag: 496379d6-1af5-489c-a869-189108c1d660
		summarizeBy: none
		sourceColumn: Trailer Type

		annotation SummarizationSetBy = Automatic

	column 'Shipper City'
		dataType: string
		lineageTag: 47118e52-f112-4f98-b237-37b453d2145d
		summarizeBy: none
		sourceColumn: Shipper City

		annotation SummarizationSetBy = Automatic

	column 'Shipper Name'
		dataType: string
		lineageTag: 5224341e-06c7-481e-96e2-9a94bb88ee79
		summarizeBy: none
		sourceColumn: Shipper Name

		annotation SummarizationSetBy = Automatic

	column 'Shipper State'
		dataType: string
		lineageTag: e8af3d0d-fd7e-48d0-a9ee-799a8d029e85
		summarizeBy: none
		sourceColumn: Shipper State

		annotation SummarizationSetBy = Automatic

	column 'Bill Distance'
		dataType: double
		lineageTag: d38d5631-55c9-451f-97f7-e740f3c3f184
		summarizeBy: sum
		sourceColumn: Bill Distance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Carrier Pay'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d55b1a42-0d00-4566-8ef5-36dc0bfc38f5
		summarizeBy: sum
		sourceColumn: Carrier Pay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Total Revenue'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ff2ce648-037f-4d92-b863-5df733e5420b
		summarizeBy: sum
		sourceColumn: Total Revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Dispatcher
		dataType: string
		lineageTag: 31ad7a3a-8b79-4189-9706-3cc9db7f8ad1
		summarizeBy: none
		sourceColumn: Dispatcher

		annotation SummarizationSetBy = Automatic

	column 'Delivery Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 018a075d-190b-4f43-8520-a8ae19ecdfeb
		summarizeBy: none
		sourceColumn: Delivery Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cases Pieces'
		dataType: int64
		formatString: 0
		lineageTag: edc0e389-4428-4c33-8563-a25120a209fe
		summarizeBy: sum
		sourceColumn: Cases Pieces

		annotation SummarizationSetBy = Automatic

	column Lane
		dataType: string
		lineageTag: 368ccdf7-c635-46f8-8ac3-04e3317d4695
		summarizeBy: none
		sourceColumn: Lane

		annotation SummarizationSetBy = Automatic

	column 'Salesperson Name'
		dataType: string
		lineageTag: 4cc86850-075b-490e-bbbc-884506f07679
		summarizeBy: none
		sourceColumn: Salesperson Name

		annotation SummarizationSetBy = Automatic

	partition pcs_loads = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://bridgelogisticsinc.sharepoint.com/sites/BL-BiTeam/Shared%20Documents/PCS/PCS%20Loads.xlsx"), null, true),
				    PCSLoads_Table = Source{[Item="PCSLoads",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(PCSLoads_Table,{{"LoadID", Int64.Type}, {"PickupDate", type datetime}, {"DeliveryDate", type datetime}, {"MilesBilled", Int64.Type}, {"Commodity", type any}, {"TotalPieces", Int64.Type}, {"TotalRevenue", type number}, {"DispUser", type text}, {"ShipName", type text}, {"ShipCity", type text}, {"ShipSt", type text}, {"ShipZip", Int64.Type}, {"ConsName", type text}, {"ConsCity", type text}, {"ConsSt", type text}, {"ConsZip", Int64.Type}, {"DriverName", type text}, {"Driver Pay", type number}, {"Saleperson Name", type any}, {"McLeodVsPCSCode.Code", type any}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"DriverName", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "ConsName", "ConsCity", "ConsSt", "ConsZip", "Driver Pay", "Saleperson Name", "McLeodVsPCSCode.Code"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"DriverName", "Carrier Name"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns",{"Carrier Name", "ConsCity", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "ConsName", "ConsSt", "ConsZip", "Driver Pay", "Saleperson Name", "McLeodVsPCSCode.Code"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"ConsCity", "Consignee City"}}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"Carrier Name", "Consignee City", "ConsName", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "ConsSt", "ConsZip", "Driver Pay", "Saleperson Name", "McLeodVsPCSCode.Code"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns2",{{"ConsName", "Consignee Name"}}),
				    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns2",{"Carrier Name", "Consignee City", "Consignee Name", "ConsSt", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "ConsZip", "Driver Pay", "Saleperson Name", "McLeodVsPCSCode.Code"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns3",{{"ConsSt", "Consignee State"}}),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Renamed Columns3",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "ConsZip", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "Driver Pay", "Saleperson Name", "McLeodVsPCSCode.Code"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Reordered Columns4",{{"ConsZip", "Consignee  Zip"}}),
				    #"Reordered Columns5" = Table.ReorderColumns(#"Renamed Columns4",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "McLeodVsPCSCode.Code", "LoadID", "PickupDate", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "Driver Pay", "Saleperson Name"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Reordered Columns5",{{"McLeodVsPCSCode.Code", "Customer ID"}}),
				    #"Reordered Columns6" = Table.ReorderColumns(#"Renamed Columns5",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "PickupDate", "LoadID", "DeliveryDate", "MilesBilled", "Commodity", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "Driver Pay", "Saleperson Name"}),
				    #"Renamed Columns6" = Table.RenameColumns(#"Reordered Columns6",{{"PickupDate", "Ship Date"}}),
				    #"Reordered Columns7" = Table.ReorderColumns(#"Renamed Columns6",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "LoadID", "DeliveryDate", "MilesBilled", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "Driver Pay", "Saleperson Name"}),
				    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns7", each true),
				    #"Renamed Columns7" = Table.RenameColumns(#"Filtered Rows",{{"LoadID", "Order ID"}}),
				    #"Reordered Columns8" = Table.ReorderColumns(#"Renamed Columns7",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "LoadType", "DeliveryDate", "MilesBilled", "TotalPieces", "TotalRevenue", "DispUser", "ShipName", "ShipCity", "ShipSt", "ShipZip", "Driver Pay", "Saleperson Name"}),
				    #"Renamed Columns8" = Table.RenameColumns(#"Reordered Columns8",{{"LoadType", "Trailer Type"}}),
				    #"Reordered Columns9" = Table.ReorderColumns(#"Renamed Columns8",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "ShipCity", "ShipName", "ShipSt", "ShipZip", "DeliveryDate", "MilesBilled", "TotalPieces", "TotalRevenue", "DispUser", "Driver Pay", "Saleperson Name"}),
				    #"Renamed Columns9" = Table.RenameColumns(#"Reordered Columns9",{{"ShipCity", "Shipper City"}, {"ShipName", "Shipper Name"}, {"ShipSt", "Shipper State"}, {"ShipZip", "Shipper Zip"}}),
				    #"Reordered Columns10" = Table.ReorderColumns(#"Renamed Columns9",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "Shipper City", "Shipper Name", "Shipper State", "MilesBilled", "Shipper Zip", "DeliveryDate", "TotalPieces", "TotalRevenue", "DispUser", "Driver Pay", "Saleperson Name"}),
				    #"Renamed Columns10" = Table.RenameColumns(#"Reordered Columns10",{{"MilesBilled", "Bill Distance"}}),
				    #"Reordered Columns11" = Table.ReorderColumns(#"Renamed Columns10",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "Shipper City", "Shipper Name", "Shipper State", "Bill Distance", "Shipper Zip", "Driver Pay", "DeliveryDate", "TotalPieces", "TotalRevenue", "DispUser", "Saleperson Name"}),
				    #"Renamed Columns11" = Table.RenameColumns(#"Reordered Columns11",{{"Driver Pay", "Carrier Pay"}}),
				    #"Reordered Columns12" = Table.ReorderColumns(#"Renamed Columns11",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "Shipper City", "Shipper Name", "Shipper State", "Bill Distance", "Shipper Zip", "Carrier Pay", "TotalRevenue", "DeliveryDate", "TotalPieces", "DispUser", "Saleperson Name"}),
				    #"Renamed Columns12" = Table.RenameColumns(#"Reordered Columns12",{{"TotalRevenue", "Total Revenue"}}),
				    #"Reordered Columns13" = Table.ReorderColumns(#"Renamed Columns12",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "Shipper City", "Shipper Name", "Shipper State", "Bill Distance", "Shipper Zip", "Carrier Pay", "Total Revenue", "DispUser", "DeliveryDate", "TotalPieces", "Saleperson Name"}),
				    #"Renamed Columns13" = Table.RenameColumns(#"Reordered Columns13",{{"DispUser", "Dispatcher"}, {"DeliveryDate", "Delivery Date"}}),
				    #"Reordered Columns14" = Table.ReorderColumns(#"Renamed Columns13",{"Carrier Name", "Consignee City", "Consignee Name", "Consignee State", "Consignee  Zip", "Customer ID", "Ship Date", "Commodity", "Order ID", "Trailer Type", "Shipper City", "Shipper Name", "Shipper State", "Bill Distance", "Shipper Zip", "Carrier Pay", "Total Revenue", "Dispatcher", "Delivery Date", "Saleperson Name", "TotalPieces"}),
				    #"Renamed Columns14" = Table.RenameColumns(#"Reordered Columns14",{{"TotalPieces", "Cases Pieces"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns14",{{"Delivery Date", type date}, {"Ship Date", type date}, {"Consignee  Zip", type text}, {"Shipper Zip", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type1", {"Consignee  Zip"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Errors",{"Consignee  Zip", "Shipper Zip"}),
				    #"Renamed Columns15" = Table.RenameColumns(#"Removed Columns",{{"Saleperson Name", "Salesperson Name"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns15",{{"Customer ID", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2",null,"UNS",Replacer.ReplaceValue,{"Customer ID"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Replaced Value",{{"Commodity", type text}, {"Order ID", type text}, {"Trailer Type", type text}, {"Bill Distance", type number}, {"Carrier Pay", Currency.Type}, {"Total Revenue", Currency.Type}, {"Salesperson Name", type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type3", each true),
				    #"Uppercased Text" = Table.TransformColumns(#"Filtered Rows1",{{"Dispatcher", Text.Upper, type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Uppercased Text","JOE","JCAMPBELL",Replacer.ReplaceValue,{"Dispatcher"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","JOECAMPBEL","JCAMPBELL",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Filtered Rows2" = Table.SelectRows(#"Replaced Value2", each true),
				    #"Trimmed Text1" = Table.TransformColumns(#"Filtered Rows2",{{"Consignee City", Text.Trim, type text}}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Trimmed Text1","TONY","TCAMPBELL",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value3",{{"Dispatcher", Text.Trim, type text}, {"Consignee State", Text.Trim, type text}, {"Shipper City", Text.Trim, type text}, {"Shipper State", Text.Trim, type text}}),
				    #"Filtered Rows3" = Table.SelectRows(#"Trimmed Text", each true),
				    #"Replaced Value4" = Table.ReplaceValue(#"Filtered Rows3","MELROD","MCHRISTIAN",Replacer.ReplaceText,{"Dispatcher"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced Value4", "Shipper City", "Shipper City - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Shipper State", "Shipper State - Copy"),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Duplicated Column1", "Consignee City", "Consignee City - Copy"),
				    #"Duplicated Column3" = Table.DuplicateColumn(#"Duplicated Column2", "Consignee State", "Consignee State - Copy"),
				    #"Merged Columns" = Table.CombineColumns(#"Duplicated Column3",{"Shipper City - Copy", "Shipper State - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Shipper City, State"),
				    #"Merged Columns1" = Table.CombineColumns(#"Merged Columns",{"Consignee City - Copy", "Consignee State - Copy"},Combiner.CombineTextByDelimiter(", ", QuoteStyle.None),"Consignee City, State"),
				    #"Merged Columns2" = Table.CombineColumns(#"Merged Columns1",{"Shipper City, State", "Consignee City, State"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Lane"),
				    #"Uppercased Text1" = Table.TransformColumns(#"Merged Columns2",{{"Lane", Text.Upper, type text}}),
				    #"Sorted Rows" = Table.Sort(#"Uppercased Text1",{{"Salesperson Name", Order.Descending}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Sorted Rows", "Salesperson Name", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), {"Salesperson Name.1", "Salesperson Name.2"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Salesperson Name.1", type text}, {"Salesperson Name.2", type text}}),
				    #"Trimmed Text2" = Table.TransformColumns(#"Changed Type4",{{"Salesperson Name.2", Text.Trim, type text}}),
				    #"Extracted Text Before Delimiter" = Table.TransformColumns(#"Trimmed Text2", {{"Salesperson Name.2", each Text.BeforeDelimiter(_, " "), type text}}),
				    #"Merged Columns3" = Table.CombineColumns(#"Extracted Text Before Delimiter",{"Salesperson Name.2", "Salesperson Name.1"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Salesperson Name")
				in
				    #"Merged Columns3"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

