table shipper_zips
	lineageTag: a1ccc5d0-5216-495c-8401-1c44ad12db42

	column 'Shipper Zip'
		dataType: string
		lineageTag: d1bcca77-9b8c-46a1-9f1b-ff10f034268d
		summarizeBy: none
		sourceColumn: Shipper Zip

		annotation SummarizationSetBy = Automatic

	column '3 Digit Zip'
		dataType: string
		lineageTag: 573e2434-e3ff-48ba-8024-82bec2c425bc
		summarizeBy: none
		sourceColumn: 3 Digit Zip

		annotation SummarizationSetBy = Automatic

	partition shipper_zips = m
		mode: import
		queryGroup: 'Zip Codes'
		source =
				let
				    Source = orders,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Shipper Zip"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Duplicates", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Inserted First Characters" = Table.AddColumn(#"Removed Blank Rows", "First Characters", each Text.Start([Shipper Zip], 3), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted First Characters",{{"First Characters", "3 Digit Zip"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

