table stop
	lineageTag: 64234da3-1a77-453d-a2c0-eefc98a8f918

	column actual_arrival
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9ef4b83e-107f-4d5b-8219-dfc77985e9a0
		summarizeBy: none
		sourceColumn: actual_arrival

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column actual_departure
		dataType: dateTime
		formatString: Long Date
		lineageTag: 293412a0-bf03-4826-8a97-1a81079f6504
		summarizeBy: none
		sourceColumn: actual_departure

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column address
		dataType: string
		lineageTag: a6adf536-0d64-4049-b9cb-fb4e2b7c21ce
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column appt_required
		dataType: string
		lineageTag: b13783ca-5bed-4105-a1c6-9e462586caf7
		summarizeBy: none
		sourceColumn: appt_required

		annotation SummarizationSetBy = Automatic

	column city_id
		dataType: int64
		formatString: 0
		lineageTag: 1bc276e1-1a39-4b1a-8aa8-2728fddc3773
		summarizeBy: sum
		sourceColumn: city_id

		annotation SummarizationSetBy = Automatic

	column city_name
		dataType: string
		lineageTag: b9224492-5ca3-41b2-9d65-50294df8851e
		summarizeBy: none
		sourceColumn: city_name

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 6a0d9d49-dd12-4e28-8e95-dd506031ddc7
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 21935e7d-cb68-49b5-a964-c5973162f4eb
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column location_id
		dataType: string
		lineageTag: c7e09021-9d78-46ed-8dfa-ab3c36eab7e0
		summarizeBy: none
		sourceColumn: location_id

		annotation SummarizationSetBy = Automatic

	column location_name
		dataType: string
		lineageTag: 87eabea0-fa60-4044-b247-608203a525dd
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 7b288303-c5a3-441a-b56d-715dfa896c8b
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column movement_id
		dataType: string
		lineageTag: 15b95255-a95d-4fc8-9d47-c75b7eceafea
		summarizeBy: none
		sourceColumn: movement_id

		annotation SummarizationSetBy = Automatic

	column movement_sequence
		dataType: int64
		formatString: 0
		lineageTag: dfd5a8c4-fb75-4f59-88b6-88cae35d48be
		summarizeBy: sum
		sourceColumn: movement_sequence

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 4b478b71-b124-4352-9f90-a0a2a6900144
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_sequence
		dataType: int64
		formatString: 0
		lineageTag: 5f215497-bae3-4a80-ba97-5c3da84c26e0
		summarizeBy: sum
		sourceColumn: order_sequence

		annotation SummarizationSetBy = Automatic

	column sched_arrive_early
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc6012aa-e2cc-4aec-a09d-a2a3a02fe890
		summarizeBy: none
		sourceColumn: sched_arrive_early

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column sched_arrive_late
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8530f8b5-73d3-460b-a721-ad343fc21d57
		summarizeBy: none
		sourceColumn: sched_arrive_late

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column state
		dataType: string
		lineageTag: e620a96a-943e-4e4d-bb7a-f68f5368bd54
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 640d19de-58ab-474a-a91b-e3238802af05
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column stop_type
		dataType: string
		lineageTag: 8e0a8995-6d9d-4c81-8a65-24f6eab50d33
		summarizeBy: none
		sourceColumn: stop_type

		annotation SummarizationSetBy = Automatic

	column zip_code
		dataType: string
		lineageTag: d791d6c9-6fa2-428e-a0a4-648163a2cc09
		summarizeBy: none
		sourceColumn: zip_code

		annotation SummarizationSetBy = Automatic

	column zone_id
		dataType: string
		lineageTag: a16067ee-c856-4307-a0df-29403459c143
		summarizeBy: none
		sourceColumn: zone_id

		annotation SummarizationSetBy = Automatic

	column actual_arrival_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 82b24748-fe8e-41cd-a0a9-18a22857365b
		summarizeBy: none
		sourceColumn: actual_arrival_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column actual_departure_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: fe8368d4-6f12-496d-b828-1c39ec0ace1a
		summarizeBy: none
		sourceColumn: actual_departure_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column sched_arrive_early_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6f719216-dbb6-4dc5-b0fd-67427613bde4
		summarizeBy: none
		sourceColumn: sched_arrive_early_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column sched_arrive_late_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 0346c9b7-6f65-40b3-b421-796db62d9f5d
		summarizeBy: none
		sourceColumn: sched_arrive_late_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition stop = m
		mode: import
		source =
				let
				    Source = Sql.Database("bl-appdb", "lme"),
				    dbo_stop = Source{[Schema="dbo",Item="stop"]}[Data],
				    #"Filtered Stops Post RefresshCutOffDate" = Table.SelectRows(dbo_stop, each [sched_arrive_early] >= RefreshCutOffDate),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Stops Post RefresshCutOffDate",{"company_id", "address2", "appointment_status_id", "appt_contact_name", "hub", "cases", "confirmed", "contact_name", "dist_from_prev", "dist_from_prev_um", "driver_load_unload", "edi_code", "edi_loc_code", "eta", "eta_distance", "eta_late", "eta_oor", "google_place_id", "inbound_status", "late_eta_colorcode", "late_route_status", "manifest_fgp_uid", "manifest_reg_uid", "move_dist_from_preassign", "move_dist_from_preassign_um", "move_dist_from_previous", "move_dist_from_previous_um", "operational_status", "orig_sched_early", "orig_sched_late", "pallets_dropped", "pallets_picked_up", "phone", "planned_arrival_time", "ponum", "prior_uncleared_stops", "projected_arrival", "rate_dist_from_previous", "rate_dist_from_previous_um", "refno", "requested_service", "seal", "service_date", "showas_address", "showas_address2", "showas_city_id", "showas_city_name", "showas_location_id", "showas_location_name", "showas_state", "showas_zip_code", "signed_for_name", "txl_uid", "volume", "volume_um", "weight", "weight_um", "ic_stop_id", "grouped_id", "payment_code_reviewed", "trimble_place_id"}),
				    #"Inserted actual_arrival_time" = Table.AddColumn(#"Removed Columns", "actual_arrival_time", each DateTime.Time([actual_arrival]), type time),
				    #"Inserted actual_departure_time" = Table.AddColumn(#"Inserted actual_arrival_time", "actual_departure_time", each DateTime.Time([actual_departure]), type time),
				    #"Inserted sched_arrive_early_time" = Table.AddColumn(#"Inserted actual_departure_time", "sched_arrive_early_time", each DateTime.Time([sched_arrive_early]), type time),
				    #"Inserted sched_arrive_late_time" = Table.AddColumn(#"Inserted sched_arrive_early_time", "sched_arrive_late_time", each DateTime.Time([sched_arrive_late]), type time),
				    #"Changed Type" = Table.TransformColumnTypes(#"Inserted sched_arrive_late_time",{{"actual_arrival", type date}, {"actual_departure", type date}, {"sched_arrive_early", type date}, {"sched_arrive_late", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"id", Text.Trim, type text}}),
				    #"Appended Query" = Table.Combine({#"Trimmed Text", stop_historic})
				in
				    #"Appended Query"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

