table Calendar
	lineageTag: c583c9ce-20dd-43b3-818e-c9d8da9a588a
	dataCategory: Time

	measure 'Calendar General' = FORMAT(MIN('Calendar'[Date]),"General Number")
		lineageTag: 060c64c1-9345-4648-a1bf-10a163a011b3

		changedProperty = IsHidden

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 8c8cd0ec-bc3a-497c-8890-727a55c10611
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Start of Month'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ebb95aa5-5e0f-4c35-92d8-0fafa766588b
		summarizeBy: none
		sourceColumn: Start of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1fc3964d-1c86-48a9-8188-68259c733be2
		summarizeBy: sum
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f47f69c1-ff67-4e2f-89d8-5290e3b12366
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column QuarterNmb
		dataType: int64
		formatString: 0
		lineageTag: 24fe33b4-7940-4d34-a726-e55a50ba02eb
		summarizeBy: sum
		sourceColumn: QuarterNmb

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 8287fd0f-b28c-4d24-bb40-08429d66461a
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: MonthNmb

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthAbv
		dataType: string
		lineageTag: 4e97bbfd-3c3e-4fda-b6f9-d12336fca1ef
		summarizeBy: none
		sourceColumn: MonthAbv
		sortByColumn: MonthNmb

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MonthNmb
		dataType: int64
		formatString: 0
		lineageTag: 9e2df293-236d-4167-aa97-27899fa85f79
		summarizeBy: sum
		sourceColumn: MonthNmb

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: e6153bd8-2b9c-4f9e-8481-d0b1e326eee3
		summarizeBy: sum
		sourceColumn: Week of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week of Month'
		dataType: int64
		formatString: 0
		lineageTag: ec41ace3-8053-410f-b7e1-a0aa2140a693
		summarizeBy: sum
		sourceColumn: Week of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 82e401e4-81e2-40eb-90cd-427d900bca55
		summarizeBy: sum
		sourceColumn: Day of Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Month'
		dataType: int64
		formatString: 0
		lineageTag: 997f426f-f5ce-43a5-8ef2-8850a375bd30
		summarizeBy: sum
		sourceColumn: Day of Month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: ccc72e4a-d3ac-464d-ac0b-84de114d234d
		summarizeBy: sum
		sourceColumn: Day of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 9da35ee3-b43a-45a0-9a4e-af097f1575fe
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day of Week'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Is Past'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6d1b380f-221b-4d89-aaf7-b3bc2dbd9e53
		summarizeBy: none
		sourceColumn: Is Past

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month / Year'
		dataType: string
		lineageTag: 18f8eb3b-bc2c-4a60-88cd-5c27079058e7
		summarizeBy: none
		sourceColumn: Month / Year
		sortByColumn: 'Start of Month'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Quarter'
		dataType: string
		lineageTag: a8a73e23-6bcf-4cf0-84ca-5f0ae725ac1a
		summarizeBy: none
		sourceColumn: Day of Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Week / Year'
		dataType: string
		lineageTag: a34020b1-473b-4db1-b090-a14e7fcca899
		summarizeBy: none
		sourceColumn: Week / Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 600e226d-a54e-4344-b9f4-7773fea19639
		summarizeBy: none
		sourceColumn: Start of Week

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Slicer Date'
		dataType: string
		lineageTag: 0a766627-4d8f-4506-95fe-93c2871d045d
		summarizeBy: none
		sourceColumn: Slicer Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	hierarchy 'Calendar Hierachy'
		lineageTag: e065a8bc-ad21-4062-99de-5d6030e02e43

		level Year
			lineageTag: c01f05c6-f273-4574-9a01-908c531fafe5
			column: Year

		level Quarter
			lineageTag: 68d60c53-4cdf-483e-b989-2411c88e8a78
			column: Quarter

		level 'Month Name'
			lineageTag: 57efdf74-b33d-4efc-b9c2-cf3042af3894
			column: 'Month Name'

		level Date
			lineageTag: b7962dec-cb7b-4b56-af30-deaa84a0e2c2
			column: Date

		changedProperty = IsHidden

	partition Calendar = m
		mode: import
		source =
				let
				    //Variables
				    StartDate = #date(2001,1,1),
				    EndDate = #date(2025,12,31),
				    Duration = Duration.Days(Duration.From(EndDate-StartDate))+1,
				    Today = DateTime.Date(DateTime.LocalNow()),
				
				    //Date Columns
				    Dates = List.Dates(StartDate,Duration,#duration(1,0,0,0)),
				    #"Converted to Table" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
				    #"Inserted Start of Month" = Table.AddColumn(#"Changed Type", "Start of Month", each Date.StartOfMonth([Date]), type date),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Start of Month", "Year", each Date.Year([Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Year", "Quarter", each "Q"&Text.From(Date.QuarterOfYear([Date]))),
				    #"Inserted QuarterNmb" = Table.AddColumn(#"Inserted Quarter", "QuarterNmb", each Date.QuarterOfYear([Date]), Int64.Type),
				    #"Inserted Month Name" = Table.AddColumn(#"Inserted QuarterNmb", "Month Name", each Date.MonthName([Date]), type text),
				    #"Inserted MonthAbv" = Table.AddColumn(#"Inserted Month Name", "MonthAbv", each Text.Start(Date.MonthName([Date]),3), type text),
				    #"Inserted MonthNmb" = Table.AddColumn(#"Inserted MonthAbv", "MonthNmb", each Date.Month([Date]), Int64.Type),
				    #"Inserted Week of Year" = Table.AddColumn(#"Inserted MonthNmb", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date]), Int64.Type),
				    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Week of Month", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    #"Inserted Day of Month" = Table.AddColumn(#"Inserted Day of Year", "Day of Month", each Date.Day([Date]), Int64.Type),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day of Month", "Day of Week", each Date.DayOfWeek([Date]), Int64.Type),
				    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day of Week", "Day Name", each Date.DayOfWeekName([Date]), type text),
				    #"Inserted Is Past" = Table.AddColumn(#"Inserted Day Name", "Is Past", each [Date]<Today),
				    #"Changed Is Past to True False" = Table.TransformColumnTypes(#"Inserted Is Past",{{"Is Past", type logical}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Is Past to True False", "Month / Year", each Date.ToText([Date], "MMM/yyyy")),
				    #"Added Day of Quarter" = Table.AddColumn(#"Added Custom", "Day of Quarter", each Date.DayOfYear(Date.From([Date])) - Date.DayOfYear(Date.From(Date.StartOfQuarter([Date]))) + 1),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Added Day of Quarter", "Week of Year", "Week of Year - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "Year", "Year - Copy"),
				    #"Merged Columns" = Table.CombineColumns(Table.TransformColumnTypes(#"Duplicated Column1", {{"Week of Year - Copy", type text}, {"Year - Copy", type text}}, "en-US"),{"Week of Year - Copy", "Year - Copy"},Combiner.CombineTextByDelimiter("/", QuoteStyle.None),"Week / Year"),
				    #"Inserted Start of Week" = Table.AddColumn(#"Merged Columns", "Start of Week", each Date.StartOfWeek([Date]), type date),
				    #"Added Custom1" = Table.AddColumn(#"Inserted Start of Week", "Slicer Date", each if [Date] = Date.From(DateTime.LocalNow()) then "today" else [Date])
				in
				    #"Added Custom1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

